### ISSUE TITLE
scale handler not playing well with rotation

### ISSUE THREAD

**Issue by trungtin** [daybrush/moveable#1]
Try rotate 180* and drag the scale handler, drag the lefty handler (which is original on the right) to the right should scale down, not scale up.

**Comment by daybrush** [comment]
@trungtin
Hi. First of all, thank you for reporting the issue.
Have you tested it with [https://daybrush.com/moveable/](https://daybrush.com/moveable/)'s demo?

If so, it wasn't a library problem, it was a demo. I fixed the demo right now. Please check again.

**Comment by trungtin** [comment]
oh terribly sorry :)) yes it on the demo only, and I saw it's fixed.
