### ISSUE TITLE
Anyway to trigger dragStart on mousedown+mousemove instead of mousedown?

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#100]
Hi,

I wanted to see if there was a way to trigger dragStart on mousedown + mousemove instead of just mousemove? I understand it is meant for users to change target and drag at the same time. But if the target is already selected, can it trigger on mousemove?

I have seen this issue - https://github.com/daybrush/moveable/issues/10#issue-473769547

**Comment by daybrush** [comment]
@adityakrshnn 

yes. You can use as follows:

```js

document.addEventListener("mousemove", e => {
    moveable.dragStart(e);
});

**Comment by adityakrshnn** [comment]
I figured it out. Thanks!

**Comment by blobinabottle** [comment]
How do you do that in React? Only via a custom build of Moveable?

**Comment by daybrush** [comment]
@blobinabottle 

use nativeEvent
```tsx
onMouseDown={e => {
   moveable.dragStart(e.nativeEvent);
}}
```

**Comment by blobinabottle** [comment]
thanks @daybrush 
Sorry if stupid question, but `movable` is undefined. 
You call this inside the <Moveable /> component?

**Comment by daybrush** [comment]
@adityakrshnn 

In react, you can use below:

```tsx
ref = {e => {
    this.moveable = e;
}}
onMouseDown={e => {
   this.moveable.dragStart(e);
}}

```

**Comment by blobinabottle** [comment]
thanks a lot you're the best! ;-)

**Comment by blobinabottle** [comment]
@daybrush do you have any idea why in this setup the click-and-drag-immediatly works well in Chrome but not in Safari? 
https://codesandbox.io/s/lucid-liskov-7b4zi?fontsize=14&hidenavigation=1&theme=dark
(if I achieve something decent I'll share it with the community to help people quickly understand the setup of Moveable in a basic app)

**Comment by daybrush** [comment]
@blobinabottle 

I think useState is asynchronous. The asynchronous behavior seems to be due to the difference between safari and chrome.

For class components, the following method is recommended.
```js
setState ({target: target}, () => {
    console.log ("callback");
});
```
If it's hooks, you should use useEffect originally, but I'm not sure if it's an event. I think you should use setTimeout.
```js
    const nativeEvent = e.nativeEvent;
    onMouseDown(e, frame);
    setTarget(e.target);
    
    setTimeout(() => {
      moveable.dragStart(nativeEvent);
    });
```

**Comment by GreatAuk** [comment]
> @blobinabottle
> 
> I think useState is asynchronous. The asynchronous behavior seems to be due to the difference between safari and chrome.
> 
> For class components, the following method is recommended.
> 
> ```js
> setState ({target: target}, () => {
>     console.log ("callback");
> });
> ```
> 
> If it's hooks, you should use useEffect originally, but I'm not sure if it's an event. I think you should use setTimeout.
> 
> ```js
>     const nativeEvent = e.nativeEvent;
>     onMouseDown(e, frame);
>     setTarget(e.target);
>     
>     setTimeout(() => {
>       moveable.dragStart(nativeEvent);
>     });
> ```

I need wrap `moveable target` in a Wrap Component to do something. First time, when I mousedown -> **mouseup** -> mousemove, `moveable target` can be drag（It should not be, because mouse is up）. after this time, everything is working fine
This is [Reproduce](https://codesandbox.io/s/moveablejs-bug-miwil?file=/src/App.tsx)
