### ISSUE TITLE
Bug?: Uncaught RangeError when dragging outside of viewport

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#1015]
## Environments
* Framework name: Vanilla JS
* Moveable Component version: 0.55.1
* [Testable Address](https://codesandbox.io/p/sandbox/vite-typescript-starter-lcckqj)

## Description
When upgrading from `0.42.2` -> any after, I encountered an `Uncaught RangeError: Maximum call stack size exceeded` error upon dragging my elements out of the view/viewport.
I did migrate the moveable scroll properties over to using `scrollOptions`.

I looked over the changes made in the release after and I was unable to determine if the issue is on my usage of the library or not.

Note: 
- The codesandbox can end up freezing if you encounter the issue within the editor mode. If you open it in its own tab, it will not freeze.
- You can switch the version of moveable back to `0.42.2` and see that it is working as intended.

**Comment by SidIcarus** [comment]
I took a look at the [storybook infinite-viewer example](https://daybrush.com/moveable/storybook/?path=/story/combination-with-other-components--components-infinite-viewer) and the issue is also within that example.

**Comment by daybrush** [comment]
@SidIcarus 


moveable's new version is released. Check it again.

**Comment by SidIcarus** [comment]
Looks good!
Thank you
