### ISSUE TITLE
How to give initial rotation to groupable?

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#102]
Hi,
Is there a way to initialize groupable in a rotated state? Like regular moveables are initialized to a rotated state if the target is rotated. Can we set the rotate property of a groupable?

**Comment by daybrush** [comment]
@adityakrshnn 

Not yet. I will add it in the next release.

Thank you :)

**Comment by daybrush** [comment]
@adityakrshnn 


`moveable@0.12.0` is released. 

Use `defaultGroupRotate` props (default: 0)
https://daybrush.com/moveable/release/latest/doc/Moveable.html#defaultGroupRotate
