### ISSUE TITLE
clickGroup does not trigger after rotating

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#103]
Hi,

After you rotate a groupable, clickGroup event stops triggering. Can you look into it?

PS. It triggers near right angles. Not otherwise

**Comment by daybrush** [comment]
@adityakrshnn 

Thank you for bug report.

 I will fix it in the next release.

**Comment by daybrush** [comment]
@adityakrshnn 


`react-moveable@0.15.0` is released. Update and check again. Thank you
