### ISSUE TITLE
Is there a way to `dragStart(e)` a component that is different from `e.target`?

### ISSUE THREAD

**Issue by zsoerenm** [daybrush/moveable#1032]
## Description

I have a toolbar from where I want to drag in new components. On some issues it is recommended to use `dragStart(e)` for newly created components, where `e` is the mousedown event.
However, in my case the component that I want to drag hasn't been created yet, when the user clicks the mouse.
I have to create the component on the fly, when the mouse button is down. Hence, the `target` of the mousedown event `e` won't be the target that I'd like to be dragged.
How would I do something like this?

**Comment by daybrush** [comment]
@zsoerenm 

You can use `.dragStart` method


```js
onMousedown={e => {
    e.preventDefault();
    moveable.waitToChangeTarget().then(() => {
         moveable.dragStart(e);
   });
}}
```

https://daybrush.com/moveable/storybook/?path=/story/combination-with-other-components--components-selecto

**Comment by zsoerenm** [comment]
Thanks,
but that problem is that `e.target` is not the element that I want to drag.
The element that I'd like to drag is created on the mouse down. Therefore, the `e.target` is different.

**Comment by daybrush** [comment]
@zsoerenm 

Setting the target to the created element and doing `.dragStart` will not be a problem.

**Comment by zsoerenm** [comment]
Okay, does that mean `moveable.target` and `e.target` don't have to be the same?
I thought it wasn't possible because `e.target` is accessed in Gesto here:
https://github.com/daybrush/gesto/blob/bae238937462160a2c9aedab36ce9e4b7132da3a/src/Gesto.ts#L307
