### ISSUE TITLE
resizable questions

### ISSUE THREAD

**Issue by xoptimal** [daybrush/moveable#1035]
## Environments
* Framework name: moveable
* Framework version: last
* Moveable Component version: last
* Testable Address(optional):

## Description
I would like to inquire about how to immediately activate resizable functionality for a dynamically created div under the react-moveable component. Currently, I am creating a div on a mouse left-click and adding it to the target. However, I want to activate resizable functionality immediately while holding the mouse button down and moving the mouse. Currently, the resizable feature is only triggered when I release the mouse button and hover over the resizable-control. I've tried using the snippet, but it doesn't seem to work!
 ``` 
movableRef.current.moveable.request('resizable', { offsetWidth: 1, offsetHeight: 1, }, true)
``` 

help, please !!!  @daybrush

**Comment by daybrush** [comment]
I think this method is also possible, but what do you think?

```js
// start
const requester = moveable.request("resizable");

// ing
requester.request({ deltaWidth: 10, deltaHeight: 10 });
requester.request({ deltaWidth: 10, deltaHeight: 10 });
requester.request({ deltaWidth: 10, deltaHeight: 10 });


// end
requester.requestEnd();
```

**Comment by xoptimal** [comment]
How do I activate the moveable-control element, which is responsible for scaling at the four points? Typically, scaling is triggered by moving the mouse to a point. Is there a way to manually trigger the scaling operation when the mouse is already on a point but hasn't moved? In other words, how can I manually invoke the scaling operation using the onResizeStart method?  @daybrush
