### ISSUE TITLE
At certain angles, moveable-control handle gets cut

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#104]
Hi,

I have observed that at certain angles, moveable-control handles get cut. Can you look into it please?

![Screenshot 2019-11-25 at 5 53 58 PM](https://user-images.githubusercontent.com/23035769/69540509-bf824a80-0fac-11ea-8c2d-0666146d43fd.png)

**Comment by daybrush** [comment]
@adityakrshnn 

Thank you for bug report.

I will fix it in the next release.

**Comment by daybrush** [comment]
@adityakrshnn 


`react-moveable@0.15.0` is released. Thank you
