### ISSUE TITLE
Moveable `dragEnd` Event Not Firing When Moveable  Created Outside Iframe

### ISSUE THREAD

**Issue by ccpu** [daybrush/moveable#1042]
## Environments
* Framework name:  moveable
* Framework version: 0.52.0
* Moveable Component version:
* Testable Address(optional): [codesandbox](https://codesandbox.io/s/moveable-touch-drag-issue-ztw3vj?file=/src/index.ts:44-52)
* Steps to Reproduce: Click on the element and drag the mouse to interact with it

## Description

I have encountered an issue with the `moveable` library where the "dragEnd" event is not firing when the `Moveable` is created outside an iframe. I need that to keep the Moveable components outside the iframe, hence using a container for that purpose. However, it seems that the "dragEnd" event is not working as expected in this scenario.

I do appreciate if you could suggest workaround so that the "dragEnd" event fires correctly when `Moveable` created outside an iframe and interacts with element inside.

**Comment by daybrush** [comment]
@ccpu 

Sorry. I know it is impossible because the context is different.
