### ISSUE TITLE
moveable-control-box misplaced when used with SVG foreignObject elements on Safari

### ISSUE THREAD

**Issue by DatLe1108** [daybrush/moveable#1048]
## Environments
* Framework name: reactjs
* Framework version: 17.0.2
* Moveable Component version: react-moveable 0.45.1
* Testable Address(optional): [Code Sandbox](https://codesandbox.io/s/dreamy-rumple-nclcjk)

## Description
Hi, I need to render html elements inside a svg therefore i used foreignObject element. The moveable-control-box is renderer correctly on Chrome but misplaced on Safari.

This is what i tried to do
```
 <>
      <Moveable target={target} draggable={true} resizable={true} />
      <svg viewBox="0 0 86 54">
        <foreignObject ref={ref} x="10" y="10" width="20" height="20">
          <div>Hi</div>
        </foreignObject>
      </svg>
</>
```

Below is a screenshot to compare:
Safari 
<img width="546" alt="Screenshot 2023-11-19 at 08 35 19" src="https://github.com/daybrush/moveable/assets/13608513/01846ca1-7b5d-4c55-94b5-7fb9ae7d4e13">

Chrome
![Screenshot 2023-11-19 at 08 34 39](https://github.com/daybrush/moveable/assets/13608513/c4629b78-8a35-4362-8eff-8d1f9b4fec4e)

**Comment by lizaemran** [comment]
I am facing similar issue in Firefox as well

**Comment by daybrush** [comment]
@lizaemran @DatLe1108 


* `croact-moveable` 0.9.0
* `@moveable/helper` 0.1.3
* `lit-moveable` 0.30.0
* `moveable` 0.53.0
* `preact-moveable` 0.55.0
* `react-moveable` 0.56.0
* `svelte-moveable` 0.45.0
* `vue-moveable` 2.0.0-beta.87
* `vue3-moveable` 0.28.0
* `ngx-moveable` 0.50.0


moveable's new version is released. Check it again.
