### ISSUE TITLE
Help request: Element "sliding" when resizing

### ISSUE THREAD

**Issue by miina** [daybrush/moveable#105]
Thanks for this great library!

We're testing your tool out to see if it would be a good fit for the plugin we're developing.

Running into the following issue:
- When resizing an element it slides while resizing. This happens always when rotated and also for each resizing handle without rotation except for the right and bottom handles.

Behavior:
![sliding](https://user-images.githubusercontent.com/3294597/69643368-8658e180-1063-11ea-9d71-3cbdad68f539.gif)

Note that this happens on Chrome and Safari but doesn't seem to happen on Firefox.

https://codesandbox.io/s/react-moveable-sliding-74s5q

Any thoughts on what could we be missing?

Thank you!

**Comment by daybrush** [comment]
@miina 

Thank you for using moveable.

How about updating the version of `react-movable`? Now it's version 0.14.5.

**Comment by miina** [comment]
Uf, right, thanks for pointing that out! It's working as expected with the updated version in Codesandbox.

Oddly though, locally I am using the latest 0.14.5 version but it still seems to not work as expected on Chrome specifically.

Here's the code for reference:
https://github.com/ampproject/amp-wp/blob/11185971897963cef3f1701131740800b2967bcd/assets/src/edit-story/components/canvas/page.js#L95-L150

I suppose it's not easy to understand what could be the issue when it's working OK in codesandbox but let me know if something seems off with the implementation in the file shared above.

Thank you!

**Comment by daybrush** [comment]
@miina 

I think the difference is probably a border. The border will be at least 1px without `box-sizing`.

I just modified it and released it in beta.

Try `npm i react-moveable@beta`.

If there is no problem, i will release official version.

**Comment by miina** [comment]
Thanks a lot for looking into this. Unfortunately, that doesn't seem to solve the issue.

It came out meanwhile that in case of some elements it works fine with the same logic, will try to figure out what's the difference between the working and non-working elements.

**Comment by daybrush** [comment]
@miina 

Can you show me a gif of how local works?

**Comment by miina** [comment]
Just realized what the issue was and why it was working as expected in Firefox and Safari -- I was zoomed out to 75% in Chrome and it looks like it slides while being zoomed out, in other browsers, too.

Does it work as expected for you when zoomed out?

Gif:
![sliding](https://user-images.githubusercontent.com/3294597/69707784-aa1b3680-10fa-11ea-8295-07d1f8f6dc1a.gif)

**Comment by daybrush** [comment]
@miina 

Thank you for your gif, description. This helped me find problems(keepRatio).

I just modified it and released it in beta.

Try `npm i react-moveable@beta`  (react-moveable@0.15.0-beta2)

If there is no problem, i will release official version.

**Comment by miina** [comment]
Seems to work as expected now, thanks a lot for looking into this! 🎉
Let's close the issue once the official version is released.

**Comment by daybrush** [comment]
@miina 

`react-moveable@0.15.0` is released. Thank you

**Comment by miina** [comment]
Thank you!
