### ISSUE TITLE
Help request:  Stop moving component and show bound  in methods onRotate, onResize

### ISSUE THREAD

**Issue by nkushniruk** [daybrush/moveable#106]
Hi, could you help me in using react-movable. I need to use bounds in methods onRotate, onResize same as in a onDrag method -  stop moving "moveable component" and show bound.
![image](https://user-images.githubusercontent.com/51203014/69659633-47d51e00-1087-11ea-8782-225fc948a7ca.png)

As in the picture during onDrag
How to achieve this during onRotate, onResize execution?
Thank you!

**Comment by daybrush** [comment]
@nkushniruk 

`onResize` implements `snappable` & `bounds` if not `keepRatio`.

Unfortunately, `onRotate` is not implemented.

**Comment by daybrush** [comment]
@nkushniruk 

Moveable 0.14.0 is released. Thank you :)
* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0
