### ISSUE TITLE
Moveable control with a different style on each corner

### ISSUE THREAD

**Issue by mysolo** [daybrush/moveable#1076]
## Environments
* Framework name: svelte
* Framework version: 3.52.0
* Moveable Component version: svelte-moveable 0.28.1

## Description

Hello.

can we have a different style of control on each corner?

I'm trying to do as on the screenshot, but the controls have a global css .moveable-control so I can't just change the css. 

Is there a way to do this?

<img width="308" alt="Screenshot 2024-01-18 at 10 30 50" src="https://github.com/daybrush/moveable/assets/11662943/043d7a83-8ca5-4786-8cd1-e3988f0ce1dc">

**Comment by HZZformGD** [comment]
You can use css. each corner has different classname such as  moveable-nw , moveable-ne,  moveable-sw , moveable-se ....etc @mysolo

**Comment by mysolo** [comment]
Thanks. It's nice.
