### ISSUE TITLE
Snappable with Scalable does not work.

### ISSUE THREAD

**Issue by daybrush** [daybrush/moveable#108]
>Hello,
>
>I have the same problem with keepRatio set to false :
>https://codesandbox.io/s/moveablescallingbounds-lh6ms
>
>No problem on drag, but when I scale i'm out of the limit (it's working great when I keep ratio)

@nums

#70

**Comment by daybrush** [comment]
@nums

Moveable is updated. Check it again.

* `moveable` 0.13.0
* `react-moveable` 0.16.1
* `preact-moveable` 0.15.0
* `ngx-moveable` 0.9.0
* `svelte-movable` 0.4.0

**Comment by nums** [comment]
It's working great !!
Thanks :)
