### ISSUE TITLE
Input box failed to get focus

### ISSUE THREAD

**Issue by MrHzq** [daybrush/moveable#110]
#### When using the input box, clicking the input box will not activate
![image](https://user-images.githubusercontent.com/24823464/70117611-d7d72100-16a0-11ea-834a-b28f942e3073.png)

**Comment by daybrush** [comment]
@MrHzq 

Try below:
```js
moveable.on("dragStart", e => {
   if (e.inputEvent.target === inputBox) {
       return false;
   }
});
```

**Comment by MrHzq** [comment]
no effect
![image](https://user-images.githubusercontent.com/24823464/70229209-b0f81800-1790-11ea-8a71-86ca6d155cdb.png)

**Comment by daybrush** [comment]
@MrHzq 

Moveable is updated. Check it again.

* `moveable` 0.13.0
* `react-moveable` 0.16.1
* `preact-moveable` 0.15.0
* `ngx-moveable` 0.9.0
* `svelte-movable` 0.4.0

**Comment by MrHzq** [comment]
## Thank you first
### But It still doesn't work. I use it like this
### Through this [website](https://codepen.io/daybrush/pen/VoQypZ), only `<span>` is replaced with `<input>`
![image](https://user-images.githubusercontent.com/24823464/70697444-7813f200-1d00-11ea-8f8e-0c70abcbb203.png)

Is it because of my wrong way of using？
How to use it correctly？
Thank

**Comment by daybrush** [comment]
@MrHzq 
I'm sorry. I was mistaken.

moveable 0.13.1 is released. Check it below:
```js
moveable.on("dragStart", e => {
    e.stop();
});
```
