### ISSUE TITLE
Moveable not working properly on Safari

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#111]
Hi,

Moveable seems to be mispositioned on Safari (Version 13.0.3 (14608.3.10.10.1)). Can you look into it please?

**Comment by daybrush** [comment]
@adityakrshnn 
Can you give me a demo address to test?

**Comment by daybrush** [comment]
@adityakrshnn 

Is your situation as follows?


https://github.com/daybrush/moveable/issues/100

**Comment by adityakrshnn** [comment]
Turns out it was happening due to some changes I had made to the library. I updated it to the latest version and it is fine now. Thanks
