### ISSUE TITLE
Timeline type bar?

### ISSUE THREAD

**Issue by scottsquirespix** [daybrush/moveable#114]
I'm looking to make a react box that is draggable only in the X axis and resizable from either end, but only that end being resized.
Most of your examples show both sides being moved on a resize action and not clear to me how to lock the other end that's not being manipulated. If I grab the left side of a box for resize, I only want to move it, not the right side also.
I also want to restrict dragging to 1 axis.
In many ways this is like your timeline project but it seems overkill and not resizable from each end directly? (Think of video edit timeline not dependent on key frames)
Just trying see which base components come closest  to what I need. Thanks.

**Comment by daybrush** [comment]
@scottsquirespix 

You just need to use 1axis.

https://codesandbox.io/s/smoosh-architecture-jufyy

**Comment by scottsquirespix** [comment]
Perfect. Thank you!
