### ISSUE TITLE
Examples of displaying images? (React)

### ISSUE THREAD

**Issue by scottsquirespix** [daybrush/moveable#116]
Are there any code examples of using movable with images to resize, drag, scale, rotate, etc?

**Comment by daybrush** [comment]
@scottsquirespix 

Is this what you want?

https://codesandbox.io/s/jovial-leakey-w4bxv

**Comment by scottsquirespix** [comment]
Yes, perfect. Thank you. You might want to add some of the demos you've done for questions to your site for other newcomers.

**Comment by iprasadg** [comment]
@scottsquirespix Yes, agree with you. @daybrush should add more demos for different elements such as image, video, svg, giphy, stickers etc. Hope so they will add soon.

**Comment by daybrush** [comment]
@iprasadg 

Sorry for not meeting your expectations.

It takes a lot of time to complete the various demos.

I'm not going to do it with codesandbox, but now with a storybook, I'm going to show everything in various frameworks.

Please wait. Thank you :)

**Comment by iprasadg** [comment]
@daybrush Yes, I can understand that it will take a lot of time. I am thoroughly going through this **awesome package**. Stuck because of some problems(that's why I am expecting demos) specially with HTML text. I will keep posting.

Big Thank You for your help.
