### ISSUE TITLE
Does Movable require an HTML element to manipulate? (React)

### ISSUE THREAD

**Issue by scottsquirespix** [daybrush/moveable#117]
All the examples show  target={document.querySelector which assumes a html element already exists in the document. Is it possible to provide a react component or dynamically generate elements?

**Comment by daybrush** [comment]
@scottsquirespix 


You just change the target. Then dynamically added elements are possible.

If react component, use `findDOMNode`

**Comment by scottsquirespix** [comment]
Thank you.
