### ISSUE TITLE
Question: Setting `keepRatio` per element in case of group resize

### ISSUE THREAD

**Issue by miina** [daybrush/moveable#118]
When implementing group resizing, there are some elements that would require `keepRatio`, others not. Is it possible to set `keepRatio`
a) per element,
b) depending on the resize handle that's being used?

Thank you!

**Comment by daybrush** [comment]
@miina


The default keepRatio for a group is true.

You can change keepRatio to false. But because minWidth exists, it may not be perfect.

**Comment by miina** [comment]
Thanks for the quick answer.

Is it possible to change the `keepRatio` per element? So that one of the elements in the group would have `keepRatio` as `false` and the other as `true`? Or is it always either `true`/`false` for the whole group?

**Comment by daybrush** [comment]
@miina 

It seems hard yet. There is also a snap problem and the calculation is not simple. sorry..

**Comment by miina** [comment]
OK, thank you!
