### ISSUE TITLE
Element snaps with elementGuideline and verticalGuideline at the same posiiton

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#121]
Hi,
If one element is exactly centered on a vertical guideline, on dragging another element to that position, it snaps with both element and vertical guideline. Can you please check?

![ezgif-5-9f6dc6fe8258](https://user-images.githubusercontent.com/23035769/70526432-8bdc1e80-1b6f-11ea-8996-971a18bc5d6c.gif)

**Comment by daybrush** [comment]
@adityakrshnn 

Moveable is upaded. Check it again.

* `moveable` 0.13.0
* `react-moveable` 0.16.1
* `preact-moveable` 0.15.0
* `ngx-moveable` 0.9.0
* `svelte-movable` 0.4.0

**Comment by adityakrshnn** [comment]
The issue is solved for verticalGuidelines but persists for horizontalGuidelines.

**Comment by daybrush** [comment]
@adityakrshnn 

moveable 0.13.1 is released. Check it again.

**Comment by adityakrshnn** [comment]
I don't think this issue is solved. Can you check again? Both vertical and horizontal guidelines are misbehaving. It happens sometimes and sometimes not.

![ezgif-1-68ebfbcb9e05](https://user-images.githubusercontent.com/23035769/71060125-b12de580-218a-11ea-8e84-2caf8367da5a.gif)

**Comment by daybrush** [comment]
@adityakrshnn 

moveable's new version is released.

* `moveable` 0.13.2
* `react-moveable` 0.16.3
* `preact-moveable` 0.15.2
* `ngx-moveable` 0.9.2
* `svelte-moveable` 0.4.2

Check it again. Thank you :)
