### ISSUE TITLE
Scale rotated elements bug

### ISSUE THREAD

**Issue by LCGijs** [daybrush/moveable#123]
Scaling rotated elements shows unexpected behavior as you can see in the gif below.

![rotate scale bug](https://user-images.githubusercontent.com/55280200/70801372-047cee00-1daf-11ea-88b3-4a4e9bdadaba.gif)

[I have created a Codepen where you can checkout my code. ](https://codesandbox.io/s/moveable-rzqhr?fontsize=14&hidenavigation=1&theme=dark)

Besides this bug, I also experience problems when scaling groups of elements. See my latest comment at issue #41 for extra info. Let me know if you would like me to provide a Codepen for that issue!

**Comment by daybrush** [comment]
@LCGijs 

When rotating after scale, the axis is distorted.

So try to scale after rotating:

```js
  target.style.transform =
      `translate(${frame.translate[0]}px, ${frame.translate[1]}px) ` +
      `rotate(${frame.rotate}deg)` +
      `scale(${scale[0]}, ${scale[1]})`;

```

**Comment by LCGijs** [comment]
Scaling after rotating solves the issue. Thank you very much for your help.

**Comment by Hexiota** [comment]
@daybrush I ran into this issue just now, maybe could consider it for a future bugfix? Above solution worked, though!

p.s. love this library and what you're doing!
