### ISSUE TITLE
Scaling of group does not match origin

### ISSUE THREAD

**Issue by LCGijs** [daybrush/moveable#124]
When scaling a group horizontally, the group also scales vertically.

![group scale bug](https://user-images.githubusercontent.com/55280200/70807338-a86d9600-1dbd-11ea-9b10-54754379aff1.gif)

[I've created a codepen with all the code to reproduce the above gif. ](https://codesandbox.io/s/xenodochial-elbakyan-l7nuq?fontsize=14&hidenavigation=1&theme=dark)

The expected behavior is that the boxes only scale in horizontal direction when scaling them horizontally (just like programms as Sketch and Illustrator).

**Comment by daybrush** [comment]
@LCGijs 


Thank you for reporting bug.
 I will fix the bug.
However, setting keepRatio to false in a group is very incomplete.

**Comment by daybrush** [comment]
@LCGijs 

* `moveable` 0.13.2
* `react-moveable` 0.16.3
* `preact-moveable` 0.15.2
* `ngx-moveable` 0.9.2
* `svelte-moveable` 0.4.2

Check it again. Thank you :)
