### ISSUE TITLE
Calling updateTarget doesn't always adapt to the changes of an element

### ISSUE THREAD

**Issue by TrevorSundberg** [daybrush/moveable#125]
If I create a Moveable for an `<img>` element that takes a little bit to load, when the Moveable is created it will obviously not know the size, however if I call `updateTarget` after the `<img>` loads it does not update to the new size of the image. Interestingly, if I change the translation of the `<img>` and call `updateTarget` it does move, it just won't adjust to the new size.

![Screenshot from 2019-12-14 13-08-00](https://user-images.githubusercontent.com/4644253/70854615-e11b7700-1e72-11ea-9bcd-34ea9b3b90b3.png)

**Comment by daybrush** [comment]
@TrevorSundberg 

updateTarget seems to be caused by not obtaining the width and height of the target. How about using updateRect?

**Comment by TrevorSundberg** [comment]
I see! When I read the docs, I didn't realize it mean the actual `width` and `height` dom property. Using `updateRect` fixed it, thank you.
