### ISSUE TITLE
Svelte codesandbox demo: doesn't work with latest version of svelte

### ISSUE THREAD

**Issue by blobinabottle** [daybrush/moveable#126]
Hello

When using the codesandbox demo of moveable Svelte it works really well except when you try to update to the latest Svelte version 3.16.x you get the error:
`Cannot read property 'container' of undefined`

Is it a simple fix? I can't seem to find it.

**Comment by daybrush** [comment]
@blobinabottle 

Thank you for bug reporting.

svelte-guides was the problem.

Minor versions of svelte were not compatible. Updated and fixed.

https://codesandbox.io/s/svelte-moveable-demo-qi7fu

**Comment by blobinabottle** [comment]
Awesome!
But, I don't know if you saw that the guides are not working anymore now (sorry for only reporting bugs at the moment :-))
