### ISSUE TITLE
Snappable is broken

### ISSUE THREAD

**Issue by copthuy** [daybrush/moveable#127]
Check your demo page. Snappable is now broken. Version 0.12.0 was working.

**Comment by daybrush** [comment]
@copthuy 

Thank you for bug reporting.
I will fix it soon.

**Comment by copthuy** [comment]
To make it work, you have to set **bounds** option. Even empty value. `bounds: {}`

**Comment by daybrush** [comment]
@copthuy 

I modified it and it seems to work fine now. Check it again.
Thank you :)

**Comment by copthuy** [comment]
Perfect! Thanks for the great library.
