### ISSUE TITLE
Crash of ngx-moveable when using --prod on angular

### ISSUE THREAD

**Issue by JulesVi** [daybrush/moveable#129]
Hello,
![image](https://user-images.githubusercontent.com/39760183/71158133-a84d1a80-2243-11ea-9e01-0934146fe7d9.png)
I have a problem only on prod mode on angular (0.9.1) : When I use the change detection with a ngif, when it has to run the ngx-moveable module, the module crash in loop has the error here

**Comment by daybrush** [comment]
@JulesVi 

Can you give me an address to test?
Or give me code to test.

I've tested it but it doesn't work.
```html
 <ngx-moveable
      #moveable
      *ngIf="resizable"
      [target]="target"
      [draggable]="true"
      [origin]="false"
      [rotatable]="true"
      [pinchable]="true"
      [scalable]="scalable"
      [resizable]="resizable"
      [warpable]="warpable"
      [keepRatio]="false"
      [throttleDrag]="1"
      [throttleScale]="0.01"
      [throttleRotate]="0.2"
      [throttleResize]="1"
      (drag)="onDrag($event)"
      (resize)="onResize($event)"
      (scale)="onScale($event)"
      (warp)="onWarp($event)"
      (rotate)="onRotate($event)"
      (pinch)="onPinch($event)"
      (dragEnd)="onEnd()"
      (resizeEnd)="onEnd()"
      (scaleEnd)="onEnd()"
      (warpEnd)="onEnd()"
      (rotateEnd)="onEnd()"
      (pinchEnd)="onEnd()"
      >
    </ngx-moveable>
```
```js
"@angular/animations": "~9.0.0-rc.7",
    "@angular/common": "~9.0.0-rc.7",
    "@angular/compiler": "~9.0.0-rc.7",
    "@angular/core": "^9.0.0-rc.7",
    "@angular/forms": "~9.0.0-rc.7",
    "@angular/platform-browser": "~9.0.0-rc.7",
    "@angular/platform-browser-dynamic": "~9.0.0-rc.7",
    "@angular/router": "~9.0.0-rc.7",
```

**Comment by JulesVi** [comment]
Hello, thanks for your answer.
I explained my problem the wrong way : I am on angular 8, but I have the problem of crash with Ngx-Moveable 0.9.2, and I use this in my code to avoid to much detections : 
ngAfterViewInit() {
        setTimeout(() => {
            this._cdRef.detectChanges();
        });
    }
Maybe it can be linked and cause trouble on prod mode ?

**Comment by daybrush** [comment]
@JulesVi 

I tried to try but it doesn't work.

Can you help me?
https://github.com/daybrush/movable-angular-error

**Comment by JulesVi** [comment]
I tried to reproduce it on an other project but it didn't happn so I will come back to you when I manage to reproduce it frequently

**Comment by daybrush** [comment]
@JulesVi 

I'm not sure why. do try `npm ci`

**Comment by JulesVi** [comment]
Hello,
I noticed something : with using an old version (0.5.7 and before) of ngxMoveable, it works perfectly, even on prod mode,
But when I come back to a newer version, it still make the "P is not a function" and signal errors on Preact (I am on Angular)
I hope it can help you

**Comment by daybrush** [comment]
@JulesVi 

Can you show me formatted code : main.***.js:1:8179   and "__e", "T", "preact_module_b"

**Comment by JulesVi** [comment]
The console show that this code seems to be problematic 

[error.js.txt](https://github.com/daybrush/moveable/files/4026408/error.js.txt)

**Comment by daybrush** [comment]
@JulesVi 

A new version has been released.
* `moveable` 0.13.4
* `react-moveable` 0.16.6
* `preact-moveable` 0.15.5
* `ngx-moveable` 0.9.4
* `svelte-moveable` 0.4.4


Update to the new version. Thank you :)

**Comment by JulesVi** [comment]
Hello,
Thanks for your hard work but after testing, reinstalling modules etc, it still the same error...

**Comment by JulesVi** [comment]
Here is the code linked to the error

[error2.js.txt](https://github.com/daybrush/moveable/files/4052938/error2.js.txt)

**Comment by daybrush** [comment]
@JulesVi 
This problem seems to be difficult to solve the problem over without removing preact.
I think it will need to replace preact and it will take a little longer. Thank you.

**Comment by JulesVi** [comment]
Okay I understand, thank you !

**Comment by daybrush** [comment]
@JulesVi 
I worked to remove the problem preact and released the next version. Would you like to test with the next version?

```js
$ npm i ngx-moveable@next
```

**Comment by JulesVi** [comment]
Hello, thanks, it is no more crash !
I share you this project https://github.com/JulesVi/BugsDragResize where you can see with activating and moving the tiles that only the first one is wrapped by the module, the other are create but not wrapped

**Comment by JulesVi** [comment]
Hello, do you have any update ? Thanks

**Comment by daybrush** [comment]
@JulesVi 

I will update it this week.

**Comment by daybrush** [comment]
@JulesVi 

Moveable 0.14.0 is released. Thank you :)
* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0

**Comment by JulesVi** [comment]
Hello, sorry to reOpen the issue, but after the updates of the module, I tried on the project that I shared to you before, but it is not resolving the problem : 
Only one tile is moving, not the others wich are created in the same time..
I share to you the link of the project : https://github.com/JulesVi/BugsDragResize

Thanks

**Comment by daybrush** [comment]
@JulesVi 

Maybe duplicate #189 #187

**Comment by JulesVi** [comment]
This seems to be the same problem, thanks

**Comment by JulesVi** [comment]
Update: Your update worked very well to make all the tiles moving, but when I want to quit the "edit" mode, the moveable element doesn't disappear. When I want to edit again, it creates a new moveable element (on the same project that I have shared before)

**Comment by daybrush** [comment]
@JulesVi 


This is a `react-simple-compat` issue and I've updated it once more. Check it again.

https://github.com/daybrush/react-simple-compat

**Comment by JulesVi** [comment]
This is perfect, thanks a lot for your work !
