### ISSUE TITLE
Error This dependency was not found: preact/compat

### ISSUE THREAD

**Issue by abinhho** [daybrush/moveable#131]
Hello,

I installed `"moveable": "^0.13.1",` then run start dev and got error
```
$ npm run serve

 ERROR  Failed to compile with 2 errors                                                                                                                                                                            12:28:56 PM

This dependency was not found:

* preact/compat in ./node_modules/preact-css-styler/dist/styler.esm.js, ./node_modules/preact-moveable/dist/moveable.esm.js

To install it, you can run: npm install --save preact/compat
```

Then I also run `npm install --save preact/compat` but got error module not found.

```
$ npm install --save preact/compat

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/preact/compat.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/binhho/.npm/_logs/2019-12-20T05_24_07_519Z-debug.log
```

Then I tried to run `npm install --save preact-compat` successfully but `This dependency was not found:` still not resolved.

Please help!

**Comment by daybrush** [comment]
@abinhho 

`preact/compat` module is `preact`

you can try below:
`npm i --save preact`


But moveable has a preact dependency, and I'm not sure why that happens. Can you give me a testable address?

**Comment by abinhho** [comment]
@daybrush 
I found the problems. 
I changed `preact: ^8.*` to `preact: ^10.1.1` from package.json then it's worked like champ.

Thank you!

**Comment by daybrush** [comment]
@abinhho 

Glad to be solved. In the past, moveable had preact 10 or higher.

Thank you :)
