### ISSUE TITLE
Is there a way to remove line dom elements (moveable-lines in control-box)?

### ISSUE THREAD

**Issue by makis-spy** [daybrush/moveable#133]
Hi thank you for the library. Really enjoying the control it offers.

I can't for the life of me figure out how to disable the extra "moveable-line" divs inserted in the control box. All I need is one resize handle. 

My config in react is:

  <Moveable
                        target            ={this.state.element}
                        ref               = {mv => this.mov = mv }
                        origin            ={false}
                        edge              ={false}
                        draggable         ={true}
                        throttleResize    ={this.props.hourWidth}
                        throttleDrag      ={this.props.hourWidth}
                        resizable         ={true}
                        renderDirections  = {["e"]}

Thanks for the help!

**Comment by daybrush** [comment]
@makis-spy 

Sorry there's no way yet.

But you can specify a className and use it like this:
`` `
.className .moveable-line {
     display: none;
}
`` `

**Comment by makis-spy** [comment]
Gotcha! Thanks very much!
