### ISSUE TITLE
make E, W, N & S controls full width

### ISSUE THREAD

**Issue by koraysels** [daybrush/moveable#134]
Hi, thanks for this amazing module!

I was trying to customize it so that the scale controls for each edge are 'grabbable' on the full width or heigth of resizable element  (the E, W, N & S movable-controls).. is that possible? I tried using css but the handles are not positioned within the actual element so I couldn't make it work.

**Comment by daybrush** [comment]
@koraysels

I didn't understand what you said.

Do you think the bottom is right?

```js
<Moveable
    renderDirections={["n", "e", "w", "s"]}
 />
```

**Comment by koraysels** [comment]
No, sorry. I mean that the squares could span the entire length instead of just being a 14px by 14px square... so the user can grab anywhere alongside an edge to start scaling... (like you see with jquery-ui resizable)

**Comment by daybrush** [comment]
@koraysels 
Do you probably want to change css to custom?

How about a demo below?

https://codesandbox.io/s/funny-williams-302e6


See also the following document.
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-custom-css

**Comment by koraysels** [comment]
well, I think you still misunderstood. Sorry English is not my native language and I don't really knwo how to make it more clear. 
To take the square in your demo for example, I want to have the _complete_ length of each side to be 'grabbable' like in the jquery example I linked to above. So that you can grab anywhere _alongside_ any edge of that square and resize.. Is that even possible with moveable?

**Comment by daybrush** [comment]
@koraysels 

Do you mean edge option?
```jsx
<Moveable
    edge={true}
 />
```

**Comment by koraysels** [comment]
omg! i just found it myself andd was returning top this question to update it. thank you that was it! Also the classname property helped to make the lines a bit thicker so they are more easily grabbed by the mousepointer! thank you so much for this library ;)!
