### ISSUE TITLE
While resizing, control box is moving only in one direction. (In Angular)

### ISSUE THREAD

**Issue by iprasadg** [daybrush/moveable#135]
@daybrush Hello,

I am working with ngx-moveable in Angular. I am trying to apply resize on an image. Resizing is working fine but the control box along with target always move only in one direction (Top Left).

Ideal Behavior Should: 
for e.g If user resize from top-left then box should moves towards bottom-right.

Need Help
Thanks.

**Comment by daybrush** [comment]
@iprasadg 

The behavior I'm expecting and wanting is:

![Dec-28-2019 14-43-51](https://user-images.githubusercontent.com/3433062/71539529-a93b2600-2980-11ea-8994-0919beaa7652.gif)

Is the action by your code up or down?

![Dec-28-2019 14-44-37](https://user-images.githubusercontent.com/3433062/71539534-ca9c1200-2980-11ea-94be-246fd1da6f73.gif)

**Comment by iprasadg** [comment]
Sorry I didn't get you. Sharing my code below.

[Codesandbox](https://codesandbox.io/s/modern-wood-rtbsh?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ajinkya-dev** [comment]
@daybrush @iprasadg 
I'm also facing similar issue.
BTW, thanks for such **awesome package**.
Thanks in advance.

**Comment by daybrush** [comment]
@iprasadg  @ajinkya-dev 

is this code?
```js
this.frame.set("width", `${width}px`);
this.frame.set("height", `${height}px`);
this.frame.set("left", `${drag.left}px`);
this.frame.set("top", `${drag.top}px`);
```

**Comment by iprasadg** [comment]
@daybrush Thanks buddy, I think I should give you a **party** :)

**Comment by ajinkya-dev** [comment]
@daybrush Thanks. Enjoying to play with this package.

**Comment by JulesVi** [comment]
Hello,
Sorry to reopen the issue but I have troubles with the resize (on angular) on left and top of the tiles on this project :
https://github.com/JulesVi/BugsDragResize
Do you have an idea of this strange behaviour ?
Thanks

**Comment by daybrush** [comment]
@JulesVi 

It seems to use `translate`, `top , left` in resize redundantly.
It also seems that the top and left sides are asynchronous.

How about below:
```js
temp.setPos(drag.beforeTranslate[0], drag.beforeTranslate[1]);

target.style.left = `${drag.beforeTranslate[0]}px`;
target.style.top = `${drag.beforeTranslate[1]}px`;
```

**Comment by JulesVi** [comment]
It works perfectly !
Thanks
