### ISSUE TITLE
Mobile behavior

### ISSUE THREAD

**Issue by TrevorSundberg** [daybrush/moveable#139]
Firstly, thanks for the library. As far as desktop is concerned it is perfect!

There's a few issues I have with how the touch interactions work. This is partly a question to ask if these are intentional, but if they're not I can split them into multiple issues:

1. When you start a drag with one finger, you can't press down a second finger to start scaling and rotating (you can only drag). It seems like there's a distance factor to this one, because if you only move slightly you can put the second finger down.
2. To scale or rotate, both fingers must be inside the box. This is incredibly difficult if you have small things that you're trying to manipulate. On applications like snap-chat when you want to rotate and scale, only one finger needs to be inside and the other can be outside (only used for reference when scaling or rotating).
3. When you're doing a two finger operation such as scaling/rotating/dragging, if you let up on one finger the entire operations stops. I believe it should continue dragging. This is also true if you start a single finger drag, then put a second finger down, and then release that second finger (it stops).
4. When you're doing a two finger scale, it seems like the center or origin moves in a strange way. For example, on the [demo page](https://daybrush.com/moveable/) if you put your fingers horizontal like this: O----------O but at the bottom of the "Moveable" box, when you start to scale the "Moveable" text moves downward. I would expect it to move upward.

Again, fantastic library! I'm developing an application that's both mobile and desktop and I would love to use the same library for both.

**Comment by daybrush** [comment]
@TrevorSundberg 

Thank you for Feature Request.

Your opinion was well understood.

Maybe pinchOutside? It will add an option to solve the central problem of pinch.

**Comment by daybrush** [comment]
@TrevorSundberg 
moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1


add `pinchOutside` props. (default: true)

Check it again.

**Comment by TrevorSundberg** [comment]
Awesome! I'll update to the latest soon. If you want to see a neat demo of using moveable:
https://madeitfor.fun

Works well on mobile too, and with this change it will be even better :)

**Comment by TrevorSundberg** [comment]
Thank you, this worked really well. I had to set `pinchThreshold` to a high value otherwise it seemed like `pinchOutside` did nothing (I just used `Number.MAX_SAFE_INTEGER`). Thank you!

**Comment by gustavopch** [comment]
> 1\. When you start a drag with one finger, you can't press down a second finger to start scaling and rotating (you can only drag). [...]
> 3\. When you're doing a two finger operation such as scaling/rotating/dragging, if you let up on one finger the entire operations stops. I believe it should continue dragging. This is also true if you start a single finger drag, then put a second finger down, and then release that second finger (it stops).

Were these fixed? They still happen when I try https://daybrush.com/moveable/storybook/index.html?path=/story/basic--basic-pinchable on an iPhone.

**Comment by retoruto-carry** [comment]
I am also experiencing a similar issue. Is there any solution?

> > 1. When you start a drag with one finger, you can't press down a second finger to start scaling and rotating (you can only drag). [...]
> > 3. When you're doing a two finger operation such as scaling/rotating/dragging, if you let up on one finger the entire operations stops. I believe it should continue dragging. This is also true if you start a single finger drag, then put a second finger down, and then release that second finger (it stops).
> 
> Were these fixed? They still happen when I try https://daybrush.com/moveable/storybook/index.html?path=/story/basic--basic-pinchable on an iPhone.

I am also experiencing a similar issue. Is there any solution?
