### ISSUE TITLE
Resize issue after rotate (Angular)

### ISSUE THREAD

**Issue by ajinkya-dev** [daybrush/moveable#140]
After rotate if we resize, the edge point from which resizing occurs the opposite edge point is shaking around its position.
ex. After rotate, while resizing with point "SE" the opposite "NW" is shaking around its position.

[Demo](https://codesandbox.io/s/distracted-water-1j3dr?fontsize=14&hidenavigation=1&theme=dark)

Note:
For better understanding zoom your browser.

Thanks

**Comment by daybrush** [comment]
@ajinkya-dev 


It's a rendering issue, but we'll fix that in the next version.

Would you like to use the following temporarily?

```css
.moveable-line {
    will-change: transform;
}
```

**Comment by ajinkya-dev** [comment]
@daybrush 
It's not working.
Will wait for next version as its not a major issue.
Thanks

**Comment by daybrush** [comment]
@ajinkya-dev 

I think it looks right, is it strange?
https://codesandbox.io/s/bold-sea-yjz5v

**Comment by ajinkya-dev** [comment]
@daybrush 
Without rotate resizing is working fine (No shaky behavior). But after rotate, if we resize control box starts to shake.

See attached gif:

![resize_issue](https://user-images.githubusercontent.com/52629529/71708590-6e217280-2e18-11ea-841b-0ae699ea5dba.gif)

**Comment by daybrush** [comment]
@ajinkya-dev 
Sorry for the late reply.

 try setOrigin?

```js
onResizeStart({ dragStart, setOrigin }) {
    setOrigin(["%", "%"]);
  }
```

**Comment by ajinkya-dev** [comment]
@daybrush 
Thanks for the reply.
It's working now. The moveable control box is not shaking. But still the NW point is shaking, is that suppose to happen even after setOrigin(["%", "%"]); ?

**Comment by daybrush** [comment]
@ajinkya-dev
Can you show me how much it shakes with a gif?

**Comment by ajinkya-dev** [comment]
@daybrush 
After adding setOrigin(["%", "%"]); it is behaving much better than before. But still after rotate shaky behavior starts. Check below:

![shaky_behavior](https://user-images.githubusercontent.com/52629529/72058761-a92f1480-32f6-11ea-9228-c96f068dad0f.gif)

[Code Demo](https://codesandbox.io/s/clever-bassi-zs82n)

**Comment by daybrush** [comment]
@ajinkya-dev 

left, top are shaken because they are calculated as integers and are incorrect for resize calculations. Use transform, translate instead

https://codesandbox.io/s/wonderful-satoshi-3kkh9

**Comment by ajinkya-dev** [comment]
@daybrush 
It is working now.
Thanks.
