### ISSUE TITLE
How to display snap distance when drag?

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#142]
Please tell me how to display snap distance as following photo:
![Screenshot from 2020-01-03 16-48-08](https://user-images.githubusercontent.com/51266596/71717008-35e65800-2e49-11ea-8874-0d493f95be5c.png)

Where: sfs is distance (px)

**Comment by daybrush** [comment]
@ladifire 

It doesn't provide the following features yet.

I will add this feature in a future version.

**Comment by ladifire** [comment]
Thanks you!

**Comment by daybrush** [comment]
@ladifire 

Moveable 0.14.0 is released. Thank you :)
* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0

**Comment by ladifire** [comment]
I think the decimal number for snap distance is not necessary, you should round it up.
And one more problem:

See this demo: [https://codesandbox.io/s/react-moveable-with-full-drag-select-wb0so](https://codesandbox.io/s/react-moveable-with-full-drag-select-wb0so)

When there's at least one SAME size element with DRAGGING ELEMENT, snap display 3 snap lines. This is not necessary.

Thanks you!

**Comment by daybrush** [comment]
@ladifire 
I will remove duplicate snap size display and add snapDigit props

**Comment by daybrush** [comment]
@ladifire 

* `moveable` 0.15.1
* `react-moveable` 0.18.0
* `preact-moveable` 0.17.0
* `ngx-moveable` 0.11.0
* `svelte-moveable` 0.6.0

Use `snapDigit`. (now default is 0) (previous 4)

https://daybrush.com/moveable/release/latest/doc/Moveable.html#snapDigit
