### ISSUE TITLE
Drag only X axis or Y axis when hold SHIFT like Photoshop, Illustrator?

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#145]
Can you implement this feature?

**Comment by daybrush** [comment]
@ladifire 

I have no photoshop or illustrations. Do you have an example gif?

I have an app called designer and when I press shift it works like this:

![Jan-06-2020 21-18-13](https://user-images.githubusercontent.com/3433062/71817764-4f4a0700-30ca-11ea-9fec-dca22a38a5f6.gif)

**Comment by ladifire** [comment]
Yes, absolutely same your app. Press Shift to drag Horizontal and vertical

**Comment by daybrush** [comment]
@ladifire 

Moveable 0.14.0 is released. Thank you :)
* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0
