### ISSUE TITLE
External drag handle just like rotate

### ISSUE THREAD

**Issue by iprasadg** [daybrush/moveable#148]
@daybrush Is there any way to add external drag handle as dragging becomes very difficult when it comes to text which is having attribute contenteditable set to true. If it is possible to add external drag handle then user can edit the text as well as he can drag it easily.

**Comment by ladifire** [comment]
@iprasadg  I think it's not necessary, if a item is contenteditable=true, just consider click outside to make contenteditable=false then drag normally.

**Comment by iprasadg** [comment]
@ladifire When width of text content and moveable box is same then dragging becomes very difficult as content is in edit mode. So, it is not user friendly. If somehow we manage to give external handle fro drag just like rotate then it will become more user friendly.

**Comment by daybrush** [comment]
@iprasadg 

Can I give it something similar to `padding`?

**Comment by iprasadg** [comment]
@daybrush Yes padding is one of the option. But still I'll prefer external drag handle, which is user friendly also.

**Comment by schester44** [comment]
yeah dragging a full-width text/input box is really hard.

**Comment by iprasadg** [comment]
@daybrush Can you please give any update on this feature? Thanks in advance

**Comment by daybrush** [comment]
@iprasadg  @schester44  @ladifire 

moveable's new version is released.
* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

add `dragTarget ` props.

like this:
```js
moveable.dragTarget = document.querySelector(".otherTarget");
```

**Comment by zis-wtag** [comment]
What if there are two drag targets? How to implement that?
