### ISSUE TITLE
[New Plugin] Click Drag to select for Moveable ❤❤❤

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#149]
Hi all,
I've made an app with react-moveable, the click drag to select is like this demo:
![ezgif com-crop](https://user-images.githubusercontent.com/51266596/71961458-ee394500-3229-11ea-8faa-e46d5a8e2817.gif)
If you need this feature, please comment bellow this, I'll to publish it if much people need this.

**Comment by daybrush** [comment]
@ladifire 
![Jan-08-2020 18-00-54](https://user-images.githubusercontent.com/3433062/71964449-efc23780-3240-11ea-9513-9321d3b88393.gif)

I am making a component called `selecto` and will probably be released this month.

Of course, React, Angular, Vue, Svelte, Preact, Lit will be supported.

Thank you :)


It will probably be supported in the example:

```js
import Selecto from "react-selecto";

<Selecto
    ref={selectoRef}
    dragContainer={document.body}
    keyContainer={window}
    selectFromInside={false}
    selectByClick={true}
    selectableTargets={[".target"]}
    toggleContinueSelect="shift"
    hitRate={0}
    onDragStart={(e: any) => {
        if (moveableRef.current?.isMoveableElement(e.inputEvent.target)) {
            return false;
        }
        return;
    }}
    onSelectEnd={e => {
        setTimeout(() => {
            setTargets(e.selected);

            if (e.isDragStart) {
                e.inputEvent.preventDefault();
            }
        });
    }}
    />
<Moveable
    ref={moveableRef}
    target={targets}
    draggable={true}
    onClickGroup={e => {
        selectoRef.current!.click(e.inputEvent, e.inputTarget);
    }}
     />
```

**Comment by ladifire** [comment]
Refer to my solution: [https://github.com/daybrush/moveable/issues/154](https://github.com/daybrush/moveable/issues/154)

**Comment by vmdao** [comment]
This feature is great, hope it release soon!

**Comment by happylinks** [comment]
@daybrush are you planning to release this? The storybook looks great! (https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--you-can-change-the-moveable-target-in-real-time-by-selecting-it) I can also get it from npm I saw, but the github repo is unavailable (not public?).

**Comment by daybrush** [comment]
@happylinks 
not yet.

I am so busy these days that I have no time to work.

**Comment by happylinks** [comment]
Ahh that's alright, thanks for the response!
Would you consider making the github repo available already? Or are you not comfortable with that yet?
If not I understand, no worries :)
Take care!

**Comment by daybrush** [comment]
@
