### ISSUE TITLE
Control points rotation is wrong

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#151]
## Environments
* Framework name: React
* Framework version: 16
* Component name:  Control points
* Component version:
* Testable Address(optional): No

## Description
Please this gif. When using rectangle shape for control points. The rotation set for them is wrong.

Please fix this in future version.
![captured](https://user-images.githubusercontent.com/51266596/72058303-79860980-3302-11ea-8282-e39dc75e9143.gif)

**Comment by daybrush** [comment]
@ladifire 

What is the component version? This problem has been solved for a long time?

<img width="624" alt="스크린샷 2020-01-10 오전 1 03 56" src="https://user-images.githubusercontent.com/3433062/72083393-1a95b400-3345-11ea-8a45-64bf1df680f0.png">



<img width="813" alt="스크린샷 2020-01-10 오전 1 06 05" src="https://user-images.githubusercontent.com/3433062/72083578-65afc700-3345-11ea-86d6-c9c4ff9281d3.png">

**Comment by ladifire** [comment]
This bug is in react-moveable package, please see this demo
[https://codesandbox.io/s/react-moveable-demo-66w9h](https://codesandbox.io/s/react-moveable-demo-66w9h)

**Comment by daybrush** [comment]
@ladifire 

This problem will be solved by updating react-moveable.

**Comment by daybrush** [comment]
@ladifire 

What version of react-moveable are you using?

**Comment by ladifire** [comment]
Yes! thankyou!

**Comment by iprasadg** [comment]
@daybrush In ngx-movable (version 0.9.3) also the direction cursor is not updating.

**Comment by daybrush** [comment]
@iprasadg 

What does it mean that the direction cursor doesn't update? is it custom CSS? Can you give me a gif?

**Comment by iprasadg** [comment]
@daybrush Without rotate cursor styles are correct i.e showing according to direction. But, after rotate cursor style should get updated. It is showing previous style of cursor. See the following gif

![cursor](https://user-images.githubusercontent.com/59184039/72162133-64cf7180-33e7-11ea-82b1-f2d694ec0381.gif)

**Comment by daybrush** [comment]
@iprasadg 

Oh I didn't think that part. This may take a while, but I'll fix it soon.

**Comment by ladifire** [comment]
This is so difficult to fix, because it's cursor, not part of component. I find out that Figma (https://www.figma.com/) generate cursor for every rotate then assign each cursor for each rotation position.

**Comment by daybrush** [comment]
@ladifire 

I'm thinking about it too, but probably an svg cursor. I'm thinking of changing the angle every 10 degrees.

**Comment by daybrush** [comment]
@ladifire  @ladifire 
There may be browser support issues, so the default is likely to be 45 degrees.

**Comment by ladifire** [comment]
Your last commit not working with edge={true}
![captured (3)](https://user-images.githubusercontent.com/51266596/72197735-2b364f00-3457-11ea-931e-c8020c02fa00.gif)

**Comment by daybrush** [comment]
@ladifire  @iprasadg 

A new version has been released.
* `moveable` 0.13.4
* `react-moveable` 0.16.6
* `preact-moveable` 0.15.5
* `ngx-moveable` 0.9.4
* `svelte-moveable` 0.4.4


Update to the new version. Thank you :)

**Comment by ladifire** [comment]
Thanks @daybrush, it's sunday but you've worked hard!

**Comment by iprasadg** [comment]
@daybrush Updated to the new version. Thanks for resolving issue. 👍
