### ISSUE TITLE
How to handle Group resize?

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#157]
Hi @daybrush 
Please see my demo [https://codesandbox.io/s/react-moveable-with-full-drag-select-9cg81](https://codesandbox.io/s/react-moveable-with-full-drag-select-9cg81)

With group resize, it's look like scale, not resize
![captured (4)](https://user-images.githubusercontent.com/51266596/72407466-37d9e080-3792-11ea-94eb-588d699bb3e0.gif)

**Comment by daybrush** [comment]
@ladifire 

I've tested it, but there's no problem, and resize (keepRatio: true) works just like gif

**Comment by ladifire** [comment]
@daybrush 
I found out that if `keepRatio` is `undefined` => moveable keep ratio. ??
May be missing check `Boolean(props.keepRatio)`

**Comment by daybrush** [comment]
@ladifire 
The default value is keepRatio is false for single targets and true for group.


keepRatio (false) in a group will only work if all target rotations are equal. Others will have a problem.

**Comment by ladifire** [comment]
If we don't assign `keepRatio`, it also `FALSE` default, OK
But if we using like this:
`<Moveable keepRatio={this.state.shiftKey}....` and `this.state.shiftKey` is `undefined` => Moveable detect it is TRUE

**Comment by ladifire** [comment]
> The default value is keepRatio is false for single targets and true for group
OK understand
