### ISSUE TITLE
snap option

### ISSUE THREAD

**Issue by comiewcom** [daybrush/moveable#16]
Are you planning to add the snap option?
For example, while holding down the shift key, it is easy to adjust the rotation to 0, 90, 180 and 270 degrees.

**Comment by daybrush** [comment]
@comiewcom 
Hi ~ :)
You probably mean `throttleRotate`.

Use as follows.
```
<Moveable
    throttleRotate={isShift ? 90 : 0}
/>

**Comment by comiewcom** [comment]
Is it possible to apply a snap only when approaching 0, 90, 180, or 270 degrees?
Thank you for the wonderful project.

**Comment by daybrush** [comment]
@comiewcom 
Thank you :)

Unfortunately, I don't know your angle, so I have to do it manually now.

```js
<Moveable
     onRotate={({ beforeDelta }) => {
        this.rotation += beforeDelta;
        const rotation = Math.floor(this.rotation / 90) * 90;

        console.log(rotation);
    }}
/>
```

**Comment by daybrush** [comment]
@comiewcom 

Moveable 0.8.0 is released!!!

You can use `set` methods and `beforeRotate` for absolute value.

```jsx
let rotation = 10;

<Moveable
     throttleRotate={90}
     onRotateStart={({ set }) => {
         set(rotation);
     }}
     onRotate={({ beforeRotate }) => {
         console.log(beforeRotate);
         rotation = beforeRotate;
     }}
```
