### ISSUE TITLE
Origin of width and height

### ISSUE THREAD

**Issue by JulesVi** [daybrush/moveable#161]
Hello,
On angular 8, moveable 0.9.5, I use width and height in the onResize function, but sometimes they got values (especially height when resizing on the bottom of an element) which are not realistic, like -200px when i start to resize, of 1050px, while the resizable element il 500px in fact.

Here is the code :

```
onResize({ target, width, height, drag }, element: Element) {
        `const` temp: Element = Object.values(element)[1];
        target.style.width = `${width}px`;
        target.style.height = `${height}px`;
        element.setPos(drag.beforeTranslate[0], drag.beforeTranslate[1]);
        target.style.left = `${drag.beforeTranslate[0]}px`;
        target.style.top = `${drag.beforeTranslate[1]}px`;
}
```

Thanks

**Comment by daybrush** [comment]
@JulesVi 

Can you show me the gif file when it matters?

**Comment by JulesVi** [comment]
![bugHeight](https://user-images.githubusercontent.com/39760183/72709579-8eb23200-3b65-11ea-86be-195b56935c71.gif)

**Comment by daybrush** [comment]
@JulesVi 


Can you see the code for resizeStart?

**Comment by JulesVi** [comment]
Yes of course : 
```
onResizeStart({ target, set, setOrigin, dragStart }, portlet: Portlet) {
        // Set origin if transform-orgin use %.
        setOrigin(['%', '%']);
        // If cssSize and offsetSize are different, set cssSize. (no box-sizing)
        const style = window.getComputedStyle(target);
        const cssWidth = parseFloat(style.width);
        const cssHeight = parseFloat(style.height);
        set([cssWidth, cssHeight]);

        // If a drag event has already occurred, there is no dragStart.
        if ( dragStart ) {
            dragStart.set(this.translates.get(portlet.id));
        }
    }
```

**Comment by daybrush** [comment]
@JulesVi 

I'm not sure why that happened.

My guess is that width or height is zero.

I don't know if this will work, but I updated ngx-moveable. Try again.
```sh
$ npm i ngx-moveable@next
# or $ npm i ngx-moveable@0.9.5-rc2
```

**Comment by JulesVi** [comment]
Thank you but it did not change the bug, but i'm not achieving to make it persistent, so I will show you again when it comes to be persistent.
However, while trying to show you the bug, I observed a move when starting to resize an element on this project : https://github.com/JulesVi/BugsDragResize

I made a comment in app.component.ts line 62 to explain what the bug is

**Comment by daybrush** [comment]
@JulesVi 

line 62 issue:
In onDrag, temp.setPos (drag.beforeTranslate [0], drag.beforeTranslate [1]); seems to be necessary.
getPos is an unsaved value when resizeStart.

**Comment by JulesVi** [comment]
Thank you, but how can I access to drag.beforeTranslate in the onDrag function (drag is undefined in onDrag) ?

**Comment by daybrush** [comment]
@JulesVi 
```js
onDrag({ beforeTranslate })
```

**Comment by JulesVi** [comment]
![bugDrag](https://user-images.githubusercontent.com/39760183/72824856-4898c380-3c76-11ea-990e-3c85dd6958da.gif)

Whith this code :
    ```onDrag({ target, left, top, beforeTranslate }, element: object) {
        target.style.left = left + 'px';
        target.style.top = top + 'px';

        const temp: Element = Object.values(element)[1];
        temp.setPos(beforeTranslate[0], beforeTranslate[1]);
    }
```

**Comment by daybrush** [comment]
@JulesVi 

```js
onDragStart(event, element: object) {
        const temp: Element = Object.values(element)[1];
        const tempElem: Element = this.translates.get('num' + temp.getIdElem());
        const test = [tempElem.getPos().x, tempElem.getPos().y];
        event.set(test);
    }

    onDrag({ target, left, top, beforeTranslate }, element: object) {
        const temp: Element = Object.values(element)[1];

        temp.setPos(beforeTranslate[0], beforeTranslate[1]);
        target.style.left = left + 'px';
        target.style.top = top + 'px';
    }
```

**Comment by JulesVi** [comment]
Thanks, and with modifiying the code, i resolved my problem of height so everything is working fine !
