### ISSUE TITLE
Support bounds for a rotated system

### ISSUE THREAD

**Issue by dvoytenko** [daybrush/moveable#163]
## Environments
* Framework name: React
* Framework version: 0.16.2

## Description
We're looking for a solution or an advice on how to bound the pan of a cropped image that is also rotated. The constraint is to not allow the image to go outside the crop area. Ideally bounds will be defined in the rotated space or as a polygon. Currently bounds can only be specified in terms of vertical lines.

Any advice would be appreciated!

<img src="https://user-images.githubusercontent.com/726049/73008870-4d6b8d80-3dc4-11ea-90c7-0930fdb932eb.png" width="200">
<img src="https://user-images.githubusercontent.com/726049/73008897-56f4f580-3dc4-11ea-875c-8328f1b4d00f.png" width="200">

**Comment by adityakrshnn** [comment]
I agree. This feature is much needed and would be awesome to have.

**Comment by daybrush** [comment]
@dvoytenko @adityakrshnn 

Again, this task is very difficult, so it is probably provided as an approximation. Are you okay?

**Comment by dvoytenko** [comment]
@daybrush I agree - this is a difficult task to solve. I find that most of time constraints are not enforced in a rotated system. I initially wanted to hear your opinion on rather you see this easily solvable. But it sounds like you don't think so. I'm ok if this was a low priority.

**Comment by adityakrshnn** [comment]
@daybrush I understand. This is one of the toughest problems, which is why very few libraries have come close to implementing this. However, if you manage to accomplish this, I am sure this feature would become a groundbreaking asset to your library. Take your time. Meanwhile, can you please elaborate on what do you mean by approximation?

**Comment by daybrush** [comment]
@adityakrshnn

It does not seem to consider the number of all cases.

**Comment by daybrush** [comment]
@dvoytenko  @adityakrshnn

I'll just add `bounds` this week.

**Comment by daybrush** [comment]
@dvoytenko @adityakrshnn 
Moveable 0.14.0 is released. Thank you :)
* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0

**Comment by adityakrshnn** [comment]
Wow! Can you show us how to use it?

**Comment by daybrush** [comment]
@adityakrshnn 

This is the same as using the existing bounds.

https://github.com/daybrush/moveable/blob/master/handbook/candbook.md#toc-snappable

**Comment by adityakrshnn** [comment]
Hi, can you provide a demo of the new changes? I am unable to find any difference in bounds. Do the bounds consider rotated position of the moveable?

**Comment by daybrush** [comment]
@dvoytenko 

http://daybrush.com/moveable

bounds is set to {left: 30, top: 30}. try to test it.

**Comment by adityakrshnn** [comment]
Yes, regular bounds work. But when I rotate the moveable, the bounds do not rotate as mentioned in this question. How can we do that?

**Comment by daybrush** [comment]
@dvoytenko @adityakrshnn

Oh, I was misunderstanding this feature.

I thought it was similar to this issue.
https://github.com/daybrush/moveable/issues/106

I'm sorry. We haven't created this feature yet.

**Comment by adityakrshnn** [comment]
Yes. When I saw the complete label, I couldn't believe that such a problem was resolved so soon. I am attaching a gif to show its functionality. Hope this comes soon.

![ezgif-5-5b966ce14a6d](https://user-images.githubusercontent.com/23035769/73775926-da431d80-47ac-11ea-8e1c-81fc4f7eefa9.gif)

**Comment by daybrush** [comment]
@dvoytenko @adityakrshnn 


* `moveable` 0.15.1
* `react-moveable` 0.18.0
* `preact-moveable` 0.17.0
* `ngx-moveable` 0.11.0
* `svelte-moveable` 0.6.0

Use `rootContainer` and `innerBounds`. rootContainer is documnet.body or no transform container.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#innerBounds

**Comment by SimeonRolev** [comment]
Can we get a working example? Couldn't get it to run with `innerBounds`. The Croppable components seems to "know" the proper logic to hit tilted bounds properly.

**Comment by SimeonRolev** [comment]
> @SimeonRolev
> 
> See this demo: https://daybrush.com/moveable/storybook2/?path=/story/snap-bound--inner-bound-with-resize
> 
> And snaps and bounds for Clippable's Clipped Area are being prepared.

I don't think this answers my question, or maybe I just didn't get it. In the example you posted, the bounds are horizontal and vertical, not rotated. What I mean is that`clipTargetBounds` works great even if the element is rotated - in that case, the blue box acts like boundaries for the green one. Here is a working example, look at the `// NOTE` at the `.target` div:

```jsx
import * as React from "react";
import Moveable from "react-moveable";

export default function App() {
  const targetRef = React.useRef<HTMLDivElement>(null);

  return (
    <div className="root">
      <div className="container">
        <div
          className="target"
          ref={targetRef}
          style={{
            top: "50px",
            left: "50px",
            width: "200px",
            height: "200px",
            // NOTE
            transform: "rotate(30deg)"
          }}
        >
          Target
        </div>
        <Moveable
          target={targetRef}
          draggable={true}
          resizable={true}
          clippable={true}
          dragWithClip={false}
          clipTargetBounds={true}
          snappable={true}
          horizontalGuidelines={[0, 100, 200, 300]}
          // verticalGuidelines={[0, 100, 200, 300]}
          snapThreshold={5}
          onDrag={(e) => {
            e.target.style.transform = e.transform;
          }}
          onResize={(e) => {
            e.target.style.width = `${e.width}px`;
            e.target.style.height = `${e.height}px`;
            e.target.style.transform = e.drag.transform;
          }}
          onClip={(e) => {
            e.target.style.clipPath = e.clipStyle;
          }}
        />
      </div>
    </div>
  );
}

```
 
Now, how do I achieve that with two separate boxes, not using "Clippable"?

**Comment by daybrush** [comment]
@SimeonRolev 

You mean <Moveable target={target} bounds={rotatedContainer} /> right?

rotatedGuidelines, rotatedBounds are very difficult but I will support.

So I am preparing a snappable package.
  https://github.com/daybrush/moveable/tree/master/packages/snappable

**Comment by SimeonRolev** [comment]
@daybrush I mean that I believe you already have the proper logic for rotated bounds implemented, and it's working fine - with the example that I gave you in my previous comment, using `Moveable.Clippable`, that has a rotation and `clipTargetBounds`. Maybe you just have to expose it. And yeah, the ability to pass a selector or a DOM element to the `bounds` argument might be a good approach.
