### ISSUE TITLE
Drag Delay 

### ISSUE THREAD

**Issue by ovidius72** [daybrush/moveable#165]
In react, when draggable is enabled, if you click on an item it is considered to be a start dragging event, and if you move the mouse even just a little bit, the item is moved around. In my case I want the item to just be selected when clicked on it and start dragging if the user keep pressing for a certain number of milliseconds. Is there a way to do that. Thanks

**Comment by daybrush** [comment]
@ovidius72 

I think it's better to turn off draggable.

Normally turn it off and on when you start dragStart.

```js
const ev = e.nativeEvent;

setTimeout(() => {
    this.setState({
        draggable: true,
    }, () => {
        this.moveable.dragStart(ev);
    });
}, 100);
```

**Comment by ovidius72** [comment]
@daybrush But if draggable is turned off, does the dragStart event fires the same. I was thinking about something like that, but I'm pretty sure it was not fired. I've also tried using the onClick event but then it captures the event and even resize doesn't fire.

**Comment by daybrush** [comment]
@ovidius72 

Perhaps you need to add events separately.
Alternatively, you can block the movement for a few seconds in the drag event.

**Comment by ovidius72** [comment]
@daybrush I was able to do that with a timer inside the onDragStart but I'm not entirely sure this is the best way to do that. Thanks for your help.
