### ISSUE TITLE
ngx-movable scrolling issue

### ISSUE THREAD

**Issue by Xumochuan** [daybrush/moveable#166]
## Environments
* Framework name: Angular
* Framework version: v8
* Moveable Component version: 0.5.5-rc
* Testable Address(optional): 

## Description

Hi,
Thanks for your amazing component.
Now, I am using ngx-movable, I have scrolling issue, but I don't know how can I fix it.
Whenever mouse scrolling, target and border is separated.
I used scrolling props, but it works nothing.
I am really glad if you let me know about it.
Thanks.

![image](https://user-images.githubusercontent.com/47884397/73380450-0834e780-42ff-11ea-9bcc-596b7a670195.png)

https://ttprivatenew.s3.amazonaws.com/pulse/mochuan-video/attachments/12391172/TinyTake29-01-2020-11-05-58.mp4

![image](https://user-images.githubusercontent.com/47884397/73368624-4674db80-42ec-11ea-9a43-7ecdcf395c7e.png)

**Comment by daybrush** [comment]
@Xumochuan 

I don't know why. Do you want to update?

It is now 0.9.4.

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Thanks so much for your support.
I have updated ngx-moveable #0.9.4.
But when I mouse scrolling, target and ball is still separated.
Please look at this image.

![Scroll_target](https://user-images.githubusercontent.com/47884397/73384968-40d8bf00-4307-11ea-9ef0-19b96cb69c8b.gif)

Hope your kind contact again.
Many thanks

**Comment by daybrush** [comment]
@Xumochuan 

remove container props.

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Thanks for your reply.
I have tried, but same as.
When scrolling, target and border is separated. 
Hope your kind solution.
Thanks

**Comment by daybrush** [comment]
@Xumochuan 
Oh right. The default value was added to document.body.


Set the container to your app
```js
constructor(elRef: ElementRef) {}

<ngx-moveable
      #moveable
      [container]="elRef.nativeElement" />
```

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Really Thanks. I have solved issue. 
This is know-how technology.
At first, moveable object was created in **body (out of app-root)**, but now it is created in 
**nativeElement**

`elRef: any;
constructor(private elementRef: ElementRef) { elRef= elementRef}

<ngx-moveable
      #moveable
      [container]="elRef.nativeElement" />`

Thanks for your kind suggestion.

**Comment by maheshts** [comment]
hi ,
I am using this library its working fine in local but in production build i am facing issue.
any idea how to resolve the null issues
ERROR TypeError: this.moveable is undefined

kindly help
