### ISSUE TITLE
Rotation origin changes when `resizable` depends on a state

### ISSUE THREAD

**Issue by wassgha** [daybrush/moveable#168]
## Environments
* Framework name: React
* Framework version: 16.12.0
* Moveable Component version: 0.16.6

## Description
If  the `resizable` property is made to be dependent on a React state field, whenever `resizable` changes (from `true` to `false`) the rotation origin (which is usually at the center) changes to become at the top left corner.

**Comment by daybrush** [comment]
@wassgha 

Thanks for the issue report.

I didn't find the reason why the origin goes to top left, but I found another problem.

I don't know if this solves the problem.

**Comment by VitDev17** [comment]
To solve this problem maybe you could calculate the centre of the object and then set it as local storage so it is never influenced by the app current state.

**Comment by daybrush** [comment]
@wassgha 


Moveable 0.14.0 is released. Thank you :)
* `moveable` 0.14.0
* `react-moveable` 0.17.0
* `preact-moveable` 0.16.0
* `ngx-moveable` 0.10.0
* `svelte-moveable` 0.5.0

**Comment by daybrush** [comment]
@VitDev17

It could be, but it would be a different matter. The key setting of children may be wrong and then unmounted and mounted. Thank you :)

**Comment by wassgha** [comment]
Fixed in `0.17.0`!
