### ISSUE TITLE
Is there a way to move an origin?

### ISSUE THREAD

**Issue by jorasso** [daybrush/moveable#169]
Is there a way to change the origin point to something different than the center?

**Comment by daybrush** [comment]
@jorasso 

There is no function to change origin by dragging yet.

You have to change the transform-origin manually.

**Comment by daybrush** [comment]
@jorasso  

moveable's new version is released.
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1

`originDraggable` is added.
https://daybrush.com/moveable/storybook/?path=/story/basic--origindraggable

**Comment by jorasso** [comment]
Beautiful, thanks a lot!
