### ISSUE TITLE
Angular Groupable Handbook Issue and about single target, group isn't working

### ISSUE THREAD

**Issue by Xumochuan** [daybrush/moveable#170]
## Environments
* Framework name: Angular
* Framework version: v8
* Moveable Component version: 0.9.4.0
* Testable Address(optional): 

## Description

Hi, @daybrush 
Thanks for your amazing moveable component.
In my thought, there are a little issue in Handbook. Maybe, I think, remove "on" is right.

![image](https://user-images.githubusercontent.com/47884397/73724509-78f85b80-4766-11ea-9db7-b873f561f640.png)

I have used your example code without change.
But, if there is only a target, then group function doesn't work.
I think, a target is also target array with length 1, but it is not working.
If target array length is over than 2, then it is working.

![Grouping_issue](https://user-images.githubusercontent.com/47884397/73740147-90ddd880-4782-11ea-9a3f-6d53b16d40d8.gif)

Hope your kind solution to solve this issue.
Many Thanks

**Comment by daybrush** [comment]
@Xumochuan 

dragGroup is an event that is triggered when there are two or more targets.

Use the drag event when there is only one target.

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#angular-example

**Comment by Xumochuan** [comment]
Thanks, @daybrush
