### ISSUE TITLE
Support for inner bounds

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#172]
## Environments
* Framework name: Angular
* Framework version: 8
* Moveable Component version: 0.14.0

## Description
Is there any way to not allow resizing moveable below a certain inner bound? Attaching sample.

![ezgif-7-3e11c96df8e3](https://user-images.githubusercontent.com/23035769/73830078-09e43b00-482a-11ea-949c-3eb6bc61ab88.gif)

**Comment by daybrush** [comment]
#163

**Comment by daybrush** [comment]
@adityakrshnn 


* `moveable` 0.15.1
* `react-moveable` 0.18.0
* `preact-moveable` 0.17.0
* `ngx-moveable` 0.11.0
* `svelte-moveable` 0.6.0


Add `innerBounds` props.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#innerBounds

**Comment by wassgha** [comment]
@dvoytenko
