### ISSUE TITLE
Make snap digits configurable

### ISSUE THREAD

**Issue by wassgha** [daybrush/moveable#173]
## Description
Would be great if it was possible to disable the snap numbers shown next to the lines (with a prop)
Related code: [https://github.com/daybrush/moveable/blob/c8a2761ebb273772b61e5d2c970fa5081a17e9c8/packages/react-moveable/src/react-moveable/ables/Snappable.tsx#L1145](https://github.com/daybrush/moveable/blob/c8a2761ebb273772b61e5d2c970fa5081a17e9c8/packages/react-moveable/src/react-moveable/ables/Snappable.tsx#L1145)

**Comment by daybrush** [comment]
@wassgha 

* `moveable` 0.15.1
* `react-moveable` 0.18.0
* `preact-moveable` 0.17.0
* `ngx-moveable` 0.11.0
* `svelte-moveable` 0.6.0

Use `snapDigit`. (now default is 0) (previous 4)

https://daybrush.com/moveable/release/latest/doc/Moveable.html#snapDigit
