### ISSUE TITLE
Element Left, Top must be updated after rotated!

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#174]
Hi @daybrush 
After check your demo page at [https://daybrush.com/moveable/](https://daybrush.com/moveable/) I think the left and top of element (or X, Y in your demo page) must be update after we rotated.

Before rotate:
![Screenshot from 2020-02-11 14-56-12](https://user-images.githubusercontent.com/51266596/74219230-d64c5980-4cde-11ea-97ed-cd94a83b07e3.png)

And after rotate:
![Screenshot from 2020-02-11 14-56-19](https://user-images.githubusercontent.com/51266596/74219241-dd736780-4cde-11ea-9121-8c23eb16caed.png)

The left and top are the same, this is not right, isn't it?

When I try to fix it, I add some thing to your `dragControlEnd` function:
`dragControlEnd(moveable: MoveableManager<RotatableProps>, e: any) {
        const { datas, isDrag } = e;

        if (!datas.isRotate) {
            return false;
        }
        datas.isRotate = false;

        triggerEvent(moveable, "onRotateEnd", fillParams<OnRotateEnd>(moveable, e, {
            isDrag,
            left: datas.left,
            top: datas.top,
        }));
        return isDrag;
    },`

... then handle the `handleRotateEnd` function:
`private handleRotateEnd: any = ( {
    	left,
    	top
    }: OnRotateEnd ) => {
    	console.log( 'rotate end with left: ', left );
    	console.log( 'rotate end with top: ', top );
    	this.unLockSelector();
    	this.hideTooltip();
    	this.onEndVisualChange();

    	const {
    		onUpdateBlockAttributes,
    		block,
    	} = this.props;
    	if ( block ) {
    		onUpdateBlockAttributes( {
    			left, // translate[0],
    			top, //translate[1],
    		} );
    	}
    };`

But still not right.

Please add some discussion here.

Thanks!

**Comment by daybrush** [comment]
@ladifire 
sorry. The demo was using the old moveable version.

The demo was updated.

**Comment by ladifire** [comment]
@daybrush 
![captured (9)](https://user-images.githubusercontent.com/51266596/74227572-554a8d80-4cf1-11ea-8b6b-9c2e806e5a51.gif)
See X changing when resize, it's wrong.
 You've used:
```
controlXElement.value = `${parseFloat(frame.get("transform", "translateX"))}`;
controlYElement.value = `${parseFloat(frame.get("transform", "translateY"))}`;
```

Using translateX for X is wrong, isn't it?

--
I have an app that using absolute position when moveable instead `translate`. So I need to set `left` and `top` for element instead `transform`. Could you please make a demo for this case? please!

Thanks!

**Comment by daybrush** [comment]
@ladifire 

The x and y values come out like that because they are translates. You can also move x and y through the input.

I will be adding the features to move to absolute values in the next update.

The name is the `request` method and the request came in in the next issue. #141

**Comment by ladifire** [comment]
Thanks you!
