### ISSUE TITLE
Resize will move rotated object?

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#175]
Please check this gif:
![captured (8)](https://user-images.githubusercontent.com/51266596/74221267-4f01e480-4ce4-11ea-97e9-3779452cbd76.gif)

**Comment by daybrush** [comment]
@ladifire 

The resize event contains a drag property. Used together, you won't have the above problem.

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#resizable
