### ISSUE TITLE
How to move Target by user input?

### ISSUE THREAD

**Issue by Xumochuan** [daybrush/moveable#176]
## Environments
* Framework name: Angular
* Framework version: v8
* Moveable Component version: 0.9.4.0
* Testable Address(optional):

## Description

Hi, @daybrush 
How are you?
I hope to receive your kind suggestion.
I am going to move target by user input instead of mouse dragging.
But, only target is moved, doesn't move balls and border.

![TinyTake-by-MangoApps-11-02-2020-04-34-57](https://user-images.githubusercontent.com/47884397/74221591-714c3000-4ced-11ea-8390-883c431cc09a.gif)
![image](https://user-images.githubusercontent.com/47884397/74221738-bcfed980-4ced-11ea-9e9f-a77e9649cb66.png)

How can I move target and border Both?
Thanks.

**Comment by daybrush** [comment]
@Xumochuan 

Call `moveable.updateRect()` after input

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Thanks for your kind reply, 
I have tried, but it didn't solve my issue. It doesn't move Rect.

![image](https://user-images.githubusercontent.com/47884397/74224215-5f6d8b80-4cf3-11ea-97a8-d05bd06acb34.png)

Hope your kind contact again.
Thanks

**Comment by daybrush** [comment]
@Xumochuan 

Does nothing happen when you call updateRect?
Or do you have any other reactions?

**Comment by Xumochuan** [comment]
Hi, @daybrush 
When I call updateRect(), it works nothing. no effect.

**Comment by daybrush** [comment]
@Xumochuan 
There is a similar method, but then call `updateTarget`.

I don't know why, but I don't know why.


Is setProperty asynchronous?

**Comment by Xumochuan** [comment]
Hi, @daybrush 
I have solved issue. Issue was in asynchronous. 
This works for me.
![image](https://user-images.githubusercontent.com/47884397/74227405-5aabd600-4cf9-11ea-943b-6f17fb5c8c06.png)

Thanks so much, @daybrush
