### ISSUE TITLE
How to set horizontalGuidelines & verticalGuidelines only inside particular area.

### ISSUE THREAD

**Issue by iprasadg** [daybrush/moveable#178]
## Environments
* Framework name: Angular
* Framework version: 8.0.0
* Moveable Component version: 0.9.4
* Testable Address(optional):

## Description
horizontalGuidelines & verticalGuidelines appears on whole window. I want to keep both inside particular div element. Is there anyway to do that?

Thanks.

**Comment by daybrush** [comment]
@iprasadg 

The guideline of a moveable is determined by the size of the container that contains the moveable.
Check it out.

**Comment by iprasadg** [comment]
@daybrush Ok I will check. Thank you for the reply.

**Comment by iprasadg** [comment]
@daybrush Hello, 
I have this [demo](https://codesandbox.io/s/vigilant-elgamal-9p2rq?fontsize=14&hidenavigation=1&theme=dark). Vertical guidelines are inside parent div but horizontal guideline is taking whole window width. What went wrong, Can you please see this?

Thanks.

**Comment by daybrush** [comment]
@iprasadg 


```html
<div
  (mousedown)="activateMoveableControl($event)"
  id="parentRef"
  #parentRef>
<ngx-moveable
    [container]="parentRef">
```

**Comment by iprasadg** [comment]
@daybrush Wow this is working like a pro. Thanks buddy 👍
