### ISSUE TITLE
Modify moveable from external panel

### ISSUE THREAD

**Issue by Yomyer** [daybrush/moveable#179]
## Environments
Framework name: Angular
Framework version: 8.0.0
Moveable Component version: 0.9.4
Testable Address(optional):

## Description
Hello, 

In the project I need to modify the parameters of position X, Y, Rotation, width and height from outside moveable.

![image](https://user-images.githubusercontent.com/6996160/74444503-3ffe6c00-4e75-11ea-8a3e-ee44908ee6f0.png)

I am having problems to calculate the X and Y displacement after rotating an element and/or group out of moveable from external inputs. I know that there are trigonometry formulas that solve this (I haven't succeeded yet) and more when it comes to rotating a group that the elements rotate around the central point of the group.

My question is:

Is there a way to modify or call the moveable events with the new parameters and it runs the internal moveable triggers so that it updates the target without having to directly modify the target?

Something like that:

this.moveable.dragTo(x, y); // moves the element to the position x and y
this.moveable.dragBy(x, y); // adds to the element the position x and y
this.moveable.rotateTo(10deg); // rotates the element up to 10 deg
this.moveable.rotateBy(10deg); // rotates the element 10 deg
this.moveable.resizeTo(width, height, [0,0]); // determines a new width and height with respect to left and top.

I can't find a way to do this with the current api, is it possible?

Thanks

**Comment by daybrush** [comment]
@Yomyer 

This feature is currently in development.

Duplicate https://github.com/daybrush/moveable/issues/141

Thank you :)

**Comment by daybrush** [comment]
@Yomyer 

fixed demo. Check it again.
https://daybrush.com/moveable/


https://github.com/daybrush/moveable/blob/482e8d63c74de82e966a638472a984f9a08ce85b/demo/src/Editor.ts#L60-L77
