### ISSUE TITLE
Moveable destroy error

### ISSUE THREAD

**Issue by monsterooo** [daybrush/moveable#18]
Hi @daybrush :

I use Moveable on the React framework，I made a mistake when I called destroy times。

I create example in Codesandbox:

https://codesandbox.io/s/moveable-zh8u5?fontsize=14

When i click destroy, to destroy Moveable. i get a error

```
Uncaught TypeError: Cannot read property 'preactMoveable' of null
```

Code:
![image](https://user-images.githubusercontent.com/18432680/62529650-99a42f00-b871-11e9-951b-4a2b19e02db3.png)

Is this the correct release?

**Comment by daybrush** [comment]
@monsterooo 

Thank you for reporting bug.
I'll fix it soon.

And on React Framework, you can use React Component
https://github.com/daybrush/moveable/tree/master/packages/react-moveable

**Comment by monsterooo** [comment]
@daybrush 

Thank you

👾

**Comment by daybrush** [comment]
@monsterooo 

moveable 0.6.1 version has been released. If you're using a vanilla version, please update it.

Thank you :)

**Comment by monsterooo** [comment]
@daybrush 

Thank you for your efforts, The problem has been solved.
