### ISSUE TITLE
onScroll is not triggered on the resize events

### ISSUE THREAD

**Issue by dvoytenko** [daybrush/moveable#180]
## Environments
* Framework name: react-moveable
* Framework version: 0.17.0

## Description
Dragging with `scrollable:true` yields `onScroll` events. However, resizing in very similar cases does not. Ideally, resize on the appropriate anchor would yield `onScroll`.

**Comment by daybrush** [comment]
@dvoytenko 

resize and scale do not yet support scrolling.

**Comment by daybrush** [comment]
@dvoytenko 

https://github.com/daybrush/moveable/releases/tag/0.15.1
react-moveable 0.18.0 is released.
Support resize, scale. Thank you :)

**Comment by dvoytenko** [comment]
Thanks! We'll try it out!

**Comment by dvoytenko** [comment]
it works!
