### ISSUE TITLE
Feature: Is it possible to support low resolution dragging (sort of snapping in a grid mode)?

### ISSUE THREAD

**Issue by born2net** [daybrush/moveable#181]
I was wondering if is it possible to support low resolution snapping.
In other words, for example if you set a value a snapping of 50x50 and drag an object, it will snap on every 50px horizontal and 50px vertical... sort of a tile layout so it is very easy to arrange many objects and align them as when you drag, the object you are dragging simply snaps in 50px jumps.
I hope my explanation makes sense. 
I used to use CanvasJS and if you wanted to drag an object and have it move up or down in X pixels resolution you would:

```
_sceneBlockMoving(i_options) {
            left: Math.round(i_options.target.left / grid) * grid,
            top: Math.round(i_options.target.top / grid) * grid
        });
```

let me know if any questions...
TX for a GREAT project,

[see video gif example of what I mean](https://digitalsignage.com/tmp/demotmp.gif)

Sean

**Comment by daybrush** [comment]
@born2net 

use `throttleDrag` option

```js
moveable.throttleDrag = grid;
```

**Comment by born2net** [comment]
AWESOMNESS!!!!!
