### ISSUE TITLE
how to do this : when drag the corner(such as ne) make the scale effect, when drag the edge (such as north) make the resize effect

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#184]
movable 0.14.1

## Description
can we switch scalable and resizable dynamic,
when drag the corner  make the scale effect, when drag the edge make the resize effect

thanks

**Comment by daybrush** [comment]
@leeboo 

It is not yet possible to use them at the same time.
Sorry.

**Comment by leeboo** [comment]
hi @daybrush 
in the resize event , how can i compute the scale data? such as scaleX, scaleY, translateX, translateY,
have anything API?
thanks

**Comment by leeboo** [comment]
![QQ20200228-120442](https://user-images.githubusercontent.com/1256745/75509457-9c8b8a80-5a22-11ea-84c6-473384a5e321.gif)
i want to do this effect

**Comment by leeboo** [comment]
the img is inside a div, and when div resize i want the img according to scale

**Comment by daybrush** [comment]
@leeboo 

```js
moveable.on("resize", ({ width, height, drag }) => {
   const startWidth; // your div's start Width
   const startHeight;
   const scaleX = width / startWidth;
   const scaleY = height / startHeight;
   const [translateX, translateY] = drag.beforeTranslate;
})
```

**Comment by daybrush** [comment]
@leeboo 

https://github.com/daybrush/moveable/issues/207

You can choose scale or resize in the direction.
