### ISSUE TITLE
getRect() width after rotate

### ISSUE THREAD

**Issue by katOstrynska** [daybrush/moveable#185]
## Environments
* Framework name: VueJS
* Framework version: 3.11.0
* Moveable Component version: vue-moveable by Probil 

When I use rotate method, my width and height from getRect() are wrong - it shows width and height of the element box (red square), not element itself (grey square).

How can I get width and height of my actual element?

![Zrzut ekranu z 2020-02-25 16-29-45](https://user-images.githubusercontent.com/32193007/75262412-c9565c80-57ec-11ea-9fb1-6864dcfab259.png)

**Comment by daybrush** [comment]
@katOstrynska 

use offsetWidth, offsetHeight in getRect()

Thank you :)

**Comment by katOstrynska** [comment]
@daybrush my offsetWidth and offsetHeight do  not change after rotate or scale - are the same as width and height of my element at the beggining

**Comment by daybrush** [comment]
@katOstrynska 

offsetSize is not changed by the transform.
I do not know your scale.
moveable does not provide a scaled size value. How about finding the distance of pos1, pos2 if you want?

```js
const {
    pos1,
    pos2,
    pos3,
    pos4,
} = moveable.getRect();

const distance = Math.sqrt(Math.pow(pos1[0] - pos2[0], 2) + Math.pow(pos1[1] - pos2[1], 2));
```

**Comment by katOstrynska** [comment]
@daybrush ok, I get it now, I used pos values and it is what I was looking for,thank You :)
