### ISSUE TITLE
moveable-control-box only one

### ISSUE THREAD

**Issue by MrHzq** [daybrush/moveable#187]
## Environments
* Framework name: Vue
* Framework version: 2.6.10
* Moveable Component version:  `> 0.13.4`

#### moveable-control-box only one：Belongs to the last
![image](https://user-images.githubusercontent.com/24823464/75309984-9c0dbb00-588d-11ea-81b7-e7c2a06434df.png)

#### moveable-control-box has three：is normal
![image](https://user-images.githubusercontent.com/24823464/75310042-c495b500-588d-11ea-8a1a-f13a92ac2391.png)

**Comment by daybrush** [comment]
@MrHzq 

It looks like a bug, but the moveable version is now 0.14.1. Would you like to update it?

**Comment by MrHzq** [comment]
When Moveable Component version  is higher than  ` 0.13.4`，exist the bug.
that means  `0.14.0, 0.14.1`  also exist  the bug. 
I've updated the latest version before

**Comment by daybrush** [comment]
@MrHzq 

How can I know how to set the target of a moveable in vue?

**Comment by MrHzq** [comment]
### all codes in component file ( `moveable-item.vue `)，It's a vue component

#### html
```html
  <div class="moveable-item">
    <!-- one moveable target start  -->
    <div
      ref="moveableDom"
      class="moveable"
    >
      <slot />
    </div>
    <!-- one moveable target end -->
  </div>
```

#### js
```js
import Moveable from 'moveable'

// use
this.moveableObj = new Moveable(this.moveableConfig.container, {
        ...this.moveableConfig,
        target: this.$refs.moveableDom,
        className: `my-custom-controlbox-classname-${item.uuid}`
}).on('drag', e => {
        // ...
})
```

Sorry, my English is limited. I wonder if you can understand

**Comment by daybrush** [comment]
@MrHzq 

I found the reason for the bug. I'll release a bug fix this week. Thank you.

**Comment by daybrush** [comment]
@leeboo 

moveable 0.15.1 is released. Check it again.

**Comment by Fisujon** [comment]
@daybrush I am experiencing the same issue. Still persists in "vue3-moveable": "^0.26.1" and "moveable": "^0.51.1".

**Comment by allenxie888** [comment]
@Fisujon Is your problem solved? I also encountered the same problem

#1106
