### ISSUE TITLE
I want to click and then drag target, not click target and then mouse up and then click target to drag

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#188]
moveable 0.14.1
hi guys, I want to click and then drag target, not click target and then mouse up and then click target to drag
how to to this

**Comment by daybrush** [comment]
@leeboo 

I didn't understand what you meant. Can you tell me in order?

`click and then drag` is `mousedown and then drag`?

**Comment by leeboo** [comment]
> @leeboo
> 
> I didn't understand what you meant. Can you tell me in order?
> 
> `click and then drag` is `mousedown and then drag`?

hi daybrush
yes, i mean is mousedown and then can drag target immediately
![QQ20200302-102944](https://user-images.githubusercontent.com/1256745/75640684-d6ea6700-5c70-11ea-870e-d2e3e70ab8d3.gif)

**Comment by daybrush** [comment]
@leeboo 

See https://github.com/daybrush/moveable/issues/82

```js
document.querySelector("..").addEventListener("click", e => {
moveable.setState({
target: ...

}, () => {
     moveable.dragStart(e);
});
});
```

**Comment by leeboo** [comment]
thanks
