### ISSUE TITLE
Moveable of Resizable strange behavior

### ISSUE THREAD

**Issue by monsterooo** [daybrush/moveable#19]
Hi @daybrush 

Moveable's Resizable doesn't seem to be normal

The image below is the Resizable of the sketch

![480](https://user-images.githubusercontent.com/18432680/62592448-c6a22180-b905-11e9-95cf-1f5f7c8c5f71.gif)

What do you thknk? 🤔

**Comment by monsterooo** [comment]
I just watched the demo.

I think I should take a closer look at how to achieve

**Comment by daybrush** [comment]
@monsterooo 
Thank you for writing issues.

The demo and the problem I think is central alignment.
It's obviously resize, but the other side also increases.


I will add **`direction`** property in the next version.
 **`direction`** is the position where you pressed the control.

The direction will soon allow you to write the code as follows:
```js
on("resize", ({ direction, delta }) => {
    width += delta;
    height += delta;
    left += direction[0] < 0 ? delta[0] : 0;
    top += direction[1] < 0 ? delta[1] : 0;
});

**Comment by daybrush** [comment]
@monsterooo 
Moveable 0.7.0 is released. It can be used as follows.
```js
on("resize", ({ direction, delta }) => {
    width += delta;
    height += delta;
    left += direction[0] < 0 ? delta[0] : 0;
    top += direction[1] < 0 ? delta[1] : 0;
});

**Comment by monsterooo** [comment]
Hi, @daybrush I use react-moveable library.

![image](https://user-images.githubusercontent.com/18432680/63317836-e5ada400-c346-11e9-8c17-300ad998871c.png)

There is no `direction`

👀

**Comment by daybrush** [comment]
@monsterooo
oh, react-moveable 0.10.4 released. 
 Use this version. thank you :)

**Comment by monsterooo** [comment]
Hi @daybrush Are you Korean?

**Comment by daybrush** [comment]
@monsterooo
Yes. If you have personal questions, contact me. 
https://twitter.com/daybrush
daybrush@gmail.com

**Comment by LCGijs** [comment]
Is it also possible to make the `onScale` and `onScaleGroup` functionality like the Sketch example given above?
