### ISSUE TITLE
What demo do you want?

### ISSUE THREAD

**Issue by daybrush** [daybrush/moveable#190]
I'm going to make a demo.

https://github.com/daybrush/moveable/blob/master/storybook/README.md

Like as follows:

https://github.com/naver/egjs-infinitegrid

https://naver.github.io/egjs-infinitegrid/storybook/?path=/story/virtual-scroll--gridlayout

Please let me know if there is a demo you want. Feel free to write a comment. I will consider.

**Comment by leeboo** [comment]
good jobs and thanks daybrush
i want to make this effect, can you give me any idea?

![QQ1](https://user-images.githubusercontent.com/1256745/75732882-b41e8800-5d2e-11ea-99b2-f7b156262522.gif)

now i have problem when use two moveables #187 #189

**Comment by schester44** [comment]
A React demo would be nice. I find the "Getting Started" docs for React to be super limited and lacking of info. For example, the getting started references a props called `target` with a value of  `document.querySelector(".target")` but there is no mention of what `document.querySelector(".target")` refers too. 

Is that a component ref?

**Comment by schester44** [comment]
As far as examples... this may be out of scope, but i'd like to see Moveable work with a SlateJS editor.

**Comment by schester44** [comment]
One issue i'm seeing while using react-moveable is how to initialize a non-targeted element with rotation.

It seems like Moveables `rotate` value initializes at 0 so the calculations are off for an item that is initially rendered with rotation.

Here is an example:
https://codesandbox.io/s/quizzical-kowalevski-qi3xk

Try rotating the `def` element. onResizeEnd, we update the element's `rotate` value which causes the transforms to be incorrect.


I need to initialize an element with transforms and after being dragged/resized/rotated, I need to update the same state that was used to initially transform the item.... if that makes sense.

**Comment by satheshrgs** [comment]
@daybrush I need a demo using any of svg elements like rect or circle **without** using frame from scenejs. I tried a basic example and made it happen..The following are some of my issues i have faced
1. setting x,y of element in onDrag resets the position of mouse pointer to edge of that element..Is there any proper way to drag svg elements ?
2. Moveable origin sets to left corner of the page. so unable to rotate properly

here is the sanbox link of what i have tried
https://codesandbox.io/s/react-moveable-demo-btg9u?file=/src/index.js

**Comment by yojona** [comment]
I want to resize an image to negative width/height and produce mirroring, is that possible?

**Comment by Naggertooth** [comment]
Demo with more than 1 moveable component :)
<details><summary>spoiler</summary>
<p>
Resize is working on 2 targets
</p>
</details>

**Comment by happylinks** [comment]
Hey @daybrush, would you have time to make a demo with "scrollable" for "moveable"? I'm trying to combine these 2 examples:
https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--select-moveable-targets-in-real-time
https://daybrush.com/selecto/storybook/?path=/story/selecto--select-in-the-scroll-area

But I'm having an issue where the element moves really fast when dragged outside of the view (scrolling) and isn't in sync with the mouse cursor anymore.
I'll try to reproduce the error in a codesandbox as well, but maybe there's an example already somewhere?

**Comment by atomoc** [comment]
Please add a demo that describes all kinds of embellishments, such as changing colors, sizes, and the like.

**Comment by usmanibrahim74** [comment]
Can you make a demo for scaling/resizing the rotated target or rotating a scaled/resized target? I'm trying to find any example for this. if there is any demo or example than please tell me.
I tried this example but it reset the scale and translate.
https://daybrush.com/moveable/storybook/?path=/story/nested-transform--rotatable

**Comment by JayBhuva** [comment]
Please tell me how can I upload the manipulated image from movable?

**Comment by daybrush** [comment]
@atomoc 

Main demo 
https://daybrush.com/moveable/

**Comment by sooryaraj** [comment]
@daybrush  can you please do this (https://daybrush.com/moveable/) this demo in vanila JS

**Comment by alezzigo** [comment]
> good jobs and thanks daybrush
> i want to make this effect, can you give me any idea?
> 
> ![QQ1](https://user-images.githubusercontent.com/1256745/75732882-b41e8800-5d2e-11ea-99b2-f7b156262522.gif)
> 
> now i have problem when use two moveables #187 #189

@leeboo can you public source code this effect?

**Comment by MiiZZo** [comment]
@daybrush can you add to your demo the ability to group items using CTRL + G for example?

**Comment by littlee** [comment]
@daybrush How to implement an "Auto-Select" feature, just like the doc's demo 

https://daybrush.com/moveable/

the demo code is too complicated to understand

in my own project, I have to click to set the target to the current layer, then start the drag with another mouse down

https://codesandbox.io/s/gifted-poitras-ubs5v

I have changed `onClick` to `onMouseDown`, but it still does not work.

**Comment by daybrush** [comment]
@MiiZZo 
Sorry, but that seems a little difficult.

@littlee 

here demo:
https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--change-the-moveable-targets-by-selecting-it

**Comment by GreatAuk** [comment]
need some doc like this😂
![image](https://user-images.githubusercontent.com/20253809/103880450-1517a900-5114-11eb-8ba2-7c29ae612d95.png)

https://github.com/daybrush/moveable/issues/311#issuecomment-687127613

**Comment by daybrush** [comment]
@happylinks 

https://daybrush.com/moveable/storybook/?path=/story/support-scroll--use-scrollable

**Comment by marcosTenorio** [comment]
how to use max-width and max-height with React, please

**Comment by ItsNotPat** [comment]
Can you make a demo of switching targets while dragging, rotating and scaling are enabled?

I seem to have a problem with the targets. They keep copying that changes applied to the other one

![My Video 1](https://user-images.githubusercontent.com/45307497/106995408-d0863880-67b9-11eb-9e55-577270c647e5.gif)

**Comment by iofjuupasli** [comment]
https://daybrush.com/moveable/

In this demo selecto is used to create new items. Is it possible to create item immediately and trigger resize? So user will see end result with actual content right while dragging new item. For example when adding circle, to see how it will look, I need to mouseup

**Comment by ItsNotPat** [comment]
Hi, @iofjuupasli, Do you have a sample with the demo code? So I can understand it better. Thank you very much. :D

**Comment by daybrush** [comment]
@marcosTenorio 
https://daybrush.com/moveable/storybook/?path=/story/use-snap-bounds-with-ables--bounds-area

**Comment by daybrush** [comment]
@ItsNotPat 

https://github.com/daybrush/scena/tree/master/packages/react-editor/src/Editor

**Comment by marcosTenorio** [comment]
move elements with the arrow keys in a react project

**Comment by phantrongbien** [comment]
Sorry, my english is not very good.
I am working on a simple tool design card with text and images
The demo code is too complicated to understand.
![スクリーンショット 2021-04-14 13 30 58](https://user-images.githubusercontent.com/24311911/114664350-c5a1d400-9d25-11eb-9de8-02462bf50789.png)

**Comment by DavidM42** [comment]
A demo implementing something like this [draggable shelf type component](https://svelte.dev/repl/7c9964de18604b2582ddd844cebdf218?version=3.15.0)

**Comment by phantrongbien** [comment]
> Sorry, my english is not very good.
> I am working on a simple tool design card with text and images
> The demo code is too complicated to understand.
> Please help me
> 
> ![スクリーンショット 2021-04-14 13 30 58](https://user-images.githubusercontent.com/24311911/114672168-07834800-9d2f-11eb-962c-27231a657afe.png)

@daybrush please help me !

**Comment by satheshrgs** [comment]
@daybrush Is it possible to show a border using moveable / selecto when hovering on a selectable target ? Or is there any possible way using CustomAbles ?

Example:
![image](https://user-images.githubusercontent.com/20806010/124596532-04a47900-de80-11eb-9c2d-43a6f55605c9.png)

**Comment by dboydgit** [comment]
@daybrush would it be possible to add customClipPath to the clippable examples? I wasn't able to get that working on my project.

**Comment by iCloudys** [comment]
There are multiple 'moveable' in a page, which are isolated from each other and can only be active within their own containers


![图片](https://user-images.githubusercontent.com/13017318/144790589-58d8702e-fe56-4872-a47f-b8c53d711458.png)

**Comment by chwancc** [comment]
> There are multiple 'moveable' in a page, which are isolated from each other and can only be active within their own containers
> 
> ![图片](https://user-images.githubusercontent.com/13017318/144790589-58d8702e-fe56-4872-a47f-b8c53d711458.png)

hey, Did you achieve the effect in this picture?

**Comment by chwancc** [comment]
> iCloudys

老哥，最后实现这个效果了吗，我这总跳到左上角，然后才正常

**Comment by AinCoder** [comment]
> @atomoc
> 
> Main demo https://daybrush.com/moveable/

How can we add the delete button?

**Comment by iCloudys** [comment]
> There are multiple 'moveable' in a page, which are isolated from each other and can only be active within their own containers
> 
> ![图片](https://user-images.githubusercontent.com/13017318/144790589-58d8702e-fe56-4872-a47f-b8c53d711458.png)

https://user-images.githubusercontent.com/13017318/154915264-e501520c-8230-4505-b4ea-e78908dbda7f.mp4

**Comment by daybrush** [comment]
@iCloudys 

Use `invidiualGroupable` option

**Comment by jtr-dev** [comment]
Hello, thanks so much for maintaining these packages. It's amazing to find such a resource. 

I'd like to ask how we could go about creating a demo for dragging at the bottom of a page so that it: 
1. Scrolls down while dragging
2. Persists that state to moveable and selecto

**Comment by RachelBra** [comment]
> I want to resize an image to negative width/height and produce mirroring, is that possible?

@daybrush how is that possible ?
