### ISSUE TITLE
getRect is not a function

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#191]
## Environments
* Framework name: vue
* Framework version: 2.6.11
* Moveable Component version: 0.14.1

## Description
i found an api getRect from https://daybrush.com/moveable/release/latest/doc/Moveable.html#getRect

but when i use this api code crash

my code:
`currentPageMoveable.setState({ target: this.$refs[pageId][0].$refs.editor }, () => {
          console.log(currentPageMoveable.getRect())
          window.scrollTo(currentPageMoveable.getRect().left, currentPageMoveable.getRect().top)
        })`

![image](https://user-images.githubusercontent.com/1256745/75842167-9a527300-5e0a-11ea-9b86-593f63fa9125.png)

so how to use this api

**Comment by daybrush** [comment]
@leeboo 

I'll fix it today. thank you :)

**Comment by daybrush** [comment]
@leeboo 

moveable 0.15.1 is released. Check it again.

**Comment by leeboo** [comment]
thanks daybrush
