### ISSUE TITLE
how to use methods like destroy  updateRect ....  ,  when i  use the react

### ISSUE THREAD

**Issue by tanghui28** [daybrush/moveable#192]
## Environments
* Framework name:React
* Framework version:16.7.0
* Moveable Component version:0.17.0
* Testable Address(optional):

## Description

![image](https://user-images.githubusercontent.com/35495310/75883516-1629db00-5e5e-11ea-81a6-2b3af536b071.png)

**Comment by daybrush** [comment]
@tanghui28 

https://daybrush.com/moveable/release/latest/doc/


```js
const moveableRef = React.useRef();
<Moveable ref={moveableRef}/>

moveableRef.current.dragStart(e);
moveableRef.current.updateRect();
```
`destroy` is not a method for react.

**Comment by tanghui28** [comment]
> @tanghui28
> 
> https://daybrush.com/moveable/release/latest/doc/
> 
> ```js
> const moveableRef = React.useRef();
> <Moveable ref={moveableRef}/>
> 
> moveableRef.current.dragStart(e);
> moveableRef.current.updateRect();
> ```
> 
> `destroy` is not a method for react.

thanks a lot

**Comment by schester44** [comment]
@daybrush Whats the differents between
```
const moveableRef = React.useRef();
<Moveable ref={moveableRef}/>
```

and 

```
const moveableRef = React.useRef();
<Moveable target={moveableRef.current}/>
```

**Comment by cuongdevjs** [comment]
how can I use ref with typescript?
