### ISSUE TITLE
what the difference about container rootContainer parentElement

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#194]
## Environments
* Framework name: Vue
* Framework version: 2.x
* Moveable Component version: 0.15.2

## Description
what the difference about container, rootContainer and parentElement？
i found if two moveable has the same parentElement, just show one control box;
parentElement is not the same, show two control boxes
#187 #189

**Comment by daybrush** [comment]
@leeboo 

parentElement = container
You do not need to use `container` props.
The `rootContainer` is a props to use when the parent of the container has a transform.


Is there anything different about trying to test to reproduce your situation?
https://codesandbox.io/s/confident-gagarin-6m7zv

**Comment by leeboo** [comment]
hi @daybrush 
i remove all node_modules and reinstall again, now it works.
thank you very much
