### ISSUE TITLE
How to limit the drag range using react-moveable

### ISSUE THREAD

**Issue by liuxuehuax** [daybrush/moveable#195]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

**Comment by liuxuehuax** [comment]
container：Invalid attribute

**Comment by liuxuehuax** [comment]
![image](https://user-images.githubusercontent.com/54133566/76373997-de9ac180-637c-11ea-90dd-71b37209e237.png)

**Comment by daybrush** [comment]
@liuxuehuax 

Use `bounds` props.

{ left : 0, right: width, top: 0, bottom: height }

**Comment by liuxuehuax** [comment]
@daybrush 
Doesn't seem to be of much use
Would you like to try it?
https://codesandbox.io/s/fervent-microservice-vj86d

**Comment by liuxuehuax** [comment]
![image](https://user-images.githubusercontent.com/54133566/76678243-2cc7f300-6611-11ea-8741-fcdd6e19b308.png)

**Comment by liuxuehuax** [comment]
![image](https://user-images.githubusercontent.com/54133566/76678276-7b758d00-6611-11ea-9e2c-c9f655bb7126.png)

**Comment by liuxuehuax** [comment]
@daybrush  sorry，my question！
                    Thank you~

**Comment by leeboo** [comment]
`  
          this.moveable.bounds = {
            left: offset.left,
            right: offset.left + (bg.width() || 0),
            top: offset.top,
            bottom: offset.top + (bg.height() || 0)
          }`
it not work

`new Moveable(this.$refs.workspace, {bounds:{
            left: offset.left,
            right: offset.left + (bg.width() || 0),
            top: offset.top,
            bottom: offset.top + (bg.height() || 0)
          }})` 
it works

how to reset the bounds?

**Comment by daybrush** [comment]
@leeboo 

use bounds with snappable.

```js
new Moveable(..., {
    snappable: true,
    bounds: { .... },
});
```

**Comment by o0Chivas0o** [comment]
> @daybrush sorry，my question！
> Thank you~

怎么解决的?
