### ISSUE TITLE
Add right-click event on moveable element.

### ISSUE THREAD

**Issue by Xumochuan** [daybrush/moveable#196]
## Environments
* Framework name: Angular
* Framework version: 8.0
* Moveable Component version: ngx-moveable 0.10.1
* Testable Address(optional):

## Description

Hi, @daybrush 
Amazing Moveable lib!
I am using this in my angular project and I want to add Right-Click custom context menu on Moveable element.
But, right-click event is not triggered.
![image](https://user-images.githubusercontent.com/47884397/76395726-ebd2a300-63b2-11ea-98d1-e8222a103cbb.png)

Could you do me a favor?
Many thanks.

**Comment by daybrush** [comment]
@Xumochuan 

If you want a contextmenu event, just add an event to the document.

```js
document.addEventListener("contextmenu", e => {
    console.log(e);
});
```

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Thanks
