### ISSUE TITLE
Ability to define keepRatio value for specific drag nodes

### ISSUE THREAD

**Issue by schester44** [daybrush/moveable#198]
I'd like to keep the aspect ratio when dragging from the corner drag nodes but for the side drag nodes, i'd like to resize the box horizontally without keeping the aspect ratio. 

Is something like this already possible? If not, is this something that you'd be open to accepting a PR for?

Example:
https://recordit.co/EpxKcn6aP7

**Comment by daybrush** [comment]
I don't know how you wrote the code.

If you do not want to keepRatio, you can change it to false.

**Comment by schester44** [comment]
I want keepRatio, but only for specific drag handles

**Comment by daybrush** [comment]
@schester44 

The resize event has a direction. You can check whether keepRatio is activated through direction.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#.event:resizeStart
https://daybrush.com/moveable/release/latest/doc/Moveable.html#.OnResizeStart
