### ISSUE TITLE
dragStart and dragEnd triggered but drag event not triggered

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#199]
## Environments
* Framework name: vue
* Framework version: 2.x
* Moveable Component version: 0.15.2

## Description
![image](https://user-images.githubusercontent.com/1256745/77083815-0bb03980-6a39-11ea-979a-3644eb8d1726.png)

**Comment by leeboo** [comment]
the img under mask can not drag, but can resize, i try to remove the mask div, still can not drag

**Comment by daybrush** [comment]
@leeboo 


"imgbg move" is mask? and "item img move" is img?

**Comment by leeboo** [comment]
i want drag "imgbg move", it's under the "img-mask"
it's works now, i don't know why
thanks
