### ISSUE TITLE
Vanilla implementation needs Preact module

### ISSUE THREAD

**Issue by taufiqahmed** [daybrush/moveable#2]
Tried to make it work with Angular 7. This message is shown : 
`ERROR in node_modules/preact-moveable/declaration/types.d.ts(2,27): error TS2307: Cannot find module 'preact'.`

**Comment by daybrush** [comment]
@taufiqahmed 
Sorry. There was a type problem. Updated `moveable` to `0.1.3`. Why don't you reinstall the `moveable`?
