### ISSUE TITLE
Snap to common element distances

### ISSUE THREAD

**Issue by wassgha** [daybrush/moveable#200]
Would be great if this could support snapping the common distance between existing elements. There are a few cases:

Base case (horizontal):
![ezgif com-crop (1)](https://user-images.githubusercontent.com/591655/77141723-1a97eb80-6a3b-11ea-91e1-1799278d599e.gif)

Vertical:
![ezgif com-video-to-gif (28)](https://user-images.githubusercontent.com/591655/77141752-33a09c80-6a3b-11ea-9fec-193db2fe80d4.gif)

Rotated:
![ezgif com-video-to-gif (29)](https://user-images.githubusercontent.com/591655/77141775-431fe580-6a3b-11ea-9feb-b6fee93b6c6c.gif)

Multiple:
![ezgif com-video-to-gif (30)](https://user-images.githubusercontent.com/591655/77141783-4e731100-6a3b-11ea-89d0-1591cca33034.gif)

**Comment by daybrush** [comment]
@wassgha 

Thank you :) I'll try it for next release.

**Comment by daybrush** [comment]
@wassgha 

Maybe it feels like this.

![무제](https://user-images.githubusercontent.com/3433062/77537057-cda39180-6ee0-11ea-9ed1-caa98132b52a.png)

**Comment by wassgha** [comment]
Looks awesome! Thank you :)

**Comment by daybrush** [comment]
@wassgha 

* `moveable` 0.16.1
* `react-moveable` 0.19.0
* `preact-moveable` 0.18.0
* `ngx-moveable` 0.12.0
* `svelte-moveable` 0.7.0

moveable's new version is released. Check it again. Thank you :)

add `snapGap` props. (default: true)

**Comment by wassgha** [comment]
Works great! Awesome work! 🎉 One little thing, when `isDisplaySnapDigit={false}` the number is displayed but set to `0`. Would be great if the number was completely hidden. Bonus points if this is controlled by a different boolean (e.g. `isGapSnapDigitVisible`). Thank you!

**Comment by daybrush** [comment]
@wassgha 

react-moveable 0.19.1 is released.

Check it again.
