### ISSUE TITLE
Using functional components How to trigger updateTarget （React，hooks）

### ISSUE THREAD

**Issue by liuxuehuax** [daybrush/moveable#202]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@liuxuehuax 

You will need to get an instance using useRef.

const moveableRect = React.useRef ();

moveableRect.current.updateRect ();

**Comment by liuxuehuax** [comment]
The problem was solved the day before yesterday and I forgot to close the question. But thank you very much.
@daybrush
