### ISSUE TITLE
reset bounds is not work

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#203]
## Environments
* Framework name: vue 2.x
* Framework version:
* Moveable Component version: 0.15.2

## Description
this.moveable.bounds = { left: offset.left, right: offset.left + (bg.width() || 0), top: offset.top, bottom: offset.top + (bg.height() || 0) }
it not work

new Moveable(this.$refs.workspace, {bounds:{ left: offset.left, right: offset.left + (bg.width() || 0), top: offset.top, bottom: offset.top + (bg.height() || 0) }})
it works

how to reset the bounds?

**Comment by daybrush** [comment]
Use bounds with `snappable: true`

**Comment by leeboo** [comment]
it works, thanks
