### ISSUE TITLE
can we know which element snap to?

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#204]
when moveable snap to a element, i want show this element all border,
can we know which element snap to?

**Comment by daybrush** [comment]
@leeboo 

I'll add snap event

**Comment by leeboo** [comment]
thanks

**Comment by daybrush** [comment]
@leeboo 
I'll add onSnap event

```js
export interface OnSnap {
    guidelines: Guideline[];
    elements: Guideline[][];
    gaps: GapGuideline[];
}
```

guidelines is verticalGuidelines, horizontalGuidelines
elements is elementGuidelines. The reason for the 2d array is that there are several guidelines for one element.
gaps is guidelines that became gap snap between elements.

Is there any information you would like to get here?

**Comment by leeboo** [comment]
can we know what elements is snapping to ?
i want to change those elements style( such as background color) and other interactive

**Comment by daybrush** [comment]
@leeboo 

* `moveable` 0.16.1
* `react-moveable` 0.19.0
* `preact-moveable` 0.18.0
* `ngx-moveable` 0.12.0
* `svelte-moveable` 0.7.0

add `snap` event.
```ts
export interface OnSnap {
    guidelines: Guideline[];
    elements: Guideline[][];
    gaps: GapGuideline[];
}
```

```js
moveable.on("snap", e => {
  console.log(e); // snapped guidelines
});
```

**Comment by leeboo** [comment]
thanks
