### ISSUE TITLE
Show rotated value of element when rotating start for changing??? 

### ISSUE THREAD

**Issue by Nazakatalikharal** [daybrush/moveable#206]
[##](url
![1111](https://user-images.githubusercontent.com/54443270/77759801-24cb7280-7057-11ea-8350-c860ca42958c.png)
![2222](https://user-images.githubusercontent.com/54443270/77759804-272dcc80-7057-11ea-89cc-40a2583c76b5.png)

) Environments
* Framework name: ReactJS
* Framework version: "react": "^16.13.0"
* Moveable Component version: 0.18.1
* Testable Address(optional):

## Description

I want to show rotation along with rotation icon ,but it hide rotation icon and show the value of currently rotation

**Comment by daybrush** [comment]
@Nazakatalikharal 

Use the `dist` parameter.
```jsx
<Moveable
onRotate={({ dist }) => console.log(dist)}
/>
```

**Comment by Nazakatalikharal** [comment]
Thanks for so quick response and for answer too and did the great work to proved such package to help others,God bless you,
stay home stay safe dear.
