### ISSUE TITLE
Can't call onResize and onScale at the same time.

### ISSUE THREAD

**Issue by junqdu** [daybrush/moveable#207]
## Environments
Framework name: ReactJS
Framework version: "react": "^16.12.0"
Moveable Component version: 0.17.0
Testable Address(optional): https://codesandbox.io/s/react-moveable-image-fk2lt, you'd have to change the version between `v0.16.3` and `v0.16.4` to see the difference in console.log.

## Description
@daybrush I see you have fixed a bug in https://github.com/daybrush/moveable/blob/master/CHANGELOG.md#0133---2019-12-30
>Fixed the problem that resize and scale occur simultaneously

What I am trying to achieve here is to scale with the corners, and resize with the side

so I have something like this
```
          scalable={true}
          resizable={true}
          onResize={this.onResize}
          onScale={this.onScale}
```

And before v0.16.4, both `onResize` and `onScale` will get triggered, but not with v0.16.4 or above (only `onResize`), is this intentional? Or is there a better way to achieve what I am looking for? Thanks!

**Comment by daybrush** [comment]
@leeboo 

* `moveable` 0.16.1
* `react-moveable` 0.19.0
* `preact-moveable` 0.18.0
* `ngx-moveable` 0.12.0
* `svelte-moveable` 0.7.0

Use `triggerAblesSimultaneously` props.

**Comment by junqdu** [comment]
@daybrush this is great, thank you so much!

**Comment by Jomimoses** [comment]
> Use `triggerAblesSimultaneously` props. (default: false)

i have tried the same but it flickers and both the resize and scale functions are not working fine for me

react-moveable 0.20.10

**Comment by schester44** [comment]
@daybrush Having the same issue as @Jomimoses ... When `triggerAblesSimultaneously` is set to true, the `drag.beforeTranslate` values are all over the place which causes the element to flicker.

Video: https://streamable.com/dz6rem

**Comment by daybrush** [comment]
@schester44 @Jomimoses 
Only one scale and resize should be performed. If you use triggerAblesSimultaneously, one should not be executed under certain conditions in scaleStart, resizeStart.

**Comment by sfausto** [comment]
I'm experiencing the same issue, when resizable and scalable are activated, I get a weird flickering. Im executing only onScale, and if i only disable resize, i get it to work right

**Comment by batru96** [comment]
In my case, it doesn't work for group.
