### ISSUE TITLE
scrollGroup is not working in new Release version, but only scroll works well.

### ISSUE THREAD

**Issue by Xumochuan** [daybrush/moveable#208]
## Environments
* Framework name: Angular
* Framework version: 9.1
* Moveable Component version: 0.11.0
* Testable Address(optional):

## Description

Hi, @daybrush 
How are you?
Thanks for your kind support on this amazing tool.
I have found a bug in your new releasement.
In ngx-moveable V0.9.4, scrollGroup worked well, but ngx-moveable_v0.10.0 & v0.11.1 is not working, only scroll works well, but scrollgroup don't work.
![image](https://user-images.githubusercontent.com/47884397/77834074-d3b59e80-717c-11ea-82cc-22f9e9e3cda8.png)

I appreciate if you check new release.
Many thanks.

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Thanks for your reply.
Sorry, did you fix it? or not, will you fix it in next release?
![image](https://user-images.githubusercontent.com/47884397/77951713-0ededb80-72fd-11ea-9c4d-fd61a3ab7887.png)

What do you mean this?

Thanks

**Comment by daybrush** [comment]
@Xumochuan 

* `moveable` 0.16.1
* `react-moveable` 0.19.0
* `preact-moveable` 0.18.0
* `ngx-moveable` 0.12.0
* `svelte-moveable` 0.7.0


moveable's new version is released. Thank you :)

**Comment by Xumochuan** [comment]
Hi, @daybrush 
Works well.
Many thanks.
