### ISSUE TITLE
Ability to format snap distances

### ISSUE THREAD

**Issue by wassgha** [daybrush/moveable#209]
## Environments
* Framework name: React
* Framework version: `0.16.1`
* Moveable Component version: `0.19`

## Description

Instead of `snapDigit`, would be great to have a `snapFormatter={(num) => ..}` to allow operations like re-scaling of numbers or displaying text instead of a number

**Comment by daybrush** [comment]
@wassgha 

moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

add `snapDistFormat` props.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#snapDistFormat
