### ISSUE TITLE
Firefox Issue

### ISSUE THREAD

**Issue by usama86** [daybrush/moveable#211]
## Environments
* Framework name: React
* Framework version:^16.12.0
* Moveable Component version:^0.14.1
* Testable Address(optional):

## Description
I am getting this error while running it on Firefox
![issue1](https://user-images.githubusercontent.com/29779708/78013564-184d5f80-7360-11ea-9894-37f5910cdcfe.png)
![issue2](https://user-images.githubusercontent.com/29779708/78013569-1a172300-7360-11ea-9b0f-b37957071607.png)

**Comment by daybrush** [comment]
@usama86 

Maybe you haven't set the viewBox in svg.

**Comment by daybrush** [comment]
@usama86 

react-moveable 0.19.1 is released.

try it again.

**Comment by usama86** [comment]
@daybrush  Thank you man, it's working now.
