### ISSUE TITLE
[React] pinchable: isPinch is undefined during onDrag (when actually pinching on mobile)

### ISSUE THREAD

**Issue by taze-fullstack** [daybrush/moveable#212]
## Environments
* Framework name: react-moveable
* Framework version: 0.19.1
* Moveable Component version: 0.19.1
* Testable Address(optional): https://codesandbox.io/s/react-moveable-hooks-kdvx2
* Mobile Device: Android: Samsung A50

## Description
When I change dependency installed to react-moveable 0.18.1, `isPinch` is working correctly and is `true`

**Comment by daybrush** [comment]
@taze-fullstack 

`react-moveable` 0.19.2 is released,

Thank you :)

**Comment by taze-fullstack** [comment]
Thank you. You rock!
