### ISSUE TITLE
[React]: pinchable: onPinchEnd is never called

### ISSUE THREAD

**Issue by taze-fullstack** [daybrush/moveable#213]
## Environments
* Framework name: react-moveable
* Framework version: 0.19.1
* Moveable Component version: 0.19.1
* Testable Address(optional): https://codesandbox.io/s/react-moveable-hooks-kdvx2

## Description
I forked the `react-moveable` codesandbox and played around with it. I added:
```
const onPinchEnd = () => {
    this.label.style.display = "none";
    document.getElementById("info").innerHTML = `onPinchEnd`;
  };
```
but it seems like it's never happening

**Comment by daybrush** [comment]
@taze-fullstack 

`react-moveable` 0.19.2 is released,

Thank you :)

**Comment by taze-fullstack** [comment]
Thank you. You rock!
