### ISSUE TITLE
Feature request: Is it possible to select `bounds` the same way `scrollContainer` is selected (i.e. via parent element selection)?

### ISSUE THREAD

**Issue by taze-fullstack** [daybrush/moveable#215]
## Environments
* Framework name: react-moveable

## Description
Currently, bounds are set by top, left, right, bottom coordinates. Is it possible to select `bounds` the same way `scrollContainer` is selected (i.e. via parent element selection)?

**Comment by daybrush** [comment]
I'm sorry. For bounds, snap, and innerBounds, container is the standard. container === ScrollContainer seems to be possible.

**Comment by taze-fullstack** [comment]
I was able to make it work by just getting moveable placement and then adding/subtracting fixed offset then set as bounds coordinates.
