### ISSUE TITLE
contenteditable target draggable: false not work

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#218]
## Environments
* Framework name: vue
* Framework version: 2.X
* Moveable Component version: 0.16

## Description
i set a div contenteditable=ture, and set moveable can not drag:
      this.moveable.setState({
        draggable: false
      })

but the moveable still can drag, and can not select editable text by mouse

how do i disable draggable on contenteditable target?

**Comment by daybrush** [comment]
@leeboo 

I think draggable is disabled well when I did
Is there an example I can test?

https://codepen.io/daybrush/pen/eYpEEBa
