### ISSUE TITLE
resizeEnd not firing up 

### ISSUE THREAD

**Issue by todorstoev** [daybrush/moveable#22]
hello based on the examples i have the following  

```
  .on('resizeEnd', ({ target, isDrag }) => {
        console.log('onResizeEnd', target, isDrag);
      });
```
but it dont seems to triger the event. No problems with resizeStart and resize.

**Comment by daybrush** [comment]
@todorstoev 

I'm sorry. Moveable needs to call `resizeEnd`, but is calling `scaleEnd`.

I'll fix it soon.

**Comment by todorstoev** [comment]
Thanks until then hooking to `scaleEnd` seem to be doing the job .

**Comment by daybrush** [comment]
@todorstoev 

Moveable 0.7.0 is released. Please check again.

**Comment by todorstoev** [comment]
Hello @daybrush  ,

unfortunately after the update im getting prompted for react and im not using it in my project.

![image](https://user-images.githubusercontent.com/24528337/63335830-bf880400-c346-11e9-972b-44157a2f04f1.png)

**Comment by daybrush** [comment]
@todorstoev
Oh my mistake...
I will remove  import and deploy it again.

Thank you

**Comment by daybrush** [comment]
@todorstoev

React type has been removed.

Moveable 0.7.2 is released. Please check again.

**Comment by todorstoev** [comment]
@daybrush 

All good now. Thanks a lot.
