### ISSUE TITLE
Moveable.request does not work

### ISSUE THREAD

**Issue by horsenit** [daybrush/moveable#220]
## Environments
* Framework name: Vanilla
* Framework version:
* Moveable Component version: 0.16.3 (latest)
* Testable Address(optional): https://codepen.io/doobob/pen/MWagzEw

## Description

In 0.16.3 Moveable.request('draggable') works for a single target, but for a group does not work and 'dragGroup' gets called with invalid (NaN) values. (This works correctly in 0.16.2)

Moveable.request('scalable') does not work. The 'scale' event gets called with invalid (NaN) values. (This doesn't seem to work in any version, on a group or a single target)

Additionally Moveable.request('resizable') seems to behave incorrectly. It seems to result in an incorrect translation, unless I'm mistaken of the intended behaviour.

**Comment by daybrush** [comment]
@horsenit

moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

Check it again. Thank you :)

**Comment by horsenit** [comment]
Hi, thank you for addressing it, but Moveable.request('draggable') still does not work for groupable moveable target.

Moveable.request('scalable') does work very well now on a group.

**Comment by daybrush** [comment]
@horsenit 

* `moveable` 0.17.5
* `react-moveable` 0.20.6
* `preact-moveable` 0.19.6
* `ngx-moveable` 0.13.6
* `svelte-moveable` 0.8.6

moveable's new version is released. Check it again.

**Comment by horsenit** [comment]
It works very well, thank you very much.
