### ISSUE TITLE
bounds not work on resize

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#221]
## Environments
* Framework name: vue
* Framework version: 2.x
* Moveable Component version: 0.16.1

## Description
the bounds setting just work on drag event, when resize it not works
![QQ20200414-225426](https://user-images.githubusercontent.com/1256745/79239286-f8ab5080-7ea2-11ea-9c12-5574d9797b10.gif)

**Comment by daybrush** [comment]
@leeboo 

is it innerBounds?

**Comment by taze-fullstack** [comment]
@daybrush Not sure if @leeboo and I mean the same thing but here's what my steps to reproduce:

1. Set resizable to `true` and snappable to `true` 
2. Drag moveable to leftmost of bounds
3. Use `NE` or `SE` drag handle to extend
4. Drag moveable again.

**Expectation:**
* User should not be able to extend with `NE` (?)

**Here's what's happening**
Sandbox: https://codesandbox.io/s/react-resizable-bounds-error-u4rzz?file=/src/index.js
GIF:
![GIF 7 May 2020 11-35-07 pm](https://user-images.githubusercontent.com/36070737/81314291-87367a80-90bb-11ea-825b-012f0a2dc452.gif)

**Comment by daybrush** [comment]
@taze-fullstack 


Use `drag` event property.
See the link below:
https://daybrush.com/moveable/storybook/?path=/story/basic--resizable

**Comment by leeboo** [comment]
> @leeboo
> 
> is it innerBounds?

maybe is my question, let me check it again

**Comment by daybrush** [comment]
@leeboo 

* `moveable` 0.17.7
* `react-moveable` 0.20.8
* `preact-moveable` 0.19.8
* `ngx-moveable` 0.13.8
* `svelte-moveable` 0.8.8


moveable's new version is released. Check it again.

**Comment by leeboo** [comment]
thank you
