### ISSUE TITLE
Gaps props in OnSnap event is empty

### ISSUE THREAD

**Issue by Yomyer** [daybrush/moveable#222]
## Environments
* Framework name: ngx-moveable
* Framework version: 0.12.2
* Moveable Component version: 0.16.3
* Testable Address(optional):

## Description

The gaps property of the OnSnap event always comes empty even if you see the guidelines with the data-size with value.

I have a zoom controlled by a conversion factor, everything works correctly but snapDigit comes with the real screen values and I wanted to see if with the OnSnap event I could factor the value.

It is normal that the gap array has no value 

Thanks

**Comment by Yomyer** [comment]
I understand the values returned by the OnSnap event:

gaps: These are the red lines that mark the distance between elements when they are equal.
elements: Are the blue guides that mark the distance between elements.

I have overwritten the values but it modifies the lines, I have looked at the code and the numerical value that is shown is the result of some calculations that are made with getElementGuidelineDist, there is no way to overwrite the numerical value or apply a zoom factor?

For example adding a label property to the Guideline object and in the renderElementGroup if that label exists show in data-size that label otherwise, it shows the initial calculation.  This way I could do the calculation with the size and pos values and then apply the conversion factor and save it in the label without affecting the line render.


```
export interface Guideline {
    type: "horizontal" | "vertical";
    element?: Element | null;
    center?: boolean;
    pos: number[];
    size: number;
    sizes?: number[];
    gap?: number;
    gapGuidelines?: Guideline[];
    gapLabel?: string;
}
```

```
function renderElementGroup(
    group: Guideline[][],
    [directionName, posName1, posName2, sizeName]: readonly [string, string, string, string],
    minPos: number,
    clientPos: number,
    clientSize: number,
    targetPos: number,
    snapThreshold: number,
    isDisplaySnapDigit: boolean,
    snapDigit: number,
    index: number,
    React: Renderer,
) {
    return flat(group.map((elementGuidelines, i) => {
        let isFirstRenderSize = true;

        return elementGuidelines.map(({ pos, size, gapLabel }, j) => {
            const {
                pos: linePos,
                size: lineSize,
            } = getElementGuidelineDist(pos[index], size, clientPos, clientSize);

            if (lineSize < snapThreshold) {
                return null;
            }
            const isRenderSize = isFirstRenderSize;

            isFirstRenderSize = false;
            let snapSize = isDisplaySnapDigit && isRenderSize ? parseFloat(lineSize.toFixed(snapDigit)) : 0;
           
            if(gapLabel && snapSize){
                snapSize = gapLabel
            }
       
            return <div className={prefix(
                "line",
                directionName,
                "guideline",
                "dashed",
            )}
                data-size={snapSize > 0 ? snapSize : ""}
                key={`${directionName}LinkGuidline${i}-${j}`} style={{
                    [posName1]: `${minPos + linePos}px`,
                    [posName2]: `${-targetPos + pos[index ? 0 : 1]}px`,
                    [sizeName]: `${lineSize}px`,
                }} />;
        });
    }));
}
```


Thank you.

**Comment by daybrush** [comment]
@Yomyer 
Do you want to change the distance figure that shows you zoom in?

**Comment by daybrush** [comment]
@Yomyer 

moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

Do you want the ability to change the format of the snap's distance?

add `snapDistFormat` props.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#snapDistFormat
