### ISSUE TITLE
Frame.ts can parse and stringify 'background-image: gradient'? i found if has css string contain gradient property, code will be crashed

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#223]
## Environments
* Framework name: vue
* Framework version: 2.x
* Moveable Component version: 0.16.1

## Description
`const frame: Frame = new Frame('background-image: gradient(linear, left 0, right 0, from(rgb(4, 94, 170)), to(rgb(1, 152, 216)))')`

code crashed and cpu 100%

**Comment by daybrush** [comment]
@leeboo 

It has not yet been able to support more than three overlapping parentheses. I'm sorry.

**Comment by daybrush** [comment]
https://github.com/daybrush/scenejs/issues/60
