### ISSUE TITLE
need to support guidelines which are not all the way through, any ideas?

### ISSUE THREAD

**Issue by born2net** [daybrush/moveable#224]
So I have this requirement in my project to support the red guidelines which are not all the way through... see image:

![image_2020_04_26T01_53_06_898Z](https://user-images.githubusercontent.com/5090936/80295382-18563a80-8727-11ea-8e70-4ce24867469b.png)

I wonder if anyone has any ideas how to achieve that.
I don't mind if the 2nd part of the red gudeline is just hidden via low opacity / alpha and still works (magnetized)... but need it to be hidden.

Thanks for a great project,

Sean.

**Comment by daybrush** [comment]
@born2net 

I think the transparent lines overlapped and became darker.

target has `moveable-target` class.

**Comment by born2net** [comment]
ok thank you.
