### ISSUE TITLE
In main demo, if the keyboard arrow is held down, drag feature eventually breaks

### ISSUE THREAD

**Issue by bxchang04** [daybrush/moveable#225]
In the main demo, if the keyboard arrow is held down, the keyboard arrow to drag feature eventually breaks (I'm on Chrome, latest ver.).

I think this is a bug. Can you please investigate? Thanks for this new feature!

_Originally posted by @bxchang04 in https://github.com/daybrush/moveable/issues/141#issuecomment-620299786_

**Comment by daybrush** [comment]
@bxchang04 

Thank you. This seems to have given the effect of being stopped by snap. I'm going to improve.

**Comment by daybrush** [comment]
@bxchang04 

moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

Check it again. Thank you :)
