### ISSUE TITLE
Drop container in the drop event?

### ISSUE THREAD

**Issue by GKatsarov** [daybrush/moveable#226]
## Environments
* Framework name: latest
* Framework version: latest
* Moveable Component version: latest
* Testable Address(optional): https://codepen.io/Vronn/pen/eYpEJvq

## Description
I've been using the library for a month now, I've tested all the events, inputEvent, target, everything, I still cant manage to get the container in which I drop the element. The thing I do is very easy. I have a div inside my main container, 50% top, 50% height, and the element at the top of the container. I try to move the element inside the div, drop it, and I can't get the div in any way. Please help!

**Comment by daybrush** [comment]
I cannot provide a drop event.

Instead, hitTest method can be used to test drop the container.

```js
moveable.hitTest(dropContainer: element | { left, top, width, height }): number;
```

**Comment by GKatsarov** [comment]
I cannot seem to find any function `hitTest` in the moveable library. I've even checked the 

[//daybrush.com/moveable/release/latest/dist/moveable.min.js](url)

for references and still nothing. Can you provide an example or anything, that I can use, for the current version of the library? Thanks a lot in advance!

**Comment by daybrush** [comment]
@GKatsarov 
oh. sorry. i'll add this method.

**Comment by daybrush** [comment]
@GKatsarov 


moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

Check `hitTest` method. Thank you :)
