### ISSUE TITLE
Is there a way to restrict the dragable element so it cannot be dragged outside of it's container?

### ISSUE THREAD

**Issue by ryanz67** [daybrush/moveable#227]
## Environments
* Framework name: Latest
* Framework version: Latest
* Moveable Component version: Latest
* Testable Address(optional): https://codesandbox.io/s/react-moveable-demo-kt6e7?file=/src/index.js

## Description
Is there anyway to restrict where draggable element can be dragged. For example in the testatble address I have added a red container, I do not want the draggable element to be able to dragged out of it's container. Is this possible ? 

Many thanks

**Comment by GKatsarov** [comment]
U need to use        
 `snappable: true,` option with 
`        bounds: {
            left:0,
            top: 0,
            right:el.width(), //200
            bottom:el.height() //200
        }` for example

**Comment by ryanz67** [comment]
Thanks a lot really appreciate it thats what i was looking for :)
