### ISSUE TITLE
Error: @Output click not initialized in 'NgxMoveableComponent' 

### ISSUE THREAD

**Issue by saurabhsksharma** [daybrush/moveable#228]
## Environments
* Framework name: Angular
* Framework version: 9.1.0
* Moveable Component version: 0.16.3 
* ngx-moveable version: 0.12.2
* Testable Address(optional):

## Description

Unable to add click event. I need to create multiple ngx-moveable elements and enable "*ables" on click. But getting error

Error: @Output click not initialized in 'NgxMoveableComponent'

**Comment by daybrush** [comment]
@saurabhsksharma 
moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

Check it again. Thank you :)

**Comment by saurabhsksharma** [comment]
Thanks, I have updated my project dependencies to latest. Error has gone now, but the click is still not working. See the screenshots. Is this the right way of implementation? Am I doing something wrong? This is the same way drag, resize, rotate are working but not click.

![image](https://user-images.githubusercontent.com/3503177/80908198-a049cf00-8d3b-11ea-8200-1428b0a3b6bd.png)
![image](https://user-images.githubusercontent.com/3503177/80908205-b5266280-8d3b-11ea-93cb-045560c11a1a.png)

**Comment by daybrush** [comment]
@saurabhsksharma 

oh. `click` and `clickGroup` are fired only when the dragArea is activated.

**Comment by saurabhsksharma** [comment]
Thanks, it's working now. Just added [dragArea]="true". Thanks again. :)

**Comment by saurabhsksharma** [comment]
Is it possible to do click while draggable = false and dragArea = true? It's not working. I should have to enable drag to fire click event.

**Comment by daybrush** [comment]
@saurabhsksharma 

* `moveable` 0.17.3
* `react-moveable` 0.20.4
* `preact-moveable` 0.19.4
* `ngx-moveable` 0.13.3
* `svelte-moveable` 0.8.3

moveable's new version is released.

Check it again.

**Comment by saurabhsksharma** [comment]
It's not pushed yet to npmjs.com. Meanwhile, I install it via `npm i <git url>`

**Comment by saurabhsksharma** [comment]
> @saurabhsksharma
> 
> * `moveable` 0.17.3
> * `react-moveable` 0.20.4
> * `preact-moveable` 0.19.4
> * `ngx-moveable` 0.13.3
> * `svelte-moveable` 0.8.3
> 
> moveable's new version is released.
> 
> Check it again.

`moveable` 0.17.3 is not pushed to [npmjs.com](https://www.npmjs.com/package/moveable). Not getting any update from `npm i moveable@latest`.

**Comment by daybrush** [comment]
@saurabhsksharma 

Oh, sorry. it's my mistake

Try it again.
* `moveable` 0.17.3
* `react-moveable` 0.20.4
* `preact-moveable` 0.19.4
* `ngx-moveable` 0.13.4
* `svelte-moveable` 0.8.4

**Comment by saurabhsksharma** [comment]
> * 0.13.4

Got the updates. But something got wrong. Getting the following error now

```
ERROR TypeError: Cannot read property 'getElement' of undefined
    at MoveableManager.__proto.updateRect (moveable.esm.js:1481)
    at MoveableManager.__proto.checkUpdate (moveable.esm.js:1663)
    at MoveableManager.__proto.render (moveable.esm.js:1336)
    at ComponentProvider.__proto._render (compat.esm.js:604)
    at ComponentProvider.__proto._update (compat.esm.js:254)
    at compat.esm.js:823
    at Array.filter (<anonymous>)
    at renderProviders (compat.esm.js:822)
    at ComponentProvider.__proto._render (compat.esm.js:610)
    at ComponentProvider.__proto._update (compat.esm.js:254)
```

**Comment by saurabhsksharma** [comment]
> @saurabhsksharma
> 
> Oh, sorry. it's my mistake
> 
> Try it again.
> 
> * `moveable` 0.17.3
> * `react-moveable` 0.20.4
> * `preact-moveable` 0.19.4
> * `ngx-moveable` 0.13.4
> * `svelte-moveable` 0.8.4

Got the updates. But something got wrong. Getting the following error now

```
ERROR TypeError: Cannot read property 'getElement' of undefined
    at MoveableManager.__proto.updateRect (moveable.esm.js:1481)
    at MoveableManager.__proto.checkUpdate (moveable.esm.js:1663)
    at MoveableManager.__proto.render (moveable.esm.js:1336)
    at ComponentProvider.__proto._render (compat.esm.js:604)
    at ComponentProvider.__proto._update (compat.esm.js:254)
    at compat.esm.js:823
    at Array.filter (<anonymous>)
    at renderProviders (compat.esm.js:822)
    at ComponentProvider.__proto._render (compat.esm.js:610)
    at ComponentProvider.__proto._update (compat.esm.js:254)
```

**Comment by daybrush** [comment]
@saurabhsksharma 

moveable's new version is released.
* `moveable` 0.17.4
* `react-moveable` 0.20.5
* `preact-moveable` 0.19.5
* `ngx-moveable` 0.13.5
* `svelte-moveable` 0.8.5


Check it again.

**Comment by saurabhsksharma** [comment]
> @saurabhsksharma
> 
> moveable's new version is released.
> 
> * `moveable` 0.17.4
> * `react-moveable` 0.20.5
> * `preact-moveable` 0.19.5
> * `ngx-moveable` 0.13.5
> * `svelte-moveable` 0.8.5
> 
> Check it again.

@daybrush, It's working now. I can click on Moveable components while all *ables are false. Thanks.
