### ISSUE TITLE
for draggable boundary feature not added

### ISSUE THREAD

**Issue by hitesh0609** [daybrush/moveable#23]
I didn't find property to set boundary for drag.

**Comment by daybrush** [comment]
@hitesh0609 
Is this what you're saying?


![boundary](https://user-images.githubusercontent.com/3433062/63006113-d0ed8e00-beb8-11e9-9a9e-2f6bd4e1d2eb.gif)

**Comment by hitesh0609** [comment]
I am sending link for reference:
https://xieziyu.github.io/angular2-draggable/#/draggable/usage/boundary.

I want this feature. Can you help me to get this feature?

**Comment by daybrush** [comment]
@hitesh0609 

Thank you. I checked.

Unfortunately, moveable does not provide the ability to check the bouncery. The user must create a check function for the bouncer.

Perhaps this function will be made next month.

**Comment by hitesh0609** [comment]
thank you. How can get target element id from for loop in angular use this package?

I am sending html and ts that i have written:
////////////////////////////// html code ////////////////////////////////////////

<ng-container *ngFor="let div of arrModificationLocations;let i=index">
                  <div #target id="tdiv_{{ i }}" (cdkDragMoved)="dragMove($event)" cdkDragBoundary=".img-text" cdkDrag>{{this.objFontProperty.text}}</div>
                  <ngx-moveable #moveable [target]="target" [rotatable]="true" [throttleRotate]="0" [keepRatio]="true"
                    (rotate)="onRotate($event)"></ngx-moveable>
                </ng-container>

/////////////////////////// ts code //////////////////////////////////
 onRotate({ target, beforeDelta }: OnRotate) {
    const rotateele = target;
    this.setTransform(rotateele);
    const deg = parseFloat(this.frame.get("transform", "rotate")) + beforeDelta;
    this.frame.set("transform", "rotate", `${deg}deg`);
    console.log('rotate', deg.toFixed(1));
  }

**Comment by daybrush** [comment]
@hitesh0609 

What is the #target if you use `for`?

I think I can use it with the following.

```js
onRotate({ target, beforeDelta }: OnRotate) {
console.log(target.getAttribute("id"));
}
```

**Comment by hitesh0609** [comment]
thank you.

**Comment by daybrush** [comment]
@hitesh0609 
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

React code is as follows.

```tsx
<Moveable bounds={{left: 0, right: 1000, top: 0, bottom: 1000}} />
```
Thank you :)
