### ISSUE TITLE
How to set min, max size for moveable.

### ISSUE THREAD

**Issue by hieuctfe** [daybrush/moveable#231]
## Environments
* Framework name: Vue
* Framework version: ^2.6.10
* Moveable Component version: ^0.14.1
* Testable Address(optional):

## Description
- I use movable to implement drag, drop resize image. I try to set default min, max size for moveable via css and use condition in on('resize') function, It work well when I resize with "bottom - right" point but three other point ("top-left", top-right, bottom-left) have flickering when I resize.
- Please help me how can I set min, max size for movable. Thanks you very much.

**Comment by daybrush** [comment]
@hieuctfe 

Oh, Sorry. Min and max sizes are not supported yet.

I will add features later.

**Comment by hieuctfe** [comment]
Thanks for your quick response. Hope you can support this feature soon. :)

**Comment by daybrush** [comment]
@hieuctfe 

* `moveable` 0.17.5
* `react-moveable` 0.20.6
* `preact-moveable` 0.19.6
* `ngx-moveable` 0.13.6
* `svelte-moveable` 0.8.6

moveable's new version is released.


it's not perfect. use `min-width`, `max-width` css properties.
It can be set as a control with the css properties.

**Comment by hieuctfe** [comment]
Thanks @daybrush, it's solve my problem that take me a lot of time. 
- before that I try to use stop() function but it not work, I try another way by throw exception in on('resize') function. (Check size and if it's max or min size I will throw exception), It's may work but it's not good way. Btw thanks you very much.
