### ISSUE TITLE
Rotate not working in firefox

### ISSUE THREAD

**Issue by masoudelahi** [daybrush/moveable#234]
version: 0.17.5
Rotate not working on Firefox, I tested main demo its also not rotating

.on('rotate', ({ target, rotate }) => {
          target.style.transform = 'rotate(' + r + 'deg)';
});

**Comment by btir** [comment]
Seems like the problem is in new version's, I'm using version 0.15.2 but it does not have any problem with Firefox and other browser's.

**Comment by daybrush** [comment]
@btir @masoudelahi 

Oh thank you. Found the cause.

In firefox, an element with a width and height of 0 has an error that results in the left and top of getBoundingClientRect () being 0.

**Comment by masoudelahi** [comment]
It's working now,
Thanks for your awesome library

**Comment by daybrush** [comment]
@masoudelahi  @btir 
* `moveable` 0.17.6
* `react-moveable` 0.20.7
* `preact-moveable` 0.19.7
* `ngx-moveable` 0.13.7
* `svelte-moveable` 0.8.7

**Comment by btir** [comment]
Thank you so much @daybrush for your quick response!
