### ISSUE TITLE
Feature request: Is it possible to implement initial throttle to drag (like a threshold to START drag)?

### ISSUE THREAD

**Issue by taze-fullstack** [daybrush/moveable#236]
## Description
When `throttle = 10`, it makes draggable drag every `10` pixels. 

Is it possible to have a `threshold of 10` for initial drag only, and then `throttle = 2` so that: after `10px` INITIAL movement, it STARTS to drag, THEN throttles for 2px after?

**Comment by taze-fullstack** [comment]
Here's how I currently did it:

```jsx
const [isDragging, setIsDragging] = useState<boolean>(false);

const onDrag = ({top, left}: OnDrag) => {
   setIsDragging(true);
}

const onDragEnd = () => {
   setIsDragging(false);
}

<Moveable throttleDrag={isDragging ? 2 : 10} />
```

I wonder if it's worth implementing so that:

```jsx
<Moveable throttleDrag={2} thresholdDrag={10} />
```

**Comment by daybrush** [comment]
@taze-fullstack 

It's what you did. You can do this by adjusting the throttleDrag value.
