### ISSUE TITLE
[react-moveable]: Too many re-renders due to forceUpdate()?

### ISSUE THREAD

**Issue by taze-fullstack** [daybrush/moveable#237]
## Environments
* Framework name: react-moveable
* Framework version: 0.20.6
* Testable Address(optional): https://codesandbox.io/s/react-moveable-demo-zy04w?file=/src/index.js

## Description
* I installed [`why-did-you-render`](https://github.com/welldone-software/why-did-you-render) as part of trying to optimize speed and I'm getting a lot of warnings pinging me that objects and props may be the same but it's still re-rendered and this is probably because of forceUpdate()?

**Comment by daybrush** [comment]
@taze-fullstack 

Yes. Use `forceUpdate` to drag or re-render when dragging is finished.

**Comment by taze-fullstack** [comment]
Turns out I had other components with a really expensive computation that really weighed it down. I also double checked all expensive re-renders with [why-did-you-render](https://github.com/welldone-software/why-did-you-render)
