### ISSUE TITLE
Svelte examples for Moveable.js not working

### ISSUE THREAD

**Issue by arperyan** [daybrush/moveable#239]
## Environments
* Framework name: Svelte 
* Framework version: 13.12.1
* Moveable Component version: + 0.4.4
* Testable Address(optional): https://codesandbox.io/s/svelte-moveable-demo-nczer?file=/index.js

## Description
TypeError
create_fragment is not a function - this happens from version 0.4.4

**Comment by daybrush** [comment]
@arperyan 

Fix svelte demo. Thank you :)

https://codesandbox.io/s/svelte-moveable-demo-qi7fu?file=/App.svelte

**Comment by arperyan** [comment]
Thank you so much!
