### ISSUE TITLE
Resize event edges/corners

### ISSUE THREAD

**Issue by RicardoLimaDev** [daybrush/moveable#24]
How can i get the edges in which a resize is occurring? eg: Top-left, Bottom Left... is that possible?

**Comment by daybrush** [comment]
@RicardoLimaDev 

Is this what you said? #23 

I plan to support this feature in a version that will be released in 8.19.

**Comment by daybrush** [comment]
@RicardoLimaDev 

Moveable 0.7.0 is released. edge drag is possible when the edge option is enabled.

```js
new Moveable(document.body, {
    resizable: truem
    edge: true,
});
```

**Comment by outpunk** [comment]
@daybrush It seems @RicardoLimaDev says that he would like to detect which control we're dragging using an event metadata.

**Comment by daybrush** [comment]
@outpunk  @RicardoLimaDev

**Comment by RicardoLimaDev** [comment]
> @outpunk @RicardoLimaDev
> Maybe you're right. I'll add it to the next feature.

Thanks!

**Comment by daybrush** [comment]
@hitesh0609 
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

React code is as follows.

```tsx
onReisze={({ direction }) => {
   // [1, 1] => right, bottom
   // [-1, -1] => left, top
  // [0, -1] => center, top
    console.log(direction);
}}
```
Thank you :)

**Comment by daybrush** [comment]
@RicardoLimaDev 
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

React code is as follows.

```tsx
onResoze={({ direction }) => {
   // [1, 1] => right, bottom
   // [-1, -1] => left, top
  // [0, -1] => center, top
    console.log(direction);
}}
```
Thank you :)

**Comment by kauly** [comment]
It's also possible to know the direction in the `onResizeEnd` event?

**Comment by kounorimich** [comment]
@kauly 
I think `onResizeEnd` essencially do not have any _direction_ .

I don't know if it is helpful for you, but you can access the last resize event by using `lastEvent`.

```
onResizeEnd={(endEvent) => {
          if (endEvent.lastEvent == null) {
            return;
          }
          lastEvent.direction
        }}
