### ISSUE TITLE
[BUG] resize doesnt work if the mouse is outside of the parent boundaries

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#241]
## Environments
* Framework name: vanilla
* Framework version:
* Moveable Component version: latest
* Testable Address(optional): https://jsfiddle.net/muah003/r9kfay7q/14/

## Description
- try to resize using any of the corners, the operation will stop once the mouse is outside of the parent
- now try to resize using the `n, s` points it will resize to the full as expected

**Comment by daybrush** [comment]
@ctf0 

* `moveable` 0.17.7
* `react-moveable` 0.20.8
* `preact-moveable` 0.19.8
* `ngx-moveable` 0.13.8
* `svelte-moveable` 0.8.8


moveable's new version is released. Check it again.

**Comment by ctf0** [comment]
not fixed yet unfortunately 😢 , maybe the issue ticket or description was misleading.

try to click and drag any of the corners handler as far as you can, once the mouse is out of the box (t-shirt in this case) the resize will stop.

what you would expect is that the resize operation will continue until the corner handler has reached the boundaries the user have set.

if you need a gif to explain it more plz tell me.

**Comment by ctf0** [comment]
**edit**

i've found the issue, the answer from https://github.com/daybrush/moveable/issues/242 was the solution, many many thanx again
