### ISSUE TITLE
[BUG] resize starts to expand from the top-left after drag

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#242]
## Environments
* Framework name: vanilla
* Framework version:
* Moveable Component version: latest
* Testable Address(optional): https://jsfiddle.net/muah003/r9kfay7q/14/

## Description
- try to resize on first run from the top-left or bottom-left, it will expand as expected.
- now drag the item & try to resize again, the expanding is now based on the top-left

**Comment by daybrush** [comment]
@ctf0 

because parent element `product` is `display: flex`.

The second action is normal.

And use drag property.

```js
    .on('resize', ({
        target,
        width,
        height,
        drag,
    }) => {
        target.style.width = width + 'px'
        target.style.height = height + 'px'
        target.style.left = drag.left + 'px'
        target.style.top = drag.top + 'px'
    })
```

**Comment by ctf0** [comment]
focken awesome, many thanx for ur work & time
