### ISSUE TITLE
[question] how to keep the movable box at place on window resize

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#244]
## Environments
* Framework name: vanilla
* Framework version:
* Moveable Component version: latest
* Testable Address(optional): https://jsfiddle.net/muah003/r9kfay7q/14/

## Description
- try to resize the demo window or inc/dec the browser zoom
- the movable box is moving all around

i managed to recalculate the boundaries on resize but how to get the movable box position to account for browser zoom/resize ?

**Comment by daybrush** [comment]
you can call `updateRect()`

```js
moveable.updateRect();
```

**Comment by ctf0** [comment]
i will give that a try, thnx

**Comment by ctf0** [comment]
the answer would be to calc the new pixel count and change the box size accordingly.

i originally thought i was missing an option that moveable can take care of this automatically, but my bad.

thanx again for ur help 🥇
