### ISSUE TITLE
[BUG] resize flicker on bottom-left & bottom-right handlers

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#245]
## Environments
* Framework name: vanilla
* Framework version:
* Moveable Component version: latest
* Testable Address(optional): https://jsfiddle.net/muah003/r9kfay7q/14/

## Description
- try to resize using either bottom-left or bottom-right handlers
- movable item will flicker

**Comment by daybrush** [comment]
@ctf0 


* `moveable` 0.17.7
* `react-moveable` 0.20.8
* `preact-moveable` 0.19.8
* `ngx-moveable` 0.13.8
* `svelte-moveable` 0.8.8


moveable's new version is released. Check it again.

**Comment by ctf0** [comment]
😍  🎊  🚀
