### ISSUE TITLE
[question] how snap to center work ?

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#247]
## Environments
* Framework name: vanilla
* Framework version:
* Moveable Component version: latest
* Testable Address(optional):

## Description
- am trying to add a snap to center btn but i cant find anywhere in the docs how the `snapCenter` calculate the h/v centering.

**Comment by daybrush** [comment]
@ctf0 

Here it is:
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-snappable

**Comment by ctf0** [comment]
no, i meant 
- how can i get the correct `left & top` measurements ?
- or what is the function moveable use ? 

so when i click a btn it would do the same thing as if i dragged the box to the center on both the x/y axis.

**Comment by daybrush** [comment]
@ctf0 

It seems to be similar to the issues raised so far.
https://github.com/daybrush/moveable/issues/244

I'll check that.

**Comment by ctf0** [comment]
no, the other issue is related to moveable being able to recalc the box position on window width & height change to make sure it stays the same.

**Comment by daybrush** [comment]
@ctf0 

Wouldn't you want elementGuidelines?
```jsx
<Moveable
elementGuidelines={[document.querySelector("container")]}/>
```

**Comment by ctf0** [comment]
am already using it, i want to snap the item with a btn instead of dragging all over until i see the vertical & horizontal guide lines

**Comment by daybrush** [comment]
@ctf0 

You can't snap through buttons. You have to find the offsetWidth and offsetHeight of the shirt yourself and move it to the center.

**Comment by ctf0** [comment]
oh, okey, thanx for ur help 👍
