### ISSUE TITLE
Unable to edit text after adding contenteditable

### ISSUE THREAD

**Issue by YGYOOO** [daybrush/moveable#250]
## Environments
* Framework name: react
* Framework version:16.9
* Moveable Component version: react-moveable 0.20.8
* Testable Address(optional):

## Description
Hi, I have noticed this issue https://github.com/daybrush/moveable/issues/132 . It would work on Angular when using the "stop" method in dragStart. But i found that there is no "stop" method in dragStart  in react-moveable.

**Comment by daybrush** [comment]
@YGYOOO 

in react call `return false`. Thank you :)

**Comment by YGYOOO** [comment]
It worked, thanks
