### ISSUE TITLE
Dragging: right-click on the element causes dragging while the mouse is not down

### ISSUE THREAD

**Issue by miina** [daybrush/moveable#252]
## Environments
* Framework name: React
* Framework version: 16.13.1
* Moveable Component version: 0.20.8
* Testable Address(optional): https://daybrush.com/moveable/ (since this can be seen on the demo page, too)
 
## Description

When doing right-click on the element and then not choosing any option from the context menu, the element is being dragged around even though the mouse/pointer is not down anymore.

To reproduce:
1. Go to https://daybrush.com/moveable/
2. Do right-click on the element that's Draggable
3. Now click somewhere outside of the context menu that opened.
4. Move the pointer around -- see the element dragging along.

![sticky](https://user-images.githubusercontent.com/3294597/83643052-e2229b00-a5af-11ea-858e-8bf93283ec63.gif)

**Comment by daybrush** [comment]
@miina 

It is also intended to bring up the context menu, so I cannot prevent myself from being selected when the right mouse button is clicked.

You set css:
```js
https://stackoverflow.com/questions/16805684/javascript-disable-text-select
```

or 
call collapse 
https://developer.mozilla.org/en-US/docs/Web/API/Selection/collapse
```js
document.getSelection().collapse(document.getSelection().focuseNode, 0)
```

**Comment by miina** [comment]
@daybrush Perhaps the video wasn't the best example. This also happens without any text being selected:
![dragging](https://user-images.githubusercontent.com/3294597/83651587-f23f7800-a5b9-11ea-9bd4-41f8ed163755.gif)

Note that the context menu appearing is expected, there is no issue with that.
The issue is that after closing the context menu, the element gets "stuck" to the mouse and is dragging along even though I'm not really dragging anything -- I'm just moving the mouse.

The expected behavior: dragging should not get started by right-click.

Thoughts?

**Comment by miina** [comment]
@daybrush Ah, okay, now I see, I'm using OSX without an actual mouse, meaning that what I'm really doing is using `cntrlKey` with `which: 1`:
<img width="276" alt="Screenshot 2020-06-04 at 10 51 27" src="https://user-images.githubusercontent.com/3294597/83736109-7bee5480-a651-11ea-94c5-9cf6130c74ac.png">
...
<img width="299" alt="Screenshot 2020-06-04 at 10 51 52" src="https://user-images.githubusercontent.com/3294597/83736096-7a249100-a651-11ea-955d-e656e0d65f6f.png">


Sorry for the confusion!

Is this something you could look into or should we handle this from our side?

Thank you!

**Comment by daybrush** [comment]
If there is a way right now

```js
onDragStart={e => {
    if (e.inputEvent.ctrlKey) {
        return false;
    }
}}
```

**Comment by daybrush** [comment]
@miina 

* `moveable` 0.17.9
* `react-moveable` 0.20.9
* `preact-moveable` 0.19.9
* `ngx-moveable` 0.13.10
* `svelte-moveable` 0.8.10

moveable's new version is released. Check it again.

**Comment by miina** [comment]
@daybrush Seems to work well, thank you!
