### ISSUE TITLE
Can't resize an element that had `min-height`.

### ISSUE THREAD

**Issue by idanen** [daybrush/moveable#256]
## Environments
* Framework name: Vanilla
* Moveable Component version: 0.17.10
* Testable Address(optional): https://codesandbox.io/s/moveable-resize-min-height-cm8bf

## Description

When an element initially has `min-height` set, the `resize` event won't fire even when removing the `min-height` in the `resizeStart` event.
This worked in versions prior to 0.17.0

**Comment by daybrush** [comment]
@idanen 
This happens because minSize and maxSize are checked just before resizeStart.


I'll consider adding this feature.

**Comment by idanen** [comment]
Can it be checked after? And only once probably? 
This check didn't exist in previous versions, right?

**Comment by daybrush** [comment]
@idanen 

There is no way yet. I started checking at 0.17.5.
https://github.com/daybrush/moveable/releases/tag/0.17.5

**Comment by daybrush** [comment]
@idanen 

moveable's new version is released.
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1

https://daybrush.com/moveable/release/latest/doc/Moveable.Resizable.html#.OnResizeStart

you can use setMin, setMax.

**Comment by idanen** [comment]
Awesome! Thanks
