### ISSUE TITLE
Highly customized rotation dot?

### ISSUE THREAD

**Issue by YGYOOO** [daybrush/moveable#259]
## Environments
* Framework name: react
* Framework version: 16.9
* Moveable Component version: 0.20.8

## Description
I want to replace the rotation dot to an icon and put it to the top right corner, like this:
![image](https://user-images.githubusercontent.com/15754991/84373921-d5d1ba00-ac0f-11ea-9f0c-9278d9a7724e.png)
Is there a way to do that? Can I make any element as a rotation dot?

**Comment by daybrush** [comment]
@YGYOOO 

Sorry there is no top-right rotation yet. 
Only top, right, bottom, left.

I will add this feature.

**Comment by YGYOOO** [comment]
> @YGYOOO
> 
> Sorry there is no top-right rotation yet.
> Only top, right, bottom, left.
> 
> I will add this feature.

That would be great, thanks.

**Comment by daybrush** [comment]
@YGYOOO 

moveable's new version is released.
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1


https://daybrush.com/moveable/storybook/?path=/story/basic--rotatable

**Comment by schester44** [comment]
@daybrush  Any chance we could replace the rotation dot with a React component? Mainly because i'd like to add an icon to the dot
