### ISSUE TITLE
Strange behaviour on demo page

### ISSUE THREAD

**Issue by renato-bohler** [daybrush/moveable#26]
I was playing with the demos, when I decided to rotate and then scale the logo, and suddenly it seems that the logo was scaled to 0 for no reason, when I tried to interact with it again it just disappears. Here's a GIF to show what happens:

![moveable](https://user-images.githubusercontent.com/25781956/63480667-1d147180-c469-11e9-80c1-25088f564d05.gif)

I'm on Windows 7, Chrome 76.0.3809.100 (64 bits).

**Comment by daybrush** [comment]
@renato-bohler
Sorry...   I checked the problem. I'll fix it quickly and reflect it.

**Comment by daybrush** [comment]
@renato-bohler 
I'm sorry. I just fixed it. Check it again. The problem was the use of incorrect parameters in the demo.

**Comment by a-c-sreedhar-reddy** [comment]
Hey @daybrush 
We have a similar kind of isssue which happens only on windows/chrome.
What was the issue here?

**Comment by a-c-sreedhar-reddy** [comment]
If case someone is facing this issue,

We had `transition-duration: 0.01ms !important;` for `prefers-reduced-motion: reduce` which was giving issues.

**Comment by daybrush** [comment]
@a-c-sreedhar-reddy 

Sorry. Moveable does not support transition. When dragging the control, the transition-duration should be 0.

But I can fix it someday.
