### ISSUE TITLE
How to handle the drag event & contentEditable

### ISSUE THREAD

**Issue by Jomimoses** [daybrush/moveable#261]
## Environments
* Framework name: react-moveable
* Framework version: 0.20.10
* Moveable Component version:
* Testable Address(optional):

## Description

I want the similar feature like this
https://www.canva.com/design/DAD9gh5mf5M/3ru5x7U0l0b-KpaIVmaRyA/edit

i need to do the editable as well the drag also

**Comment by daybrush** [comment]
@Jomimoses 

Drag is not working in contenteditable state. When dragStart, we need to make sure that the element we are dragging is contenteditable.
