### ISSUE TITLE
Draggable update from state

### ISSUE THREAD

**Issue by fitzmode** [daybrush/moveable#262]
## Environments
* Framework name: react-moveable
* Framework version:  16.8.4
* Moveable Component version: 0.18.1
* Testable Address(optional): https://codesandbox.io/s/moveable-ondragend-jank-9sytu

## Description

I'm trying to persist moveable position to a global store `onDragEnd`. 
The target element has an initial `translate(x,y)` , and this should be updated `onDragEnd` to allow target position state to be reused. Please see attached issue repro on link provided

**Comment by daybrush** [comment]
@fitzmode 

Thank you :) I'll add this feature to next release.

**Comment by fitzmode** [comment]
Thanks, ideally if we can get higher level `props` to set positions `x` and `y` and rotation;
```
<Moveable position={{x: 50, y: 50}} rotation={45} />
```

**Comment by daybrush** [comment]
@fitzmode 

* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1


lastEvent is added.

https://daybrush.com/moveable/storybook/?path=/story/use-state-at-the-last-event--draggable
