### ISSUE TITLE
Moveable box goes beyond bounds when entering/adding text in content editable div

### ISSUE THREAD

**Issue by iprasadg** [daybrush/moveable#264]
## Environments
* Framework name: Angular
* Framework version: 8
* Moveable Component version: 0.9.4
* Testable Address(optional):

## Description
If I am editing a text in content editable div and suppose the div is at bottom. The container also have bounds. So when the div is at bottom touched to the bounds and if I am entering text the box goes outside of bounds (or say container). I want the box to go towards up side not outside. I know it can be solved with overflow hidden to the container but I can't use that. Is there any other way?

**Comment by daybrush** [comment]
@iprasadg 

I will tell you how to do it in the next release. Thank you :)

**Comment by iprasadg** [comment]
@daybrush No problem !! Thanks for your reply

**Comment by daybrush** [comment]
@iprasadg 

* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1


Try code:
```js
    window.addEventListener("keyup", e => {
        moveable.updateRect();
        moveable.request("draggable", { deltaX: 0, deltaY: 0 }, true);
    })
```
