### ISSUE TITLE
Dragging by particular axis

### ISSUE THREAD

**Issue by elisabedashvili-exceed** [daybrush/moveable#265]
## Environments
* Framework name: React
* Framework version: Latest
* Moveable Component version: Latest
* Testable Address(optional):

## Description
Is there any chance to drag items only in one direction (axis)? Which props should I add/edit?

**Comment by daybrush** [comment]
It is not ready, but if possible, only the x-axis or the x- and y-axes can be moved.
* Only X Axis
```tsx
<Moveable
   throttleDragRotate={180}
/>
```
* Only X, Y Axis
```tsx
<Moveable
   throttleDragRotate={90}
/>
```

**Comment by elisabedashvili-exceed** [comment]
Thanks a lot
