### ISSUE TITLE
Updating element guidelines

### ISSUE THREAD

**Issue by adam-26** [daybrush/moveable#266]
## Environments
* Framework name: `react`
* Framework version: 16.13.1
* Moveable Component version: 0.20.10
* Testable Address(optional):

## Description
Hi, great library!

[Here, the element guidelines are cached](https://github.com/daybrush/moveable/blob/37113c1f425d34ec639ff28cf909260a70852392/packages/react-moveable/src/react-moveable/ables/Snappable.tsx#L53), it doesn't appear possible to update them after they are cached, is that correct?

I need to be able to update the element guidelines. There's probably a few ways to solve this problem, one would simply be to introduce a flag that prevents the guidelines from being cached. 

Another option may be to introduce  a new `elementGuidelinesRects` prop that expects an array of type:
```js
type GuidelineRect = {
  left: number,
  top: number,
  right: number,
  bottom: number,
}
```

[This would remain compatible with the existing API](https://github.com/daybrush/moveable/blob/37113c1f425d34ec639ff28cf909260a70852392/packages/react-moveable/src/react-moveable/ables/Snappable.tsx#L91) (as the `elementGuidelines` prop can just `.map` the `.getClientBoundingBox()` values to this new property), while allowing the developer greater control over the guidelines. Using the above approach it's easy for the developer to cache the guideline positions and only update them as required. 

What do you think?

Thanks, Adam.

**Comment by daybrush** [comment]
@adam-26 


https://github.com/daybrush/moveable/blob/37113c1f425d34ec639ff28cf909260a70852392/packages/react-moveable/src/react-moveable/ables/Snappable.tsx#L1613

The cache is created on dragStart and the cache disappears on dragEnd.

Would you like to update elementRect during the drag?

**Comment by adam-26** [comment]
Sorry, my mistake.

I had copied&pasted from the demo, and had:
```js
elementGuidelines={[document.querySelector(".cube.target")]}
```

so it was only displaying guidelines for the first element found, I needed to change it to 👍 
```js
elementGuidelines={document.querySelectorAll(".cube.target")}
```

Now it works as expected. Sorry for wasting your time.
