### ISSUE TITLE
can we hide the control box when resizing or dragging

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#268]
## Environments
* Framework name: vue
* Framework version: vue 2.x
* Moveable Component version: 0.17.10

## Description
like this
![QQ20200628-180043](https://user-images.githubusercontent.com/1256745/85944470-8f978d00-b969-11ea-812f-b291da7b50d5.gif)

**Comment by daybrush** [comment]
@leeboo 

not yet.

I will add a dragging class while dragging. Then you can add the CSS corresponding to the dragging class.


I will try to add it to the release this Sunday.

**Comment by daybrush** [comment]
@leeboo 
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1


if dragging, `moveable-dragging` class is added.

you add css to .moveable-dragging.
