### ISSUE TITLE
Get width, height, left, top on onScale event

### ISSUE THREAD

**Issue by abinhho** [daybrush/moveable#269]
## Environments
* Framework name: `Vuejs`
* Framework version: `2.6.11`
* Moveable Component version: `1.8.7`
* Testable Address(optional):

## Description

I'd like to get width, height, left, top of element on onScale event, I see current example are using `transform` attribute. 
From example:
```
moveable.on("scale", ({ target, transform, dist }) => {
  target.style.transform = transform;
});
```
Expected:
```
moveable.on("scale", ({ target, widht, height, left, top }) => {
  // Do something
});
```

Any help!

**Comment by daybrush** [comment]
@abinhho 

Width and height cannot be obtained from scale.


```js
moveable.on("scale", ({ target, drag }) => {
  //  get drag.left, drag.top
  // get moveable.getRect().offsetWidth
  //  get moveable.getRect().offsetHeight

});

**Comment by daybrush** [comment]
moveable's new version is released.
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1

https://daybrush.com/moveable/release/latest/doc/Moveable.Scalable.html#.OnScale
you can use offsetWidth, offsetHeight

**Comment by abinhho** [comment]
@daybrush Nice! Thank you!
