### ISSUE TITLE
Resize not working properly after updating ngx-moveable from 0.9.4 to 0.13.11

### ISSUE THREAD

**Issue by iprasadg** [daybrush/moveable#272]
## Environments
* Framework name: Angular
* Framework version: 8
* Moveable Component version: 0.13.11
* Testable Address(optional):

## Description
After updating ngx-moveable from 0.9.4 to 0.13.11 resize is not working properly. The calculation of left value is getting wrong, it is suddenly becoming 240px from 0px. This is the code I used for resize.

`onResize({ target, width, drag }: OnResize) {
    this.frame.set('left', `${drag.left}px`);
    this.frame.set('width', `${width}px`);
    this.setTransform(target);
  }`

**Comment by daybrush** [comment]
@iprasadg 

* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1

moveable's new version is released.
Check it again.
