### ISSUE TITLE
Change Angular peer dependencies to allow versions greater than 8

### ISSUE THREAD

**Issue by kristijanbambir** [daybrush/moveable#274]
## Environments
* Framework name: Angular
* Framework version: 10

## Description
The Angular 9 to 10 update throws this error:
```bash
Package "ngx-moveable" has an incompatible peer dependency to "@angular/core" (requires "^8.0.3" (extended), would install "10.0.2").
Package "ngx-moveable" has an incompatible peer dependency to "@angular/common" (requires "^8.0.3" (extended), would install "10.0.2").
✖ Migration failed: Incompatible peer dependencies found.
```
A flag can be used to ignore these incompatibilities during the update, but unmet peer dependencies cause issues later on as well.

Looking at the source, it should work fine with never Angular versions, so I propose to change the peer dependencies from:
```json
"peerDependencies": {
  "@angular/common": "^8.0.3",
  "@angular/core": "^8.0.3"
}
```
to:
```json
"peerDependencies": {
  "@angular/common": ">=8",
  "@angular/core": ">=8"
}
```
Would that be acceptable?

**Comment by daybrush** [comment]
@kristijanbambir 
Thank you

I'll fix for next release.

**Comment by daybrush** [comment]
@kristijanbambir 

moveable's new version is released.
* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1

Check it again.
