### ISSUE TITLE
add a react component from outside

### ISSUE THREAD

**Issue by chj20051863** [daybrush/moveable#275]
How to add react components from outside？
Can you provide a demo, thanks

**Comment by daybrush** [comment]
@chj20051863 

What does it mean?

**Comment by cbazza** [comment]
Basically your 'target' takes a DOM element. It would be nice to also take any react component. 
So the react component would render and then findDOMNode() would return that to your target. 
You could have it as a child component or render prop.

**Comment by daybrush** [comment]
@cbazza

**Comment by daybrush** [comment]
@cbazza @chj20051863 

So you have to update the target after using the first mount or ref.

**Comment by cbazza** [comment]
I know but that's not as clean as just using a react component like:
<Moveable>
     <MyReactComponent/>
</Moveble>

**Comment by daybrush** [comment]
@cbazza 

Well that method is good, but it seems to be difficult to provide.
findDOMNode is now very difficult to use because it is deprecated.
You should use ref, forwardRef in the future.

I will add refObject type and selector string type to target later.

**Comment by cbazza** [comment]
Great, thank you.

**Comment by daybrush** [comment]
@cbazza  

* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's new version is released. 

Support string(selector), RefObject type.
Try it. Thank you :)
