### ISSUE TITLE
Two Moveable in one component

### ISSUE THREAD

**Issue by atomoc** [daybrush/moveable#277]
https://codesandbox.io/s/react-moveable-demo-1lje3

It is impossible to separate their behavior.

**Comment by atomoc** [comment]
https://codesandbox.io/s/react-moveable-demo-nkm67

Dividing Moveable by component is still a problem.

https://ttprivatenew.s3.amazonaws.com/pulse/sergej-saveljev/attachments/14045130/TinyTake09-07-2020-06-16-24.mp4

**Comment by daybrush** [comment]
@atomoc 

That's probably because the target is relative.
The target width and height will be affected by other targets.

**Comment by atomoc** [comment]
@daybrush

Please give an example of how to solve this problem

**Comment by daybrush** [comment]
Change your targets to absolute

**Comment by atomoc** [comment]
I just didn’t understand what you mean, sorry

**Comment by atomoc** [comment]
I think I'm starting to understand, I'll try how I'll be at home

**Comment by atomoc** [comment]
Thank! You are well done!
