### ISSUE TITLE
Simplified version?  React moveable with full drag select

### ISSUE THREAD

**Issue by clarkmu** [daybrush/moveable#280]
I've been looking at this for a few days:
https://codesandbox.io/s/9cg81

The code is busy and hard to understand (to me) between the TypeScript, on-page styling, classes , etc.  Does anyone have a simplified version of using react-moveable with the mouse drag selector?

**Comment by daybrush** [comment]
@clarkmu 

The simplified version means you just want to use draggable? Is it a size problem?

**Comment by clarkmu** [comment]
Thanks for the reply!

It's not a package size problem, just very hard to understand that demo and fit into my own use case so I thought I would ask if anyone has a simplified version of it.

I need resizable, draggable, and select-multiple-to-drag components so basically that demo.  My use case is having multiple pages of items (PDF sized).  Each page, you can add boxes to to resize, change styling, and move.  Select multiple to drag (and copy/paste).

**Comment by daybrush** [comment]
@clarkmu 
In moveable, the drag tool is used for this.
https://github.com/daybrush/drag
