### ISSUE TITLE
[QUESTION] Force updating moveable control box.

### ISSUE THREAD

**Issue by vin-ce** [daybrush/moveable#281]
## Environments
* Framework name: React
* Framework version: 16.13.1
* Moveable Component version: 0.19.2

## Description

I have an app with undo/ redo. Upon undo/ redo, the component's stylings (height, width etc) and frame (transform, rotate) are all updated. The Moveable component is saved in a ref variable (accessed via `moveable.current`) that is set to null, and after the primary component has been updated (and is re-rendered), the Moveable component is assigned a value again with the updated target. 

![updating-control-box](https://user-images.githubusercontent.com/57646932/87248978-66c3cd00-c42a-11ea-9b22-2f3faf59a998.gif)

However, as you can see, the frame is not updated. I noticed `updateRect()` and `updateTarget()` as methods. If I wanted refresh the moveable control box, do I use those? If so, how do I access them when I'm using Moveable as a component?

Thank you for this _incredible_ project!

**Comment by daybrush** [comment]
@vin-ce 

Yes. Calling updateRect will change the moveable box styles.

Access it with `<Moveable ref={??} />`

**Comment by vin-ce** [comment]
Perfect thank you so much!

**Comment by Darkside73** [comment]
In some reason it works only if call like that:
```
    setTimeout(() => {
      moveable.updateRect()
    })
```

**Comment by FlandiaYingman** [comment]
Hi, I am new to React. I addd some dependencies to `useEffect(() => {setTarget(...)}`. When the dependencies are changed, React re-renders the `<Moveable>` automatically. I guess this is better than updating moveable box manually by calling `updateRect()`.
