### ISSUE TITLE
Requester for group scalable

### ISSUE THREAD

**Issue by tannguyen248** [daybrush/moveable#283]
## Environments
* Framework name:
* Framework version: "moveable": "^0.17.8",
* Moveable Component version: Requester
* Testable Address(optional):

## Description
Hi @daybrush ,  I need to scale the group elements by a requester at the available ratio but it has not worked as when I scale manually and the layout is up-side-down

I guess that something wrong with the translate in the scaleGroup event

Here is my code:

-  The requester:

`   const scaleRequester = moveable.request("scalable");
    scaleRequester.request({ direction: [1, 1], deltaWidth: -rect.width * minRatio, deltaHeight: -rect.height * minRatio })
    scaleRequester.requestEnd()
    console.log(scaleRequester)
`

- The event handler:
` const { events } = props
  events.forEach((ev, i) => {
    frames[i].translate = ev.drag.beforeTranslate
    frames[i].scale = ev.scale
    ev.target.style.transform = ```translate(${frames[i].translate[0]}px, ${frames[i].translate[1]}px) rotate(${frames[i].rotate}deg) scale(${frames[i].scale[0]}, ${frames[i].scale[1]})```
  })
`

![image](https://user-images.githubusercontent.com/33176330/87298883-33219980-c535-11ea-9f50-463c47f3cdf2.png)

**Comment by daybrush** [comment]
@tannguyen248 

* `moveable` 0.18.3
* `react-moveable` 0.21.4
* `preact-moveable` 0.20.5
* `ngx-moveable` 0.14.1
* `svelte-moveable` 0.9.1

Try 0.18.3 version.
