### ISSUE TITLE
ngx-moveable depends on React?

### ISSUE THREAD

**Issue by eduardocalixtoviasoft** [daybrush/moveable#284]
## Environments
* Framework name: Angular
* Framework version: 9.1.9
* Moveable Component version: >= 14

## Description
**ngx-moveable** depends of **moveable** which, since v14, depends of **react-compat-moveable**, which requires react to work.

The following error happens when trying to use it
![image](https://user-images.githubusercontent.com/42845879/87362119-2193be00-c544-11ea-9d4c-d5ae8cd478d7.png)

**Comment by daybrush** [comment]
@eduardocalixtoviasoft 

Thank you. I'll fix it.

**Comment by daybrush** [comment]
@eduardocalixtoviasoft 
ngx-moveable 0.14.1 is released. Check it again.

**Comment by daybrush** [comment]
@eduardocalixtoviasoft 

* `moveable` 0.18.4
* `react-moveable` 0.21.5
* `preact-moveable` 0.20.6
* `ngx-moveable` 0.14.2
* `svelte-moveable` 0.9.2

**Comment by eduardocalixtoviasoft** [comment]
Working just fine, thank you guys
