### ISSUE TITLE
Moveable Positioning issue of selecting element on safari....!

### ISSUE THREAD

**Issue by Nazakatalikharal** [daybrush/moveable#285]
## Environments
* Framework name: ReactJS
* Framework version: "react": "^16.12.0"
* Moveable Component version: "react-moveable": "^0.19.2"
* Testable Address(optional): 

## Description
After Clicking on text element like giving below, outter moveable selection area in safari positioning not working properly, in chrome , FireFox, and Opera it work well. but only issue on Safari.
<div><p><span
                
![element-structure](https://user-images.githubusercontent.com/54443270/87418336-f3b58480-c5ea-11ea-95c5-f869e80afdea.png)
data-target="text_dtarget19"
                style={{
                  width: "123px",
                  transform: "translateX(50px) translateY(50px) rotate(0deg)",
                  position: "absolute",
                  fontSize: "30px",
                  color: "rgb(5, 25, 43)"
                }}
              > 
              P R O F I L E
</span></p></div>
![Chrome-Snip](https://user-images.githubusercontent.com/54443270/87417813-2448ee80-c5ea-11ea-8796-e7ddb1c81374.png)
![Safarai-snip](https://user-images.githubusercontent.com/54443270/87417821-2612b200-c5ea-11ea-862f-41ea2dad437f.png)

**Comment by daybrush** [comment]
@Nazakatalikharal 

Try react-moveable 0.21.4 version

**Comment by Nazakatalikharal** [comment]
I tried update react-moveable 0.21.4 version but issue remains same.

**Comment by daybrush** [comment]
@Nazakatalikharal 

 can you give me some code to test? codesandbox?

**Comment by daybrush** [comment]
@Nazakatalikharal 

test `react-moveable@0.21.6-rc` version.

**Comment by Nazakatalikharal** [comment]
@daybrush  Thanks dear this version react-moveable@0.21.6-rc resolved the issue on safari Thanks again 👍

**Comment by daybrush** [comment]
@Nazakatalikharal 


moveable's new version is released.
* `moveable` 0.18.5
* `react-moveable` 0.21.6
* `preact-moveable` 0.20.7
* `ngx-moveable` 0.14.3
* `svelte-moveable` 0.9.3
