### ISSUE TITLE
SVG Element Origin 

### ISSUE THREAD

**Issue by kujeah** [daybrush/moveable#286]
## Environments
* Framework name: vue
* Framework version: 2.X
* Moveable Component version: 0.18.2
* Testable Address(optional):

## Description

We are developing a part that moves an element within svg. When rotated, it operates on the basis of origin, but in the case of svg element, the position of origin is strange.

In the case of path element, origin is shown as below.

<img width="803" alt="Screen Shot 2020-07-15 at 8 24 20" src="https://user-images.githubusercontent.com/12984182/87486121-7b47d580-c675-11ea-8fb0-5cae5e4c5935.png">

For text element, ogin is shown as below.

<img width="767" alt="Screen Shot 2020-07-15 at 8 26 09" src="https://user-images.githubusercontent.com/12984182/87486139-88fd5b00-c675-11ea-84ef-c1ba4919d851.png">

Is this right position?

In my opinion, origin should be located in the center of the element. 

What other settings should there be?

**Comment by daybrush** [comment]
@kujeah 
moveable's new version is released. Check it again.
* `moveable` 0.18.5
* `react-moveable` 0.21.6
* `preact-moveable` 0.20.7
* `ngx-moveable` 0.14.3
* `svelte-moveable` 0.9.3

**Comment by kujeah** [comment]
thank you for your update

but I tested it again after the update, but it was not modified. Origin is displayed in the same position as before.

What else should I do?

**Comment by daybrush** [comment]
@kujeah 

The default value of transform-origin of svg element is 0 0 of SVG parent.

The% value does not work.

**Comment by ehsan096** [comment]
"react": "^17.0.2",
"react-moveable": "^0.29.0",

I am facing the same issue with react.
the origin of the svg element is not at center. How can I get it into center?

**Comment by ehsan096** [comment]
@daybrush ??
