### ISSUE TITLE
While resizing element, element is not resizing from top-left, top and right side

### ISSUE THREAD

**Issue by PramodIndusved** [daybrush/moveable#287]
## Environments
* Framework name: react, umi
* Moveable Component version: 0.19.3

## Description
I used react-resizable for element. But while resizing from top element get extended from bottom, when i resize from left it get extended from right.
Something is not good with it. Any solution ?

**Comment by PramodIndusved** [comment]
@daybrush its working using
```
const beforeTranslate = drag.beforeTranslate;
target.style.transform = `translate(${beforeTranslate[0]}px, ${beforeTranslate[1]}px)`;

```
but while resizing from top, top-left, left and bottom-left corner, it get flickers in between the previous position of the element and the new one.

**Comment by PramodIndusved** [comment]
> ## Environments
> * Framework name: react, umi
> * Moveable Component version: 0.19.3
> 
> ## Description
> I used react-resizable for element. But while resizing from top element get extended from bottom, when i resize from left it get extended from right.
> Something is not good with it. Any solution ?

**Comment by daybrush** [comment]
@PramodIndusved 
Update once. If the update is the same, I think it's related to origin.

**Comment by ErickLuis00** [comment]
Try:

`target.style.transform = drag.transform`

It solved both problems for me.
