### ISSUE TITLE
SVG Text Element Box, scale

### ISSUE THREAD

**Issue by kujeah** [daybrush/moveable#288]
## Environments
* Framework name: vue
* Framework version: 2.X
* Moveable Component version: 0.18.4
* Testable Address(optional):

## Description

We are developing a section to scale the element within svg.

when use svg text element, you can use text-anchor as start, middle, and end, but if text-anchor is "start", height is not calculated.

If text-anchor = middle, work fine

<img width="761" alt="Screen Shot 2020-07-16 at 9 14 52" src="https://user-images.githubusercontent.com/12984182/87612694-3344b380-c746-11ea-84f7-7e1ff84de415.png">

<img width="1215" alt="Screen Shot 2020-07-16 at 9 14 58" src="https://user-images.githubusercontent.com/12984182/87612736-566f6300-c746-11ea-9c7d-1056fee782d6.png">

If text-anchor = start, height is 0

<img width="763" alt="Screen Shot 2020-07-16 at 9 14 18" src="https://user-images.githubusercontent.com/12984182/87612745-5c654400-c746-11ea-973a-306f9a7eb033.png">

<img width="1202" alt="Screen Shot 2020-07-16 at 9 14 26" src="https://user-images.githubusercontent.com/12984182/87612750-6129f800-c746-11ea-86e4-753dd0f32893.png">

The height is 0, so the position is not calculated when the scaled

<img width="1169" alt="Screen Shot 2020-07-16 at 9 21 48" src="https://user-images.githubusercontent.com/12984182/87612762-65eeac00-c746-11ea-9a69-fc9581bd00ba.png">

**Comment by parth181195** [comment]
i am also facing this issue 
![image](https://user-images.githubusercontent.com/17850142/87620011-1f478480-c73b-11ea-8c05-7ed912921d9f.png)

**Comment by daybrush** [comment]
@kujeah @parth181195 


moveable's new version is released. Check it again.
* `moveable` 0.18.5
* `react-moveable` 0.21.6
* `preact-moveable` 0.20.7
* `ngx-moveable` 0.14.3
* `svelte-moveable` 0.9.3

**Comment by kujeah** [comment]
Thank you :) it's fixed

**Comment by parth181195** [comment]
thanks @daybrush u saved my ass for real i will donate to this project once my project is finished thank u for the quick response.u are DA best
