### ISSUE TITLE
Cannot find name 'OnDrag'.  TS2304

### ISSUE THREAD

**Issue by RajaTheKing826** [daybrush/moveable#290]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@RajaTheKing826 

Hi ??

Please write a description.

**Comment by RajaTheKing826** [comment]
i'm working on react i have created a ref as exampleRef= React.createRef <HTMLElement>() for this im getting typescript error that missmatch of exampleRefTypes and target im searched about this all over the internet but i didn't get the answer so help me to 
get out of this typescript problem
i not able to write types for my React Ref which can suitable to your target

**Comment by daybrush** [comment]
@RajaTheKing826 

Can you show me a screenshot with that error?
What is the TypeScript version?

**Comment by RajaTheKing826** [comment]
yah this is the screenshot of that error
![Screenshot from 2020-07-22 12-57-51](https://user-images.githubusercontent.com/59301270/88147603-1531f400-cc1b-11ea-81f8-c36d2aa0c454.png)

**Comment by daybrush** [comment]
@RajaTheKing826 
ref type is not supported.

use current.
```
target={this.headerRef.current}
```

**Comment by RajaTheKing826** [comment]
@daybrush 
yah i have tried that also this time i didn't get an error but i didn't get movable in in my out put page
![Screenshot from 2020-07-22 14-18-36](https://user-images.githubusercontent.com/59301270/88155942-65fb1a00-cc26-11ea-965a-6adaa4f5bd8f.png)

**Comment by RajaTheKing826** [comment]
if i write target={document.body} im getting movable for entire doc but when im giving a specific ref like above screenshot im not getting movable there

**Comment by RajaTheKing826** [comment]
these are the screen shots of my code and its outputs
![Screenshot from 2020-07-22 14-43-03](https://user-images.githubusercontent.com/59301270/88158532-ca6ba880-cc29-11ea-8b38-631c2749ab1f.png)
![Screenshot from 2020-07-22 14-43-28](https://user-images.githubusercontent.com/59301270/88158542-ccce0280-cc29-11ea-963f-7cc8f2496f2b.png)

**Comment by daybrush** [comment]
@RajaTheKing826 


Before mounted, current was null. So please update it once.

**Comment by daybrush** [comment]
@RajaTheKing826 

* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's new version is released. 

Support string(selector), RefObject type.
Try it. Thank you :)
