### ISSUE TITLE
unable to select multiple targets

### ISSUE THREAD

**Issue by usmanibrahim74** [daybrush/moveable#291]
## Environments
* Framework name: Vue
* Framework version: 2.6.11
* Moveable Component version:0.17.10

## Description
I'm trying to set multiple targets but I got this error in return
![image](https://user-images.githubusercontent.com/20674784/87790875-b5260100-c85a-11ea-84f5-5ecf6b4ea4cd.png)

the code I used for this purpose is this
```
const targets = [].slice.call(document.querySelectorAll(".target"));
                this.moveable = new Moveable(this.container, {
                    target: targets,
                    dragTarget: null,
                    container: this.container,
                    dragArea: true,
                    draggable: true,
                    resizable: true,
                    scalable: true,
                    rotatable: true,
                    warpable: true,
                    groupable: false,
                    pinchable: true, // ["resizable", "scalable", "rotatable"]
                    origin: false,
                    keepRatio: false,
                    edge: false,
                    throttleDrag: 0,
                    throttleResize: 0,
                    throttleScale: 0,
                    throttleRotate: 0,
                });
```

**Comment by daybrush** [comment]
@usmanibrahim74 

do not use groupable props (should be true)

**Comment by usmanibrahim74** [comment]
it worked, thanks. but when selecting one target with `groupable= true;` it is not selecting.
so in that situation i have to keep it false. right?

**Comment by daybrush** [comment]
@usmanibrahim74 

Don't put the groupable props.

it's not public props.

**Comment by usmanibrahim74** [comment]
ohh ok. now I got it. thanks
