### ISSUE TITLE
Clippable bounds to target

### ISSUE THREAD

**Issue by fitzmode** [daybrush/moveable#292]
## Environments
* Framework name: React 
* Framework version: 16.8.4
* Moveable Component version: 0.21.4
* Testable Address(optional):

## Description

Thanks for the update! How can I keep a `Clippable` within bounds of the target?. I would like it to have it such that when I drag the `Clippable` component, it does not leave the the boundaries of the target.

**Comment by daybrush** [comment]
@fitzmode 

There are no bounds and snap settings related to clippables yet.

**Comment by happylinks** [comment]
Would really like to have this! I'm building cropping with clippable. Do you think you'll add bounds + snap eventually?

**Comment by daybrush** [comment]
@happylinks @fitzmode 

* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's new version is released. 

`clipTargetBounds` prop is added for bound .
`clipVerticalGuidelines`, `clipHorizontalGuidelines`, `clipSnapThreshold` are added for snap.
Try it.
Thank you :)
