### ISSUE TITLE
el.ownerSVGElement is getting null as svg parent getSVGViewBox(el.ownerSVGElement) 

### ISSUE THREAD

**Issue by parth181195** [daybrush/moveable#293]
## Environments
* Framework name: angular 
* Framework version: 0.14.3
* Moveable Component version: 0.18.5
* Testable Address(optional):

## Description

i am trying to change things by using make request by passing values via form controls but for some reason i am getting null when it tries to get ownersvg   at 
  var viewBox = getSVGViewBox(el.ownerSVGElement); in getSVGGraphicsOffset function. any ideas how i can fix it

**Comment by parth181195** [comment]
plus i am use nested svgs it works fine when its done by event like dragging or rotate it only fails with makerequest

**Comment by daybrush** [comment]
@parth181195 

 What was the `target`?
can you show me used moveable code?

**Comment by parth181195** [comment]
apparently i had a data binding to width property so that was causing it to behave in in a bit weird manner  and that was the cause of this null issues sorry for late replay. we should close this issue. if u want to look around i can upload code and share with u.
