### ISSUE TITLE
Group rotate not working

### ISSUE THREAD

**Issue by usmanibrahim74** [daybrush/moveable#294]
## Environments
* Framework name: Vue

## Description
this example code is not working. can you have a look?
https://codesandbox.io/s/263vs

**Comment by daybrush** [comment]
@usmanibrahim74 

Oh Thank you :) This demo was fixed.

**Comment by daybrush** [comment]
@usmanibrahim74 

https://daybrush.com/moveable/storybook/?path=/story/group--rotatable-origindraggable
