### ISSUE TITLE
Active and Inactive States

### ISSUE THREAD

**Issue by rodneygen22** [daybrush/moveable#296]
## Environments
* Framework name: Nuxt
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

Hello, we have multiple moveable components. Our problem is how to set the moveable to "active" state on mouse click or drag and set it to "inactive" when we click outside of the component. We want to achieve the same behavior in your demo in https://daybrush.com/moveable/. 

Thanks. Awesome JS library!

**Comment by daybrush** [comment]
@rodneygen22 
I used selecto.

https://github.com/daybrush/selecto


it's moveable homepage demo source.(Scena project).

https://github.com/daybrush/scena/blob/a59844a6e7b71699b5a9e491d36ad70248a3f3fe/packages/react-editor/src/Editor/Editor.tsx#L203-L264

**Comment by rodneygen22** [comment]
Thanks @daybrush. I'll check it out. Great work!
