### ISSUE TITLE
Interaction becomes impossible when height is 0 AND no other interactions have been taken

### ISSUE THREAD

**Issue by HopefulLlama** [daybrush/moveable#3]
On the demo page:

* Resize the component such that it has 0 height
* Release the mouse click
* Try to interact with the component
* Nothing happens

Additionally, this only happens IF that's all you do. Interacting with it in any other way, such as moving, resizing or rotating, prevents this bug from occurring.

**Comment by daybrush** [comment]
@HopefulLlama 

I have a question to ask you to confirm exactly. Did you interact a diagonally oriented control box when you were resizing? (like nw, ne, sw, se direction)

Maybe that's because the size is 0 and the ratio is gone. I'm currently fixing the problem.

**Comment by HopefulLlama** [comment]
The interaction was done with the north control, and I resized straight down to 0 height, and not exceeding the height to invert it.

**Comment by daybrush** [comment]
@HopefulLlama 

Thank you. I know what the problem is. I will reply a comment if I am fixed.

**Comment by daybrush** [comment]
@HopefulLlama 
Hi. moveable@0.3.0 has been published. It's fixed.

**Comment by HopefulLlama** [comment]
It works, and looks great! I'll close this issue now.

Great work and keep it up.

**Comment by ThomasLipman** [comment]
For me it's still not working, even in newer versions. The x and y scale get set to NaN for some reason when the width of height is 0. If you move fast, nothing happens, but when you move slowly and hit 0 on either of them, one or both jump to NaN and the component resizes itself to the default size. After that you can't scale or rotate the component anymore. Screenshot of the 'tooltip' (or how it's called) says NaN. My cursor was at the red dot.
![2019-11-12](https://user-images.githubusercontent.com/49814847/68673952-cf317600-054c-11ea-9224-b6b9e7aa2c36.png)

**Comment by daybrush** [comment]
@ThomasLipman 

Thank you for reporting bug.

react-moveable 0.13.10 is released. 
The demo was also updated.
try it again.

https://codesandbox.io/s/react-moveable-demo-jl69c
