### ISSUE TITLE
destroy() error 0.7.3

### ISSUE THREAD

**Issue by comiewcom** [daybrush/moveable#30]
Uncaught TypeError: this.getMoveable(...).componentWillUnmount is not a function
    at t.e.destroy (Moveable.tsx:129)
    at pen.js:122

Reproduce it by adding moveable.destroy () to the last line.
https://codepen.io/daybrush/pen/VoQypZ

**Comment by daybrush** [comment]
@comiewcom 

Thank you for reporting bug.

I'll fix it right away and deploy it.

**Comment by daybrush** [comment]
@comiewcom 

Moveable 0.7.5 is released. Please check again.

Thank you

**Comment by comiewcom** [comment]
Thank you for your support.
I checked.
There was no problem.
