### ISSUE TITLE
Feature Request: update ngx-moveable to angular 10

### ISSUE THREAD

**Issue by xiaoxiangmoe** [daybrush/moveable#301]
```
./node_modules/ngx-moveable/__ivy_ngcc__/fesm2015/ngx-moveable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/ngx-moveable/ngx-moveable.module.ts" URL is not supported
```

Updating to ng 10 can remove this warning.

**Comment by daybrush** [comment]
@xiaoxiangmoe 
Okay. I'll publish with angular 10
Thank you :)

**Comment by xiaoxiangmoe** [comment]
@daybrush Can I create an pr to upgrade angular 10？

**Comment by daybrush** [comment]
Anytime is good.  Thank you


2020년 8월 11일 (화) 오후 1:00, ZHAO Jinxiang <notifications@github.com>님이 작성:

**Comment by xiaoxiangmoe** [comment]
@daybrush can you publish an new version of `@daybrush/utils`, including  https://github.com/daybrush/utils/commit/e28977c68338d0ab435caff416d698e7904e2fcd ?

**Comment by xiaoxiangmoe** [comment]
@daybrush Can you review my PR?

**Comment by xiaoxiangmoe** [comment]
Can you review it? Thank you.

**Comment by daybrush** [comment]
@xiaoxiangmoe 

ngx-moveable 0.14.4 is released. Thank you :)
