### ISSUE TITLE
Issue with the translateZ(50px) moveable-control-box on safari

### ISSUE THREAD

**Issue by tannguyen248** [daybrush/moveable#302]
## Environments
* Framework name: **moveable**
* Framework version: 0.17.10
* Moveable Component version: moveable-control-box

I don't know why we should have the translateZ(50px) but on Safari, it works as the z-index and covers all my material-ui popup (with translateZ(0px). The image below describes the issue, do you have any idea with it?

![image](https://user-images.githubusercontent.com/33176330/89772458-3d32ba00-db2c-11ea-9e22-e3ec3bee9e4f.png)

**Comment by daybrush** [comment]
@tannguyen248 

I wish there was a demo.

The reason I set translateZ to 50px is that the moveable component should always be shown in front. So that picture is normal.

**Comment by tannguyen248** [comment]
@daybrush day
so do we have any way to override the translateZ?

**Comment by tannguyen248** [comment]
I cannot override the control box translateZ because it's added by every single move, so I override the material-ui to work-around with this issue.

**Comment by daybrush** [comment]
* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's new version is released.
`translateZ` prop is added.
 Thank you :)

**Comment by tannguyen248** [comment]
Thank you ;)
