### ISSUE TITLE
After making element group ,not  able to make inside element editable by contentEdtiable="true", suggest a solution for that because non of clicking events work on that

### ISSUE THREAD

**Issue by Nazakatalikharal** [daybrush/moveable#309]
## Environments
* Framework name:  ReactJS
* Framework version: 16.13.1
* Moveable Component version:  react-selecto + react-moveable

## Description
i try to make group inner element after click or any event editable, but non of event work for me , i want to make element editable by contentEdtiable="true", please suggest solution for that...

**Comment by daybrush** [comment]
@Nazakatalikharal 
Could you ever share your address again?

**Comment by Nazakatalikharal** [comment]
sorry... which address  are you talking about ?

**Comment by Nazakatalikharal** [comment]
if you're talking about codesandbox address then here it is https://codesandbox.io/s/sparkling-darkness-or805

**Comment by daybrush** [comment]
@Nazakatalikharal 

Update react-moveable 0.22.0-rc9 and try this code:
`onClick`, `checkInput`
https://codesandbox.io/s/proud-pond-nf4jb?file=/src/App.js

**Comment by Nazakatalikharal** [comment]
still on group span onClick doesn't work 
https://www.screencast.com/t/nDfDMiRhIY6V
https://codesandbox.io/s/amazing-driscoll-52yg2?file=/src/App.js

**Comment by Nazakatalikharal** [comment]
![group1](https://user-images.githubusercontent.com/54443270/91813653-756d7a00-ec4c-11ea-9ea6-f8453164e1f3.png)

**Comment by Nazakatalikharal** [comment]
![2020-09-01_12-19-46](https://user-images.githubusercontent.com/54443270/91814382-7b178f80-ec4d-11ea-807f-8f4d2dcea065.png)

**Comment by daybrush** [comment]
@Nazakatalikharal 
Add `dragArea={!this.state.groupEditing}`

**Comment by Nazakatalikharal** [comment]
@daybrush 
group is editable now but after editing when we click on others element and click again on same edited element , this error shows
https://www.screencast.com/t/sWVyvj5X6
https://codesandbox.io/s/amazing-driscoll-52yg2?file=/src/App.js

![error1](https://user-images.githubusercontent.com/54443270/91968152-a83b6f00-ed2d-11ea-9754-ae875de032f5.png)

**Comment by Nazakatalikharal** [comment]
@daybrush 
after editing inner group span , no group dragging works, also inner group only single span is editable not multiple

https://www.screencast.com/t/lvmYMODSRJ

https://codesandbox.io/s/vibrant-leakey-b8byo?file=/src/App.js

**Comment by Nazakatalikharal** [comment]
how i can stop "onDragGroupStart" with , this.moveableRef.current , kindly also tell how i can stop react-selecto "onDragStart" with this.selectoRef ...

**Comment by daybrush** [comment]
@Nazakatalikharal 

Update 0.22.0-rc10(beta)

If you want to stop the drag event, return false.

Use passDragArea instead of dragArea and add blur event.

https://codesandbox.io/s/lucid-wood-tr1m7?file=/src/App.js

**Comment by Nazakatalikharal** [comment]
passDragArea work well currently if their'll be issues i'll let you know, thanks for you guidance and support

**Comment by daybrush** [comment]
* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's official new version is released. Check it again. Thank you :)
