### ISSUE TITLE
Production Issue

### ISSUE THREAD

**Issue by usama86** [daybrush/moveable#310]
## Environments
* Framework name: React
* Framework version: ^16.13.1
* Moveable Component version:^0.21.6

## Description
I am getting this error on production, any help would be appreciated.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/29779708/91942681-c648a580-ed14-11ea-890f-ae9d689624a5.png)

**Comment by daybrush** [comment]
@usama86 
Can you know what the moveable.cjs.js 92 line is?

**Comment by usama86** [comment]
![desss](https://user-images.githubusercontent.com/29779708/91960839-d320c580-ed23-11ea-9b6a-504bf220cd7c.png)
@daybrush

**Comment by daybrush** [comment]
@usama86 

Thank you :) I'll fix it soon.

**Comment by jamalnsr** [comment]
@daybrush  issue is with egjs/agent library update, new update to version 2.2.0 is not compatible with movable. we have reverted back to older version, but this needs a fix.

**Comment by daybrush** [comment]
@jamalnsr 

Test 0.22.0-rc10(beta) or reinstall react-moveable.

**Comment by jamalnsr** [comment]
@daybrush  we are facing issues with scaling too can we talk on any kind of messenger.

**Comment by daybrush** [comment]
@jamalnsr 

I'll give you a slack address.

https://daybrush.slack.to

**Comment by daybrush** [comment]
@jamalnsr 

* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's new version is released. Thank you :)
