### ISSUE TITLE
Onscale: after saving target with getRect() width height return different shape 

### ISSUE THREAD

**Issue by qaseem-aly** [daybrush/moveable#311]
## Environments
* Framework name: react
* Moveable Component version: 0.21.6

## Description
when i take height and width after scale and apply same on on render elements height width seems different then control-box. 
i am using getRect() width and height.

Onscale before save and render
![image](https://user-images.githubusercontent.com/3625347/92079456-5a7c4080-edd9-11ea-92b5-9dabbf453667.png)
after render.
![image](https://user-images.githubusercontent.com/3625347/92079598-96afa100-edd9-11ea-918d-a27ff7c78415.png)

**Comment by qaseem-aly** [comment]
@daybrush 

we just save following attributes for each object 
width, height, left, top and rotate, though moveable transform each element and i tend to get moveable rect info and apply on object after it changes. 

In case of scale direct width, height isn't available,  i calculate or get box rect both are same. is there a way to get actual height and width for selected target?

**Comment by daybrush** [comment]
@qaseem-aly 

The actual size can be obtained as follows.
```js
const { offsetWidth, offsetHeight } = getRect();
```

**Comment by qaseem-aly** [comment]
@daybrush 

offsetWidth, offsetHeight remain same as we scale scale selected target.

**Comment by daybrush** [comment]
@qaseem-aly 
right. offsetWidth and offsetHeight do not affect scale. That's why you have to save the css style transform(scale, rotate). In moveable, the transform value of css style is not saved.

**Comment by qaseem-aly** [comment]
unfortunately in my case i have to rely height, width. Is there a way to calculate distance from react positions and then calculate width, height, simply i am asking to calculate width height, equivalent to transform scale?

**Comment by daybrush** [comment]
@qaseem-aly 

That is the width and height of getRect() to which all transforms (scale, rotate) are applied. Separately, the width and height that only scale is applied cannot be obtained.

**Comment by qaseem-aly** [comment]
@daybrush 

height width and top left from pos1 getRect() works fine but after object is rotated getRect() seems to return different values. Also i am trying to find what is missing in control-box because its no updating on rotated object.
![sample2](https://user-images.githubusercontent.com/3625347/92237309-92b27a80-eed0-11ea-9d97-a820b9d8a0db.gif)

```
if (transformAttr.translateX || transformAttr.translateY) {
      let tx = this.moveable.getRect().pos1[0];
      let ty = this.moveable.getRect().pos1[1];

      newObject.geometry.left = tx;
      newObject.geometry.top = ty;
    }
    newObject.geometry.width = this.moveable.getRect().width;
    newObject.geometry.height = this.moveable.getRect().height;
```

**Comment by daybrush** [comment]
@qaseem-aly 
![3F157916-9973-4D6B-B42D-0600125DA309](https://user-images.githubusercontent.com/3433062/92241701-a2928480-eef9-11ea-9e73-e99f924b2353.png)

**Comment by qaseem-aly** [comment]
@daybrush 

Thank you for this awesome package.
