### ISSUE TITLE
resizable request doesn't work in versions 0.18.x

### ISSUE THREAD

**Issue by Mark-Fenng** [daybrush/moveable#312]
## Environments
* Framework name: 
* Framework version:
* Moveable Component version: from v0.18.2  to v0.18.5
* Testable Address(optional): https://codepen.io/mark-fenng/pen/MWyrmNx

## Description
`moveable.request("resizable",{})` this API doesn't work from v0.18.2  to v0.18.5. When I execute this function, nothing happens. But it works well before v0.17.10(include v0.17.10).
In my testable address, I wrote a simple demo to resize a div element, the resize result is different between v0.17.10 and v0.18.2.
I'm not sure whether it's a bug or you have changed the usage of this API.

**Comment by daybrush** [comment]
@Mark-Fenng 

* `moveable` 0.19.1
* `react-moveable` 0.22.3
* `preact-moveable` 0.21.3
* `ngx-moveable` 0.15.1
* `svelte-moveable` 0.10.1

moveable's new version is released. Thank you :)

**Comment by Mark-Fenng** [comment]
@daybrush It works well now. You did a really good job and moveable is a pretty useful tool
