### ISSUE TITLE
Touch two points at the same time (not the rotated point)

### ISSUE THREAD

**Issue by DaiHangLin** [daybrush/moveable#313]
## Environments
* Framework name:  chrome touch screen
* Testable Address(optional):  https://daybrush.com/moveable/

## Description

Touch two points at the same time (not the rotated point), after moving, the picture will move outside the screen

**Comment by daybrush** [comment]
@DaiHangLin 

The demo was updated. Pinch Scale is not yet available, but Pinch Rotate is possible.
