### ISSUE TITLE
Difference in ClientX and currentTargit.getRect().pos1[0]

### ISSUE THREAD

**Issue by jamalnsr** [daybrush/moveable#314]
I need to identify which side of the controller  is clicked by user for scaling the target,  as I have to make some adjustments to the target, but no information was available for that.

I tried a workaround to identify if left side was clicked or not what I did is I got pos1 and pos3  and check if mouse pointer is bisecting these points or not but I found that pos1 and clientX is giving different values while target.getboundedRect().x and clientX return the same value. I tried if the difference between both values is constant but found that it change with rotation value.

please help! 

![2020-09-07_15-28-05](https://user-images.githubusercontent.com/20680971/92378229-ea462580-f11e-11ea-80ae-584261745c27.png)

**Comment by daybrush** [comment]
@jamalnsr 

The reason the value is different is because getRect is based on container
This is because getBoundingClientRect is based on the screen.

**Comment by jamalnsr** [comment]
How can we identify which node or side of the controller is clicked for scaling.

**Comment by daybrush** [comment]
@jamalnsr 

Are you talking about onScaleStart

Here are three e.direction.

```jsx
<Moveable onScaleStart={e => {
    console.log(e.direction);
}}
```

**Comment by jamalnsr** [comment]
oh wow can you please explain how this works?

**Comment by daybrush** [comment]
@jamalnsr 

[-1, -1] left, top
[-1, 0] left
[-1, 1] left, bottom

[0, -1] top
[0, 1] bottom
[1, -1] right, top
[1, 0] right
[1, 1] right bottom

https://daybrush.com/moveable/storybook/?path=/story/basic--scalable

**Comment by jamalnsr** [comment]
thanks for the help, this will solve the issue.
