### ISSUE TITLE
Live guidelines for items that are moving at the same time

### ISSUE THREAD

**Issue by mamsoudi** [daybrush/moveable#317]
## Environments
* Framework name: Vue
* Framework version: 2.6.11
* Moveable Component version: 0.18.5 (Vanilla)
* Testable Address(optional): [Gif](https://user-images.githubusercontent.com/8385009/92572324-dcc3a380-f2b6-11ea-9ae5-19afe2b7036c.gif)

## Description
In our app, we have a requirement that items in our canvas are tied to each other, meaning that if you resize one, you're moving another one, up and down depending on the resizing direction. However, we just realized that maybe there's a caching for getting guidelines, and since we're moving both elements, Moveable is using the previous position of the item.

<p align="center">
  <img src="https://user-images.githubusercontent.com/8385009/92572324-dcc3a380-f2b6-11ea-9ae5-19afe2b7036c.gif" />
</p>

In the gif above, we can see that while the text below the image is moving accordingly, the guidelines are still referring to the previous position. Is there any way to improve this?

**Comment by daybrush** [comment]
@mamsoudi 

It seems that the target element guideline should not be changed.
And it seems that the element guideline below should not move.
`position: relative` is not yet considered.

**Comment by mamsoudi** [comment]
@daybrush Thanks for the clarification; I understand, however, we're not using `position: relative` but we apply changes accordingly on other items as well through a custom logic. I was wondering if there's or will be a way to work around this behavior?
