### ISSUE TITLE
Svelte-moveable typings

### ISSUE THREAD

**Issue by samedro** [daybrush/moveable#320]
## Environments
* Framework name: svelte
* Framework version: 3.24.1
* Moveable Component version: svelte-moveable v0.9.3

## Description

Hi, I'm currently trying to upgrade all of my svelte components into typescript svelte components, and I would like to know if (or when) you would be able to provide typings for the default export, that could be identified as a component.

For the moment, I cannot use the default export as it shows this error : 
![image](https://user-images.githubusercontent.com/47422343/93482346-e6c15400-f8ff-11ea-8815-c803d9f7ac90.png)

My import is basic : 
```  import Moveable, { MoveableInterface, OnRender, OnScale } from 'svelte-moveable';```

Maybe there is already a solution that I am not aware of, could you help me on that subject ?

**Comment by daybrush** [comment]
@samedro 

svelte-moveable 0.10.3 is released.

Check it again.

**Comment by samedro** [comment]
Thanks a lot @daybrush
