### ISSUE TITLE
Resizing a group of elements changes position of group unexpectedly

### ISSUE THREAD

**Issue by nelsondude** [daybrush/moveable#322]
## Environments
* Framework name: React / Your Demo
* Framework version: 
* Moveable Component version: Latest
* Testable Address(optional):

## Description
When resizing a group of elements, the position of the group changes unexpectedly. https://share.getcloudapp.com/L1uJLNPd

I would expect that the opposite corner / side of the group becomes fixed when resizing a group depending on whether a side or corner was selected.

**Comment by daybrush** [comment]
@hjurie 

Thank you :) It's fixed.

The ratio of the group should be maintained. It's my mistake.

**Comment by nelsondude** [comment]
@daybrush Thanks for the fix! Where are the changes that you made? I saw the most recent commit but everything is minified

**Comment by daybrush** [comment]
@nelsondude 

editor demo is here. 
http://github.com/daybrush/scena
