### ISSUE TITLE
storybook React All examples are typos. resizable bug

### ISSUE THREAD

**Issue by hjurie** [daybrush/moveable#324]
## Environments
* Framework name: react
* Framework version: react 16.8
* Moveable Component version:  "react-moveable": "^0.22.6",
* Testable Address(optional):
https://daybrush.com/moveable/storybook/?path=/story/basic--resizable
tab react click!

## Description

https://daybrush.com/moveable/storybook/?path=/story/basic--resizable

React.   All examples are typos.

Edit reiszable to resizable this.

plz!

**Comment by daybrush** [comment]
@hjurie 

Thank you :) It's fixed.
