### ISSUE TITLE
Console log "has: null"

### ISSUE THREAD

**Issue by jvnm-dev** [daybrush/moveable#329]
## Environments
* Framework name: TypeScript, no framework
* Framework version: /
* Moveable Component version: 0.19.3 (installed with npm)
* Testable Address(optional): /

## Description
I created a moveable component and when I resize/drag it, there are a lot of console log "has null".
<img width="1193" alt="Screenshot 2020-10-06 at 10 58 52" src="https://user-images.githubusercontent.com/9156538/95180950-ee6b6e80-07c2-11eb-8fb7-a2a8f51e32bf.png">
<img width="313" alt="Screenshot 2020-10-06 at 10 59 15" src="https://user-images.githubusercontent.com/9156538/95180999-fcb98a80-07c2-11eb-8224-43b83e2eb9a8.png">

But I can't find that console log in the source code. I think the build has been done then the line has been removed.

**Comment by daybrush** [comment]
@jvnm-dev 

moveable 0.19.4 is released.

Thank you :)

**Comment by lixue007** [comment]
exist in react-moveable 0.22.5 also

**Comment by daybrush** [comment]
@lixue007 

Update react-moveable 0.22.6. Thank you :)
