### ISSUE TITLE
Feature request: Support an option for dragging using .moveable-line

### ISSUE THREAD

**Issue by stevezhu** [daybrush/moveable#330]
## Environments
* Framework name: react
* Framework version: 16.x
* Moveable Component version: react-moveable@0.22.6
* Testable Address(optional):

## Description
Requesting support for an option to drag the target using the `.moveable-line` divs similar to how dragArea works.

**Comment by daybrush** [comment]
@stevezhu 

Will you resize or scale with a moveable-line? Then try using the `edge` option.

**Comment by stevezhu** [comment]
Ah yeah this option is useful as well, but we wanted to have the draggable functionality when dragging the lines. The use case is when editing text, we want to be able to move the target as well.

**Comment by daybrush** [comment]
@stevezhu 

Ah, I will consider it. Maybe the name I'm going to add is ʻedgeDraggable`?

**Comment by stevezhu** [comment]
Sounds good thanks!

**Comment by daybrush** [comment]
@stevezhu 

* `moveable` 0.20.0
* `react-moveable` 0.23.0
* `preact-moveable` 0.22.0
* `ngx-moveable` 0.16.0
* `svelte-moveable` 0.11.0

moveable's new version is released.

use `edgeDraggable = true`.

**Comment by stevezhu** [comment]
This doesn't seem to be working, am I doing anything wrong here? https://codesandbox.io/s/jolly-mountain-0q3z7?file=/src/App.tsx

**Comment by stevezhu** [comment]
@daybrush This prop doesn't seem to be working, am I doing anything wrong here? https://codesandbox.io/s/jolly-mountain-0q3z7

**Comment by daybrush** [comment]
@stevezhu 

* `moveable` 0.21.0
* `react-moveable` 0.24.0
* `preact-moveable` 0.23.0
* `ngx-moveable` 0.17.0
* `svelte-moveable` 0.12.0

moveable's new version is released.

Check it again.

**Comment by stevezhu** [comment]
Thanks! Seems good now
