### ISSUE TITLE
When the element has scaleX: -1 or scaleY: -1 ,group rotation has a strange behavior.

### ISSUE THREAD

**Issue by xueerli** [daybrush/moveable#332]
## Environments
* Framework name:
* Framework version: "react-moveable": "^0.22.5"
* Moveable Component version:
* Testable Address(optional):

## Description

Hi @daybrush ,  the div3 (blue one) has transform: scaleX(-1), when group rotation, it behaves incorrectly, and div2 is correct.
![image](https://ftp.bmp.ovh/imgs/2020/10/a3d8b6c1b8672592.gif)
my code is
```
onRotateGroupStart={({ events }) => {
        events.forEach((ev) => {
          const {
            target: { id },
            dragStart,
          } = ev
          const frame = getFrameMap(id)
          ev.set(frame.rotate)
          dragStart && dragStart.set([frame.translate[0], frame.translate[1]])
        })
      }}
onRotateGroup={({ events }) => {
        events.forEach((ev) => {
          const { target, rotate, drag } = ev
          const frame = getFrameMap(target.id)
          frame.rotate = simplifyRotate(rotate)
          frame.translate = [drag.beforeTranslate[0], drag.beforeTranslate[1]]
          target.style.transform = setTransform({ data: frame })
        })
      }}
```

**Comment by xueerli** [comment]
@daybrush 
Hi, this problem still exists.
[https://codesandbox.io/s/romantic-sky-we6px?file=/src/App.js](https://codesandbox.io/s/romantic-sky-we6px?file=/src/App.js)   
![demo](https://ftp.bmp.ovh/imgs/2020/10/edec7e2989a88303.gif)

**Comment by daybrush** [comment]
@xueerli 


Use beforeRotate instead of rotate.

**Comment by xueerli** [comment]
@daybrush thank you very much!
