### ISSUE TITLE
svg text element origin point issue between chrome and safari

### ISSUE THREAD

**Issue by kujeah** [daybrush/moveable#334]
## Environments
* Framework name: vue
* Framework version: 2.6.12
* Moveable Component version: 0.19.4
* Testable Address(optional):

## Description

I am using moveable to move the svg element.

When moving is applied by configuring general svg and adding text element, other origin points are displayed in Safari and chrome, causing problems.

Here is the text element code I used.

```
        <svg
            class="svg4"
            width="600"
            height="600"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 600 600"
            style="border: 1px solid #000000; overflow: hidden; position: relative; float: left"
        >
            <text
                ref="moveable"
                class="moveable"
                x="0"
                y="0"
                text-anchor="middle"
                fill="#000000"
                font-size="40px"
                font-style="normal"
            >
                <tspan>Jon doe</tspan>
            </text>
        </svg>
```

Below is an image captured by two browsers.

chrome
<img width="627" alt="Screen Shot 2020-10-20 at 16 22 13" src="https://user-images.githubusercontent.com/12984182/96555293-8eacb180-12f2-11eb-84dc-a469026f2076.png">

safari
<img width="619" alt="Screen Shot 2020-10-20 at 16 22 27" src="https://user-images.githubusercontent.com/12984182/96555247-7e94d200-12f2-11eb-8764-3319f60de51a.png">

The problem occurs only in text element, and the other element displays the same origin point in both browsers.

In fact, the origin point is displayed differently, but when the element is rotated, it rotates around the same point.

<img width="613" alt="Screen Shot 2020-10-20 at 16 22 45" src="https://user-images.githubusercontent.com/12984182/96555317-99674680-12f2-11eb-988d-7f54a40b085a.png">

<img width="624" alt="Screen Shot 2020-10-20 at 16 38 14" src="https://user-images.githubusercontent.com/12984182/96555384-ac7a1680-12f2-11eb-9fb8-1b5df1f7b445.png">

Therefore, it is suspected that the origin point displayed on the screen is misplaced.

Please let me know if anyone have any comments or hints about the issue.

**Comment by daybrush** [comment]
@kujeah 
* `moveable` 0.20.0
* `react-moveable` 0.23.0
* `preact-moveable` 0.22.0
* `ngx-moveable` 0.16.0
* `svelte-moveable` 0.11.0

moveable's new version is released. Check it again.
