### ISSUE TITLE
svg image inside div drag & clip

### ISSUE THREAD

**Issue by kujeah** [daybrush/moveable#337]
## Environments
* Framework name: vue
* Framework version: 2.6.12
* Moveable Component version: 0.19.4
* Testable Address(optional):

## Description

I have a question.

Can we use moveable by adding svg within div?

Below is the code of div that I designated as moveable.

```
<div class="moveable" style="position: absolute; display: flex; flex-direction: column; width: 172.8px; height: 216.16px; transform: translate(68.5965px, 52.1053px) rotate(0deg) scale(1, 1); clip-path: inset(0px);">

  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 172.8 216.16" preserveAspectRatio="none">
    <image xlink:href="[image url]" width="172.8" height="216.16" class="not-control"></image>
  </svg>

</div>
```

There is no problem when dragging the code, but if use clip, a problem occurs when drag.

<img width="839" alt="Screen Shot 2020-10-22 at 17 37 00" src="https://user-images.githubusercontent.com/12984182/96847342-095e0400-148e-11eb-89d9-12b66f59bc17.png">

<img width="855" alt="Screen Shot 2020-10-22 at 17 37 13" src="https://user-images.githubusercontent.com/12984182/96847373-0f53e500-148e-11eb-8f1d-fd92113f2c8c.png">

What advice do you have on the issue?

**Comment by daybrush** [comment]
@kujeah 

Oh, i will fix it.

**Comment by daybrush** [comment]
* `moveable` 0.20.0
* `react-moveable` 0.23.0
* `preact-moveable` 0.22.0
* `ngx-moveable` 0.16.0
* `svelte-moveable` 0.11.0

moveable's new version is released. Check it again.
