### ISSUE TITLE
Question: Is it possible to use fewer handles for Roundable?

### ISSUE THREAD

**Issue by miina** [daybrush/moveable#338]
## Environments
N/A

## Description

Is it possible to allow using fewer handles for Roundable, e.g. having maximum only 4 handles, 1 per each corner?

I'd like to enforce the border-radius only have one value per corner, for example:
`border-radius: 1px 2px 3px 4px` as opposed to `border-radius: 1px 24px / 34px 21px 20px 65px;` (result from testing)

Thank you!

**Comment by daybrush** [comment]
@miina 

Are you saying you want to do horizontal and vertical handles separately?

The maximum number of controls for roundable is 8.

Try double-clicking on the line and the control will increase.

**Comment by miina** [comment]
> Are you saying you want to do horizontal and vertical handles separately?
> The maximum number of controls for roundable is 8.

Currently, it's possible to have 8 controls but I'd like to know if it's possible to restrict that number and now allow more than 4 controls (or maybe even allow only 1 control) -- would that be possible?

**Comment by daybrush** [comment]
@miina 

Can you know what your desired motion is?

What kind of behavior do you expect when only one control is moved?

Do only one radius change or do all radiuses change proportionally?

**Comment by miina** [comment]
@daybrush Yes, exactly -- having just one control that changes border-radius for all 4 corners simultaneously. Would that be possible?

**Comment by daybrush** [comment]
@miina 

* `moveable` 0.20.0
* `react-moveable` 0.23.0
* `preact-moveable` 0.22.0
* `ngx-moveable` 0.16.0
* `svelte-moveable` 0.11.0

moveable's new version is released.
Use `maxRoundControls=[horizontal, vertical]`

if you show 1 control, Use `maxRoundControls=[1, 0]`

**Comment by miina** [comment]
Thank you, seems to work great on initial testing!
