### ISSUE TITLE
Where is the code for calculating the reference line and adsorption？

### ISSUE THREAD

**Issue by fulus06** [daybrush/moveable#341]
## Environments
* Framework name: 
* Framework version:
* Moveable Component version: 0.20.0
* Testable Address(optional):

## Description
Where is the code for calculating the reference line and adsorption？

**Comment by daybrush** [comment]
@fulus06 

* The original starts with react-moveable.
https://github.com/daybrush/moveable/tree/master/packages/react-moveable

* Drawing lines is done in the MoveableManager.
https://github.com/daybrush/moveable/blob/master/packages/react-moveable/src/react-moveable/MoveableManager.tsx#L106-L110

* The code to get 4 dots required to draw a line is caculateElementInfo, caculateMatrixStack, and caculateMoveablePosition.
https://github.com/daybrush/moveable/blob/master/packages/react-moveable/src/react-moveable/utils.ts#L350

**Comment by fulus06** [comment]
thank
