### ISSUE TITLE
How to support hoverable state on any element that can be selected by react-moveable

### ISSUE THREAD

**Issue by nelsondude** [daybrush/moveable#342]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

Hello, I'd like to create a custom able to support adding a hover state to any hovered target regardless of whether it is selected or not. I originally coded it completely separate from react-moveable by using an on mouse move event handler and calculating if the mouse position is inside a moveable element and if it is then rendering the hover state. However, this is definitely not ideal and it would be great if I could hook into any of the able params, just not sure which one.

**Comment by daybrush** [comment]
@nelsondude 

I will consider the hover state.

There may be a performance problem, so I will investigate further and provide it.

Will it be provided as an event like this?
```js
const customAble = {
   mouseEnter(e, moveable) {}
   mouseOut(e, moveable) {}
};

**Comment by nelsondude** [comment]
Yeah exactly, this way we can render conditionally based on those events

**Comment by nelsondude** [comment]
Probably `mouseLeave` instead of `mouseOut`

**Comment by daybrush** [comment]
@nelsondude 
* `moveable` 0.21.0
* `react-moveable` 0.24.0
* `preact-moveable` 0.23.0
* `ngx-moveable` 0.17.0
* `svelte-moveable` 0.12.0


```jsx


const MouseCustomAble = {
    name: "mouseTest",
    props: {},
    events: {},
    mouseEnter() {
        console.log("ENTER");
    },
    mouseLeave() {
        console.log("LEAVE");
    }
}
<Moveable
            ables={[MouseCustomAble]}
            props={{
                mouseTest: true,
            }} />

```

**Comment by mtofful** [comment]
Hi @daybrush how can I write unit tests to check for those mouse events using React+Jest+Enzyme? thank you I appreciate your time :)
