### ISSUE TITLE
"export 'calculateBoundSize' was not found in '@daybrush/utils'

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#344]
## Environments
* Framework name: vanilla
* Framework version: 0.20.1
* Moveable Component version: 
* Testable Address(optional):

## Description
- error in compile

```
WARNING in ./node_modules/react-compat-moveable/dist/moveable.esm.js 6891:9-27
"export 'calculateBoundSize' was not found in '@daybrush/utils'
 @ ./node_modules/moveable/dist/moveable.esm.js
```

**Comment by daybrush** [comment]
@ctf0 

resintsall `moveable`

It seems like a temporary dependency problem.

**Comment by ctf0** [comment]
it seems an issue with yarn, deleting everything and start with npm seems to fix the issue, thanx
