### ISSUE TITLE
group resizes to min size(1px) problem

### ISSUE THREAD

**Issue by xueerli** [daybrush/moveable#345]
## Environments
* Framework name: react
* Framework version: 16.13.1
* Moveable Component version: react-moveable 0.23.0
* Testable Address(optional): https://daybrush.com/moveable/storybook/?path=/story/group--resizable

## Description

When a group resizing to minimum size( 0 or 1px), the child elements have the same size after getting bigger. And the position of the child elements overlap. 
![gif](https://ftp.bmp.ovh/imgs/2020/11/ee88b03aee76ed0f.gif)

**Comment by daybrush** [comment]
@xueerli 

But that will be right.

If the width and height are 0, the left and top are also 0.

Since all are 0, 0, 0, 0, they eventually overlap.


If you want to set a minimum size. Call setMin on resizeStart.

**Comment by xueerli** [comment]
@daybrush 
You are right.
If i don't set the width and height to 0, but 2 or 20. It still has size and lication issues.
test: https://codesandbox.io/s/fervent-bose-ke03h?file=/src/App.tsx
```
onResizeGroupStart={e => {
  e.setMin([2, 2]);
}}
```
![demo](https://ftp.bmp.ovh/imgs/2020/11/805d616369590d21.gif)
before resize:
![before](https://ftp.bmp.ovh/imgs/2020/11/adad18cccd9513da.png)
setMin([20,20])
![20](https://ftp.bmp.ovh/imgs/2020/11/8b6723d733de92db.png)
setMin([2,2])
![2](https://ftp.bmp.ovh/imgs/2020/11/4746dd66f169219b.png)

**Comment by daybrush** [comment]
@xueerli 

But unfortunately, this problem occurs because the width and height are rounded to integers... I think this is a problem with the browser.
