### ISSUE TITLE
problem with importing movable from npm in pycharm

### ISSUE THREAD

**Issue by nathalieroemer** [daybrush/moveable#346]
## Description
I try to implement 'moveable' via npm with PyCharm. The package is installed and listed in the dependency but it tells me 'interface cannot be instantiated' when I try to import it with "import Moveable from 'moveable'" in my js. Any suggestions are highly appreciated!

**Comment by daybrush** [comment]
@nathalieroemer 

Oh sorry. Previously, there was a similar issue with angular.

I will solve it soon.

**Comment by nathalieroemer** [comment]
That would be great!

**Comment by daybrush** [comment]
@nathalieroemer 

moveable 0.20.2 is released. Check it again.

**Comment by nathalieroemer** [comment]
Great news! Thanks for the quick update. I do not get an error message anymore, however, unfortunately, it is still not working. I am trying with this example: https://github.com/lelouchB/moveable-example, and changed nothing but importing Moveable from npm instead of including the script via the webpage (btw, I am also getting an error message there: 'There is no locally stored library for the HTTP link' but I want to use it locally anyways). Any ideas what could be the problem?

**Comment by daybrush** [comment]
@nathalieroemer 

It doesn't seem to be a moveable issue. Isn't it a problem that the `script` `module` cannot be used locally?

**Comment by nathalieroemer** [comment]
No it wasn't a moveable issue, sorry! Fixed it. Thanks a lot!

**Comment by nathalieroemer** [comment]
Sorry to bother you again, I'm moving on with my project and wanted to include selecto: here the same issue arises as before ("interface cannot be instantiated"). Is there a possibility to fix this, too ? Thanks a lot!
