### ISSUE TITLE
[In Demo] Move outside with rotated is problem

### ISSUE THREAD

**Issue by alezzigo** [daybrush/moveable#349]
## Environments
* Framework name: react-moveable / Demo
* Framework version: 0.21.0
* Moveable Component version: 0.24.0
* Testable Address(optional): https://daybrush.com/moveable/

## Description
1. "The Description element" move inside Logo then rotate 45 deg.

<img width="1113" alt="Screen Shot 2020-11-10 at 1 56 59 PM" src="https://user-images.githubusercontent.com/26524788/98640831-5599b700-235d-11eb-906b-b6a8e9e3d7cf.png">

2. Then "the Description element"move outsite Logo.

<img width="651" alt="Screen Shot 2020-11-10 at 1 57 28 PM" src="https://user-images.githubusercontent.com/26524788/98640929-7eba4780-235d-11eb-8633-79efe1dca7ea.png">

Result: "the Description element" keep 0 deg. 
-----------------------------------
I try find some but is fail. How keep rotation for "the Description element"?
Thanks!

**Comment by daybrush** [comment]
@alezzigo 

It's fixed. Thank you :)

**Comment by alezzigo** [comment]
@daybrush  you are Great
