### ISSUE TITLE
[In Demo] Problems with elements when scaling

### ISSUE THREAD

**Issue by MiiZZo** [daybrush/moveable#352]
## Environments
* Framework name: React
* Framework version: 16.13.1
* Moveable Component version: 0.22.6 (react-moveable)
* Testable Address(optional): https://daybrush.com/moveable/

## Description
Hi I'm using your package in development based on your demo. And I noticed two problems:
1. at large zoom in, the blue borders of the selected element are too thick.
2. When you change the scale, the created elements start to appear in the wrong place
Could you please help me with solving these problems?

**Comment by daybrush** [comment]
@MiiZZo 

I have identified all two problems. I'll try to fix it.

**Comment by daybrush** [comment]
@MiiZZo 

Demo is fixed. Check again. Thank you :)

**Comment by MiiZZo** [comment]
Nice. Thank you!
