### ISSUE TITLE
rotationPosition "bottom" issue

### ISSUE THREAD

**Issue by copthuy** [daybrush/moveable#353]
Set the **rotationPosition** to "_bottom_" and the knob is placed in the wrong direction.
Checked with your demo page. https://daybrush.com/moveable/storybook/index.html?path=/story/basic--rotatable

Version 0.19.4 is working fine. Problem started from version 0.20.0.

**Comment by daybrush** [comment]
@copthuy 

Thank you. It's fixed and check again

**Comment by copthuy** [comment]
Thanks, it's working!
