### ISSUE TITLE
when do scale, element will disappear, but if drag first, then scale works

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#355]
## Environments
* Framework name: vue
* Framework version: 2.x
* Moveable Component version: 0.17.10

## Description

```javascript
{
        renderDirections: ['ne', 'nw', 'se', 'sw'],
        draggable: true,
        scalable: true,
        resizable: false,
        rotatable: false,
        warpable: false,
        snappable: true,
        className: ''
      }
```

![QQ20201117-180442 copy](https://user-images.githubusercontent.com/1256745/99377260-f578b700-2900-11eb-92fb-49aa2f7a2a12.gif)

![image](https://user-images.githubusercontent.com/1256745/99377343-0fb29500-2901-11eb-9f99-bc371b05fea7.png)

**Comment by daybrush** [comment]
@leeboo 

Setting itemScale and changing css are like asynchronous.

css should run synchronously.
```
target.style.transform =  `scale(${scale[0]}, ${scale[1]})`;

```

**Comment by leeboo** [comment]
but why drag first, scale is work as expected

**Comment by daybrush** [comment]
@leeboo 

That is, snappable must be used with dragStart in scale.

You are not using the onScaleStart, dragStart, drag properties in onScale.
