### ISSUE TITLE
Select child when parent is selected

### ISSUE THREAD

**Issue by MiiZZo** [daybrush/moveable#356]
## Environments
* Framework name: React
* Framework version: -
* Moveable Component version: -
* Testable Address(optional): https://daybrush.com/moveable/

## Description
I want to be able to select a child when a parent is selected. As you can see in the demo, if I select the top layer, I cannot select the child layer. How can I fix it?

**Comment by AustinHatem** [comment]
Hello, is this possible now? Since it is in the WIP-Complete?

**Comment by daybrush** [comment]
@AustinHatem 

It's released. Thank you :)
