### ISSUE TITLE
Snapgrid vertical/horizontal guidelines relative to a specific container

### ISSUE THREAD

**Issue by nelsondude** [daybrush/moveable#357]
## Environments
* Framework name: React
* Framework version: Latest
* Moveable Component version: Latest
* Testable Address(optional):

## Description
Hello, I'm looking for a way to pass a list of vertical and horizontal guidelines using the snappable able, but make the guidelines relative to the container of the element or a user-specified container. Would it be possible to include a prop like the following: 

`guidelinesContainer: (selected: (HTMLElement | SVGElement)[]) => HTMLElement`

Return value of this would be the container that the guidelines are relative to.

This way when I pass guidelines to verticalGuidelines and horizontalGuidelines, the values can depend on a container other than the container of the react-moveable instance.

**Comment by nelsondude** [comment]
On second thought, I'm thinking a better way for this would be when passing in verticalGuidelines/horizontalGuidelines, the prop would have the following typing: 
`type verticalGuidelines = number[] | {container: HTMLElement, value: number}[]`
This would allow the user to specify the guideline relative to a particular container before hand. My use case is that I have a single moveable instance managing the components on multiple "pages" but these pages can be zoomed in and out. Since the moveable instance currently lives outside of the pages, the vertical guidelines have to be changed every time the zoom of the page is changed

**Comment by daybrush** [comment]
@nelsondude 

The second opinion was good. I'll add it.

**Comment by daybrush** [comment]
@nelsondude 

What does it mean to create guidelines that depende on container.

is this right?:
![51A3D284-9BD3-44E0-A95B-08181895E432](https://user-images.githubusercontent.com/3433062/100256038-9a416700-2f87-11eb-880a-a4c71d13ac8f.jpeg)

**Comment by nelsondude** [comment]
Yes, so say it looks like
```
<div class="larger-div">
	<ReactMoveable />
	<div class="smaller-div />
		<div class="component-to-drag />
	</div>
</div>
```

If i pass `verticalGuidelines=[0]` and `horizontalGuidelines=[0]` then the component will snap to the left and top bounds of the smaller-div if i pass `document.querySelector('.smaller-div')` as the element/container. If i passed `document.querySelector('.larger-div')` then it would snap to the left and top bounds of larger-div

**Comment by daybrush** [comment]
@nelsondude 

It will be added. Test react-moveable@beta(0.25.0-beta6)
Use elementGuidelines.
```jsx
const element = document.querySelector('.larger-div');

elementGuidelines={[
    element, // or
    { element, top: true, left: true, bottom: false, right: false },
]}
```

**Comment by nelsondude** [comment]
Hey how does this prop work exactly? I was originally asking about `verticalGuidelines` and `horizontalGuidelines` but I see that you updated `elementGuidelines`

**Comment by daybrush** [comment]
@nelsondude 
Sorry. Test react-moveable@beta(0.25.0-beta7)


First, it is difficult to add to verticalGuidelines and horizontalGuidelines.
So I decided to add it to elementGuidelines instead.

**Comment by nelsondude** [comment]
No problem, i think this should help me accomplish what I was trying to do. Thanks! works great.
