### ISSUE TITLE
Ratio is changed. KeepRatio is true.

### ISSUE THREAD

**Issue by xueerli** [daybrush/moveable#358]
## Environments
* Framework name: react 
* Framework version: 17.0.1
* Moveable Component version: react-moveable 0.23.0
* Testable Address(optional): 

## Description
I resized element to minimum size that i set the minWidth and minHeight according to the original ratio. But when i resizing it bigger, the ratio was changed. I read the source code, and found that the ratio calculated using the value of startWidth and startHeight is correct. But it seems you are using startOffsetWidth and startOffsetHeight. Is this a bug?
```
    // react-moveable/ables/Resizable.ts
    console.log(startOffsetWidth, startOffsetHeight)
    console.log(startWidth, startHeight)
```

**Comment by daybrush** [comment]
`set([startWidth, startHeight])` is to set your css width, height.
offsetWidth and offsetHeight are the actual size of the element.

**Comment by xueerli** [comment]
@daybrush 
This is test address https://codesandbox.io/s/reverent-morning-j2fse?file=/src/App.tsx.
The origin ratio is 6. After resizing to minimum size, the ratio is changed.
I want to keep the ratio no matter how i change the size.

**Comment by xueerli** [comment]
@daybrush 
Is this a bug?😊

**Comment by daybrush** [comment]
@xueerli 

This can't be helped. This is a browser issue.
Because width and height are integers (rounded), they can change ratio.

Instead, I'm make function called `setRatio` now.

**Comment by xueerli** [comment]
@daybrush 
Ok, i will wait for using `setRatio`. Thanks.

**Comment by daybrush** [comment]
@xueerli 

`react-moveable@0.25.0-beta` is released. Test it.
```
onResizeStart={e => {
    e.setRatio(ratio);
}}
```

**Comment by xueerli** [comment]
@daybrush 
It is very useful. Thank you so so so much.
