### ISSUE TITLE
Getting error on dragging, scaling and resizing after making Angular build

### ISSUE THREAD

**Issue by vinaykugarg** [daybrush/moveable#36]
i have used Moveable library in my Angular 7 project. I have used three features of that Drag, Resize,Scale for DOM elements. Its working good on local environment. But after making AOT build its giving error of this.setState() is not a function.

Please help.

**Comment by daybrush** [comment]
@vinaykugarg 

Thank you for reporting bug.
I'll check it.

**Comment by daybrush** [comment]
@vinaykugarg 

`ngx-moveable` 0.4.2 is released. Please check again.

Thank you

**Comment by born2net** [comment]
I still see the issue with latest release, please see:
https://github.com/daybrush/moveable/issues/56

**Comment by daybrush** [comment]
@vinaykugarg  @born2net 

`ngx-moveable` 0.5.4 version  is released. Please check again.

You just need to update `ngx-moveable`.


---

### The reason for the error
Angular aot and prod modes removed preact code.

```js
// Angular aot and prod modes removed preact code.
extend(Component.prototype, {
        setState: function(state, callback) {
            if (!this.__s) this.__s = this.state;
            this.state = extend(extend({}, this.state), 'function' == typeof state ? state(this.state, this.props) : state);
            if (callback) this.__h.push(callback);
            enqueueRender(this);
        },
        forceUpdate: function(callback) {
            if (callback) this.__h.push(callback);
            renderComponent(this, 2);
        },
        render: function() {}
    });
```
So, update preact 8 => preactX

**Comment by born2net** [comment]
great I'm going to check it out later today and report back. any chance that you guys can add the guideline feature to the anglular project as well?
regards

**Comment by daybrush** [comment]
@born2net 
Sorry. I missed the snappable option.

`ngx-moveable` 0.5.5 released

Below is a simple example of guidelines.

https://stackblitz.com/edit/ngx-moveable-snappable-test

**Comment by born2net** [comment]
TX!!!!
