### ISSUE TITLE
Allow customtarget for rotatable handle

### ISSUE THREAD

**Issue by ctrl-alt-deleted** [daybrush/moveable#361]
## Environments
* Framework name: vanilla js moveable
* Framework version:  0.20.2
* Moveable Component version:  0.20.2

## Description
Hey Guys

For draggable we can attach custom target using **dragTarget** ,  Is it possible to have same thing for  rotatable?  looked at the source could not see any options.

**Comment by daybrush** [comment]
@ctrl-alt-deleted 

Where are you trying to set the rotate target?

If you want to have an external target, use `request`.

https://daybrush.com/moveable/release/latest/doc/Moveable.Rotatable.html#request

**Comment by ctrl-alt-deleted** [comment]
@daybrush  thanks for the reply 

well I  was thinking along the line of  `rotateTarget`, as an additional option.  

Didn't realizes u could use  `request`,  so will check that out and see.  

Thanks for  help 👍🏼
