### ISSUE TITLE
Resizeable max width is jumpy under certain circumstances

### ISSUE THREAD

**Issue by idanen** [daybrush/moveable#362]
## Environments
* Framework name: Vanilla
* Moveable Component version: 0.21.1
* Testable Address(optional): [codesandbox](https://codesandbox.io/s/moveable-resize-max-width-in-grid-ds29o)

## Description
Setting an element in a flex container, which is in a grid container, to be Resizeable.
Flex has items aligned to center.
The max width is very "jumpy".
In a test we have where we use it, the test fails constantly.
Couldn't recreate the test in the code sandbox, but the issue definitely happens there.

**Comment by daybrush** [comment]
@idanen 

Thank you. I will consider more ways to maintain the ratio. Since the size of resizable is an integer, very small numbers (decimal points) can be broken.

**Comment by daybrush** [comment]
@idanen 

moveable's new version is released.

in onRotateStart event, call `e.setRatio(ratio)` function.

**Comment by idanen** [comment]
> in onRotateStart event, call `e.setRatio(ratio)` function.
Great! 
Don't you mean onResizeStart?

**Comment by daybrush** [comment]
@idanen 

Oh. yes.
