### ISSUE TITLE
Controls shifted when use transform:scale() style

### ISSUE THREAD

**Issue by b-des** [daybrush/moveable#364]
Hi. First of all, thank you for such great tools. But I faced with some troubles using moveable.
## Environments
* Framework name: preact
* Framework version: 10.5.7
* Moveable Component version: 0.21.1
* Testable Address(optional):

## Description

I use moveable with preact(it doesn't matter actually), but when container has css property transform:scale() then the target has wrong controls offset. Here is screenshot:
![image](https://user-images.githubusercontent.com/14833882/100366348-673fb780-3009-11eb-95fe-ca1d38e93246.png)

And this is styles of the parent container:
`transform-origin: 0px 0px 0px;
width: 1000px;
height: 1500px;
transform: scale(0.705);`

When drug the target the distance between target and controls changes nonlinear.

I noticed that on this page https://daybrush.com/moveable/ when I've added scale() to container - everything was fine, there was no distortion. Is there somewhere source code of this page?

Please, give me advice how to solve such problem. Thanks!

**Comment by daybrush** [comment]
@b-des 


If you want to use a scale or other transform on the container or its parent, set the rootContainer(document.body or higher)

rootContainer={document.body}

**Comment by b-des** [comment]
@daybrush 
Thank you. It helps me

**Comment by b-des** [comment]
@daybrush 
Another one question. Which component do you use there(mean container, looks like it's scenejs) https://daybrush.com/moveable/?
![image](https://user-images.githubusercontent.com/14833882/100450325-1d64d900-30be-11eb-9544-bebab7596cea.png)

**Comment by daybrush** [comment]
@b-des 

It is `infinite-viewer`. 
https://github.com/daybrush/infinite-viewer
