### ISSUE TITLE
Angular 10 problem!

### ISSUE THREAD

**Issue by TnPoDoLsKi** [daybrush/moveable#365]
## Environments
* Framework name: Angular 
* Framework version:  10.0.8
* Moveable Component version: 0.14.2
* Testable Address(optional):

## Description

Any solution please?

![Screenshot from 2020-11-27 00-28-20](https://user-images.githubusercontent.com/45011898/100396952-a2f97200-3047-11eb-8c4f-b3a97719ba5e.png)

**Comment by daybrush** [comment]
@TnPoDoLsKi 

If you want to use a scale or other transform on the container or its parent, set the rootContainer(document.body or higher)

rootContainer={document.body}

**Comment by daybrush** [comment]
@TnPoDoLsKi  

Try using module instead of component?
```js
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    NgxMoveableModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})

**Comment by TnPoDoLsKi** [comment]
Thank you :+1:
