### ISSUE TITLE
Calling update moveable rect while maintaining the previous rotation of the moveable element

### ISSUE THREAD

**Issue by nelsondude** [daybrush/moveable#366]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

Hello, I'd like to call `moveable.updateRect()` so that it recalculates the bounds given the selected targets but not have it reset the rotation of the moveable element. how can i do this? If i rotate a group of elements and then call updateRect, it sets the rotation to 0.

**Comment by daybrush** [comment]
@nelsondude 

use updateTarget() with beta version(0.25.0-beta6). Test it.

**Comment by nelsondude** [comment]
Thanks, it is mostly working great, however i did notice a small bug. After resizing the group and rotating, I noticed that sometimes the center of rotation is no longer the center of the group. To reproduce,
1. select more than 1 component
2. rotate the group 
3. resize the group (make it larger)
4. then rotate the group again

**Comment by nelsondude** [comment]
Here is a demo: https://codesandbox.io/s/quizzical-wozniak-i4go2?file=/src/App.tsx . As you can see, when rotating the group, the origin of rotation is constantly changing while on 0.25.0-beta6

**Comment by daybrush** [comment]
@nelsondude 

Oh. It's fixed. Test react-moveable@beta(0.25.0-beta7).

**Comment by nelsondude** [comment]
Thanks, everything is working amazing!
