### ISSUE TITLE
drag is starting with quick mousedown and mouseup (mouseup is missed)

### ISSUE THREAD

**Issue by hkoz461** [daybrush/moveable#368]
## Environments
* Framework name: Vue
* Framework version: 2.6.10
* Moveable Component version: "svelte-moveable": "^0.12.1"+"svelte-adapter": "^0.3.0"  "vue-selecto": "^1.5.0"
* Testable Address(optional):

## Description
Hi Daybrush,
I am using selecto and moveable together. Sometimes when i click (mouse down and up) on a moveable component it starts dragging by itself. What i found mouseup event is coming before DragStart finishes. Then drag is continuing (with mouseup) until i click again and see dragEnd event. This is not happening always but sometimes when i think browser is busy.

onSelectEnd(e) {
  this.moveable.target = e.selected;
  if (e.isDragStart) {
      e.inputEvent.preventDefault();
          setTimeout(() => {
            this.$refs.sMove.comp.dragStart(e.inputEvent);
          });
  }
}
Above function is behaving sometimes like you give 1sec for instance for the timeout and mouseup never works "setTimeout(() => {           this.$refs.sMove.comp.dragStart(e.inputEvent);
          }, 1000);

How can i prevent this to happen?   
Thank You

**Comment by daybrush** [comment]
@hkoz461 

This problem is too difficult for me. Could mouseup happen before dragStart?

Would you like to set dragContainer to window?

**Comment by hkoz461** [comment]
Hi @daybrush 
dragContainer to window didn't change. Some view updates in onSelectEnd (selecto) was causing it to last long and so dragStart to be called after mouseup. I put additonal mouseup and mousedown listeners to get the status of mouse and used in onDrag(moveable) to catch the condition and stop dragging in this case. Now it is ok.
Thank you.

**Comment by innerop** [comment]
drag starts on mousedown and never ends on mouseup ... keeps dragging and dragging.. i am also having numerous issues with the behavior of resize ... it is simply bonkers, doing nothing right and I followed the example in the readme.. and if I hadn't set position:relative on parent I would still have the controls displayed on the container rather than on the target...

**Comment by tribeAppMobile** [comment]
Hi @hkoz461 , @daybrush . How to stop the drag programmatically ? I also face the problem after mouseup, it keeps dragging. 

<Moveable
        ref={this.moveableRef}
        draggable={true}
	resizable={false}
	edge={true}
	origin={true}
	bounds={{left: 0, top: 0}}
	target={selectedTargets}
	
	onDragStart={e => {
		console.log('onDragStart', e, selectedTargets)
		const target = e.target;
		let frameMap = this.state.frameMap;
		if (!frameMap.has(target)) {
			frameMap.set(target, {
				translate: [0, 0],
			});
		}
                // Stop the drag when mouse up ?
		document.addEventListener('mouseup', () => {
			console.log('=> mouseUp in dragStart')
			// this.moveableRef.current.draggable = false;
			e.stop();
		})
		// const frame = frameMap.get(target);
		// e.set(frame.translate);
	}}
/>

Great Thanks.

**Comment by hkoz461** [comment]
Hi @tribeAppMobile Yes I used something to catch mouse up on dragStart as you tried.. You may need other lock bits not to make collusions with others ..

      onDragStart({ detail: e}) {
        if(this.auxLock){
          this.auxLock = false;
          if(this.saveFromMissedMouseUp())
            return;
        }
        .....
  }

      saveFromMissedMouseUp(){
        if(!this.mouseDown){ // if mouseup comes before reaching here..
          let oldTargets = this.moveable.target.map((v)=>{return v})
           this.moveable.target = null;
           this.$nextTick(()=>{
             this.moveable.target = [];
             oldTargets.forEach((v)=>{
               this.moveable.target.push(v);
             })
           })
          console.log("RETURNED FROM DRAG");
          return true;
        }
        else
          return false;
      },

      onSelectEnd(e) {
        // console.log("on select end");
        this.moveable.target = e.selected;
        if (e.isDragStart) {
          e.inputEvent.preventDefault();
          setTimeout(() => {
            this.auxLock = true;
            this.$refs.sMove.comp.dragStart(e.inputEvent);
          }, 0);
        }
        ....
     }


    mounted () {
      ...
      document.addEventListener("mousedown", ()=>{this.mouseDown = true;});
      document.addEventListener("mouseup", ()=>{this.mouseDown = false;});
      ...
    }

**Comment by bluematter** [comment]
I had this issue too, it was super annoying, took me a whole day... Here is my solution, open to criticism to make it better, but it's working from my initial testing

Using React

Mouse up listener
```
const setUp = (e: any) => {
  const target = e.target.parentElement;

  if (target?.classList.contains("target")) {
    target.setAttribute("data-mouse", "up");
  }
};

useEffect(() => {
  document.addEventListener("mouseup", setUp);

  return () => {
    document.removeEventListener("mouseup", setUp);
  };
}, []);
```

handleSelectEnd
```
const handleSelectEnd = (e: OnSelectEnd) => {
  const target = e.selected[0]; // can be improved
  e.inputEvent.stopPropagation();
  e.inputEvent.preventDefault();

  if (e.isDragStart) {
    setTimeout(() => {
      if (target?.getAttribute("data-mouse") !== "up") {
        moveableRef?.current?.dragStart(e.inputEvent);
      }
    });
  }

  target?.removeAttribute("data-mouse");
};
```

handleDragStart
```
const handleDragStart = (e: OnDragStart) => {
  if (moveableRef.current) {
    const moveable = moveableRef.current;
    const target = e.inputEvent.target;

    if (
      moveable.isMoveableElement(target) ||
      targets.some((t) => t === target || t.contains(target))
    ) {
      e.stop();
    }
  }
};
```

The idea is to quickly set the data attribute on the target node to mouse-up so that when the timeout gets called we know the state of the mouse. Then to reset it.
