### ISSUE TITLE
Transformation through rotation gets lost when rescaling or dragging afterwards

### ISSUE THREAD

**Issue by nathalieroemer** [daybrush/moveable#369]
## Environments
* Framework name: Vanilla JS
* Moveable Component version: draggable, resizable, rotateable

## Description
If I rotate an element, and resize or drag the rotated element, then the transformation through the previous rotation gets lost. Is there a solution to this problem?

Thanks a lot!
Nathalie

**Comment by daybrush** [comment]
@nathalieroemer 

You have to save  T(ranslate) , R(otate) ,S(ale) values. And you can set translate in resize, rotate
