### ISSUE TITLE
Feature Request: Adding custom element / button on the handler

### ISSUE THREAD

**Issue by chenxeed** [daybrush/moveable#371]
## Description

Hello @daybrush, thank you again for the awesome library!

I would like to ask your opinion about this use-case:

![image](https://user-images.githubusercontent.com/3530355/100821879-3a1d5a00-348c-11eb-8e06-302bc62c61d1.png)

Imagine in the visual editor, when we select an element, aside from the handler to make it resizeable/draggable, we also want to show a custom button like (+) and (x), to trigger custom event, for ex: "add another item", "delete item", etc.

I was thinking of rendering the button as part of the element, but then it would be great if the button stays on top of the canvas. Currently, the moveable handler is capable of doing that because the handler DOM can be rendered on top of the canvas:

![image](https://user-images.githubusercontent.com/3530355/100823008-6a65f800-348e-11eb-9096-45ac95c7142f.png)

This is why I'm thinking that if I can render the custom button as part of the moveable handler, then the button shall stay on top as well.

I would love to hear your opinion about this use-case, and if handling this from moveable is a good feature to expand the usability more.

**Comment by daybrush** [comment]
@chenxeed 

See this document. I made it temporarily.
https://github.com/daybrush/moveable/tree/master/packages/react-moveable/src/react-moveable/ables#example

**Comment by chenxeed** [comment]
Thanks a lot @daybrush . The example looks good as it allows us to create our custom element and render it as part of the `Moveable` component.

I wonder if we can attach the custom element in the codebase that's using either vanilla or from other framework like Vue.

**Comment by xiaochong44** [comment]
@chenxeed 
const DimensionViewable = {
      name: 'dimensionViewable',
      props: {},
      events: {},
      css: ['moveable-dimension'],
      render(moveable: MoveableManagerInterface<any, any>, React: any) {
        const rect = moveable.getRect();
        return React.createElement('div', {
          class: 'moveable-dimension',
          style: {
            position: 'absolute',
            left: `${rect.width / 2}px`,
            top: `${rect.height + 20}px`,
            background: '#4af',
            borderRadius: '2px',
            padding: '2px 4px',
            color: 'white',
            fontSize: '13px',
            whiteSpace: 'nowrap',
            fontWeight: 'bold',
            willChange: 'transform',
            transform: 'translate(-50%, 0px)',
          },
          key: 'dimension-viewer',

        },Math.round(rect.offsetWidth)+'X'+Math.round(rect.offsetHeight));
      },
    };
this.moveable = new Moveable(this.container, {
      draggable: true,
      resizable: true,
      container: this.container,
      keepRatio: false,
      origin: false,
      snapHorizontal: true,
      snappable: true,
      ables: [DimensionViewable],
      dimensionViewable: true,
      horizontalGuidelines: this.guideLines?.x,
      verticalGuidelines: this.guideLines?.y,
    });

**Comment by chenxeed** [comment]
Closing since this is not an issue anymore.
