### ISSUE TITLE
[QUESTION] Possibility to disable(unselect) moveable programmatically 

### ISSUE THREAD

**Issue by b-des** [daybrush/moveable#372]
## Environments
* Framework name: preact
* Framework version: 10.3.2
* Moveable Component version: 0.23.1
* Testable Address(optional): -

## Description
Hi, @daybrush. 
Is there an API to temporary disable(make non-moveable) element in react/preact?
For example(using react reference): this.ref.current.disable(); and then this.ref.current.enable();

If there is no API, please, advise how to achieve this functionality with react?

P.S. I've read the API documentation but haven't found the solution.

**Comment by daybrush** [comment]
@b-des 

What feature do you want to disable?

**Comment by b-des** [comment]
@daybrush, in the most cases this will be draggable(but probably could few features as well).
More exact requirement is to disable draggable and hide all controls. 
I know I can disable some features using state and hide controls manually, but would be great if there were some special methods or attributes for this.
Is it possible using any API?

**Comment by b-des** [comment]
@daybrush 
In fact, I wanna to achieve such functionality(it's canva.com):
![image](https://user-images.githubusercontent.com/14833882/101050468-1aba2600-358d-11eb-93e6-63f6f9b557fc.png)


That's why I'm interested to disable some feature and put child(ghosted) element to crop image

**Comment by daybrush** [comment]
@b-des 

Try using css' display property to set it to none or set draggable to false.

**Comment by b-des** [comment]
@daybrush

Got it, thank you!
