### ISSUE TITLE
Moveable onRotate gives new rotation degree rather than entire rotation of the element

### ISSUE THREAD

**Issue by PramodIndusved** [daybrush/moveable#377]
## Environments
* Framework name: React
* Framework version: 16.8.19
* Moveable Component version: 0.21.6-rc
* Testable Address(optional):

## Description
I have added the moveable to the element. when I try to rotate the element it goes perfectly, but onRotate function give me rotate degree starting from 0.

Suppose I rotate the element by 90 degree (Works fine and give proper value of rotation in degree), again I want to rotate the element by 5 degree, then expected value should be 95 degree, but the resultant value is 5 degree only

My function onRotate is 
```
  const onRotate = ({ target, delta, dist, transform, clientX, clientY }) => {
    console.log(transform)
    target.style.transform = transform;
  } 
```
The resultant transform value is based on how much degree we rotated recently, not the entire rotation of the element.

Thanks in advance

**Comment by Psychokiller1888** [comment]
I added a delta variable to overcome this... You never get the real rotation, only the delta since last onRotate

**Comment by daybrush** [comment]
@Psychokiller1888 
Yes. I can never know the source of the transform. You have to save the rotate value.

use onRotateStart, onRotate

https://daybrush.com/moveable/storybook/?path=/story/basic--rotatable

**Comment by PramodIndusved** [comment]
saving previously rotated value in state and the adding it later on rotate value give me exact value for element rotation. Thanks

**Comment by Psychokiller1888** [comment]
@daybrush Yes, but you need to add a delta variable, adding each step to get the final rotation, instead of having a "total rotation" directly accessible. Same for movements and resize

**Comment by daybrush** [comment]
@Psychokiller1888 

onRotate has delta, dist, rotate values.

**Comment by Psychokiller1888** [comment]
Yes....... But we are talking with absolute rotation... Delta and dust give rotation since last placement. You never get the absolute element rotationSent from my Galaxy

**Comment by daybrush** [comment]
@Psychokiller1888 


The absolute rotation value is provided. See rotation of getRect(). But it is not accurate.

**Comment by Psychokiller1888** [comment]
Well, you could add it as a listener, as for delta and dist?

**Comment by daybrush** [comment]
@Psychokiller1888 

moveable's new version is released.
in rotate event, provide absoluteRotate, absoluteDelta, absoluteDist properties. Thank you :)

**Comment by Psychokiller1888** [comment]
Great news, and great job, thank you!
