### ISSUE TITLE
Nested moveable behaving in a weird way

### ISSUE THREAD

**Issue by Psychokiller1888** [daybrush/moveable#378]
## Environments
* Framework name: Vue.js
* Framework version: 2
* Moveable Component version: 0.21.1
* Testable Address(optional):

## Description
I'm building a floor plan designer for our Voice assistant. The interface is based on vue, and I'm using moveable to add rooms to the floor plan. I'm not using the vue-moveable plugin, as it's not usable for me. I cannot deactivate moveable components, it's too strict etc etc, I rather use the vanilla version.

Everything seems to work rather fine, but the problems start when I try to nest components. The way I work is with only 1 moveable instance, that is cleared and recreated with the target set to the location I click on.

I create my first location, that is an active moveable as soon as I click on it, it behaves nicely. I create a second location, click on it to activate it, drag and drop it into the first location. It's "somehow ok". If I try to move that second location, it jumps of page with the slightest movement. Every value, dist, delta for on drag print the same, completly wrong, of something like 650px

This is a short gif to demonstrate the issue:
![https://puu.sh/GVuaX.gif](https://puu.sh/GVuaX.gif)
https://puu.sh/GVuaX.gif

**Comment by daybrush** [comment]
@Psychokiller1888 
I am curious about the structure of the DOM when two items are nested. I am also curious about the moveable's DOM.

**Comment by Psychokiller1888** [comment]
Thanks for the answer!

Ok, the project is here: https://github.com/project-alice-assistant/webui/blob/master/src/components/views/myhome.vue

The custom tag `location` is the moveable: https://github.com/project-alice-assistant/webui/blob/master/src/components/views/location.vue

The actual rendered DOM: with a nested moveable: https://pastebin.com/fPCqcqQK (formatting with https://www.freeformatter.com/)

**Comment by Psychokiller1888** [comment]
Hmmm, for some reason, it seems that it is dragged to 0:0 of body, on drag start, if it's in a moveable:

![https://puu.sh/GVPLe.png](https://puu.sh/GVPLe.png)

**Comment by daybrush** [comment]
@Psychokiller1888 

Call destroy();

```diff
this.moveable.target = null;
+ this.moveable.destroy();
this.moveable = new Moveable(...);
```

**Comment by Psychokiller1888** [comment]
I don't want to destroy it, I want it to move and not jump to Body 0x0 👍🏻

**Comment by daybrush** [comment]
@Psychokiller1888 
Then create moveable only once. And don't change the container.

**Comment by Psychokiller1888** [comment]
I don't understand.... The issue is not about that, the issue is about the fact, that if a moveable if nested, and I try to move it, it all happily jumps to 0x0. I'm changing to destroys instead of target null, to see what it changes, no problem

**Comment by Psychokiller1888** [comment]
@daybrush Does exactly the same:
https://puu.sh/GWe0x.gif

**Comment by Psychokiller1888** [comment]
@daybrush 

Maybe this helps understanding the issue? I added a log about the dragging. See how everything's fine, up until the point I try to move the freshly nested element:

https://puu.sh/GWeaV.gif

**Comment by Psychokiller1888** [comment]
@daybrush 

Can you please explain what these `containers` are:

`this.moveable = new Moveable(container, options)` => container??
`container in options` => container??
`rootContainer in options` => rootContainer??

I just don't get it right and I can't find an understandable explanation in the doc as the one is too elusive

**Comment by Psychokiller1888** [comment]
I got it to jump only to the parent container  now... And it's very very interesting.... The move corresponds to the width the height of the moveable....

Check this one out https://puu.sh/GWyR8.gif

**Comment by Psychokiller1888** [comment]
Ok, got it working, the bounds were making a mess, as well as my not understanding of the different definitions of "container"

**Comment by daybrush** [comment]
@Psychokiller1888 
```js

new Moveable(container, { // <-
    container: // <-
});

```
These two containers are the same.

The container is the location where the moveable element is appended.
It is calculated differently depending on the container.

**Comment by daybrush** [comment]
@Psychokiller1888 

Don't use the container option.

If the container is set differently, the calculation becomes strange.
