### ISSUE TITLE
Events on children of Moveable not working

### ISSUE THREAD

**Issue by random-42** [daybrush/moveable#38]
I have Moveables on the page but would like their children elements to be able to have their own events and triggers. And bubble a prevent up to the Moveable instance so that the container is moveable but the elements with their own drag triggers prevent the moveable from triggering. But nothing triggers.

Pseudocode:

<MoveableTarget
    <Child
        draggable={true}
        onDragStart={ this.handleDragStart } -- does not trigger
        onDrag={ this.handleDrag } -- does not trigger
    
<Moveable
    target={this.moveableTarget.current}

**Comment by random-42** [comment]
It took a while to realise you're not using the React events, not mouse/touch events from your other code in @daybrush/drag. So @daybrush/drag was binding directly to the element from the DOM preventing the React events top trigger. Changing my code to use standard addEventListener and stopPropagation worked.

**Comment by daybrush** [comment]
@random-42 

Thank you for reporting bug.

I'll check it.

Maybe I'll give you a new option.

I added an event to the real target. But for the same reason as you, I will give you the option to add events to Moveable.

**Comment by daybrush** [comment]
@RicardoLimaDev 
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

React code is as follows.

```tsx
<Moveable dragArea={true} />
```
Thank you :)

**Comment by daybrush** [comment]
@random-42  
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

React code is as follows.

```tsx
<Moveable dragArea={true} />
```
Thank you :)
