### ISSUE TITLE
The SnapDigit style was wrong when setting zoom

### ISSUE THREAD

**Issue by tianyuya** [daybrush/moveable#380]
## Environments
* Framework name: 
* Framework version:  
* Moveable Component version: 0.21.1
* Testable Address(optional):  https://codesandbox.io/s/vue-demo-mnmqk?file=/src/views/Home.vue

## Description

I want the Moveable Container to still show its normal size when it scales，So I added `style="transform: scale(0.5)"` to the Container and set` moveable.zoom =2`，But SnapDigit styles show some problems when moving，I hope to solve this problem, or there are other solutions
![image](https://user-images.githubusercontent.com/6645546/102606236-6958ea00-4161-11eb-9c9e-73a3ea79f781.png)

`style="transform: scale(2)"` and  ` moveable.zoom =.5` , SnapDigit should be a normal size

![image](https://user-images.githubusercontent.com/6645546/102606627-fa2fc580-4161-11eb-911e-4e9630c3ca01.png)

**Comment by tianyuya** [comment]
hi,When I upgraded to 0.22.0, moving the box will report an error, but I'm fine with 0.21.1，I don't know what to do
![image](https://user-images.githubusercontent.com/6645546/103478619-e8f1e480-4e02-11eb-949f-5ef74f124a89.png)
[https://codesandbox.io/s/vue-demo-mnmqk?file=/src/views/Home.vue](url)

**Comment by daybrush** [comment]
@tianyuya 


moveable 0.22.1 is released.

Check it again.

**Comment by tianyuya** [comment]
> @tianyuya
> 
> moveable 0.22.1 is released.
> 
> Check it again.

thank you
