### ISSUE TITLE
[feature request] Pass custom controls components as props and share controls handlers via moveable ref or pass them to the custom components

### ISSUE THREAD

**Issue by zaqqaz** [daybrush/moveable#382]
In order to provide more flexibility we may consider have a way passing custom controls components to moveable (we can omit this feature for vanila js implementation or pass either dom node element or selector )

Styling with css it's ok, but not really enough when we want show additional content (like text or icons in the control... or maybe tooltip) plus in some cases we may want to show some extra controls on click/hover or any other event and devs will be able to handle that as part of their component.

And in addition to that I think it worth to share controls handlers via moveable ref (or pass them to our custom controllers?) in this case we will be able to attach them to specific parts of our controller and implement custom positioned controls, like for rotation in this example: 

https://user-images.githubusercontent.com/2823336/102825892-c3231380-43f0-11eb-8dc4-63fb46fb91fd.mov

@daybrush what do you think ? 🙂

**Comment by daybrush** [comment]
@zaqqaz 

You can make custom ables(controls)

https://daybrush.com/moveable/storybook/?path=/story/make-custom-able--editable-with-buttons

And you can set rotation target 
```js

<Moveable
 rotataionTarget={".direction-controls"}


/>

**Comment by Statfine** [comment]
> @zaqqaz
> 
> You can make custom ables(controls)
> 
> https://daybrush.com/moveable/storybook/?path=/story/make-custom-able--editable-with-buttons
> 
> And you can set rotation target
> 
> ```js
> <Moveable
>  rotataionTarget={".direction-controls"}
> 
> 
> />
> ```
use rotationTarget not rotataionTarget
