### ISSUE TITLE
Uncaught TypeError: Cannot read property 'move' of null

### ISSUE THREAD

**Issue by richardsolomou** [daybrush/moveable#383]
## Environments
* Framework name: React
* Framework version: 17
* Moveable Component version: react-moveable v0.25.0
* Testable Address(optional): https://codesandbox.io/s/react-moveable-move-of-null-z1phh

## Description
I want to dynamically change the `target` when rotating so that I can target a child of the original target. When `onRotate` fires, it crashes the app and shows this error:

![image](https://user-images.githubusercontent.com/2622273/102977246-65cfb500-450b-11eb-9860-3eebfda7d1d4.png)

I've added a minimum-reproducable codesandbox above. Any ideas what could be going on?

**Comment by daybrush** [comment]
@richardsolomou 


Sorry, but don't change the target after starting to rotate.
