### ISSUE TITLE
auto scrolling (feature request)

### ISSUE THREAD

**Issue by comiewcom** [daybrush/moveable#39]
Hello.
I have a feature request.

[auto scroll]
If the pointer crosses the edge of the container while dragging, scroll automatically.

I would be happy if you could consider it.

**Comment by daybrush** [comment]
@comiewcom 
Thank you for your feature request.

I'll consider that function.

**Comment by daybrush** [comment]
@comiewcom 

moveable 0.10.0 is released

Add scrollabe props, other scrollable props, scrollable events

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-scrollable

Thank you :)
