### ISSUE TITLE
How can I change the state of ngx-moveable

### ISSUE THREAD

**Issue by huanghuadong527** [daybrush/moveable#394]
## Environments
* Framework name: angular
* Framework version: 11.0.3
* Moveable Component version: ngx-selecto@1.10.1 ngx-moveable@0.18.1
* Testable Address(optional):

## Description

![image](https://user-images.githubusercontent.com/22953694/103862671-80548180-50fa-11eb-8386-240d11f6742a.png)
Hi, How can I change the state of ngx-moveable like losing focus

**Comment by ilyes24** [comment]
@huanghuadong527 

I'm just new to using this library but I think you can solve this by removing this element from the `targets` array.

If you can provide us with your code we may help you better

**Comment by daybrush** [comment]
set [target]="null" or [target]="[]"

You probably set the targets to an empty array to lose focus.

**Comment by huanghuadong527** [comment]
Yes, I set target="[]", but if I lose focus, the selection again will not be selected and I have to click on the non-target area to select again
![image](https://user-images.githubusercontent.com/22953694/103960594-7760c000-518d-11eb-9dd7-233beab32d1a.png)
![image](https://user-images.githubusercontent.com/22953694/103960608-8182be80-518d-11eb-8583-ce4cc9260328.png)
![image](https://user-images.githubusercontent.com/22953694/103960797-f9e97f80-518d-11eb-9568-ba3049a8a7f1.png)

**Comment by daybrush** [comment]
@huanghuadong527 


call this.selecto.setSelectedTargets([]);

**Comment by huanghuadong527** [comment]
There are no setSelectedTargets on ngxSelectoComponent。

(this.selecto as any).setSelectedTargets([]);

I tried this, but it still doesn't work, and after this call, clicking on the non-target area won't make the target lose focus, is there a problem with my dependency

**Comment by huanghuadong527** [comment]
The moveable component is used in conjunction with the angular-gridster2 component, and this call is needed in many places
![image](https://user-images.githubusercontent.com/22953694/103968049-2efdce00-519e-11eb-8215-54c9be391515.png)

**Comment by daybrush** [comment]
@huanghuadong527 

See
https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--change-the-moveable-targets-by-selecting-it

**Comment by huanghuadong527** [comment]
Yes, I did follow this example, but [target]="[]" doesn't quite do the trick

**Comment by daybrush** [comment]
@huanghuadong527 

Sorry. It's type error. ngx-selecto 1.10.3 is published.

```js
this.selecto.setSelectedTargets([]);
this.targets = [];
```

https://codesandbox.io/s/festive-brook-x3u0o?file=/src/app/app.component.ts

**Comment by huanghuadong527** [comment]
Thank you. That's all right
