### ISSUE TITLE
Add ability to pass extra className with elementGuidelines when using snappable

### ISSUE THREAD

**Issue by nelsondude** [daybrush/moveable#397]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

It would be great if when passing elementGuidelines, there was an additional field in `ElementGuidelineValue` of the type: `customClassName?: string` what would append this className to any snappable element line that is associated with the element that was snapped to in the array. For example, if i passed `elementGuidelines = [{element: document.querySelector('.el'), customClassName: 'myelClass'}]`, if a component was snapping to that element, the snappable lines associated with it would have the class `myelClass` appended. This would make it so that they would be easier to style with css. I'd like to style certain elementGuidelines differently based on the components that are snapping but currently I'm unable to do so

**Comment by daybrush** [comment]
@nelsondude 

* `moveable` 0.23.0
* `react-moveable` 0.26.0
* `preact-moveable` 0.25.0
* `ngx-moveable` 0.19.0
* `svelte-moveable` 0.14.0

`className` is added in elementGuidelines


```
elementGuidelines=[{ element, className: "aaa" }]
```

**Comment by tianyuya** [comment]
> @nelsondude
> 
> * `moveable` 0.23.0
> * `react-moveable` 0.26.0
> * `preact-moveable` 0.25.0
> * `ngx-moveable` 0.19.0
> * `svelte-moveable` 0.14.0
> 
> `className` is added in elementGuidelines
> 
> ```
> elementGuidelines=[{ element, className: "aaa" }]
> ```

This feature caused another bug, that expired when I reset ElementGuidelines , I went back to the previous version, the example also seems to be broken(Click blank, and then click the Target element),https://daybrush.com/moveable/storybook/?path=/story/use-snap-bounds-with-ables--snap-guidelines-elements
