### ISSUE TITLE
Init svg elements round origin in element center

### ISSUE THREAD

**Issue by ilyes24** [daybrush/moveable#399]
## Environments
* Framework name: Angular
* Framework version: 8.2.14
* Moveable Component version: ngx-moveable 0.18.3

## Description
SVG Elements origin point needs to be set on the element center so it can be rounded easily.

Is there any method to set the origin automatically in the element center (how to calculate that center with viewBox)

**Comment by daybrush** [comment]
@ilyes24 

You have to save both the translate value and the rotate value.

And you need to set both translate rotate in transform.

**Comment by daybrush** [comment]
@ilyes24 


It is not the role of a moveable that initializes the origin of the children of svg. I'm sorry.

**Comment by AlexandrBerlin** [comment]
https://codesandbox.io/s/react-moveable-svg-test-forked-ctg42?file=/src/index.tsx:83-97

How i can set origin point in the center of figure? Can't find any methods :(   it's all SVG.

**Comment by AlexandrBerlin** [comment]
> @ilyes24
> 
> It is not the role of a moveable that initializes the origin of the children of svg. I'm sorry.

Help!

**Comment by GreatAuk** [comment]
@AlexandrBerlin https://stackoverflow.com/a/58805105/6880617
