### ISSUE TITLE
Connecting two objects

### ISSUE THREAD

**Issue by kethan** [daybrush/moveable#4]
How to connect or link two objects? For example rete.js.org

**Comment by daybrush** [comment]
@kethan 
Hi. First of all, thank you for question.
But, i don't know what you mean.

Did you mean the group?

**Comment by kethan** [comment]
I mean having link to two objects

**Comment by daybrush** [comment]
@kethan 

Do you think link is like this?
https://codepen.io/daybrush/pen/pMeMxP

**Comment by kethan** [comment]
Thanks for your efforts. I actually meant like this.
https://codepen.io/Ni55aN/pen/xzgQYq

Check number - > number connection

**Comment by monsterooo** [comment]
@daybrush 

Can I combine multiple elements for dragging?

I made a patch method

![image](https://user-images.githubusercontent.com/18432680/62536522-beec6980-b880-11e9-9d46-ea7cef2e6d3d.png)


I have a moveable nested inside element A and element B.

When I manipulate the moveable, I change the element A and the element B.

If you can provide a combined parameter, I think that's awesome.

**Comment by daybrush** [comment]
@mosterooo
I think that's a group function.

Maybe I'll try to make it this week or next week.

@kethan 
Is that what you think is the same as that?

> @daybrush
> 
> Can I combine multiple elements for dragging?
> 
> I made a patch method
> 
> ![image](https://user-images.githubusercontent.com/18432680/62536522-beec6980-b880-11e9-9d46-ea7cef2e6d3d.png)
> 
> I have a moveable nested inside element A and element B.
> 
> When I manipulate the moveable, I change the element A and the element B.
> 
> If you can provide a combined parameter, I think that's awesome.

**Comment by kethan** [comment]
No. I wanted to create a curve to connect two objects.

**Comment by daybrush** [comment]
Perhaps the function of providing a line connecting two objects is not possible.
However, you can know the position using drag.
```js
let left1 = 0;
let top1 = 0;
let left2 = 0;
let top2 = 0;

this.moveable1.on("drag", ({ left, top }) => {
    left1 = left;
    top1 = top;
    link(left1, top1, left2, top2);
});
this.moveable2.on("drag", ({ left, top }) => {
    left2 = left;
    top2 = top;
    link(left1, top1, left2, top2);
});
``

**Comment by geoffbullen** [comment]
Hi @kethan did you end up getting this working?

**Comment by kethan** [comment]
Now
