### ISSUE TITLE
Rotation handle position

### ISSUE THREAD

**Issue by lukrak** [daybrush/moveable#40]
Hi,

I assume there's currently no way to have a rotation handle on the bottom instead of the top ? At least I can't find a way. Would you be able to add this feature later on ?

**Comment by daybrush** [comment]
@lukrak 
Thank you for your feature request.

I'll consider that function.

**Comment by lukrak** [comment]
Thank you for adding this feature to 0.9.0 . Is there an estimate date of 0.9.0 release as this functionality is really important to us ?

**Comment by daybrush** [comment]
@lukrak 

It will probably be released on September 28th.

**Comment by daybrush** [comment]
@lukrak 
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

React code is as follows.

```tsx
<Moveable rotationPosition="bottom"/>
```
Thank you :)

**Comment by lukrak** [comment]
Fabulous. Just gave it a try and it works perfect. Appreciated ! :)
