### ISSUE TITLE
drag bug ?

### ISSUE THREAD

**Issue by GreatAuk** [daybrush/moveable#402]
## Environments
* Framework name: React
* Framework version: 16.12.0
* Moveable Component version: "react-moveable": "^0.25.0"
* Testable Address(optional):

## Description
I need wrap moveable target in a Wrap Component to do something. First time, when I mousedown -> mouseup -> mousemove, moveable target can be drag（It should not be, because mouse is up）. after this time, everything is working fine
This is [Reproduce](https://codesandbox.io/s/moveablejs-bug-miwil?file=/src/App.tsx)

**Comment by daybrush** [comment]
```js
  const mousedown = (e: React.MouseEvent, nextTarget: HTMLDivElement | null) => {
    if (target !== nextTarget) {
      console.log(target);
      setTarget(nextTarget!);
      setTimeout(() => {
        moveableRef.current.dragStart(e.nativeEvent);
      }, 100);
    }
  };
```

**Comment by GreatAuk** [comment]
@daybrush Thank you for your reply, It is still reproduce,  very fast click(mousedown -> mouseup ) -> mousemove, moveable target can be drag（It should not be, because mouse is up）

**Comment by daybrush** [comment]
@GreatAuk 

This is because setTimeout is called later than mouseup.

**Comment by GreatAuk** [comment]
@daybrush Thank you for you reply, this solution seems ok. https://codesandbox.io/s/moveablejs-bug-miwil?file=/src/App.tsx

**Comment by GreatAuk** [comment]
By the way, It's a awesome project

**Comment by mamsoudi** [comment]
@daybrush I am in a similar situation where the target moves from one container to another and we'd have to remove the target dom element before adding it to the other page. This approach works perfectly fine for a single selection but for groups of items, for some reason, calling `event.currentTarget.dragStart(event.inputEvent)` doesn't work. The removal and the `dragStart` all happen in a sequence inside `on('drag')`. Any idea on how to make it possible?

![selection](https://user-images.githubusercontent.com/8385009/127301204-ae4bdd89-e431-4336-a8ed-2c3dd1b68a81.gif)

**Comment by SidIcarus** [comment]
@mamsoudi 
Did you have any luck figuring out how to do that?
