### ISSUE TITLE
updating elementGuidelines during drag not working

### ISSUE THREAD

**Issue by adl-g** [daybrush/moveable#404]
## Environments
* Framework name: Vanilla
* Moveable Component version: 0.22.3
* Testable Address(optional): [codesandbox](https://codesandbox.io/s/moveable-update-elementguidelines-777l1?file=/src/index.js)

## Description
I'm trying to update `elementGuidelines` during drag so the dragged element will snap to other elements than the elements that was defined in `Moveable` constructor, but is it not working.
I tried also to set `elementGuidelines` with the `refresh` option but it did not work.

**Comment by daybrush** [comment]
@adl-g 

* `moveable` 0.23.0
* `react-moveable` 0.26.0
* `preact-moveable` 0.25.0
* `ngx-moveable` 0.19.0
* `svelte-moveable` 0.14.0

moveable's new version is released. Try it again.

**Comment by adl-g** [comment]
It's working, thanks!

**Comment by fwh1990** [comment]
This problem still happened at `react-moveable@0.26.1`. 
```html
<Wrapper style={{ transform: `translate() scale()` }}>
  <Moveable />
  <Moveable />
  <Moveable />
</Wrapper>
```
When I change the scale or translate of outside wrapper, the guidelines disappear. Now I have to downgrade to version `0.25.x`.

**Comment by fwh1990** [comment]
> This problem still happened at `react-moveable@0.26.1`.
> 
> ```
> <Wrapper style={{ transform: `translate() scale()` }}>
>   <Moveable />
>   <Moveable />
>   <Moveable />
> </Wrapper>
> ```
> 
> When I change the scale or translate of outside wrapper, all guidelines disappear. Now I have to downgrade to version `0.25.x`.

Maybe worse. The guidelines only appear once without any other operation (react-moveable@0.26.1)

**Comment by znlbwo** [comment]
## Environments
* Framework name: Vue
* Framework version: 2.26.0
* Moveable Component version: 0.23.0
* Testable Address(optional): https://codesandbox.io/s/moveable-issue-411-75zh5?file=/package.json

## Description
I also encountered the same problem. 
When dragging the same element multiple times, elementGuidelines only appear the first time.

**Comment by daybrush** [comment]
@fwh1990 


react-moveable 0.26.2-rc beta version is released. Check it again.
Thank you :)


@znlbwo 

I will release it after testing in react.

**Comment by fwh1990** [comment]
> react-moveable 0.26.2-rc beta version is released. Check it again.

@daybrush  Hi there, It seem that this version is unavailable to install?

**Comment by daybrush** [comment]
@fwh1990 

Oh sorry. I was mistaken. Try again

**Comment by daybrush** [comment]
@fwh1990  @znlbwo 

* `moveable` 0.23.1
* `react-moveable` 0.26.2
* `preact-moveable` 0.25.2
* `ngx-moveable` 0.19.1
* `svelte-moveable` 0.14.1
* 
moveable's new version is released. Check it again.
