### ISSUE TITLE
control-box misplaced when the selected element is a <g>

### ISSUE THREAD

**Issue by ilyes24** [daybrush/moveable#407]
## Environments
* Framework name: Angular
* Framework version:  8.2.14
* Moveable Component version: ngx-moveable 0.18.3

## Description
@daybrush 
after the update on #390 the elements on `SVG` are great surrounded by the control-box but when using `g` elements the `control-box` is placed in `(0,0)`.

you have updated only `react-moveable` i think to fix this one.

![image](https://user-images.githubusercontent.com/17337220/105707438-3b5e8680-5f13-11eb-9bbe-c661c01651fe.png)

**Comment by daybrush** [comment]
@ilyes24 

Sorry, react hasn't been updated yet. It will be updated by tomorrow.

**Comment by ilyes24** [comment]
No, I'm using `ngx-moveable` (ANGULAR) and I found that you have updated only `react-moveable`.

Thank you very much for your effort.

**Comment by daybrush** [comment]
@ilyes24 

Oh, the react code has been fixed, but it has not been released yet.  Thank you

**Comment by ilyes24** [comment]
@daybrush 

Can you please try to fix it in ngx-moveable also?

**Comment by daybrush** [comment]
@ilyes24 

ngx-moveable can be updated only when react-moveable is released. The reason is that ngx-moveable has a dependency on react-moveable.

**Comment by daybrush** [comment]
@ilyes24 

`ngx-moveable`@0.19.0 is released. Check it again.

**Comment by ilyes24** [comment]
@daybrush 

It works great, YOU'RE THE BEST.
