### ISSUE TITLE
Resizable, Scalable north and west controls want to behave like sketches and illustrators.

### ISSUE THREAD

**Issue by daybrush** [daybrush/moveable#41]
Resizable, Scalable north and west controls want to behave like sketches and illustrators.

You can have one more drag event in the resize event.

**Comment by daybrush** [comment]
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-resizable

```ts
import Moveable from "moveable";

const moveable = new Moveable(document.body, {
    target: document.querySelector(".target"),
    resizable: true,
});

const frame = {
    translate: [0, 0],
};
moveable.on("resizeStart", ({ set, setOrigin, dragStart }) => {
    // Set origin if transform-orgin use %.
    setOrigin(["%", "%"]);

    // If cssSize and offsetSize are different, set cssSize. (no box-sizing)
    const style = window.getComputedStyle(ev.target);
    const cssWidth = parseFloat(style.width);
    const cssHeight = parseFloat(style.height);
    set([cssWidth, cssHeight]);

    // If a drag event has already occurred, there is no dragStart.
    dragStart && dragStart.set(frame.translate);
}).on("resize", ({ target, width, height, drag }) => {
    target.style.width = `${width}px`;
    target.style.height = `${height}px`;

    // get drag event
    frame.translate = drag.beforeTranslate;
    target.style.transform
        = `translate(${drag.beforeTranslate[0]}px, ${drag.beforeTranslate[1]}px)`;
}).on("resizeEnd", ({ target, isDrag, clientX, clientY }) => {
    console.log("onResizeEnd", target, isDrag);
});
```

**Comment by LCGijs** [comment]
This is not yet implemented for `scale` right?

**Comment by daybrush** [comment]
@LCGijs 

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#scalable

```ts
import Moveable from "moveable";

const moveable = new Moveable(document.body, {
    target: document.querySelector(".target"),
    scalable: true,
    throttleScale: 0,
    keepRatio: false,
});

const frame = {
    translate: [0, 0],
    scale: [1, 1],
};
moveable.on("scaleStart", ({ set, dragStart }) => {
    set(frame.scale);

    // If a drag event has already occurred, there is no dragStart.
    dragStart && dragStart.set(frame.translate);
}).on("scale", ({ target, scale, drag }) => {
    frame.scale = scale;
    // get drag event
    frame.translate = drag.beforeTranslate;
    target.style.transform
        = `translate(${drag.beforeTranslate[0]}px, ${drag.beforeTranslate[1]}px)`
        + `scale(${scale[0]}, ${scale[1]})`;
}).on("scaleEnd", ({ target, isDrag, clientX, clientY }) => {
    console.log("onScaleEnd", target, isDrag);
});

```

**Comment by outOFFspace** [comment]
@daybrush, resize doesn't work when an element is rotated. I wonder how does it works in a demo, but not in the example section.

**Comment by daybrush** [comment]
@outOFFspace 
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-resizable
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-rotatable

Following the example in the handbook looks like the following link:
https://codepen.io/daybrush/pen/XWWdeZX?editors=1010

**Comment by LCGijs** [comment]
> @LCGijs
> 
> https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#scalable
> 
> ```ts
> import Moveable from "moveable";
> 
> const moveable = new Moveable(document.body, {
>     target: document.querySelector(".target"),
>     scalable: true,
>     throttleScale: 0,
>     keepRatio: false,
> });
> 
> const frame = {
>     translate: [0, 0],
>     scale: [1, 1],
> };
> moveable.on("scaleStart", ({ set, dragStart }) => {
>     set(frame.scale);
> 
>     // If a drag event has already occurred, there is no dragStart.
>     dragStart && dragStart.set(frame.translate);
> }).on("scale", ({ target, scale, drag }) => {
>     frame.scale = scale;
>     // get drag event
>     frame.translate = drag.beforeTranslate;
>     target.style.transform
>         = `translate(${drag.beforeTranslate[0]}px, ${drag.beforeTranslate[1]}px)`
>         + `scale(${scale[0]}, ${scale[1]})`;
> }).on("scaleEnd", ({ target, isDrag, clientX, clientY }) => {
>     console.log("onScaleEnd", target, isDrag);
> });
> ```

You mentioned that the above code enables **scaling** controls like they are implemented in Sketch and Illustrator, however in my case it still scales from the center. Am I missing something?

**Comment by daybrush** [comment]
@LCGijs 

Well I don't know unless I see your code
I've copied the codepen in the same way and it seems to be working fine.

https://codepen.io/daybrush/pen/QWWVZdR

**Comment by LCGijs** [comment]
Sorry, it seems like the absence of `frame.translate = drag.beforeTranslate;` was the cause of the problem. It now seems to be correctly working.

Thank you for your help.

**Comment by LCGijs** [comment]
Hey, I've implemented scaleGroup as documented in your handbook:

```js  
  const handleScaleGroup = ({ events }) => {
        events.forEach(({ target, scale, drag }, i) => {
            const frame = windows[i];

            frame.scale = scale;

            // get drag event
            frame.translate = drag.beforeTranslate;
            target.style.transform
                = `translate(${drag.beforeTranslate[0]}px, ${drag.beforeTranslate[1]}px) `
                + `scale(${scale[0]}, ${scale[1]})`
                + `rotate(${frame.rotate}deg)`;
        });
    };
```

However, the behaviour of scaling is not as aspected. It does not seem like the behaviour as in Sketch. I've included a gif to show the current behaviour.

![Peek 2019-12-05 14-31](https://user-images.githubusercontent.com/55280200/70239732-1ede1880-176c-11ea-9a59-9b809a2bba33.gif)

When increasing the height of the group, the width also changes. This problem does not occur for scale events with only one element selected.

![Peek 2019-12-05 14-35](https://user-images.githubusercontent.com/55280200/70239944-9449e900-176c-11ea-9841-6094105bc38f.gif)

Scale of single elements is implemented in this way:

```js
    const handleScale = ({ target, scale, drag }) => {
        const frame = windows[0];

        frame.scale = scale;
        // get drag event
        frame.translate = drag.beforeTranslate;
        target.style.transform
            = `translate(${frame.translate[0]}px, ${frame.translate[1]}px) `
            + `scale(${scale[0]}, ${scale[1]})`
            + `rotate(${frame.rotate}deg)`;
    };
```

Thank you for your awesome package, and thanks in advance for your help!
