### ISSUE TITLE
Can we update the elementGuidelines dynamically?

### ISSUE THREAD

**Issue by znlbwo** [daybrush/moveable#411]
## Environments
* Framework name: vue
* Framework version: 2.6.11
* Moveable Component version: 0.20.0
* Testable Address(optional):

## Description

About elementGuidelines.
I want update elementGuidelines when drag.

![image](https://user-images.githubusercontent.com/8335856/106441547-23f44000-64b5-11eb-8aa7-58eb3afca11e.png)
*Unsupported gif*

The elementGuidelines is "1", "2", "3", "4", "5" elements when start move "移动" element.
Update the elementGuidelines to "6", "7", "8", "9" elements when move "移动" element to top.
But no guidelines are shown.

Can we update the elementGuidelines dynamically?

**Comment by daybrush** [comment]
@znlbwo 

update moveable's new version. Real-time update is supported in 0.23.0.

**Comment by znlbwo** [comment]
@daybrush 

I will try update and  read the release document first. thx.
