### ISSUE TITLE
clippable demo

### ISSUE THREAD

**Issue by iprasadg** [daybrush/moveable#412]
## Environments
* Framework name: Angular
* Framework version:
* Moveable Component version:
* Testable Address(optional): https://codesandbox.io/s/rr12j

## Description
Above mentioned testable address is taken from your storybook, I am working on clippable but here in your demo you have used e (event) as follows

onClip({ clipType, clipStyle }) {
        if (e.clipType === "rect") {
            e.target.style.clip = e.clipStyle;
        } else {
            e.target.style.clipPath = e.clipStyle;
        }
        this.frame.clipStyle = e.clipStyle;
    }

Here e is never defined, and even though after defining e, clippable is not working

**Comment by daybrush** [comment]
@iprasadg 

Thank you. Demo fixes were done.
