### ISSUE TITLE
Origin of translate and scale at the center of the element.

### ISSUE THREAD

**Issue by alejandromizraji** [daybrush/moveable#414]
## Environments
* Framework name: reactjs
* Framework version: 17
* Moveable Component version: 0.26.1
* Testable Address(optional):

## Description
Hi, I need position and scale to happen around the center origin just like the rotation and not the top left. Is there any possibility to do that?

I tried to fix it by summing or subtracting the width and height of the element divided by 2 and apply that in the transform. It works for the drag part but it gets shaky when I resize.

is there any solution you can think of?

Thank you! Amazing library by the way.

**Comment by daybrush** [comment]
@alejandromizraji 

Yes. use `setFixedDirection` on `onScaleStart`


https://codesandbox.io/s/react-moveable-setfixeddirection-foq5u

**Comment by alejandromizraji** [comment]
Thank you!!
