### ISSUE TITLE
Snap guideline disappear after left changed

### ISSUE THREAD

**Issue by peter-jerry-ye** [daybrush/moveable#415]
## Environments
* Framework name: React
* Framework version: 17.0.1
* Moveable Component version: 0.26.1
* Testable Address(optional): https://codesandbox.io/s/snappable-3y8ir?file=/src/App.tsx

## Description

Hello,

I use a state to control the position of the rectangle. After the rectangle is dragged, I'll update the position. However, after the position is updated, the snap guideline no longer appears. I've tried updateRect and updateTarget and had no luck.

**Comment by peter-jerry-ye** [comment]
Appeared in 0.26.1. 0.25.2 is not affected.

**Comment by daybrush** [comment]
@peter-jerry-ye 

react-moveable 0.26.2-rc beta version is released. Check it again.
Thank you :)

**Comment by peter-jerry-ye** [comment]
> @peter-jerry-ye
> 
> react-moveable 0.26.2-rc beta version is released. Check it again.
> Thank you :)

Sorry, but how should I test 0.26.2-rc beta since it is not published on npm?

**Comment by daybrush** [comment]
@peter-jerry-ye 

Oh sorry. I was mistaken. Try again

**Comment by peter-jerry-ye** [comment]
> @peter-jerry-ye
> 
> Oh sorry. I was mistaken. Try again

I tried in codesandbox and it is fixed. Thank you.
