### ISSUE TITLE
elementGuidelines gone after snapped once?

### ISSUE THREAD

**Issue by xwraithin** [daybrush/moveable#416]
## Environments
* Framework name: Svelte
* Framework version: 3.32.1
* Moveable Component version: 0.23.0 (svelte-movable @ 0.14.0)
* [CodePen Showcase (Vanilla)](https://codepen.io/wraithin/pen/LYbRpYx)
## Description
Hello folks, this is my very first question/issue post on github, bear with me when I did something wrong.

**Current Behaviour**
After Box2 has been snapped to Box1 it's not possible anymore to do it again.
**Wanted behaviour**
Being able to move Box2 around as often as wanted and being able to snap it everytime to Box1 back again.

I've searched the API for some reset behaviours but couldn't find anything related to it, is this behaviour as intended?

P.S Couldn't find the option to tag this as "question" :x

**Comment by daybrush** [comment]
@xwraithin 

* `moveable` 0.23.1
* `react-moveable` 0.26.2
* `preact-moveable` 0.25.2
* `ngx-moveable` 0.19.1
* `svelte-moveable` 0.14.1

moveables's new version is released. Check it again.
