### ISSUE TITLE
Position in custom-able

### ISSUE THREAD

**Issue by peter-jerry-ye** [daybrush/moveable#417]
Can we get the translation value through `MoveableManagerInterface` please? I tried `state.beforeMatrix` with `left` and `top`, but it seems that they are rounded, so the value I got by doing calculations does not reflect the real position.

**Comment by daybrush** [comment]
@peter-jerry-ye 

The left and top of the state are the positions of the moveable-control-box.


Use moveable.getRect() for the left and top of the target.

**Comment by peter-jerry-ye** [comment]
The problem is that the 'left' and 'top' is not the real 'left' and 'top'. For example, if I have a box with `position:relative; left: 100px; right: 100px`, and then I have a box inside it with `position: absolute; left: 100px; right: 100px;`, then the left and top will be 200px.

**Comment by daybrush** [comment]
@peter-jerry-ye 

I'm sorry. Target's relative left and top values are not provided. It must be obtained through getComputedStyle or offsetLeft, offsetTop.

In moveable, getRect(), left, and top are values that can be obtained based on container. So it is similar to getBoundingClientRect.

**Comment by peter-jerry-ye** [comment]
Ok, thank you for the clarification.
