### ISSUE TITLE
Moveable under zoom might have floating point

### ISSUE THREAD

**Issue by peter-jerry-ye** [daybrush/moveable#418]
## Environments
* Framework name: React
* Framework version:
* Moveable Component version: react-moveable 0.26.2
* Testable Address(optional): https://codesandbox.io/s/moveable-under-zoom-x5lxc

## Description

When the parent is zoomed, moveable will give floating point number instead of integer (normal behavior when scale = 1). Not sure if this is expected or not.

**Comment by daybrush** [comment]
@peter-jerry-ye 

The browser rounds the decimal point. There is no rounding process in moveable.

And if you use translate and then use left and top at the end, of course there will be a difference.

**Comment by peter-jerry-ye** [comment]
So it's the browser behavior. Thanks.
