### ISSUE TITLE
Is it possible to hide every selected target control-box and show single control-box for all targets?

### ISSUE THREAD

**Issue by vasylHordynskyy** [daybrush/moveable#419]
## Environments
* Framework name: React
* Framework version: 17.0.1
* Moveable Component version: 0.26.2
* Testable Address(optional):

## Description
First of all thanks for the great library. 
In moveable component when selected more then one target then every control has hisown control-box and general control-box for selected targets. My question is: Is it possible to hide every selected target control-box and show single control-box for all targets?

**Comment by Fisujon** [comment]
@vasylHordynskyy How did you solve this?

**Comment by jadiagaurang** [comment]
Hi @vasylHordynskyy @Fisujon 

You should be able to achieve by using `hideChildMoveableDefaultLines` property!

Here is the example:
var $container = $(".container");  // jQuery Ref of the Container
MoveableRef = new Moveable($container[0], {
    target: $(".target").get(),   // Array of HTML Elements to get selected by Moveable!

    hideChildMoveableDefaultLines: true   // To toggle visualize all Elements within a Group!
});

**Comment by Fisujon** [comment]
@jadiagaurang Thanks for the prompt reply, It's working.

There is another question I would like to ask about moveable creates multiple moveable-control-box of itself.
#Issue: https://github.com/daybrush/moveable/issues/187.

The issue persists even after I tried the "vue3-moveable": "^0.26.1" and "moveable": "^0.51.1".

Thanks

**Comment by jadiagaurang** [comment]
@Fisujon You need to initialize the Moveable Object without any target (Empty Array).

```javascript
var $container = $(".container");  // jQuery Ref of the Container
var MoveableRef = new Moveable($container[0], {
    target: []
});
```
later you can use `target` to select multiple HTML Elements.

@daybrush has wrote a very useful library [Selecto](https://github.com/daybrush/selecto). It works very nicely to select multiple elements while keeping only one instance of the Moveable Object, which should make only one control-box in the DOM.

Here is an example where I have used both library to demonstrate Moveable + Selecto. https://codepen.io/jadiagaurang/pen/QWJyEaE

**Comment by Fisujon** [comment]
@jadiagaurang It appears that the codepen example has the same problem.

When I choose one element, it functions properly. However, when I select multiple elements, several moveable control boxes are generated. The official [demo](https://daybrush.com/moveable/) shows it working with just one moveable control box.

I have attached a video that shows the problem.
https://drive.google.com/file/d/1Uxb7th0CayfFBMy_fwfTdNHOGqPSqBZW/view?usp=sharing

I would greatly appreciate your help.

**Comment by jadiagaurang** [comment]
@Fisujon Got it. Well, in that case @daybrush should be able to answer or update the library to generate single control-box `DIV`.
