### ISSUE TITLE
global variable (b)

### ISSUE THREAD

**Issue by comiewcom** [daybrush/moveable#42]
Hello.
The following are global variables
Is this a specification?

window.b

<img width="296" alt="スクリーンショット 2019-09-20 21 24 25" src="https://user-images.githubusercontent.com/48230911/65326739-22421900-dbed-11e9-8cbf-d009916e58c8.png">

**Comment by daybrush** [comment]
@comiewcom 

Thank you for reporting bug.

I'll fix the bug. It will probably be released on September 28th.

Thank you :)

**Comment by daybrush** [comment]
@comiewcom 

`moveable` 0.9.0  is released. Please check again.
Thank you :)
