### ISSUE TITLE
A lot of types are not visible to typescript when using ngx-moveable as they are not part of the public api

### ISSUE THREAD

**Issue by zrajnai** [daybrush/moveable#427]
## Environments
* Framework name:
angular
* Framework version:
11.2.0
* Component name: 
ngx-moveable
* Component version:
0.19.0

## Description
There a lot of types are not visible to typescript when using ngx-moveable as they are not part of the public api.
The fix is to copy the declarations folder from react-moveable to ngx-moveable, and to append `export * from './declaration/types';` to the end of `public-api.d.ts`. This worked for me locally.

A workaround is to import the types from react-moveable directly:
`import { OnDrag, OnDragEnd, OnDragGroup, OnDragGroupEnd, OnDragGroupStart, OnDragStart } from 'react-moveable/declaration/types';` but this is kind of hacky.

**Comment by daybrush** [comment]
@zrajnai 

ngx-moveable 0.19.2 is released. Check it again.

**Comment by zrajnai** [comment]
Thanks for the quick turnaround, however it's not working :(
I get the following when trying to compile it:

An unhandled exception occurred: The target entry-point "ngx-moveable" has missing dependencies:
 - react-moveable/declaration/types
 
 This even happens when I change the path in public-api.d.ts  to be `../react-moveable/declaration/types` (with a leading ../ which seems to be the correct path.
 
 Perhaps the tsconfig.json file needs to have the `declarations` set to `true` for this project as well so it will have the types generated (and not have to depend on the react version's types)?

**Comment by daybrush** [comment]
@zrajnai 


ngx-moveable 0.19.3 is released. Check it again.

The dependency tree is as follows. All types are in react-moveable and have been inherited below.
`react-moveable > react-compat-moveable > moveable > ngx-moveable`

**Comment by zrajnai** [comment]
It works now.
Thanks!
