### ISSUE TITLE
Cannot assign to 'x' because it is a read-only property.

### ISSUE THREAD

**Issue by alejandromizraji** [daybrush/moveable#429]
## Environments
* Framework name: React
* Framework version: 17.0.1
* Moveable Component version: 0.23.1
* Testable Address(optional):

## Description

I'm having the following issue when trying to assign a property:

"Cannot assign to 'target' because it is a read-only property." it happens with every property.

Reproduce:

1. Create an app with create-react-app with typescript
2. Create a component
3. add useeffect

`useEffect(() => {
        const container = containerRef.current;
        if(container){
            const moveable = new Moveable(container, {
                target: [],
                draggable: true,
            })
            moveable.target = try to asign something
        }
    }, [])`

**Comment by daybrush** [comment]
@alejandromizraji 

* `moveable` 0.24.1
* `react-moveable` 0.27.0
* `preact-moveable` 0.26.0
* `ngx-moveable` 0.20.1
* `svelte-moveable` 0.15.1
* `lit-moveable` 0.1.1

moveable's new version is released.
