### ISSUE TITLE
Can not get delta x coordinate

### ISSUE THREAD

**Issue by whizsid** [daybrush/moveable#43]
https://github.com/daybrush/moveable/blob/a40caecd603c10f14555bc817b1f1452357c8591/packages/react-moveable/src/App.tsx#L209

This drag property is not defined in type definitions. 

```
export interface OnResize {
    target: HTMLElement | SVGElement;
    clientX: number;
    clientY: number;
    datas: IObject<any>;
    direction: number[];
    width: number;
    height: number;
    dist: number[];
    delta: number[];
    isPinch: boolean;
}
```

Can you add the `drag` property? Thank You for this great library.

**Comment by daybrush** [comment]
@whizsid 

The drag event with resizable will be deployed on the 28th of this week.

Thank you.

**Comment by whizsid** [comment]
Thank You for the quick reply!

**Comment by daybrush** [comment]
@whizsid 
`moveable` 0.9.0  is released. 
`react-moveable` 0.12.1  is released. 
`preact-moveable` 0.11.2  is released. 
`ngx-moveable` 0.5.1 is released. 

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#react--preact-example-1

Thank you :)
