### ISSUE TITLE
can't resize more than 100px if max-width/height set to 100%

### ISSUE THREAD

**Issue by thekhairul** [daybrush/moveable#430]
## Environments
* Framework name: Vanilla
* Framework version:
* Moveable Component version: 0.23.1
* Testable Address(optional):

## Description
The resizable module doesn't seem to be working for items that have 'max-width' or 'max-height' set to 100%. I can resize it down below 100px but can't scale it up more than 100px.

https://www.loom.com/share/ea4ad6ad9959441d82e3109ff437dd99

**Comment by daybrush** [comment]
@thekhairul 
* `moveable` 0.24.1
* `react-moveable` 0.27.0
* `preact-moveable` 0.26.0
* `ngx-moveable` 0.20.1
* `svelte-moveable` 0.15.1
* `lit-moveable` 0.1.1
moveable's new version is released. Check it again.

**Comment by thekhairul** [comment]
Ah. Works like a charm. Thanks a bunch for the quick fix :slightly_smiling_face:

**Comment by thekhairul** [comment]
Hey, found a new issue with the latest release (0.24.1). Resizable not working if the immediate parent of the target has 'display:flex' provided that the target is normally positioned element (not absolute/fixed)

**Comment by daybrush** [comment]
@thekhairul 

* `moveable` 0.24.3
* `react-moveable` 0.27.2
* `preact-moveable` 0.26.2
* `ngx-moveable` 0.20.3
* `svelte-moveable` 0.15.3
* `lit-moveable` 0.1.3
moveable's new version is released. Check it again.

**Comment by thekhairul** [comment]
Great ! everything's working fine. FYI: a console.log in 'dragControlStart' function

**Comment by daybrush** [comment]
@thekhairul 

* `moveable` 0.24.4
* `react-moveable` 0.27.4
* `preact-moveable` 0.26.3
* `ngx-moveable` 0.20.4
* `svelte-moveable` 0.15.4
* `lit-moveable` 0.1.4

Thank you :) i removed console.log.
