### ISSUE TITLE
groups request("resizable") TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by razr001** [daybrush/moveable#432]
## Environments
* Framework name: react
* Framework version: react 16.13
* Moveable Component version: react-moveable 0.27
* Testable Address(optional): https://codesandbox.io/s/damp-microservice-p47fu?file=/src/Moveable.jsx

## Description
if targets length > 1 call request("resizable") 
![image](https://user-images.githubusercontent.com/3770596/111096312-306ebc80-857a-11eb-8eb0-af26688c14cb.png)

**Comment by daybrush** [comment]
@razr001 
* `moveable` 0.24.2
* `react-moveable` 0.27.1
* `preact-moveable` 0.26.1
* `ngx-moveable` 0.20.2
* `svelte-moveable` 0.15.2
* `lit-moveable` 0.1.2

moveable's new version is released. Check it again.

**Comment by razr001** [comment]
Cool，it works now. 
Thanks!
