### ISSUE TITLE
Change Moveable control box to use translate3d for z-index support in Safari

### ISSUE THREAD

**Issue by robinslange** [daybrush/moveable#433]
Currently in Safari when using Moveable it applies 

`transform: translate(0px, 0px) translateZ(50px);` 

This creates a compatibility issue in Safari with z-indexes as described here: https://bucketpress.com/css-translate-and-z-index-problems-in-safari-browser

Ideal solution would be to have Moveable use translate3d instead of translate+translateZ to allow the setting of z-index to be respected in Safari.

**Comment by daybrush** [comment]
@robinslange 

* `moveable` 0.24.2
* `react-moveable` 0.27.1
* `preact-moveable` 0.26.1
* `ngx-moveable` 0.20.2
* `svelte-moveable` 0.15.2
* `lit-moveable` 0.1.2

moveable's new version is released. Check it again.
