### ISSUE TITLE
scrollable not work

### ISSUE THREAD

**Issue by gauseen** [daybrush/moveable#435]
```js
const moveable = new Moveable(document.body, {
  target: document.querySelector(".target"),
  resizable: true,
  scrollable: true, // not work
  scrollContainer: document.body,
  // scrollThreshold: 0,
  getScrollPosition: ({ scrollContainer }) => {
    console.log("scrollContainer: ", scrollContainer);

    return [scrollContainer.scrollLeft, scrollContainer.scrollTop];
  }
});
```

DEMO Link: https://codesandbox.io/s/moveable-32mfx?file=/index.html

## Description
https://codesandbox.io/s/moveable-32mfx?file=/index.html

**Comment by daybrush** [comment]
* `moveable` 0.24.5
* `react-moveable` 0.27.5
* `preact-moveable` 0.26.4
* `ngx-moveable` 0.20.5
* `svelte-moveable` 0.15.5
* `lit-moveable` 0.1.5


moveable's new version is released. Check it again. Thank you :)
