### ISSUE TITLE
How to use methods inside function based components. 

### ISSUE THREAD

**Issue by ma3ve** [daybrush/moveable#438]
## Environments
* Framework name: React
* Framework version: 17.0.1
* Moveable Component version: 5.0.2

## Description
How to use methods inside function based components.

**Comment by ma3ve** [comment]
sorry found it #192

**Comment by ma3ve** [comment]
If it is ok I can create a pr updating the docs for react .

**Comment by ma3ve** [comment]
If it is ok I can create a pr updating react docs and mention using methods in react.

**Comment by daybrush** [comment]
@ma3ve 
I thought the method of the API documentation would suffice and I could get the instance through ref.

If you write PR,  i'll check it.

Thank you :)

**Comment by ma3ve** [comment]
Sure. I will add a PR as soon as possible. Thanks.
