### ISSUE TITLE
Select area React demo

### ISSUE THREAD

**Issue by AlexanderNosenko** [daybrush/moveable#443]
## Environments
* Framework name: Movable
* Framework version: 0.24.5
* Moveable Component version: 0.24.5
* Testable Address(optional): -

## Description
Great library! So far i've used resizable and movable features and my experience was smooth.
Now i'm, trying to implement this element from the demo.
<img width="855" alt="Screenshot 2021-04-04 at 1 39 05 PM" src="https://user-images.githubusercontent.com/13070163/113507509-9a63fb80-9553-11eb-96bd-ed7103c84409.png">

I'm failing to find an example of a component which can be used to achieve this effect =(
If anybody knows how to do it, please comment bellow, your help would be much appreciated!

**Comment by daybrush** [comment]
@AlexanderNosenko 

I didn't understand what you were saying.

Do you want the feature to add new elements to the dragging area?

**Comment by tianyuya** [comment]
like this?
https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--select-moveable-targets-in-real-time

**Comment by AlexanderNosenko** [comment]
Thanks for response. Yes, exactly. I wanted to know if there's a demo showcasing how to add new elements (rectangles, circles, etc.) on the area selected. I guess you could call it dragging area
Also @tianyuya has pointed out another interesting feature being "select existing elements under the dragging area"

**Comment by tianyuya** [comment]
> Thanks for response. Yes, exactly. I wanted to know if there's a demo showcasing how to add new elements (rectangles, circles, etc.) on the area selected. I guess you could call it dragging area
> Also @tianyuya has pointed out another interesting feature being "select existing elements under the dragging area"

I'm sorry I misunderstood，Here's how I did it，`new Selecto({}).on('selectEnd',(e)=>{ console.log(e.rect)})` , `e.rect` is the width and height of the area I just drew，Then add elements to the canvas。I'm sorry my English is poor

**Comment by AlexanderNosenko** [comment]
Mine's not perfect either 😅
Understood, thank you.

**Comment by tianyuya** [comment]
&nbsp;I Understood，thank you



发自我的iPhone


------------------ Original ------------------
From: Alexander ***@***.***&gt;
Date: Thu,Apr 29,2021 5:57 PM
To: daybrush/moveable ***@***.***&gt;
Cc: 田雨呀 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [daybrush/moveable] Select area React demo (#443)





 
Mine's not perfect either 😅
 Understood, thank you.
