### ISSUE TITLE
Weird shift of the origin when resizing after rotating

### ISSUE THREAD

**Issue by JonathanTreffler** [daybrush/moveable#444]
## Environments
* Framework name: Vue
* Framework version: Vue 2
* Moveable Component version: 1.8.10
* Testable Address(optional):
can be run by opening it in a gitpod:
https://gitpod.io/#https://github.com/fractava/notes-core/tree/MovableTest .
The dev server starts automatically and a popup will ask if you want to open it in a new tab

## Description
I cannot figure out why resizing is behaving weirdly.

Heres a video of it:
https://www.youtube.com/watch?v=cI-7VmmegBo

It is pretty much just the example code from here: https://github.com/probil/vue-moveable

The dom structure in my project is much more complex, than in the example, but i cannot figure out how that would make the origin shift in weird ways when resizing.

I created this issue here, because i don't think it is related to the vue wrapper.

**Comment by JonathanTreffler** [comment]
# Code:
(all unrelevant parts removed, full file here: https://github.com/fractava/notes-core/blob/MovableTest/core/src/components/objects/Shape.vue)
<details>
  <summary>Expand</summary>

```vue
<template>
	<div class="shapeContainer">
        <div ref="container">
		<Moveable
			class="moveable"
			v-bind="moveableOptions"
                        :container="$refs.container"
                        v-if="isMounted"
                        @drag="handleDrag"
			@resize="handleResize"
			@rotate="handleRotate"
		>
			        [...]
			</div>
		</Moveable>
        </div>
	</div>
</template>
<script>
import Moveable from 'vue-moveable';

export default {
	components: {
		Moveable,
	},
	props: {
		id: {
			type: Number,
		},
	},
	data: function() {
		return {
                      isMounted: false,
                      moveableOptions: {
                          draggable: true,
                          throttleDrag: 1,
                          resizable: true,
                          throttleResize: 1,
                          keepRatio: false,
                          scalable: false,
                          throttleScale: 1,
                          rotatable: true,
                          throttleRotate: 1,
                          pinchable: true,
                          origin: true,
                          originDraggable: true,
                          edge: true,
                      },
		};
    },
    mounted: function() {
        this.isMounted = true;
        });
    },
	computed: {
		[...]
	},
	methods: {
                [...]
                handleDrag({ target, transform, left, top }) {
                    console.log('onDrag left, top', transform);
                    target.style.transform = transform;
        
                    this.$store.commit("moveShape", {id: this.id, x: left, y: top,}, {module: "core" });
                },
                handleResize({target, width, height, delta, drag, }) {
                    console.log('onResize', width, height);
                    delta[0] && (target.style.width = `${width}px`);
                    delta[1] && (target.style.height = `${height}px`);
        
                    this.$store.commit("resizeShape", {id: this.id, width, height,}, {module: "core" });
                },
                handleRotate({ target, rotate, transform }) {
                    console.log('onRotate', rotate);
                    target.style.transform = transform;
        
                    this.$store.commit("rotateShape", {id: this.id, rotation: rotate,}, {module: "core" });
                },
	},
};
</script>
```

</details>

**Comment by daybrush** [comment]
@JonathanTreffler 

See this demo: 
https://daybrush.com/moveable/storybook/?path=/story/basic--resizable

if you want resize, you have to use both resize(set width, height) and drag(set translate, or top,left)

**Comment by JonathanTreffler** [comment]
Thanks, i will try to adapt the code of the demo.

But how does the vue moveable demo not have this problem ? Its demo code is [here](https://github.com/probil/vue-moveable/blob/master/src/App.vue) and it is pretty much the same as mine. No extra handling of the drag, that occurs when resizing.

**Comment by daybrush** [comment]
@JonathanTreffler 

Sorry, but the vue demo code has the same problem.

**Comment by JonathanTreffler** [comment]
Ok, thanks for your help :)
