### ISSUE TITLE
SVG Line Problem

### ISSUE THREAD

**Issue by onurbozkurt** [daybrush/moveable#446]
## Environments
* Framework name: VanillaJS
* Framework version: -
* Moveable Component version: 0.24.5
* Testable Address(optional): https://codepen.io/onurbozkurt/pen/BapwgwW

## Description
I'm trying to use svg lines in combination with infinite-viewer. There are two issues I'm trying to solve but could not succeed yet.

1. Control box is not wrapping the svg element. (Wider than it should be).
2. Control box is not tracking the svg element if I zoom via the infinite-viewer and drag.

Any help would be appreciated.

**Comment by daybrush** [comment]
* `moveable` 0.24.6
* `react-moveable` 0.27.7
* `preact-moveable` 0.26.5
* `ngx-moveable` 0.20.6
* `svelte-moveable` 0.15.
* `lit-moveable` 0.1.6


@onurbozkurt 
moveable's new version is released. Check it again.
