### ISSUE TITLE
Get dragged anchor on resizeStart.

### ISSUE THREAD

**Issue by ruojianll** [daybrush/moveable#447]
## Environments
* Framework name: moveable.js
* Framework version: 0.24.5
* Moveable Component version: vanilla
* Testable Address(optional):

## Description
Get dragged anchor on resizeStart.
```javascript
moveable.on('resizeStart', (arg) => {
    const foo = arg.anchor //e.g. a enum value Anchor.ResizeNW
})
```

**Comment by ruojianll** [comment]
I can get the anchor from `arg.inputEvent.target`, but this is not a good practice。

**Comment by daybrush** [comment]
@ruojianll 
you can find target in arg.
But if you really want the object to be dragged, do it via inputEvent.
```js
moveable.on('resizeStart', (arg) => {
    const foo = arg.target
})
```

**Comment by ruojianll** [comment]
Actually, I want implement resize with `left,top,width,height` instead of `transform`. So I want to get the controller on resize and update styles. Is there another way to do this? @daybrush

**Comment by daybrush** [comment]
@ruojianll 

Refer to the following code:
```js
on("resize", e => {
   e.target.style.cssText = `width: ${e.width}px; height: ${e.height}px; top: ${e.drag.top}px; left: ${e.drag.left}px;`
});
```

**Comment by ruojianll** [comment]
@daybrush 
So the property `drag` in event contains the coordinate of the dragged element not the dragged control?
The code you provided works well in my scene.

**Comment by daybrush** [comment]
@ruojianll 
It doesn't exist. I'm sorry.
