### ISSUE TITLE
How to collapse tranform functions into a single transform matrix?

### ISSUE THREAD

**Issue by bkowzx** [daybrush/moveable#455]
I noticed the event transform field combines the use of the matrix function as well as translate, rotate, scale, etc. based on the operations being made. Sometimes however, it combines the translate, rotate, scale, etc. into the matrix. How do I do this manually; I always just want the matrix representation of the transform, I don't want the individual transform functions. This is so that I can store the fields in DB in an efficient representation. Is there a utility function that takes something like ```matrix(.......) rotate(.....) translate(.....) etc``` into just ```matrix(....)``` equivalent transform? I know I can review linear algebra and combine them myself but I feel like this is a solved problem, and since this library is already doing it, I assume there are utility functions available?

Thanks!

**Comment by bkowzx** [comment]
It seems ```window.getComputedStyle(target).transform``` has the desired effect as it returns a single transform matrix. Is there a better way?

**Comment by daybrush** [comment]
@bkowzx 

There is no API.
https://github.com/daybrush/css-to-mat

```js
import { parseMat } from "css-to-mat";

const matrix = parseMat(`matrix(.......) rotate(.....) translate(.....)`);

const m = `matrix(${matrix.join(", ")})`;

**Comment by bkowzx** [comment]
Thanks, that answers my question!

**Comment by mamsoudi** [comment]
We're using [DOMMatrix](https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix):

``` 
Array.from(new DOMMatrix(target.style.transform).toFloat32Array())
```

> If you're supporting modern browsers
