### ISSUE TITLE
There are no guidelines numbers when a rectangle contains another rectangle

### ISSUE THREAD

**Issue by tianyuya** [daybrush/moveable#456]
![微信截图_20210424181249](https://user-images.githubusercontent.com/6645546/115955581-f950db00-a529-11eb-877f-cbd36a70af4c.png)
![微信截图_20210424183122](https://user-images.githubusercontent.com/6645546/115955783-513c1180-a52b-11eb-88de-162b9fc30903.png)

there should have

**Comment by daybrush** [comment]
@tianyuya 

Sorry, but this is normal. It does not appear if it is contained within an element.

**Comment by tianyuya** [comment]
> @tianyuya
> 
> Sorry, but this is normal work. It does not appear if it is contained within an element.
Thanks for replying.  can you add display? I really need it

**Comment by tianyuya** [comment]
> @tianyuya
> 
> Sorry, but this is normal work. It does not appear if it is contained within an element.

Thanks for replying.Can you add this feature?

**Comment by daybrush** [comment]
@tianyuya 

I think it looks weird because the lines overlap.

How do you think it should look?

**Comment by tianyuya** [comment]
> @tianyuya
> 
> I think it looks weird because the lines overlap.
> 
> How do you think it should look?

Thanks for replying.Yes, the lines will overlap,it looks weird, I think the user will want to know the distance between the two when they drag and drop. Snap works and can easily add the distance display. I don't know if I'm right without looking at the source

**Comment by daybrush** [comment]
@tianyuya 

Okay. I'll consider it.

**Comment by daybrush** [comment]
@tianyuya 

<img width="527" alt="스크린샷 2021-06-05 오후 5 43 46" src="https://user-images.githubusercontent.com/3433062/120885789-b18f9a00-c625-11eb-941f-37c7f93dfc09.png">
