### ISSUE TITLE
Unable to use svg icon in the custom able with plain javascript

### ISSUE THREAD

**Issue by ccpu** [daybrush/moveable#462]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Moveable version: 0.24.6
* Testable Address(optional):  [codesandbox](https://codesandbox.io/s/moveable-able-svg-icon-derdj)

## Description

Somehow SVG icons used with custom ables are not rendered properly when using moveable in the plain javascript (e.g. `new Moveable(document.body, {...})`.

**Comment by daybrush** [comment]
@ccpu 

oh sorry.

svg is not supported in custom able.

I'll support svg.

**Comment by daybrush** [comment]
@ccpu 

* `moveable` 0.25.1
* `react-moveable` 0.28.1
* `preact-moveable` 0.27.1
* `ngx-moveable` 0.21.1
* `svelte-moveable` 0.16.1
* `lit-moveable` 0.2.1

moveable's new version is released. svg is available.
