### ISSUE TITLE
ngx-clippable for cropping

### ISSUE THREAD

**Issue by michaeldever** [daybrush/moveable#464]
## Environments
* Framework name: Angular
* Framework version: 10.2
* Moveable Component version: 0.21.4
* Testable Address(optional):

## Description
* I am trying to use clippable to enable a crop function on an image.
* I would like the boundary of the moveable to keep in sync with the crop. EG if I crop down 100px, the top border of the moveable moves down 100px
* Currently the clipping works fine, but I can't get the moveable to stay in sync. `updateRect()` and `updateTarget()` have no effect.

**Comment by daybrush** [comment]
@michaeldever 

You can see the clip area, but the offsetWidth and offsetHeight remain the same regardless of cropping. This is an area that I can't decide. I'm sorry.

**Comment by michaeldever** [comment]
Sure thing, we used a different library for clip/crop.
