### ISSUE TITLE
[Resizable] Guidelines are hidden when using makeMoveable

### ISSUE THREAD

**Issue by ccpu** [daybrush/moveable#466]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Moveable Component version: 0.27.7
* Testable Address(optional): [codesandbox](https://codesandbox.io/s/guideline-problem-925xu)

## Description
When using `makeMoveable` for tree shaking, The guidelines are not displayed while resizing, however it does work when dragging!

**Comment by daybrush** [comment]
@ccpu 

If the snappable comes in the first order, it will work.

```js
const Moveable = makeMoveable<
  DraggableProps & ResizableProps & RotatableProps & SnappableProps
>([Snappable, Draggable, Resizable, Rotatable]);
```

**Comment by ccpu** [comment]
indeed order is matter, thanks.
