### ISSUE TITLE
Scalable and snappable with `keepRatio={true}`

### ISSUE THREAD

**Issue by jrga03** [daybrush/moveable#470]
## Environments
* Framework name: react
* Framework version: 17.0.1
* Moveable Component version: react-moveable 0.27.0 and above
* Testable Address(optional): https://codesandbox.io/s/priceless-zhukovsky-g57ns?file=/src/Moveable.jsx

## Description
Scaling with snappable causes the moveable to scale uncontrollably when `keepRatio={true}`. This happens on the `nw`, `ne`, `sw`, `se`, `e`, and `w` handles but not on the `n` and `s`. This doesn't seem to happen on `react-moveable@0.26.2`

**Comment by daybrush** [comment]
@jrga03 

Almost everything has been fixed now.

It will be released within this week.

**Comment by daybrush** [comment]
@jrga03 
Test with this version `react-moveable@0.27.8-beta.1`

**Comment by jrga03** [comment]
@daybrush Thanks for the swift turnaround! I've tested and I noticed some weird behavior when scaling along the bounds. It happens on the `ne`, `se`, and `sw` on my test. I assume it's the same with `nw`. Here is a testable address with the new version https://codesandbox.io/s/inspiring-wozniak-f0f6d


![Test new version](https://media.giphy.com/media/K7lizZ4jMZvXNJRrt2/giphy.gif)

**Comment by daybrush** [comment]
@jrga03 

Test with this version react-moveable@0.27.8-beta.2

**Comment by jrga03** [comment]
@daybrush Works as expected now!

**Comment by daybrush** [comment]
@jrga03 

react-moveable 0.28.1 is released. Thank you :)

**Comment by jrga03** [comment]
@daybrush Thanks a lot!
