### ISSUE TITLE
[Feature request] Snap to grid

### ISSUE THREAD

**Issue by yojona** [daybrush/moveable#482]
I would like to be able to drag and resize my elements while snapping to a grid

![chrome-capture](https://user-images.githubusercontent.com/13840865/120121364-dbdde500-c157-11eb-944d-8b2d1832e1cd.gif)

This is my workaround:

```javascript
  const getGrid = (grid: number) => {
    const items = [0];

    while(items[items.length - 1] < width) {
      items.push(items[items.length - 1] + grid)
    }

    return items;
  }
  
```

```jsx
<Moveable
  verticalGuidelines={getGrid(8)}
  horizontalGuidelines={getGrid(8)}
/>
```

This solution is not good for big layouts.

We can do something like ```X % gridWidth === 0```  and ```Y % gridHeight === 0``` to check the grid lines instead of checking thousands of  items in an array.

It could look like this

```jsx
<Moveable
  snapToGrid={true}
  gridWidth={8}
  gridHeight={8}
/>
```

**Comment by daybrush** [comment]
@yojona 

react-moveable@0.28.0 is released.

Try this code:
```jsx
<Moveable
   snappable={true}
  gridWidth={8}
  gridHeight={8}
/>

```

**Comment by yojona** [comment]
> @yojona
> 
> react-moveable@0.28.0 is released.
> 
> Try this code:
> 
> ```js
> <Moveable
>    snappable={true}
>   snapGridWidth={8}
>   snapGridHeight={8}
> />
> ```

this is really good stuff! 

The only thing is that is not snapping to the end of the grid in the right and bottom, for left and top works great. 
Is this expected behavior?


(see the last seconds of the gif)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/13840865/121754140-b2627900-cac8-11eb-83e7-cfed835c3462.gif)

**Comment by daybrush** [comment]
@yojona 

react-moveable@0.28.1 is released.

Check it again. Thank you :)

**Comment by daybrush** [comment]
Thank you for PR.

`react-moveable` 0.28.3 is released.

Check it again.

**Comment by yojona** [comment]
works great, thanks!

**Comment by rememberlenny** [comment]
This is a great feature. Thank you!
