### ISSUE TITLE
why refTarget can be different with moveable.props.target?

### ISSUE THREAD

**Issue by lvqingxiang** [daybrush/moveable#485]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:

* Testable Address(optional):
i made some moveable elements, and set them zIndex ,then make one element  to drag or resize ,then i found the target is not equal
pic url:https://cdn.dmhub.cn/image/d8e05ccad3604dddaba3c1d90343ea6f

**Comment by daybrush** [comment]
@lvqingxiang 

The user's target is ["#module773"], and internally, it is searched through querySelector. Did the element ID of 773 change to 760?

**Comment by lvqingxiang** [comment]
https://codesandbox.io/s/charming-elbakyan-8gi5d?file=/src/App.tsx just like this

**Comment by lvqingxiang** [comment]
https://codesandbox.io/s/test-q0h6w?file=/src/App.tsx just like this




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "daybrush/moveable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月5日(星期六) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [daybrush/moveable] why refTarget can be different with moveable.props.target? (#485)





 
@lvqingxiang
 
The user's target is ["#module773"], and internally, it is searched through querySelector. Did the element ID of 773 change to 760?

**Comment by daybrush** [comment]
@lvqingxiang 

If you use an array, specify the key.
```jsx
<div key={e.id} id={e.id} style={e.style} onClick={() => setTarget("#" + e.id)}>
          {e.content}
        </div>
```

**Comment by lvqingxiang** [comment]
oooooh! it works! thanks!
