### ISSUE TITLE
how to listen click event when rotate end

### ISSUE THREAD

**Issue by lvqingxiang** [daybrush/moveable#490]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

now i listen click event on parent element ,but when child element rotate end, will trigger parent click. how to avoid ?

**Comment by daybrush** [comment]
@lvqingxiang 
* `moveable` 0.25.3
* `react-moveable` 0.28.3
* `preact-moveable` 0.27.3
* `ngx-moveable` 0.21.3
* `svelte-moveable` 0.16.3
* `lit-moveable` 0.2.3

moveable's new version is released.
Check it again.

**Comment by lvqingxiang** [comment]
when i rotate end ,if my mouse position current on  moveable internal ,it is work.when the mouse position out of moveable element and on parent node will trigger parent click, my version is 0.28.3 is there any way to avoid click trigger

**Comment by lvqingxiang** [comment]
just like this https://codesandbox.io/s/rotateend-dpcii

**Comment by daybrush** [comment]
@lvqingxiang 

Test 0.28.4-beta.0 version

**Comment by lvqingxiang** [comment]
after rotate end , any click event can not be triggered。😭

**Comment by daybrush** [comment]
@lvqingxiang 
oh sorry, 

Test 0.29.0-beta.0 version

**Comment by daybrush** [comment]
@lvqingxiang 
Oh sorry.

Test 0.29.0-beta.1 version.

**Comment by lvqingxiang** [comment]
Thanks a million. it works ✌️

**Comment by lvqingxiang** [comment]
😱 why 0.29.0-beta.1 can not trigger the current moveable target click event, @daybrush

**Comment by daybrush** [comment]
@lvqingxiang 

Use onClick in Moveable 
```js
<Moveable
     onClick={e => {
     }}
/>
