### ISSUE TITLE
On dragging SVG elements location of drag controls is affected by the parent element's margin.

### ISSUE THREAD

**Issue by pinoybai** [daybrush/moveable#498]
## Environments
* Framework name: Vanilla JS
* Moveable Component version: 0.25.3
* Testable Address(optional): https://codepen.io/gurgoon32/pen/VwbLqdy

## Description
The location of the drag/resize controls frame is working perfectly fine on other elements but when choosing the SVG element it is affected by the margin of the parent element (In the example, the body's margin and padding). so the 'Transform3d' x and y value is offsetting with the body's margin and padding.

Could you please help me fix this?

**Comment by daybrush** [comment]
@pinoybai 

I think it's a bug. I'll let you know after I fix it.

**Comment by daybrush** [comment]
@pinoybai 

moveable 0.26.0 is released.
https://codepen.io/daybrush/pen/MWmjrOQ

**Comment by pinoybai** [comment]
@daybrush Thank you for your update!

Also do you provide an event on select of moveable target?
