### ISSUE TITLE
show blue lines, only when clincking contents. 

### ISSUE THREAD

**Issue by kobe2sha** [daybrush/moveable#500]
## Environments
* Framework name: Vue.js, Vue Moveable
* Framework version: vue@2.6.12
* Moveable Component version:0.25.3
* Testable Address(optional):

## Description
At first thank you for great library. 

https://daybrush.com/moveable/

I wanna make function In this web site.  When I click contents, bules lines are showed. I click outside the content, blue lines are concealed.  this is just I hope. 

To make this function I tried v-on click and dynamically change classes (eg. moveable-control and moveable-rotation), but it didnt work. Because using <Moveable></Moveable> tag,  automatically genarated these casses div tag <div class="moveable-control moveable-rotation">.  so there are not these tags in my written code, i can't operate them. 　

How did you make it? Thanks!!

**Comment by daybrush** [comment]
@kobe2sha 


I use this with selecto.

https://github.com/daybrush/selecto

**Comment by kobe2sha** [comment]
thank you for your reply. I'll try "selecto".
