### ISSUE TITLE
How to restrict the drag position with SHIFT resize like the demo

### ISSUE THREAD

**Issue by chenxeed** [daybrush/moveable#507]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

Hi @daybrush ,

I was checking your awesome demo here: https://daybrush.com/moveable/

I see that on dragging while holding SHIFT, it'll restrict the drag position to certain direction based on the mouse position.

<img src="https://gyazo.com/6e587b8c8bacf3a321fd6f74d1500396.gif"/>

I couldn't find the API to enable this 🙇 May I ask your help on how to enable it? Thanks!

**Comment by chenxeed** [comment]
I found out how to do it, thanks to my colleague @elvinlkh.

We can use the param `throttleDragRotate` and set the coordinate for it to point to.

Then, to toggle the param while user is dragging and press SHIFT is by updating the state on `drag / dragGroup`:

```js
    .on('drag', (event) => {
      const shiftKey = event.inputEvent.shiftKey
      // set drag throttle base on shift key
      event.currentTarget.setState({
        throttleDragRotate: shiftKey ? 90 : 0
      })
      // continue with your own logic
    })
```

**Comment by xiaopujun** [comment]
> I found out how to do it, thanks to my colleague @elvinlkh.
> 
> We can use the param `throttleDragRotate` and set the coordinate for it to point to.
> 
> Then, to toggle the param while user is dragging and press SHIFT is by updating the state on `drag / dragGroup`:
> 
> ```js
>     .on('drag', (event) => {
>       const shiftKey = event.inputEvent.shiftKey
>       // set drag throttle base on shift key
>       event.currentTarget.setState({
>         throttleDragRotate: shiftKey ? 90 : 0
>       })
>       // continue with your own logic
>     })
> ```

Hey bro, you're awesome with this problem and solution, I've tried a lot of ways and even tried to implement this effect myself and failed. Luckily I saw your issue and it solved my problem perfectly. Thank you bro. Also thanks to the author
