### ISSUE TITLE
Import error during build

### ISSUE THREAD

**Issue by pgrodrigues90** [daybrush/moveable#508]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Moveable Component version: 0.29.0
* Testable Address(optional):

## Description

When running `npm build` in my Azure DevOps pipeline I get the following error:
![build](https://user-images.githubusercontent.com/38471984/126494464-e9fabb1d-24db-4f6b-9cb6-34a2319a4904.png)

This started to happen only after upgrading from 0.28.3 to 0.29.0. When reverting back to 0.28.3 the build is successful. 

When building locally in my dev machine either with 0.28.3 or 0.29.0 this error does not occur.

Do you have any idea of what could be the reason?

**Comment by daybrush** [comment]
@pgrodrigues90 

It could be a version issue with @daybrush/utils.

Would you like to delete package-lock and node_modules and test again?
