### ISSUE TITLE
Ability to Snap Only Center of Objects

### ISSUE THREAD

**Issue by onurbozkurt** [daybrush/moveable#511]
## Environments
* Framework name: VanillaJS
* Framework version:
* Moveable Component version: 0.26.0
* Testable Address(optional): https://daybrush.com/moveable/storybook/index.html?path=/story/use-snap-bounds-with-ables--snap-guidelines-elements

## Description
There is an option for snap to enable/disable center snap via 'snapCenter'. It would be nice to only enable snap center with an option like 'snapEdges'.

Thanks.

**Comment by daybrush** [comment]
@onurbozkurt 

* `moveable` 0.27.0
* `react-moveable` 0.30.0
* `preact-moveable` 0.29.0
* `ngx-moveable` 0.23.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.4.0
* `vue-moveable` 2.0.0-beta.2
* `vue3-moveable` 0.2.0

moveable's new version is released. 

```js
new Moveable(..., {
     snapDirections: { center: true, middle: true },
     elementSnapDirections: { top: true, bottom: true, right: true, left: true },
});
```
