### ISSUE TITLE
Use zoom in `infinite-viewer`, drag target does not follow the mouse, `vue3-moveable` and `moveable` are invalid

### ISSUE THREAD

**Issue by iDerekLi** [daybrush/moveable#519]
## Environments
* Framework name: vue3
* Framework version: 3.0.0
* Moveable Component version: 0.26.0
* Testable Address(optional): -

## Description

Use `zoom` property in `infinite-viewer`, drag target does not follow the mouse, `vue3-movable` and `moveable` are invalid

Using `portalContainer` properties can solve that zoom does not follow the target, but the drag container is missing.
v_v~

**Comment by glancel** [comment]
@iDerekLi Have you found any solution for the drag container in vue3? Thank you for your help

**Comment by iDerekLi** [comment]
> @iDerekLi Have you found any solution for the drag container in vue3? Thank you for your help

Did not find a good one, either replace the technology stack or implement it manually

**Comment by daybrush** [comment]
@glancel @iDerekLi 



* `moveable` 0.27.0
* `react-moveable` 0.30.0
* `preact-moveable` 0.29.0
* `ngx-moveable` 0.23.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.4.0
* `vue-moveable` 2.0.0-beta.2
* `vue3-moveable` 0.2.0

moveable's new version is released. Check it again.
