### ISSUE TITLE
请问如何取消选中，让选中框消失

### ISSUE THREAD

**Issue by luoyiyi** [daybrush/moveable#521]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@luoyiyi 

It's a good feature. I'll add it later.

**Comment by daybrush** [comment]
@znlbwo @luoyiyi 



* `moveable` 0.27.0
* `react-moveable` 0.30.0
* `preact-moveable` 0.29.0
* `ngx-moveable` 0.23.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.4.0
* `vue-moveable` 2.0.0-beta.2
* `vue3-moveable` 0.2.0

moveable's new version is released. Check it again.

You can use:
```js
hideDefaultLines={true}
```
