### ISSUE TITLE
Able 不起作用

### ISSUE THREAD

**Issue by JoeABCDEF** [daybrush/moveable#527]
## Environments
* Framework name: vue3
* Framework version: 3.2.6
* Moveable Component version: 0.26.0
* Testable Address(optional):

## Description
```ts
import { h } from 'vue'
import Moveable, { getElementInfo, MoveableManagerInterface, MoveableOptions, Able, Renderer } from "moveable";

export function Moving(parentElement: HTMLElement | SVGElement, target?: HTMLElement | SVGElement, options?: MoveableOptions, events?: Record<string, Function>) {
    const moveable = new Moveable(parentElement, {
        target,

        ables: [DimensionViewable],
        ...options
    })

    return moveable;
}
export const DimensionViewable: Able = {
    name: 'dimensionViewable',
    // updateRect: true,
    render(moveable: MoveableManagerInterface<any, any>, { createElement }: Renderer) {
        const rect = moveable.getRect();

        return h('div', {
            style: {
                width: '90px',
                height: '90px',
                backgroundColor: '#dc3f3c',
                transform: 'translate(-50%, 0px)',
                left: `${rect.width / 2}px`,
                top: `${rect.height + 24}px`,
                position: 'absolute'
            }
        });
    },
    dragStart(moveable, e) {
        console.dir(moveable);
        console.dir(e);
    }
}
```

这个 `able` 不起作用 是我写的有问题吗

**Comment by dekinsq** [comment]
import { h } from 'vue'
import Moveable, { getElementInfo, MoveableManagerInterface, MoveableOptions, Able, Renderer } from "moveable";

export function Moving(parentElement: HTMLElement | SVGElement, target?: HTMLElement | SVGElement, options?: MoveableOptions, events?: Record<string, Function>) {
    const moveable = new Moveable(parentElement, {
        target,

        ables: [DimensionViewable],
       props: {
                dimensionViewable: true
       },
        ...options
    })

    return moveable;
}
export const DimensionViewable: Able = {
    name: 'dimensionViewable',
    // updateRect: true,
    render(moveable: MoveableManagerInterface<any, any>, { createElement }: Renderer) {
        const rect = moveable.getRect();

        return createElement('div', {
            key:"custom-element",
            className:"moveable-custom",
            style: {
                width: '90px',
                height: '90px',
                backgroundColor: '#dc3f3c',
                transform: 'translate(-50%, 0px)',
                left: `${rect.width / 2}px`,
                top: `${rect.height + 24}px`,
                position: 'absolute'
            }
        });
    },
    dragStart(moveable, e) {
        console.dir(moveable);
        console.dir(e);
    }
}

修改下,这样就可以正常显示了
