### ISSUE TITLE
After setting the target, need to click again to move it？

### ISSUE THREAD

**Issue by kechen123** [daybrush/moveable#528]
## Environments
* Framework name: jQuery
* Framework version:jquery-1.8.3.min.js
* Moveable Component version:0.26.0 daybrush.com/moveable/release/latest/dist/moveable.min.js
* Testable Address(optional):

## Description

Hi Daybrush,

I used your plug-in in the jQuery project, but now I have a problem

I want to set target or dragstart when MouseDown, and move the mouse to move the dom

const moveable = new Moveable($('#divCvsBody')[0],{
     draggable: true,
     resizable: true,
     scalable: true,
     rotatable: true,
});

moveable.on("drag",function({ target, left, top}){
target.style.left = `${left}px`;
target.style.top = `${top}px`;
})

$(document).on('mousedown', '#divCvs > [id^=screenChart_][cpntype]', function (eventDown){
    moveable.target=$(this)[0];
    moveable.dragStart($(this)[0]);
});

**Comment by xinnai** [comment]
@kechen123 Can you share how did you resolve this?

**Comment by kechen123** [comment]
@xinnai 

$(document).on('mousedown', '#divCvs > [id^=screenChart_][cpntype]', function (eventDown){
  moveable.target=$(this)[0];
   setTimeout(function (){
      moveable.dragStart(eventDown);
  })
});

 moveable.target are async . use settimeout

**Comment by kechen123** [comment]
@xinnai 

$(document).on('mousedown', '#divCvs > [id^=screenChart_][cpntype]', function (eventDown){
  moveable.target=$(this)[0];
   setTimeout(function (){
      moveable.dragStart(eventDown);
  })
});

 moveable.target are async . use settimeout
