### ISSUE TITLE
Is there a way to clone and drag an element?

### ISSUE THREAD

**Issue by pistell** [daybrush/moveable#54]
As seen here: http://jsfiddle.net/nichollascarter/qgwzch0v/

This manipulation library is pretty interesting because it allows you to click on drag the yellow square and it clones the element.

**Comment by daybrush** [comment]
@pistell 

Is this what you want?


https://codepen.io/daybrush/pen/KKKdLqw

**Comment by pistell** [comment]
Yes. Wow I can't believe I missed that. I should really stop asking questions at 3am and get some sleep

**Comment by daybrush** [comment]
@pistell 

Feel free to write issues if you have a question or a feature request.

Thank you :)

**Comment by pistell** [comment]
Hi there. I reworked this because I didn't want to include scene.js. It uses the HTML5 drag-and-drop API along with moveable.js

Just in case anyone else was curious how I did it I am including a pen

https://codepen.io/pistell/pen/XWWdZrv

Thanks for the awesome library!
