### ISSUE TITLE
API Documentation of Movable.Draggable has a mistake

### ISSUE THREAD

**Issue by 18595439829** [daybrush/moveable#540]
https://daybrush.com/moveable/release/latest/doc/Moveable.Draggable.html#.OnDrag
The mistake at OnDrag's Properties: width/height/right; Thires description is wrong

**Comment by daybrush** [comment]
@18595439829 


Thank you :) I'll fix it soon.

**Comment by daybrush** [comment]
* `moveable` 0.27.0
* `react-moveable` 0.30.0
* `preact-moveable` 0.29.0
* `ngx-moveable` 0.23.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.4.0
* `vue-moveable` 2.0.0-beta.2
* `vue3-moveable` 0.2.0

moveable's new version is released.
