### ISSUE TITLE
Moveable contextmenu event

### ISSUE THREAD

**Issue by pgrodrigues90** [daybrush/moveable#544]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Moveable Component version: react-moveable 0.28.3, react-selecto 1.13.0, @scena/react-guides 0.16.0

## Description
Following your [Selecto with Moveable example](https://codesandbox.io/s/dtxrz) I want to display a custom context menu when the user selects multiple items and performs a right click on the moveable-area selection.

The `<Moveable />` component does not seem to provide an `onContextMenu` event handler and the `onClickGroup` handler is only triggered when a left click is performed.

What would be the best way to detect the contextmenu event or a right click on a selection of multiple items?

Thanks in advance.

**Comment by daybrush** [comment]
@pgrodrigues90 

It seems difficult to support contextmenu.
As you said, it would be better to control it in the parent div.
