### ISSUE TITLE
The elements snap only working with their initial position

### ISSUE THREAD

**Issue by nzbin** [daybrush/moveable#548]
## Environments
* Framework name:
* Framework version:
* Moveable Component version: `0.27.0`
* Testable Address(optional): https://codesandbox.io/s/moveable-snap-e0znh?file=/index.html

## Description

When move one element to another place, the snap can not working exactly. But version `0.26.0` is OK.

You can test with following example.

https://codesandbox.io/s/moveable-snap-e0znh?file=/index.html

**Comment by daybrush** [comment]
@nzbin 

* `moveable` 0.27.1
* `react-moveable` 0.30.1
* `preact-moveable` 0.29.1
* `ngx-moveable` 0.23.1
* `svelte-moveable` 0.18.1
* `lit-moveable` 0.4.1
* `vue-moveable` 2.0.0-beta.3
* `vue3-moveable` 0.2.1


moveable's new version is released. Check it again.
