### ISSUE TITLE
Resize does not work if div has CSS width and height

### ISSUE THREAD

**Issue by Darkside73** [daybrush/moveable#551]
## Environments
* Framework name: Vanilla
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description
I want to create movable for element with width and height styles. But it breaks resize
```html
<div style="width: 100px; height: 100px;"></div>
```
![Peek 2021-11-10 14-08](https://user-images.githubusercontent.com/339596/141110336-3cb0bf8e-d332-484e-a228-4a3112d23d9b.gif)

What is the correct way to create moveable with predefined width and height?

**Comment by daybrush** [comment]
Can you tell me how you are using it in the resize event?

**Comment by Darkside73** [comment]
It's basic example from the docs. Only difference is the ```style``` attribute.
I've ended with setting values via JS:
```js
target.style.width = '100px'
target.style.height = '100px'
```

**Comment by daybrush** [comment]
@Darkside73 

I can't figure it out with just your example. Is it set as below?

```js
onResize={e => {
                        e.target.style.width = `${e.width}px`;
                        e.target.style.height = `${e.height}px`;
                        e.target.style.transform = e.drag.transform;
                    }}
```

**Comment by Darkside73** [comment]
Yes. Sorry. I've created clean example and it works as expected
