### ISSUE TITLE
Invalid elementguidelines for the same DOM size

### ISSUE THREAD

**Issue by kechen123** [daybrush/moveable#555]
## Environments
* Framework name: jQuery
* Framework version:1.83
* Moveable Component version:0.26.0
* Testable Address(optional):

## Description
 let moveable = new MyMoveAble(document.getElementById('content'),{
      keepRatio:false,
      origin:false, 
      draggable:true,
      resizable:true,
      rotatable:true,
      throttleRotate:1,
      passDragArea: false,
      renderDirections: ["n", "nw", "ne", "s", "se", "sw", "e", "w"],
      snappable:true, 
      snapThreshold:5,
      snapCenter:true,
  })
let elements = $.makeArray($('.move'));
moveable.elementGuidelines = elements;

Two elements of the same size do not show guides when moving.

When I change one of the size ,it's run

**Comment by daybrush** [comment]
@kechen123 

When I test it behaves strangely, but the guidelines are visible. Could you show me an url or a screenshot to test on?

**Comment by daybrush** [comment]
@kechen123 

* `moveable` 0.27.2
* `react-moveable` 0.30.2
* `preact-moveable` 0.29.2
* `ngx-moveable` 0.23.2
* `svelte-moveable` 0.18.2
* `lit-moveable` 0.4.2
* `vue-moveable` 2.0.0-beta.5
* `vue3-moveable` 0.2.2

moveable's new version is released. Check it again.

**Comment by kechen123** [comment]
@daybrush The function of the new version is normal. This is a screenshot of the difference between versions 0.26.0 and 0.27.2
![微信图片_20211117093133](https://user-images.githubusercontent.com/16396880/142092834-aecdcec2-0e4f-4b30-88e9-aa7d1e5c7c56.png)
![微信图片_20211117093138](https://user-images.githubusercontent.com/16396880/142092844-4b6b5967-3075-48ed-8756-4e1c6d088a97.png)
