### ISSUE TITLE
Using Moveable component in Vue, drag event and resize event not be trigger

### ISSUE THREAD

**Issue by chenp1204** [daybrush/moveable#558]
## Environments
* Framework name: Vue
* Framework version: 2.6.13
* Moveable Component version: vue-moveable 1.8.11
* Testable Address(optional):

## Description
Using Moveable component in Vue after import, bind dragStart drag dragEnd event and resizeEnd event not be trigger,  following is the code, please give me help, thank you very much.

![111](https://user-images.githubusercontent.com/29192482/141760042-c4dd6d40-120a-4f7c-9791-0dda18736034.jpg)

![222](https://user-images.githubusercontent.com/29192482/141760082-de09972e-d17c-4efe-8080-1e090b582cb1.jpg)

**Comment by daybrush** [comment]
@chenp1204 

vue-moveable < 2.0.0 is deprecated. Test vue-moveable@beta.
