### ISSUE TITLE
can't click

### ISSUE THREAD

**Issue by topdevelop** [daybrush/moveable#567]
when i set draggable=false,onClick disabled together

**Comment by daybrush** [comment]
* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.
