### ISSUE TITLE
I need demo's code

### ISSUE THREAD

**Issue by 18595439829** [daybrush/moveable#569]
https://daybrush.com/moveable/
this demo is great,but i can't find it's code,can you give me,please?thank you🙂

**Comment by 18595439829** [comment]
https://daybrush.com/moveable/
this demo is great,but i can't find it's code,can you give me,please?thank you🙂

**Comment by dev181992** [comment]
Hi, @daybrush , thanks for your hard work.
I also want to get source code of this demo. https://daybrush.com/moveable/

Thanks

**Comment by daybrush** [comment]
@18595439829 


Here's code:


https://github.com/daybrush/scena


https://github.com/daybrush/scena/tree/master/packages/react-editor

**Comment by 18595439829** [comment]
> @18595439829
> 
> Here's code:
> 
> https://github.com/daybrush/scena
> 
> https://github.com/daybrush/scena/tree/master/packages/react-editor

thank you very match!🙂

**Comment by akshaypjoshi** [comment]
The source code is in React but I want to achieve these functionalities in pure javascript.
Is there any way to do this? I want to draw the area on selecting rect in sidebar and then filling colors and all that stuff. 
How can we achieve this in core javascript?

**Comment by hqiaozhang** [comment]
请问下https://alis.oss.aliyuncs.com/page/moveble/#/这个Dome有源码吗

**Comment by 18595439829** [comment]
> 请问下[https://alis.oss.aliyuncs.com/page/moveble/#/这个Dome有源码吗](https://alis.oss.aliyuncs.com/page/moveble/#/%E8%BF%99%E4%B8%AADome%E6%9C%89%E6%BA%90%E7%A0%81%E5%90%97)
应该是这一个
https://github.com/daybrush/scena/tree/master/packages/react-editor
