### ISSUE TITLE
Question: After moveable created, how can i hide the default line 

### ISSUE THREAD

**Issue by chenp1204** [daybrush/moveable#572]
## Environments
* Framework name: Vue
* Framework version: 2.6.13
* Moveable Component version: 0.27.2
* Testable Address(optional):

## Description
Hi @daybrush ,
I have multi moveable, when i select one of them, it show default line, when i select another one, i only want to hide previous moveable's default line, not destory it, moveable has not provide ‘setOption’ function,
how can i do?

**Comment by chenp1204** [comment]
sorry to bother you, i understand

**Comment by cutemurphy2022** [comment]
@chenp1204 chenp1204 how u do that`
