### ISSUE TITLE
New Feature: add zIndex option

### ISSUE THREAD

**Issue by nzbin** [daybrush/moveable#573]
Now the `moveable-control-box` has a css attr `z-index: 3000`. I don't know whether there has a option to modify its `z-index`.

**Comment by ccpu** [comment]
Use css rules:

https://github.com/daybrush/moveable/issues/478
https://github.com/daybrush/moveable/blob/808d27f102ac121fa2e9c4fb0d73ff926b727dce/custom_css.md#default-css

**Comment by daybrush** [comment]
Use `style` prop

**Comment by nzbin** [comment]
> Use `style` prop
> 
> ```js
> <Moveable
> style={{
>     zIndex: 1000,
> }}/>
> ```

It's not working with Angular.
