### ISSUE TITLE
Question: When infinite-viewer Guides set custom height and width, the guideline's position wrong

### ISSUE THREAD

**Issue by chenp1204** [daybrush/moveable#575]
## Environments
* Framework name: Vue
* Framework version: 2.6.13
* Moveable Component version: 
* Testable Address(optional): https://codesandbox.io/s/red-http-s870w?file=/src/App.vue

## Description
Hi, @daybrush 

When i use Guides in  infinite-viewer, i set my custom height and width for the guides（your Guides default height is 30px, my custom height is 20px）, however, the drag guideline's position is wrong, how to adjust this distance ?

This is my test demo

 https://codesandbox.io/s/red-http-s870w?file=/src/App.vue

And the phenomenon is as follows

![1638528483728](https://user-images.githubusercontent.com/29192482/144590905-80a93939-e04c-466b-90a6-6a5c675ddb3f.jpg)

![1638528453681](https://user-images.githubusercontent.com/29192482/144591058-0e7c90e1-97e7-4086-abb6-6a7f44227f1b.jpg)

**Comment by daybrush** [comment]
@chenp1204 

Thank you :) It's Guides' bug. I'll fix it soon.
