### ISSUE TITLE
Moveable with scaled containers

### ISSUE THREAD

**Issue by pdaloisio** [daybrush/moveable#578]
## Environments
* Framework name: Vue
* Framework version: 2.6.11
* Moveable Component version: 2.0.0-beta.4
* Testable Address(optional): https://codesandbox.io/s/snowy-night-lt7ek?file=/src/App.vue

## Description

Hi @daybrush,

we are trying to work with moveable in a scaled context (we need to realize a layout editor for surfaces that can be very big), but as you can see in the testable address we aren't able to config moveable correctly to work in such situation.

Another thing, it's possible to set snappable guidelines with decimal numbers (ex. 172.5)? We are trying, but when I call "getRect()" after snapping the values are integer (ex. 173).

We are asking this because if snappable can work with decimal numbers then we can avoid to work with scaled containers.

Thank you for your help.

**Comment by daybrush** [comment]
vue-moveable@2.0.0-beta.5 is released.

Check it again.
