### ISSUE TITLE
can't click

### ISSUE THREAD

**Issue by sunshinegyx** [daybrush/moveable#582]
## Environments
* Framework name: vue3-moveable
* Framework version: 0.2.2
* Moveable Component version:
* Testable Address(optional):

## Description

The click event does not work on Android phones after dragging，It was good before dragging

**Comment by daybrush** [comment]
@sunshinegyx 

I'm blocking the click event while dragging.

**Comment by daybrush** [comment]
@sunshinegyx 

* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.

If it doesn't work, set clickable to false.
