### ISSUE TITLE
Custom ables buttons problem  with groups

### ISSUE THREAD

**Issue by JoseLuisRNP** [daybrush/moveable#583]
## Environments
* Framework name: Vue
* Framework version: 3.2.16
* Moveable Component version: 0.27.2 vanilla
* Testable Address(optional): https://codesandbox.io/s/lucid-driscoll-wzdt2?file=/src/App.vue

## Description

I'm trying to create a custom able with buttons but seems like this has some problem with groups. 
When you click in a button in a custom able in group it launch a drag event in .moveable-area and avoid launch the button event

**Comment by daybrush** [comment]
@JoseLuisRNP 

Try adding moveable- as prefix to the class name.

<Button :selector="'moveable-toolbar-group'" v-if="loaded" />
<Button :selector="'moveable-toolbar'" v-if="loaded" />

```vue
<button :class="selector" @click="clicked()">Click</button>
```

**Comment by JoseLuisRNP** [comment]
That's do the trick, thanks for your great work @daybrush !

**Comment by daybrush** [comment]
@JoseLuisRNP 

* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.
Conversely, there must be no `moveable-` prefix.
