### ISSUE TITLE
feature: provide option for Multi select rectangle drag box

### ISSUE THREAD

**Issue by born2net** [daybrush/moveable#59]
feature: provide option for Multi select rectangle drag box
Hold down and drag a box to select / group multiple object...
tx for a great lib

Sean

**Comment by daybrush** [comment]
@born2net 

See the following documents:
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-group

**Comment by born2net** [comment]
thank you but it would be awesome but was referring to something like this:
https://thibaultjanbeyer.github.io/DragSelect/

**Comment by born2net** [comment]
or https://simonwep.github.io/selection/

**Comment by daybrush** [comment]
@born2net 
Oh, of course, it is a very necessary function for me.

But I won't add it as a moveable feature. Instead, use an external library or create a new one.

I will write a comment again when I make the select function.

**Comment by born2net** [comment]
tx

**Comment by jmsegrev** [comment]
Was this feature ever completed?

**Comment by daybrush** [comment]
@jmsegrev 


See this component:
https://github.com/daybrush/moveable

**Comment by jmsegrev** [comment]
@daybrush awesome project, thanks for your hard work.

For anyone looking for the selection component, here is a direct link. https://github.com/daybrush/selecto

**Comment by daybrush** [comment]
@jmsegrev 
Oh sorry. I'm posting the wrong link, the selecto is right. Thank you :)
