### ISSUE TITLE
Demo 是否有源码

### ISSUE THREAD

**Issue by zhxiaoyu123** [daybrush/moveable#595]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

**Comment by 18595439829** [comment]
https://github.com/daybrush/moveable/issues/569
看一下这个是否是你需要的?

**Comment by zhxiaoyu123** [comment]
是的 是这一个 谢谢

**Comment by salahcgp** [comment]
full-scale demo on svelte

**Comment by hqiaozhang** [comment]
请问下https://daybrush.com/moveable Dome有源码吗
