### ISSUE TITLE
feature: add snap lines feature to the Angular lib as well...

### ISSUE THREAD

**Issue by born2net** [daybrush/moveable#60]
feature: add snap lines feature to the Angular lib as well...
thanks for a great lib
Sean

**Comment by daybrush** [comment]
@born2net 

See the following documents:
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-snappable

**Comment by born2net** [comment]
TX... I was under the impression it is not supported under the Angular lib.
closing!
