### ISSUE TITLE
Ables triggering drag event when I click on the ables, I want to trigger moveable events only from the target inside, not from the ables. Is that possible ?

### ISSUE THREAD

**Issue by PramodIndusved** [daybrush/moveable#600]
## Environments
* Framework name: typescript
* Moveable Component version: 0.25.0

## Description
I am using a moveable component for dragging elements on screen, I am also using ables to show delete, clone functionality for the same element. But the problem arises when I click on the ables, drag event in triggering. I dont want any moveable events from the ables. Is that possible ?

**Comment by daybrush** [comment]
@PramodIndusved 

* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.

If it doesn't work, set `clickable` to false.
