### ISSUE TITLE
Moveable blue box displaced compared to the target

### ISSUE THREAD

**Issue by olavblj** [daybrush/moveable#602]
## Environments
* Framework name: React
* Framework version: 17.0.1
* Moveable Component version: 0.27.3

## Description
When trying to drag and drop a circle in an SVG, I am not able to make the blue box track the circle correctly. The SVG needs to be panable and rotatable, which is why I cannot set both parent and container to document.body. If I set both to document.body, the box tracks the circle correctly, but rotation and panning does not work.

Is this an issue in the framework, or is there any way I can get the desired behaviour?

![Screen Recording 2022-01-27 at 10 32 40 mov-679FCBE3-38D9-4D83-A903-683EBAB20056](https://user-images.githubusercontent.com/10499451/151332028-eb9ce57a-cc0d-4d5a-982c-d2a7ce55b2ff.gif)

**Comment by PaleHazy** [comment]
I am having the same

**Comment by daybrush** [comment]
@olavblj 

* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.
