### ISSUE TITLE
Moveable area click doesn't work

### ISSUE THREAD

**Issue by liran19960215** [daybrush/moveable#606]
## Environments
* Framework name: moveable
* Framework version: 0.26.0
* Component name: 
* Component version:
* Testable Address(optional): 

## Description
when I select group targets, and after drag them, then I want to click on target of them, but the event is not work.
I used like this in my vue project:
```
this.groupMoveable = new Moveable(document.querySelector('.canvas-screen'), {
        ...MOVEABLE_OPTIONS,
        dragArea: true,
        target: curSliceTargetGroup,
});
this.groupMoveable
    .on('click', this.handleDragGroupClick)
    .on('dragGroupStart', this.handleDragGroupStart)
    .on('dragGroup', this.handleDragGroup)
    .on('dragGroupEnd', this.handleDragGroupEnd)
    .on('scaleGroupStart', this.handleScaleGroupStart)
    .on('scaleGroup', this.handleScaleGroup)
    .on('scaleGroupEnd', this.handleScaleGroupEnd);
```
But the 'click' listener doesn't work, which means the 'handleDragGroupClick' method is not be arrived.
Which effect I want to achieve is like the issue [(https://github.com/daybrush/moveable/issues/309)], I want to change the value of contentEditable in the 'handleDragGroupClick' method, but now I don't know how to do.

Look forward to your reply, thanks a lot!

**Comment by daybrush** [comment]
@liran19960215 

Use `clickGroup` instead of `click` in group.

Also, a bug related to click is being fixed, but if a group is used, the event listener of the target does not work.
```js
target.addEventLister("click");
```

**Comment by daybrush** [comment]
@JoseLuisRNP  

* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0


moveable's new version is released.

If not work, set clickable to false.

**Comment by daybrush** [comment]
@liran19960215 


* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.

If it doesn't work, set clickable to false.
