### ISSUE TITLE
Are onDragGroupStart/onScaleGroupEnd/onRotateGroupEnd/onResizeGroupEnd etc. missing property `events`?

### ISSUE THREAD

**Issue by xiaoyuze88** [daybrush/moveable#610]
## Environments
* Framework name:
* react-moveable
* Framework version:
* 0.30.3

## Description
In `onDragGroupStart|onDragGroup`, there is a property called `events`, where we can access the `OnDragStart|OnDrag` event for each child nodes in group, however in the `onDragGroupEnd`  I don't find this `events` property.

Is this an accidental missing? Because I need to access each child nodes's `OnDragEnd['lastEvent']`, to store the latest position to my state, so missing this `events` make it very tricky..

Maybe should do something like this? Just like what's done in `dragGroup`.
![image](https://user-images.githubusercontent.com/5201649/155284909-846d1de2-e4aa-4e97-9553-c8f5d254afa8.png)

**Comment by daybrush** [comment]
@xiaoyuze88 

* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0
moveable's new version is released.

Check it again. Thank you :)
