### ISSUE TITLE
OnResize problem

### ISSUE THREAD

**Issue by Raserad** [daybrush/moveable#618]
## Environments
* Framework name: vue
* Framework version: 3.0.0
* Moveable Component version: vue3-moveable 0.2.3
* Testable Address(optional):

## Description
OnResize width and height takes only rounded values but other values (OnDrag, OnRotate, OnScale) can take decimal values. It produce mistakes when i try move object and resize it to fit something.

**Comment by Raserad** [comment]
@daybrush i tried set throttleResize to 0 but it takes only rounded values again.

**Comment by Raserad** [comment]
![image](https://user-images.githubusercontent.com/34380690/157332907-e6dffc49-9594-46be-99db-7613daecf241.png)
https://github.com/daybrush/moveable/blob/master/packages/react-moveable/src/react-moveable/ables/Resizable.ts#L413
I guess this problem occurs here. width and height rounded.

**Comment by Raserad** [comment]
@daybrush so can you look it?

**Comment by daybrush** [comment]
@Raserad

The browser's css width and height are rounded, so the round function is used. onDrag, onRotate, and onScale are not rounded because they are transforms.

**Comment by Raserad** [comment]
@daybrush but is it possible to make without round? When i set throttleResize to 0, in example.

**Comment by Raserad** [comment]
> @daybrush but is it possible to make without round? When i set throttleResize to 0, in example.

@daybrush so what?

**Comment by daybrush** [comment]
@Raserad 
I will add an option to not round in the next version.

**Comment by Raserad** [comment]
> @Raserad I will add an option to not round in the next version.

Thank you very much

**Comment by daybrush** [comment]
@Raserad 

* `moveable` 0.29.1
* `react-moveable` 0.32.1
* `preact-moveable` 0.31.1
* `ngx-moveable` 0.25.1
* `svelte-moveable` 0.19.1
* `lit-moveable` 0.6.1
* `vue-moveable` 2.0.0-beta.8
* `vue3-moveable` 0.4.1

moveable's new version is released.

`throttleResize={0}` is possible.
