### ISSUE TITLE
Can I know which direction control handle do I drag?

### ISSUE THREAD

**Issue by ZRichV** [daybrush/moveable#619]
## Environments
* Framework name: Vue
* Framework version: V2
* Moveable Component version:  0.27.2

## Description
When I drag direction control handle which is ne,  nw, sw or se, I want to do scale keeping ratio. But I want to do scale not keeping ratio or do resize when I drag direction control handle which is n, s, w, e. So I want to know which direction control handle do I drag, to realize different functions. Can I get that? Or any other suggestion？

**Comment by raarts** [comment]
@ZRichV Did you find out how to get the direction?
