### ISSUE TITLE
Setting `setFixedDirection` while resizing

### ISSUE THREAD

**Issue by seahindeniz** [daybrush/moveable#623]
## Environments
* Moveable Component version: 0.27.2

## Description

Setting the `setFixedDirection` with `onResizeStart` event is possible, but seems like we can't change its value without clicking on the handler again to change its value.

I have a case where I need to change `setFixedDirection` value while I'm resizing an element (possibly with `onResize` event). For example, when I resize an element, I want to hold `Shift` button to toggle the value so that I can have more functionality.
Is there are way that we can achieve this without forcing the `onResizeStart` event to be triggered again?

**Comment by daybrush** [comment]
@seahindeniz 

okay I'll add this function on resize event.

**Comment by daybrush** [comment]
* `moveable` 0.29.1
* `react-moveable` 0.32.1
* `preact-moveable` 0.31.1
* `ngx-moveable` 0.25.1
* `svelte-moveable` 0.19.1
* `lit-moveable` 0.6.1
* `vue-moveable` 2.0.0-beta.8
* `vue3-moveable` 0.4.1

moveable's new version is released.

use `beforeResize` event
```jsx
onBeforeResize={e => {
   // direction
   e.setFixedDirection([0, 0]);
}}
```
