### ISSUE TITLE
Incorrect transform calculation when `setFixedDirection` set to `[0, 0]`

### ISSUE THREAD

**Issue by seahindeniz** [daybrush/moveable#624]
## Environments
* Moveable Component version: 0.28.0
* Testable Address(optional):
  * https://codesandbox.io/s/moveable-scale-fixed-direction-issue-tcmlfo
  * https://codesandbox.io/s/moveable-resize-fixed-direction-issue-0m50uo

## Description
When I use `setFixedDirection([0, 0])` mouse position is not calculated correctly or as it should.
I have recorded my screen and tried to show how to reproduce this issue and how I expect it to work: https://www.loom.com/share/2d92fa6230774874a64bf441dbb30bde

**Comment by daybrush** [comment]
@seahindeniz 

* `moveable` 0.29.1
* `react-moveable` 0.32.1
* `preact-moveable` 0.31.1
* `ngx-moveable` 0.25.1
* `svelte-moveable` 0.19.1
* `lit-moveable` 0.6.1
* `vue-moveable` 2.0.0-beta.8
* `vue3-moveable` 0.4.1

moveable's new version is released.


try it again.

**Comment by seahindeniz** [comment]
Hey @daybrush! Thanks for the new release. One small issue though. Seems like the corner handle, still doesn't follow the mouse cursor. 

Here:

https://user-images.githubusercontent.com/5789670/163562150-0df6bd1b-7c45-4c77-a48a-c67da31f0f52.mp4

From what I can tell, and logically speaking, the handle should also follow the mouse cursor as like the non-setFixedDirection version of it.

Like this:

![bcfcc108-ce57-47c5-990d-146fd46e4b7c](https://user-images.githubusercontent.com/5789670/163562598-56946cf4-4dfa-4b1e-9d05-3c3ef6fc5781.gif)

**Comment by daybrush** [comment]
@seahindeniz 

* `moveable` 0.29.2
* `react-moveable` 0.32.2
* `preact-moveable` 0.31.2
* `ngx-moveable` 0.25.2
* `svelte-moveable` 0.19.2
* `lit-moveable` 0.6.2
* `vue-moveable` 2.0.0-beta.9
* `vue3-moveable` 0.4.2

moveable's new version is released. Try it again.

**Comment by seahindeniz** [comment]
Hey @daybrush it is still the same 
https://codesandbox.io/s/moveable-scale-fixed-direction-issue-0-29-2-863kcr

![96cf7e1a-7dfc-4c46-a780-aaa4a8ec9a30](https://user-images.githubusercontent.com/5789670/163829377-155ff8cd-57fe-45ed-bf0d-5249f4eb0edc.gif)

**Comment by daybrush** [comment]
@seahindeniz 

* `moveable` 0.29.3
* `react-moveable` 0.32.3
* `preact-moveable` 0.31.3
* `ngx-moveable` 0.25.3
* `svelte-moveable` 0.19.3
* `lit-moveable` 0.6.3
* `vue-moveable` 2.0.0-beta.10
* `vue3-moveable` 0.4.3


moveable's new version is released. Check it again.

**Comment by seahindeniz** [comment]
Hey @daybrush, it works as expected and perfectly ✨ Kudos to you!

**Comment by seahindeniz** [comment]
Hey @daybrush 
I've found a case that the fixed issues still persist.
Here:

https://user-images.githubusercontent.com/5789670/165495299-e94b7ff4-91ef-4921-b296-84f791d7acaf.mov

https://codesandbox.io/s/moveable-resize-fixed-direction-issue-0-29-4-q3hyri

**Comment by daybrush** [comment]
@seahindeniz 


Test 0.29.8 version. It works, but there is another minor problem. I'll check.

**Comment by daybrush** [comment]
@seahindeniz 

0.29.9 is released. Check it again.

**Comment by seahindeniz** [comment]
Hi @daybrush, seems like the last issue still persist
https://codesandbox.io/s/moveable-resize-fixed-direction-issue-0-29-9-gyj9gq

https://user-images.githubusercontent.com/5789670/172699822-e318bc58-4789-47c9-a05f-cef42e4b6d7d.mp4

**Comment by daybrush** [comment]
@seahindeniz 

Set target's style

```css
    position: absolute;
    top: 0;
    left: 0;
```

**Comment by seahindeniz** [comment]
It's working quite nice 🙏🏻 Thank you, @daybrush 

https://codesandbox.io/s/moveable-resize-fixed-direction-issue-0-33-0-success-wsh1d8
