### ISSUE TITLE
Crop with opacity for non-croped section

### ISSUE THREAD

**Issue by acabreragnz** [daybrush/moveable#627]
## Description
@daybrush is there a way with the current API to show the non-clipped section with some opacity?

Something like this:
![Screenshot from 2022-03-21 13-31-00](https://user-images.githubusercontent.com/6330366/159310713-0a4dee3b-b767-4701-a96f-62d96ac99daf.png)

**Comment by jamesopti** [comment]
@acabreragnz Did you figure this out? I'm wondering the same thing!

**Comment by acabreragnz** [comment]
@jamesopti we are using vuejs, we finally created two instances of moveable, one for the clippable (native functionality) and another one for the background with less opacity, we called it "ghost" and we sync its position when moving the main moveable instance. Let me know if you need further information

**Comment by acabreragnz** [comment]
> @acabreragnz how are you syncing the position when moving the main moveable instance?

We are using vuex, we dispatch an action to sync the ghost, and the ghost repaint with the new position. Let me know if you need further details.
