### ISSUE TITLE
Moveable dragStart method error

### ISSUE THREAD

**Issue by jaacu** [daybrush/moveable#629]
## Environments
* Framework name: vue
* Framework version: 2.6.11
* Moveable Component version: vue-moveable@2.0.0-beta.6
* Testable Address(optional):

## Description

A change on the latest version 2.0.0-beta.6 causes the next error when trying to call the `dragStart` method on the moveable instance at the `selectEnd` event on the selecto component (Selecto version: vue-selecto 1.14.0) 
 
![imagen](https://user-images.githubusercontent.com/17502865/159804365-de153838-de46-4785-9cee-f45465b3413d.png)

This problem only happens on the last version, the previous versions vue-moveable@2.0.0-beta.4 and vue-moveable@2.0.0-beta.5 both works as expected.

This is an example of what the `selectEnd` event handler looks like, which worked fine in the previous versions
![imagen](https://user-images.githubusercontent.com/17502865/159804909-2711f90a-d08f-45e2-b815-0366fe03ccdf.png)

**Comment by XM-zombie** [comment]
targets

**Comment by XM-zombie** [comment]
moveable targets delay

**Comment by daybrush** [comment]
@jaacu 
Sorry, there seems to be a problem in the process of changing the target. I will fix it soon.

**Comment by daybrush** [comment]
@jaacu 


* `moveable` 0.29.1
* `react-moveable` 0.32.1
* `preact-moveable` 0.31.1
* `ngx-moveable` 0.25.1
* `svelte-moveable` 0.19.1
* `lit-moveable` 0.6.1
* `vue-moveable` 2.0.0-beta.8
* `vue3-moveable` 0.4.1

moveable's new version is released.

Try it again.
