### ISSUE TITLE
Hide controls selectively

### ISSUE THREAD

**Issue by outOFFspace** [daybrush/moveable#63]
Is it possible? For example, for some elements, I need the only left middle and right middle controls. I can do this with CSS, but it would be great to have this feature in API.

**Comment by daybrush** [comment]
@outOFFspace 

The answer to your question may be found in this document.
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-custom-css
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#moveable-control

And I made an example for you to use easily.
https://codepen.io/daybrush/pen/dyyXjyV

**Comment by outOFFspace** [comment]
But in this case, controls will be hidden for all of the elements.

**Comment by daybrush** [comment]
@outOFFspace 

So what do you say is similar to this?

https://github.com/daybrush/moveable/issues/53

**Comment by daybrush** [comment]
@outOFFspace 

Perhaps the first one will be difficult. I will proceed with the second option.

**Comment by daybrush** [comment]
@outOFFspace 

`moveable` 0.10.0 is released.

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#show-partial-control-box

1. you can use renderDirections for showng partial control box.
2. or set className
3. or use important

thank you :)
