### ISSUE TITLE
"form element select" moveable not working

### ISSUE THREAD

**Issue by mhaciyev** [daybrush/moveable#631]
Hello i need make "form element select" moveable but not working. I record video for this problem.I hope help me fix this problem.

this is video -> [https://streamable.com/0bibdv](https://streamable.com/0bibdv)

**Comment by daybrush** [comment]
@mhaciyev 
okay. I'll fix it soon. Thank you :)

**Comment by metion** [comment]
> 

Not at all. Thank you too for fix)

**Comment by daybrush** [comment]
@metion 
* `moveable` 0.29.1
* `react-moveable` 0.32.1
* `preact-moveable` 0.31.1
* `ngx-moveable` 0.25.1
* `svelte-moveable` 0.19.1
* `lit-moveable` 0.6.1
* `vue-moveable` 2.0.0-beta.8
* `vue3-moveable` 0.4.1

moveable's new version is released.

Try it again.
