### ISSUE TITLE
我的程序出现问题

### ISSUE THREAD

**Issue by w934423231** [daybrush/moveable#636]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

**Comment by w934423231** [comment]
My original program uses 2.0.0-beta 5 can be used, but I don't know when new exceptions appear. I've tried other versions with different exception prompts

**Comment by w934423231** [comment]
![image](https://user-images.githubusercontent.com/38958128/163096252-19c22d40-72e4-4118-aba9-c6792776932c.png)

**Comment by w934423231** [comment]
![image](https://user-images.githubusercontent.com/38958128/163097074-4b1a1551-0e3e-4ecb-8c77-3fd72335e61f.png)

**Comment by daybrush** [comment]
@w934423231 

* `moveable` 0.29.0
* `react-moveable` 0.32.0
* `preact-moveable` 0.31.0
* `ngx-moveable` 0.25.0
* `svelte-moveable` 0.19.0
* `lit-moveable` 0.6.0
* `vue-moveable` 2.0.0-beta.7
* `vue3-moveable` 0.4.0

moveable's new version is released.

Try it again.

**Comment by w934423231** [comment]
> @w934423231
> 
> * `moveable` 0.29.0
> * `react-moveable` 0.32.0
> * `preact-moveable` 0.31.0
> * `ngx-moveable` 0.25.0
> * `svelte-moveable` 0.19.0
> * `lit-moveable` 0.6.0
> * `vue-moveable` 2.0.0-beta.7
> * `vue3-moveable` 0.4.0
> 
> moveable's new version is released.
> 
> Try it again.

OK, I'll try it. Thank you
