### ISSUE TITLE
Possible bug when requesting resizable and keepRatio

### ISSUE THREAD

**Issue by GrigoreAlexandru** [daybrush/moveable#638]
In my setup (vue + core moveable, no vue-moveable) I've been debugging a weird bug that happens sporadically (about 1/3 of the time) where requesting a resizable with offsetWidth and offsetHeight, I'm getting other values for width and height in the onResize callback . I've narrowed the problem down to 2 triggers:

1. Requesting a resizable with different values that the current target has in DOM
2. keepRatio = true

This seems to happen on Chrome (100.0.xxx..) and Opera sporadically, I have the request on a mounted hook in a vue component so refreshing a few times triggers the bug. I'm thinking moveable somehow forces the previous ratio: Reads offsetWidth, calculates height on previous ratio and ignores offsetHeight? It should ignore keepRatio if both offsetWidth and offsetHeight are present.

This is speculation based on my setup, sadly for the time being I can't setup a sandbox to showcase the bug.

**Comment by daybrush** [comment]
@GrigoreAlexandru 
I'm sorry. If keepRatio is enabled, the ratio is maintained as one size
 I will add an option to force it by adding the keepRatio attribute of the request.

**Comment by daybrush** [comment]
@GrigoreAlexandru 

* `moveable` 0.29.0
* `react-moveable` 0.32.0
* `preact-moveable` 0.31.0
* `ngx-moveable` 0.25.0
* `svelte-moveable` 0.19.0
* `lit-moveable` 0.6.0
* `vue-moveable` 2.0.0-beta.7
* `vue3-moveable` 0.4.0
moveable's new version is released.


use keepRatio option
```js
moveable.request({ keepRatio: false, offsetWidth: 11, offsetHeight: 11 }, true);
```
