### ISSUE TITLE
Bug: Group resizing throw error

### ISSUE THREAD

**Issue by nzbin** [daybrush/moveable#639]
## Environments
* Framework name:
* Framework version:
* Moveable Component version: 0.29.1
* Testable Address(optional):

## Description

Please check the storybook demo

https://daybrush.com/moveable/storybook/?path=/story/group--resizable

**Comment by daybrush** [comment]
@nzbin 

* `moveable` 0.29.2
* `react-moveable` 0.32.2
* `preact-moveable` 0.31.2
* `ngx-moveable` 0.25.2
* `svelte-moveable` 0.19.2
* `lit-moveable` 0.6.2
* `vue-moveable` 2.0.0-beta.9
* `vue3-moveable` 0.4.2
moveable's new version is released. And Demo is fixed. Thank you :)
