### ISSUE TITLE
Q: Do we expect React 18 to be supported out of the box? 

### ISSUE THREAD

**Issue by zaqqaz** [daybrush/moveable#640]
## Description
As I can see current expected (based on [dev dependencies](https://github.com/daybrush/moveable/blob/master/packages/react-moveable/package.json#L98)) version of react is ^16.  Though moveable fully supports 17.

Do we expect react 18 to be supported with concurrent rendering mode? 

ps. I haven't tested yet, but will do and share the feedback.

**Comment by daybrush** [comment]
@zaqqaz 

react-moveable 0.32.3 is released. And Tested in react 18 concurrent mode and it works.

**Comment by golnaaz73** [comment]
@daybrush 
Hi
I was using react-moveable 0.33.0 with react 17.0.1 and everything was working fine. After upgrading to react 18.2.0, I faced a problem, while dragging/rotating/resizing ,moveable frame moves with delay relative to the target .Do you have any idea why this happens?

**Comment by daybrush** [comment]
@golnaaz73 


See https://github.com/daybrush/moveable/tree/master/packages/react-moveable#react-18-concurrent-mode

**Comment by golnaaz73** [comment]
@daybrush 
Thank you for the fast reply.
It fixed my problem. thank you so much
