### ISSUE TITLE
Dynamically modify properties

### ISSUE THREAD

**Issue by danielangelo** [daybrush/moveable#642]
## Environments
* Framework name: React 
* Framework version: 18.0.0
* Moveable Component version: 0.32.3
* Testable Address(optional):

## Description
**Is it possible to update the properties dynamically ? ( width, height, position, rotation , etc)**
_For example for the rotation, if I have a field and I modify the value inside to rotate my component._

**Comment by daybrush** [comment]
@danielangelo 

are you saying this?

https://daybrush.com/moveable/storybook2/?path=/story/request-ables-through-a-method--draggable-template

see the request method

**Comment by danielangelo** [comment]
I think so. Thank you so much. Will get back to you after I try it out.
