### ISSUE TITLE
What browsers are supported?

### ISSUE THREAD

**Issue by bartblast** [daybrush/moveable#65]
Hey! The "Basic Support" section lists Webkit Safari (Mac, iOS) support, does it mean that Chrome, Firefox and IE are not supported yet in the react-moveable package?

**Comment by born2net** [comment]
I think that goes without saying :)
if you don't support Chrome you might as well call it quits :)

**Comment by daybrush** [comment]
@bartblast 
You can think so.

moveable supports major browsers. (Firefox, Chrome, Safari, ..)
but IE has not tested.

Previously, safari was added because it was not supported.

**Comment by born2net** [comment]
The next version of IE we powered by chromium so everything will work as expected

**Comment by daybrush** [comment]
@born2net

Now edge is chromium, but IE is a built-in browser.... :(

**Comment by bartblast** [comment]
Got it! Thanks for the info.
