### ISSUE TITLE
 error in running the Vue

### ISSUE THREAD

**Issue by mm58508536** [daybrush/moveable#650]
## Environments
* Framework name: vue
* Framework version: 2.6.14
* Moveable Component version: moveable@0.29.4 & vue-moveable@beta 
* Testable Address(optional):

## Description
I just run demo in my project, but always throw this error:
![image](https://user-images.githubusercontent.com/13673143/165517479-c4c9c21e-5d54-48e9-b7ec-e91e627292af.png)
 
the same situation  when i use vue-moveable 
but when  I use  [probil](https://github.com/probil)/[vue-moveable](https://github.com/probil/vue-moveable)(based on the  moveable 0.25.2) , It works.
I find this problem occurred in the  react-simple-compat
![image](https://user-images.githubusercontent.com/13673143/165518248-62a4eaed-0a0f-47af-95fc-cf948135c5d3.png)
Comparison of correct and wrong objects ：
![image](https://user-images.githubusercontent.com/13673143/165518451-116a6ace-124b-4f65-908a-46cfa128938b.png)

**Comment by daybrush** [comment]
@mm58508536 

 * `lit-moveable` 0.6.6
* `moveable` 0.29.6
* `preact-moveable` 0.31.6
* `react-compat-moveable` 0.17.6
* `react-moveable` 0.32.5
* `svelte-moveable` 0.21.6
* `vue-moveable` 2.0.0-beta.13
* `vue3-moveable` 0.4.6
* `ngx-moveable` 0.26.6

moveable's new version is released. Try it again.

**Comment by mm58508536** [comment]
It works! thank you for your support! but I found

**Comment by daybrush** [comment]
@mm58508536 

I'll fix commonjs bug. Thank you :)

**Comment by daybrush** [comment]
@mm58508536 

Test 2.0.0-beta.17 version. Thank you :)
