### ISSUE TITLE
OnResizeEnd problem

### ISSUE THREAD

**Issue by alteregoist** [daybrush/moveable#654]
## Environments
* Framework name:
* Framework version:
* Moveable Component version: react-moveable 0.32.5
* Testable Address(optional):

## Description

"drag" property is missing from lastEvent in onResizeEnd.

**Comment by daybrush** [comment]
@alteregoist 

lastEvent does not exist unless resize occurs. Check if lastEvent exists.

**Comment by alteregoist** [comment]
```
        onResizeEnd={({ lastEvent }) => {
            if (lastEvent) {
                const { target, drag } = lastEvent;
                const { left, top, width, height } = drag;
                ...
            }
        }}
```

"drag" property is missing

**Comment by daybrush** [comment]
@alteregoist 

Can you take a picture of the lastEvent value and show it to the console?

**Comment by alteregoist** [comment]
on react-moveable 0.31.1
<img width="626" alt="Screen Shot 2022-05-02 at 2 48 28 AM" src="https://user-images.githubusercontent.com/2988045/166158183-09179a01-1e3e-472c-a5ba-eebb33dd2907.png">


on react-moveable 0.32.6
<img width="690" alt="Screen Shot 2022-05-02 at 2 51 36 AM" src="https://user-images.githubusercontent.com/2988045/166158205-52ce38da-87b2-49fe-b042-bfa901d64bb6.png">

**Comment by daybrush** [comment]
@alteregoist 

I checked the bug. Try updating to version 0.32.7.

**Comment by alteregoist** [comment]
Thank you :)
