### ISSUE TITLE
Group functionality not working in React 18

### ISSUE THREAD

**Issue by Gbuomprisco** [daybrush/moveable#656]
## Environments
* Framework name: React
* Framework version: 18
* Moveable Component version: 0.32.7
* Testable Address(optional): https://codesandbox.io/s/fancy-forest-gk9bq8?file=/src/App.tsx

## Description

Hi! First of all, thank you for this package and your hard work on this; it's incredibly helpful to what I am working on. I'd love to sponsor this as soon as I can.

The issue I am having is due to the group functionality not working in React 18 (dev mode, I have not tested a production build yet).

The issue can be reproduced at https://codesandbox.io/s/fancy-forest-gk9bq8?file=/src/App.tsx

Unfortunately, I have tried debugging but without much success :|

Thank you!

**Comment by daybrush** [comment]
@Gbuomprisco 

I have released version 0.32.8-beta.2. wanna test it?

**Comment by Gbuomprisco** [comment]
Hey, @daybrush, thank you for sorting this out so quickly. It works perfectly in my project, but not in the Sandbox above (maybe I'm doing something wrong there though?). 

I'll give it another try and close the issue :) Thanks again! Wonderful work.

**Comment by daybrush** [comment]
@Gbuomprisco 

Your code sandbox seems to be version 0.32.8-beta.1. I tried it with beta.2 and it works.

**Comment by Gbuomprisco** [comment]
It totally works! Thanks again
