### ISSUE TITLE
countinue select in moveable-area  error

### ISSUE THREAD

**Issue by mm58508536** [daybrush/moveable#657]
## Environments
* Framework name:vue
* Framework version:2.6.14
* Moveable Component version:vue-moveable
* Testable Address(optional):

## Description
when i add dom which in 'moveable-area' (moveable group) :
![image](https://user-images.githubusercontent.com/13673143/167147768-1b768537-3c76-4613-b2e6-773c851a8f1a.png)

![image](https://user-images.githubusercontent.com/13673143/167147035-27710490-338b-4cd9-b5f5-bd58b39d742f.png)
![image](https://user-images.githubusercontent.com/13673143/167148084-d7f57d45-983b-49bc-9fa2-18af5df8141f.png)

**Comment by daybrush** [comment]
@mm58508536 

I think the moveable group was changed during dragging.

It is not recommended to change during dragStart => drag => dragEnd.

**Comment by mm58508536** [comment]
thanks for your support! I review code  and confirm that have not change group during dragStart => drag => dragEnd.
my situation：
use vue-selecto select 2 dom  =>  update moveable.target => shift+click continue select 1 dom which in   'moveable-area'  => after update moveable.target then throw that error
