### ISSUE TITLE
sveltekit typescript ssr sample

### ISSUE THREAD

**Issue by msh2050** [daybrush/moveable#658]
## Environments
* Framework name: sveltekit
* Framework version: 
* Moveable Component version:
* Testable Address(optional):

## Description
can you please provide a working sample with sveltekit in typescript.

**Comment by daybrush** [comment]
@msh2050 

https://daybrush.com/moveable/storybook/?path=/story/basic--clippable


Is there a problem with the svelte kit?

**Comment by msh2050** [comment]
thanks for the help;
the sample you mention did not work, even in sandbox
find other one : https://daybrush.com/moveable/storybook/?path=/story/use-state-at-the-last-event--resizable
