### ISSUE TITLE
Clippable (circle): Constrain clip to max when dragging outside of bounds 

### ISSUE THREAD

**Issue by jamesopti** [daybrush/moveable#659]
## Environments
* Framework name: react-moveable
* Framework version: latest
* Moveable Component version: Clippable
* Testable Address(optional): https://daybrush.com/moveable/storybook/index.html?path=/story/basic--clippable
 (circle, clipTargetBounds, clipArea)

## Description
When clipping with a circle pattern, I'd like to prevent the size from decreasing when the cursor is dragged out of the bounds. Id like it to just max out and stay there. The current behavior feels like a strange user experience.

Also, if you drag far enough across the origin, the circle appears to grow outside of the bounds. See the GIF below

## Expected Behavior

When `clipTargetBounds: true`, ignore mousemove's outside of the bounds.

![clippable-circle](https://user-images.githubusercontent.com/3718812/167259424-035c6239-b565-49ce-9204-1e092489d507.gif)

**Comment by jamesopti** [comment]
Any idea when this fix will be merged?

**Comment by daybrush** [comment]
@jamesopti 

* `lit-moveable` 0.6.9
* `moveable` 0.29.9
* `preact-moveable` 0.31.9
* `react-compat-moveable` 0.17.9
* `react-moveable` 0.32.9
* `svelte-moveable` 0.21.9
* `vue-moveable` 2.0.0-beta.20
* `vue3-moveable` 0.4.9
* `ngx-moveable` 0.26.9

moveable's new version is released.
