### ISSUE TITLE
How to use Boundaries with angular ?

### ISSUE THREAD

**Issue by JulesVelo** [daybrush/moveable#66]
Hello,
I use this code in Angular but it does not affect the behaviour of the draggable elements :
(HTML)
  [dragArea]="true"
  [bounds]="{left: 0, right: 500, top: 0, bottom: 500}"

Can you explain why ?

**Comment by daybrush** [comment]
@JulesVelo 


Activate the `snappable` option.

[snappable]="true"

**Comment by JulesVelo** [comment]
Thanks you very much, it works well
great module
