### ISSUE TITLE
Clippable (inset): Option to keepRatio when clipping using the SHIFT key

### ISSUE THREAD

**Issue by jamesopti** [daybrush/moveable#660]
## Environments
* Framework name: react-moveable
* Framework version: latest
* Moveable Component version: Clippable
* Testable Address(optional): 

## Description

When using clippable, I cant seem to figure out how to maintain the aspect ratio. For my use case, I'd like to detect the shift key and then lock the current aspect ratio.

I see this is possible in `onResizeStart` with Resizable, but I cant figure out how to do it with Clippable.

Seems related to #442 - It would be nice to change it during clipping (and have it then locked to the current aspect ratio), but first just being able to lock the aspect ratio on start would be useful.

***FYI** Awesome library! Been quite happy with it so far*

**Comment by daybrush** [comment]
thanks :) I was aware of an issue with this feature.

I'm going to add keepRatio to Clippable as well.

**Comment by daybrush** [comment]
@jamesopti 

* `lit-moveable` 0.6.9
* `moveable` 0.29.9
* `preact-moveable` 0.31.9
* `react-compat-moveable` 0.17.9
* `react-moveable` 0.32.9
* `svelte-moveable` 0.21.9
* `vue-moveable` 2.0.0-beta.20
* `vue3-moveable` 0.4.9
* `ngx-moveable` 0.26.9

moveable's new version is released. keepRatio is applied.

**Comment by corey34** [comment]
@daybrush this has caused a different issue. Could you make it so that keepRatio can be applied differently for clippable and resizeable?

In my case, I want true for resizeable and false for clippable but that does not seem possible now.

Thanks

**Comment by daybrush** [comment]
@corey34 

write a new issue I'll add it in the next release.
