### ISSUE TITLE
Snappable (+ Resizeable): vertical guidelines don't show up when resizing in horizontal direction

### ISSUE THREAD

**Issue by jamesopti** [daybrush/moveable#661]
## Environments
* Framework name: react-moveable
* Framework version: latest
* Moveable Component version: Resizable
* Testable Address(optional):

## Description

I'm only allowing resizing in the E, W direction (keepRatio=true) but would like to enable snapping based on horizontal **_AND_** vertical lines.

How can i make the vertical guidelines appear for the circles above/below? Is this possible?

<img width="521" alt="Screen Shot 2022-05-08 at 9 35 42 AM" src="https://user-images.githubusercontent.com/3718812/167305996-679f64f2-bd84-4aad-8f4c-ff85843e591a.png">

## Code setup

```ts
<Moveable
      ref={(instance) => {
        moveableInstance.current = instance
      }}
      className={wrapperClassName}
      target={imageWrapperRef.current}
      renderDirections={['e', 'w']}
      keepRatio={true}
      draggable={false}
      resizable={true}
      snappable={true}
      isDisplayInnerSnapDigit={false}
      isDisplaySnapDigit={false}
      snapGridHeight={5}
      snapGridWidth={5}
      snapDirections={true}
      elementSnapDirections={true}
      // horizontalGuidelines={['0%', '50%', '100%']}
      // verticalGuidelines={[0, 50, 100, 150, 200]}
      elementGuidelines={Array.from(
        document.querySelectorAll('[data-image-node-element]')
      )}
      origin={false}
      onResizeStart={() => {
      }}
      onResize={({ target, width }) => {
      }}
      onResizeEnd={({ target }) => {
      }}
    />
```

**Comment by daybrush** [comment]
@jamesopti 

it seem like a bug. i'll check it.

**Comment by jamesopti** [comment]
> @jamesopti
> 
> it seem like a bug. i'll check it.

@daybrush This was actually an issue with our own CSS (`overflow-y: hidden`). Removing that fixes the issue!

A related request would be documentation around the CSS classes used for each of the guideline types. For example, I want to change the color of the dashed lines but can't seem to find the right classes. Happy to file another issue for that.
