### ISSUE TITLE
Display controls only when the element is selected (clicked)

### ISSUE THREAD

**Issue by ghominejad** [daybrush/moveable#666]
## Environments
* Framework name: React
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

By default all controls are shown on the all elements on the page but I need them to be shown only when an element is active (user clicked on it);

Thank you

**Comment by JigarPrajpati** [comment]
How you solved this issue sir in vanila javascript?

**Comment by ghominejad** [comment]
@JigarPrajpati By the selecto tool
