### ISSUE TITLE
Preventing click behavior on Anchor element

### ISSUE THREAD

**Issue by seahindeniz** [daybrush/moveable#671]
## Environments
* Framework name: Vanilla
* Moveable Component version: 0.29.8
* Testable Address(optional): https://codesandbox.io/s/moveable-drag-issue-rfkfdb

## Description
I have a target element that I'm trying to move by using the draggable feature. However, the dragging behavior creates a problem when my target element contains an anchor (`<a>`) element.

I have tried preventing its click behavior, but non has worked. 
Here's a record of how it works and doesn't

https://user-images.githubusercontent.com/5789670/171035737-14ce08ff-edf9-4043-817c-0b5fc041cc86.mov

**Comment by daybrush** [comment]
@seahindeniz 

I'll add a prop so that I can block the click event.
