### ISSUE TITLE
How to prevent Drag on middle mouse (wheel) down?

### ISSUE THREAD

**Issue by Crazy-Ivan** [daybrush/moveable#674]
## Environments
* Framework name: React
* Framework version: 16.13.1
* Moveable Component version: 0.30.3
* Testable Address(optional):

## Description
Hello,

I would like to drag elements only when the left mouse button is down. Currently, dragging is fired on the left mouse button down and the middle one (wheel). I tried to find options to define it but it looks like there is no such thing. In one post I found info that there should be a function stop() attached to event onDragStart but it seems to not be true. I Can't find such function in the object and in the documentation. Does anyone have an idea how this simple thing could be nicely achieved?

**Comment by daybrush** [comment]
@Crazy-Ivan 

I'll fix it. Thank you :)

**Comment by daybrush** [comment]
@Crazy-Ivan 

* `lit-moveable` 0.7.0
* `moveable` 0.30.0
* `preact-moveable` 0.32.0
* `react-compat-moveable` 0.18.0
* `react-moveable` 0.33.0
* `svelte-moveable` 0.22.0
* `vue-moveable` 2.0.0-beta.21
* `vue3-moveable` 0.5.0
* `ngx-moveable` 0.27.0

moveable's new version is released. Try it again.
