### ISSUE TITLE
svelte-moveable@0.22.0 not support vite v2.9.12

### ISSUE THREAD

**Issue by Soya-xy** [daybrush/moveable#680]
When I updated the svelte-moveable@0.22.0 dependency, the terminal reported an error

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/56671014/174260495-cc1047dd-76e2-4c2e-a146-e3eba853427b.png">

**Comment by daybrush** [comment]
@Soya-xy 

Thank you for reporting bug.

Test 0.22.1-beta.0 version.
