### ISSUE TITLE
Elements mapped through the Web Components slot do not display borders correctly

### ISSUE THREAD

**Issue by LHongHui** [daybrush/moveable#684]
## Environments
* Framework name: moveable
* Framework version: 0.30.0
* Moveable Component version: 0.30.0
* Testable Address(optional): https://stackblitz.com/edit/js-b1r49n

## Description
When using the Web Components slot to map elements, the elements display in the correct position, but the Moveable border does not.
![image](https://user-images.githubusercontent.com/74345779/175274015-17cf458f-60ea-4ab2-b83a-5ed89894d4df.png)

**Comment by LHongHui** [comment]
@daybrush Hello, is this an unsolvable problem?

**Comment by duoduoObama** [comment]
@daybrush moveable and interact.js this problem exists

**Comment by daybrush** [comment]
@duoduoObama @LHongHui 

it is yet
is being tested

**Comment by daybrush** [comment]
@duoduoObama @LHongHui 

* `lit-moveable` 0.9.0
* `moveable` 0.32.0
* `preact-moveable` 0.34.0
* `react-compat-moveable` 0.20.0
* `react-moveable` 0.35.0
* `svelte-moveable` 0.24.0
* `vue-moveable` 2.0.0-beta.26
* `vue3-moveable` 0.7.0
* `ngx-moveable` 0.29.0

moveable's new version is released.
Suppport custom element. Check it again.

**Comment by LHongHui** [comment]
> @duoduoObama @LHongHui
> 
> * `lit-moveable` 0.9.0
> * `moveable` 0.32.0
> * `preact-moveable` 0.34.0
> * `react-compat-moveable` 0.20.0
> * `react-moveable` 0.35.0
> * `svelte-moveable` 0.24.0
> * `vue-moveable` 2.0.0-beta.26
> * `vue3-moveable` 0.7.0
> * `ngx-moveable` 0.29.0
> 
> moveable's new version is released. Suppport custom element. Check it again.

Hello, the Bounds property doesn't seem to work properly when using the web Components internal element as the root node of Moveable.
Testable Address(optional): https://stackblitz.com/edit/js-b1r49n

**Comment by daybrush** [comment]
@LHongHui 

Are you saying that the target being bounds is wrong?

I guess it's because you set the snapContainer to document.body?

**Comment by LHongHui** [comment]
> @LHongHui
> 
> Are you saying that the target being bounds is wrong?
> 
> I guess it's because you set the snapContainer to document.body?

Thank you, I have found the parameter configuration error.
