### ISSUE TITLE
[docs] it shoud be useResizeObserver not Zoom

### ISSUE THREAD

**Issue by jamaluddinrumi** [daybrush/moveable#685]
## Environments
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Package Manager:  `yarn@1.22.19`
- movable version: `"vue-moveable": "^2.0.0-beta.5",`
------------------------------
## Description

just a small typo in there, where it shoud be `useResizeObserver` not `Zoom`

![Screen Shot 2022-06-26 at 7 01 04 PM](https://user-images.githubusercontent.com/446780/175813373-5edaa034-e657-4b26-bac7-8891a94253d1.png)

**Comment by daybrush** [comment]
@jamaluddinrumi 

Thank you :). I'll fix next patch.

**Comment by daybrush** [comment]
@jamaluddinrumi 


* `lit-moveable` 0.8.0
* `moveable` 0.31.0
* `preact-moveable` 0.33.0
* `react-compat-moveable` 0.19.0
* `react-moveable` 0.34.0
* `svelte-moveable` 0.23.0
* `vue-moveable` 2.0.0-beta.22
* `vue3-moveable` 0.6.0
* `ngx-moveable` 0.28.0

moveable's new version is released. Thank you :)

**Comment by jamaluddinrumi** [comment]
@daybrush  youre so responsive & have done a great work i should say
