### ISSUE TITLE
Rotating a group of elements from the center of the group doesn't work

### ISSUE THREAD

**Issue by Shmebulocked** [daybrush/moveable#687]
## Environments
* Framework name: React
* Framework version: 16.8
* Moveable Component version: latest
* Testable Address(optional): https://codesandbox.io/s/group-rotation-forked-goo6bq

## Description
I'm using moveable and scene.js in React, and this is a demo of what I'm working on right now: 
https://codesandbox.io/s/group-rotation-forked-goo6bq

When I'm trying to rotate this group of elements by hand, everything's working just fine, and the rotation works as expected.

But when I hit play on the scene.js timeline, rotation works differently. If you try it yourself, you can see the transform-origin of the rotation is not at the center of the group, it's at the center of the whole page.

Is there any solution to this predicament?

**Comment by daybrush** [comment]
@Shmebulocked 

This is because the 3 elements are grouped and the moveable is rotated. Both translate and rotate are corrected to move together.

It must be different from the timeline with CSS.

**Comment by Shmebulocked** [comment]
Can you share your codesandbox @daybrush fixing this?

**Comment by Shmebulocked** [comment]
@daybrush 

I know that; What I do not know, is how can I control the moveable group with scene.js?

I've made some modifications:
https://codesandbox.io/s/group-rotation-22gynx

And when you hit play, the rotation works as expected. It rotates around the middle of the group.

But that's not a real solution. As soon as I change the position of the group (translate it to somewhere else by hand), the origin of rotation will change.

I still couldn't find any solution to this.

**Comment by daybrush** [comment]
@Shmebulocked 

In Scene.js, the rotate value of the container is changed.
Moveable will be difficult because the 3 target translate and rotate values change.


https://codesandbox.io/s/group-rotation-forked-5gtknz?file=/src/App.tsx

**Comment by Shmebulocked** [comment]
@daybrush 

You're right.

Your solution is great, but again, there are some edge cases. Imagine we're having a different translation for any of the elements. In that case, the origin will change drastically, as you can see in this example:

https://codesandbox.io/s/group-rotation-forked-7ovijg?file=/src/App.tsx

Mind that I've forked this from your solution, and I've only changed line 39 of `App.tsx`.
