### ISSUE TITLE
Map control box to a certain moveable instance / provide a container for the control box divs

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#689]
## Environments
* Framework name: Vanilla
* Framework version:
* Moveable Component version: 0.30.0 (but applies to any)
* Testable Address(optional):

## Description
Is there a way to specify the container of the control box? I am saving the resulted HTML to the backend and use it to restore it at a later time. In the resulted HTML, the control box divs are present and linked to a non existing moveable instance. If there was a way to map a control box to a certain moveable instance, I would be able to correctly remove it before storing the HTML to the server. Also, specifying a container for the control boxes could also work. Is there any way to achieve this?

Thank you!

**Comment by daybrush** [comment]
@alexconstantin 

Not a perfect hydrate, but use the portalContainer option.


```html
<div class="container">
     <div class="moveable-control-box"></div>
</div>
```

```js
new Moveable(container, {
    portalContainer: controlBox,
});
```

**Comment by alexconstantin** [comment]
Thank you!
