### ISSUE TITLE
Question: Cancel selecto moveable element bound

### ISSUE THREAD

**Issue by chenp1204** [daybrush/moveable#692]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description
![image](https://user-images.githubusercontent.com/29192482/177308961-5d122994-c2c2-4688-8f72-8325c4559ee8.png)

Hi @daybrush ,
When i use selecto and moveable, i select the moveable element,
i only want to  display outside bound, but don't want inside element display the bound, 
what can i do, i don't find config item

**Comment by chenp1204** [comment]
Thank you for your hard work !

**Comment by daybrush** [comment]
* `lit-moveable` 0.8.0
* `moveable` 0.31.0
* `preact-moveable` 0.33.0
* `react-compat-moveable` 0.19.0
* `react-moveable` 0.34.0
* `svelte-moveable` 0.23.0
* `vue-moveable` 2.0.0-beta.22
* `vue3-moveable` 0.6.0
* `ngx-moveable` 0.28.0


@chenp1204 

moveable's new version is released.

use `hideChildMoveableDefaultLines` to true
