### ISSUE TITLE
Guidelines aren't shown when edge dragging

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#694]
## Environments
* Framework name: Vanilla
* Framework version: - 
* Moveable Component version: 0.30.0
* Testable Address(optional): https://codesandbox.io/s/elegant-ully-m4lcri?file=/src/index.ts

## Description
Dragging from the center of the element correctly shows the guidelines. However, using edgeDraggable = true and triggering the dragging from one of the edges fails to show guidelines. In this case, snapping works, it's just the lines which are not shown.

**Comment by daybrush** [comment]
@alexconstantin 

* `lit-moveable` 0.8.0
* `moveable` 0.31.0
* `preact-moveable` 0.33.0
* `react-compat-moveable` 0.19.0
* `react-moveable` 0.34.0
* `svelte-moveable` 0.23.0
* `vue-moveable` 2.0.0-beta.22
* `vue3-moveable` 0.6.0
* `ngx-moveable` 0.28.0

moveable's new version is released.

**Comment by alexconstantin** [comment]
Thank you! I can no longer reproduce this issue.

**Comment by 1393254712** [comment]
When using edgeDraggable=true in ngx movable, the guide will still not be displayed

**Comment by 1393254712** [comment]
> @alexconstantin
> 
> * `lit-moveable` 0.8.0
> * `moveable` 0.31.0
> * `preact-moveable` 0.33.0
> * `react-compat-moveable` 0.19.0
> * `react-moveable` 0.34.0
> * `svelte-moveable` 0.23.0
> * `vue-moveable` 2.0.0-beta.22
> * `vue3-moveable` 0.6.0
> * `ngx-moveable` 0.28.0
> 
> moveable's new version is released.

When using edgeDraggable=true in ngx movable, the guide will still not be displayed
