### ISSUE TITLE
Error thrown when edge dragging

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#695]
## Environments
* Framework name: Any
* Framework version: -
* Moveable Component version: 0.30.0
* Testable Address(optional): https://codesandbox.io/s/focused-minsky-914jyi

## Description
When having resizable: true, edge: true and edgeDraggable: true, an error is thrown when I try to resize / drag from the edge of the object. How should we handle such cases?

Stack trace:
gesto.esm.js:433 Uncaught TypeError: Cannot read properties of undefined (reading 'prevClients')
    at __proto.move (gesto.esm.js:433:29)
    at setCustomDrag (moveable.esm.js:399:28)
    at Object.dragControl (moveable.esm.js:5471:38)
    at eval (moveable.esm.js:8248:35)
    at Array.filter (<anonymous>)
    at triggerAble (moveable.esm.js:8241:28)
    at Object.eval [as listener] (moveable.esm.js:8349:22)
    at eval (event-emitter.esm.js:87:12)
    at Array.forEach (<anonymous>)
    at __proto.emit (event-emitter.esm.js:86:28)
    at Gesto._this.onDrag (gesto.esm.js:302:34)

Thank you!

**Comment by daybrush** [comment]
@alexconstantin 

edge and edgeDraggable cannot be used together. use only one

**Comment by daybrush** [comment]
@alexconstantin 

I'll add this feature to next release.

**Comment by daybrush** [comment]
@alexconstantin 

* `lit-moveable` 0.8.0
* `moveable` 0.31.0
* `preact-moveable` 0.33.0
* `react-compat-moveable` 0.19.0
* `react-moveable` 0.34.0
* `svelte-moveable` 0.23.0
* `vue-moveable` 2.0.0-beta.22
* `vue3-moveable` 0.6.0
* `ngx-moveable` 0.28.0

moveable's new version is released.

use edge as array type.
```js
edge={["n", "s"]}
```

**Comment by alexconstantin** [comment]
Works perfectly. Thank you so much!

**Comment by alexconstantin** [comment]
Hello @daybrush! This issue reappeared in 0.38.1. Please check this code: 
https://codesandbox.io/s/cocky-dijkstra-hg86m0?file=/src/index.ts

Thank you!

**Comment by daybrush** [comment]
@alexconstantin 

* `@moveable/helper` 0.0.4
* `lit-moveable` 0.16.0
* `moveable` 0.39.0
* `preact-moveable` 0.41.0
* `react-compat-moveable` 0.27.0
* `react-moveable` 0.42.0
* `svelte-moveable` 0.31.0
* `vue-moveable` 2.0.0-beta.48
* `vue3-moveable` 0.14.0
* `ngx-moveable` 0.36.0

moveable's new version is released.

**Comment by alexconstantin** [comment]
Thank you! It's working again in 0.39.0
