### ISSUE TITLE
Wrong control box position (only) on safari

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#696]
## Environments
* Framework name: Any
* Framework version: -
* Moveable Component version: 0.30.0
* Testable Address(optional): https://codesandbox.io/s/holy-rain-xpcc8z?file=/src/styles.css

## Description
Please check the sandbox link in Safari (15.5, but I think all of them are affected). It seems that when a parent container has scale set, the control boxes are misplaced (setting scale to 1 leads to correct positioning). Is there any way around this without setting the parent container to another element (in my case, I need to keep document.body as my parent element)? Also, calling updateRect() does not solve this issue.

Thank you!

**Comment by alexconstantin** [comment]
![Screenshot 2022-07-10 at 15 43 53](https://user-images.githubusercontent.com/6921332/178145385-7cab3a85-d486-472e-bc16-36a815bca00a.png)

**Comment by daybrush** [comment]
@alexconstantin 

Confirmed. I will fix it in the next release along with the Edge issue.

**Comment by daybrush** [comment]
@alexconstantin 

* `lit-moveable` 0.8.0
* `moveable` 0.31.0
* `preact-moveable` 0.33.0
* `react-compat-moveable` 0.19.0
* `react-moveable` 0.34.0
* `svelte-moveable` 0.23.0
* `vue-moveable` 2.0.0-beta.22
* `vue3-moveable` 0.6.0
* `ngx-moveable` 0.28.0

moveable's new version is released. Check it again.

**Comment by alexconstantin** [comment]
Works perfectly. Thank you!
