### ISSUE TITLE
Different behaviour for E-W resizing in older versions

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#697]
## Environments
* Framework name: React 
* Framework version: 17
* Moveable Component version: 0.24.1 vs 0.30.0
* Testable Address(optional):

OLD: https://codesandbox.io/s/magical-fermi-6cn47?file=/src/App.js
NEW: https://codesandbox.io/s/inspiring-dan-2cj1kj

## Description
I was checking the resize behaviour presented in this issue: https://github.com/daybrush/moveable/issues/363 and I saw that left-right resizing was keeping the top-left / top-right corners in place, regardless of the rotation. In the new codesandbox URL I only updated the versions from react-moveable 0.21.1 to 0.30.0 and scenejs from 1.4.3 to 1.6.0 and it seems that the corners (top left / top right) get moved based on the element height.

Is there any way to achieve that same effect in the latest version of the library?

Thank you!

**Comment by alexconstantin** [comment]
![Screenshot 2022-07-13 at 00 11 53](https://user-images.githubusercontent.com/6921332/178596173-18128187-192d-4b5c-8270-53b35c16a282.png)
![Screenshot 2022-07-13 at 00 12 22](https://user-images.githubusercontent.com/6921332/178596241-127f58d1-851c-40dd-96fa-86454e618139.png)

**Comment by daybrush** [comment]
@alexconstantin 

If direction is [1, x], call `e.setFixedDirection([-1, -1]);`
If direction is [-1, x], call `e.setFixedDirection([1, -1]);`

**Comment by alexconstantin** [comment]
Works like a charm. This is a really amazing library. Thank you!
