### ISSUE TITLE
when i press a right click, dragging starts

### ISSUE THREAD

**Issue by swimyoung** [daybrush/moveable#7]
Thanks for awesome project!

I found an issue about a  dragging feature. when i press a right click it starts dragging like below.
![](https://media.giphy.com/media/TJZQEeMvMCedVpyPJI/giphy.gif)

I think [drag](https://github.com/daybrush/drag/blob/master/src/drag.ts#L78) library needs a moving distance feature.(mousedown -> mousemove = trigger drag start)

**Comment by daybrush** [comment]
@swimyoung 
Oh Thank you for reporting bug.

We're going to reflect it right away.
It will be deployed tomorrow with bug fixes and new features.

**Comment by daybrush** [comment]
@swimyoung 
0.4.1 has been released. Right-click issues are resolved.

And 3D Transform support and Warpable feature are added.
https://github.com/daybrush/moveable/releases/tag/0.4.1

**Comment by swimyoung** [comment]
it works well 
thanks!
