### ISSUE TITLE
How can I keep it from going beyond the boundaries when scaling?

### ISSUE THREAD

**Issue by t4y3** [daybrush/moveable#70]
Hello

Even if you set bounds, the boundary will protrude by scale or resize.
Is there a way to deal with it?

Example
https://codesandbox.io/s/moveablescallingbounds-wtihy

**Comment by daybrush** [comment]
@t4y3
 
try this
```js

const transform = {
  translate: [0, 0],
  scale: [1, 1],
};
function draw(target) {
  const { translate, scale } = transform;

  target.style.transform = `translate(${translate[0]}px, ${translate[1]}px) scale(${scale[0]}, ${scale[1]})`;
}
draggable.on("scaleStart", ({ set, dragStart }) => {
  set(transform.scale);
  dragStart && dragStart.set(transform.translate);
});
draggable.on("scale", ({ target, drag, scale }) => {
  transform.scale = scale;
  transform.translate = drag.beforeTranslate;
  draw(target);
});
draggable.on("dragStart", ({ set }) => {
  set(transform.translate);
});
draggable.on("drag", ({ target, beforeTranslate }) => {
  transform.translate = beforeTranslate;
  draw(target);
});

```

**Comment by t4y3** [comment]
@daybrush 
Thank you for the answer.
I tried the following method, but there is one problem.
It ignores keepRatiio.

For example, when the bounds top or bottom is reached, only width is scaled, ignoring keepRatio, is this a specification?

https://codesandbox.io/s/moveablescallingbounds-wtihy

**Comment by daybrush** [comment]
@t4y3 

Thank you. We will fix the bug as soon as possible.

**Comment by daybrush** [comment]
@t4y3 
moveable 0.10.0 is released.

Please check again. Thank you :)

**Comment by t4y3** [comment]
@daybrush 
Thank you. It worked as expected! :)

**Comment by nums** [comment]
Hello,

I have the same problem with keepRatio set to false :
https://codesandbox.io/s/moveablescallingbounds-lh6ms

No problem on drag, but when I scale i'm out of the limit (it's working great when I keep ratio)

**Comment by daybrush** [comment]
@nums 

Thank your for bug reporting. I'll fix it soon.

**Comment by daybrush** [comment]
@nums


`moveable` 0.13.2 is released.

Please check again. Thank you :)
