### ISSUE TITLE
keepRatio for both clippable and resizeable

### ISSUE THREAD

**Issue by corey34** [daybrush/moveable#701]
Could you make it so that keepRatio can be applied differently for clippable and resizeable?

In my case, I want true for resizeable and false for clippable but that does not seem possible now.

Thanks

**Comment by daybrush** [comment]
@corey34 
* `lit-moveable` 0.9.0
* `moveable` 0.32.0
* `preact-moveable` 0.34.0
* `react-compat-moveable` 0.20.0
* `react-moveable` 0.35.0
* `svelte-moveable` 0.24.0
* `vue-moveable` 2.0.0-beta.26
* `vue3-moveable` 0.7.0
* `ngx-moveable` 0.29.0


moveable's new version is released.


https://daybrush.com/moveable/storybook2/?path=/story/advanced-clippable--keepratio-for-both-clippable-and-resizeable

```jsx
                   resizable={{
                        keepRatio: true,
                    }}
                    clippable={{
                        keepRatio: false,
                    }}
```

**Comment by corey34** [comment]
Thanks @daybrush
