### ISSUE TITLE
[feature request] Resume moveable object after destroy method

### ISSUE THREAD

**Issue by tissi-2** [daybrush/moveable#71]
I would like to resume dragging, scaling and roatating the target after having called the destroy method. Is it possible with and without going back to the original state? I kind of think of a 

1. reset method that restores the original place, orientation and scale of the moveable object
2. method that makes the object moveable again with the current place and orientation and scale

**Comment by daybrush** [comment]
@tissi-2 
In moveable, the rotation, scale, and translate values are not known. Only the user knows.

The moveable only knows the computed transform and only needs to set the target without having to resume it.

If you have an example of CodePen, I will help you.

**Comment by tissi-2** [comment]
Hi Younkue,

 isn‘t it possible to store the values relative to the dragArea‘s top left position into a variables when calling onDragEnd, onScaleEnd, onRotateEnd? I would like to store an image with these values into a database to let it be displayed in the same way in the dragArea after reading the values out of the database.

I am a couple of days not at home. As soon as I am back, I will send you the code.

Generally I have some questions:
Every js code that I put behind the moveable code isn‘t executed. Why?

Is the moveable code interpreted by firefox and chrome or do I need to convert it into „older“ javascript code? I get an error when using exactly the code from the pen, and moveable is behaving strange. Is it because of babel js? 

Greetings from Los Angeles



> Am 26.10.2019 um 07:22 schrieb Daybrush (Younkue Choi) <notifications@github.com>:
> 

﻿
@tissi-2
In moveable, the rotation, scale, and translate values are not known. Only the user knows.

The moveable only knows the computed transform and only needs to set the target without having to resume it.

If you have an example of CodePen, I will help you.

**Comment by daybrush** [comment]
@tissi-2 

It's still an experimental method. But this is a method that will be officially added in 0.10.0.


```ts
const rectInfo = moveable.getRect();

export interface RectInfo {
    pos1: number[];
    pos2: number[];
    pos3: number[];
    pos4: number[];
    left: number;
    top: number;
    width: number;
    height: number;
}
```

**Comment by andreasvirkus** [comment]
I think it's possible to set the `moveable.target` to `null` to temporarily disable and then to set the same (original) target again when you need to continue from the same position, no?
