### ISSUE TITLE
Clicking is not working after resizing

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#713]
## Environments
* Framework name: Vanilla
* Framework version: - 
* Moveable Component version: 0.34.2 
* Testable Address(optional): https://codesandbox.io/s/suspicious-murdock-1hnl0m?file=/src/index.ts

## Description
Please try clicking the button. It displays the current date in MS format. After triggering a resize using one of the handles, clicking the button is not possible anymore. I believe the event is prevent defaulted.

Some notes:
1. It didn't happen with older versions (0.32.0 works ok)
2. I believe it has something to do with "preventClickEventOnDrag" flag (setting it to false fixes the issue).
3. If you drag the element after resizing it, the button starts working again.

Thank you!

**Comment by vohzd** [comment]
I was just about to report this very same issue. (Using version 0.34.2)

Downgrading to` 0.32.0` or `preventClickEventOnDrag: false` resolves the issue.

**Comment by daybrush** [comment]
@alexconstantin  @vohzd 

moveable's new version is released. Check it again.

**Comment by alexconstantin** [comment]
@daybrush The button is clickable again starting with 0.34.3 version. Thank you! However, I'm seeing a different issue now:

0.34.3: https://codesandbox.io/s/recursing-thunder-zfjc4m?file=/src/index.ts
0.32.0: https://codesandbox.io/s/autumn-moon-8uwhpz

An additional click event is being propagated to the body, when executing a resize like this: start using handle, but move the mouse outside of the target and finish the resize over the body, not over the resize trigger itself. Please check this loom for details: https://www.loom.com/share/84d8a63ceac04b83a3cd24195a470e4c (however it seems the cursor is not recorded property)

**Comment by daybrush** [comment]
@alexconstantin 


moveable's new version is released.

Check it again.

**Comment by alexconstantin** [comment]
Working perfectly in 0.35.0. Thank you!
