### ISSUE TITLE
React Moveable ref set target with setState not working

### ISSUE THREAD

**Issue by ngocducdim** [daybrush/moveable#714]
Hi, in React I have the moveable ref, when mousedown to the component I use `setState` to set the `target` but it not affect:
![image](https://user-images.githubusercontent.com/97713182/183011311-52e9f1be-f440-426d-8ea4-59f3228f9db2.png)
The codesanbox:
https://codesandbox.io/embed/vibrant-mestorf-j5byc1?fontsize=14&hidenavigation=1&theme=dark

**Comment by daybrush** [comment]
@ngocducdim 

sorry but you can't use moveable.setState

You must use the target={target} prop.

**Comment by daybrush** [comment]
@ngocducdim 

I'll add waitTarget method for dragStart.

```jsx
moveable.waitTarget().then(() => {
    moveable.dragStart(e);
});
setTarget(target);
```

**Comment by daybrush** [comment]
@ngocducdim 

moveable's new version is released.

`waitToChangeTarget` method is added.

```jsx
moveable.waitToChangeTarget().then(() => {
    moveable.dragStart(e);
});
setTarget(target);
```

**Comment by ngocducdim** [comment]
Update the sandbox it work, but when integrate with my project
```
moveable.waitToChangeTarget().then(() => {
    console.log('updated');
});
```
the console never log the 'updated', maybe because I use Selecto package, thanks you anyway for the work

**Comment by daybrush** [comment]
@ngocducdim 

call setTargets after waitToChangeTarget

**Comment by ngocducdim** [comment]
I have call setTargets, but still can't work, my small part of the code:
![image](https://user-images.githubusercontent.com/97713182/184620114-a5dd4db2-a30f-4f94-b7d6-b274e4a5199d.png)
![image](https://user-images.githubusercontent.com/97713182/184620719-133bf973-c7c0-4b10-a605-009218f18eb5.png)
![image](https://user-images.githubusercontent.com/97713182/184620339-e41223f2-eec5-4636-9617-28a5fb81c397.png)
- Try to select:
![image](https://user-images.githubusercontent.com/97713182/184620504-46fbe082-67a6-4386-a2ad-fad32b1ef6bb.png)
- The console output:
![image](https://user-images.githubusercontent.com/97713182/184620764-e17489d6-6df8-4e99-810f-7aaccf516eb5.png)

**Comment by daybrush** [comment]
@ngocducdim 


Okay. I'll check it again.

**Comment by daybrush** [comment]
@ngocducdim 

0.38.2 was released. check it again.

**Comment by ngocducdim** [comment]
It works now, thank you for your fix!
