### ISSUE TITLE
moveable bound 관련

### ISSUE THREAD

**Issue by 0hhanum** [daybrush/moveable#715]
Environments
Framework name: vue.js / moveable / selecto
Framework version: vue2 / 0.24.6 / 1.11.1
Description
안녕하세요.

moveable / selecto 감사히 사용하고 있습니다.

거의 혼자서 이 많은 레포를 관리하시는게 존경스럽네요

현재 moveable / selecto 를 동시에 사용중인데,

moveable 컨테이너, selecto 컨테이너의 속성을 모두 position: relative 로 둬도

moveable 객체가 컨테이너 밖까지 drag가 가능하고 transform 에 의해 무한히 스크롤이 생겨버립니다.

인수인계 없이 혼자 진행중인 프로젝트를 떠안게 된 상황이라 전체 소스코드 파악이 힘들어 moveable 의 bound 속성으로 해결할까 하

는데, 이를 left/right 값이 아니라 컨테이너 영역으로 & 여러 영역에 설정하는 방법이 있을지 질문드립니다. 감사합니다.

**Comment by 0hhanum** [comment]
+ 추가)

bound 를 여러 영역에 설정하는 것과 더불어
moveable Container (Moveable 클래스의 parentElement) 를 여러 개로 지정할 수 있는 방법이 있는지 질문드립니다.

group oprtion 은 moveable target 에 대한 옵션인데, target 말고 container 를 여러 개 설정할 수 있는 방법이 있는지 / 혹은 여러개의 Moveable 객체를 생성해야만 가능한지도 질문드립니다.

항상 감사합니다~

**Comment by daybrush** [comment]
@0hhanum 

안녕하세요. left, right, top, bottom을 통해 bounds를 설정할 수 있고 스냅 컨테이너를 지정하여 설정할 수 있습니다.

```js
snapContainer={snap, bounds의 기준이 되는 컨테이너}
bounds={{ position: "css", left: 0, right: 0}}
```

container는 moveable-control-box의 엘리먼트가 있는 위치이기 때문에 잘 다루지 않는 값입니다.

`group oprtion 은 moveable target 에 대한 옵션인데, target 말고 container 를 여러 개 설정할 수 있는 방법`은 무슨 의미인지 잘 모르겟습니다.

여려 영역을 설정한다는 것이 target당 bounds영역 1:1 로 설정하고 싶다는 것 같습니다.
이런 경우에는 Moveable의 객체를 여러개 생성해야만 가능할 것 같습니다.

**Comment by 0hhanum** [comment]
여려 영역을 설정한다는 것이 target당 bounds영역 1:1 로 설정하고 싶다는 것 같습니다. => 맞습니다

항상 정확한 답변 감사합니다

**Comment by 0hhanum** [comment]
`이런 경우에는 Moveable의 객체를 여러개 생성해야만 가능할 것 같습니다.`

해당 방식으로 진행하니 각 영역별로 잘 작동합니다.

웹페이지 내에 섹션을 나눠 영역별로 Moveable 객체를 생성해 적용하고, 각 섹션을 fold/unfold 할 수 있는 구조인데(unfold 시 영역 전체가 `display:none;` 처리)

a영역의 target 을 움직였는데 b영역의 moveable-control-box 가 반응할 때가 있어 drag 는 가능하지만 정상적으로 moveable-control-box가 표시되지 않습니다

각 Moveable 객체별로 설정을 달리해줘야 할까요?

control-box 관련 API 확인이 안되어 재질문드립니다.

감사합니다.

**Comment by 0hhanum** [comment]
제 코드가 잘못됐었네요 ㅎㅎ;

해결했습니다

감사합니다
