### ISSUE TITLE
[Bug] target's translate style will change when rotating

### ISSUE THREAD

**Issue by HZZformGD** [daybrush/moveable#716]
## Environments
* Framework name: React 
* Framework version: 16.8
* Moveable Component version: react-moveable@0.38.0
* Testable Address(optional): <a href="https://codesandbox.io/s/stupefied-bush-ckobtk?file=/src/App.tsx">https://codesandbox.io/s/stupefied-bush-ckobtk?file=/src/App.tsx</a>

## Description

if i initial target dom style with rotate, like this 
```html
 <div
          className="target"
          style={{
            top: "0px",
            left: "0px",
            width: "50px",
            height: "50px",
            transform: "rotate(0deg) translate(150px, 100px)"
          }}
        >
          Target
        </div>
```
the target style translate will change  when i rotate the moveable-box. but without initial style (rotate)  , it will not change the target's translate. i don't know why.

**Comment by HZZformGD** [comment]
@daybrush  is it a bug? or it is normal. I want to keep the target translate style when i initial the target's style with rotate. Because i will edit after getting data from service

**Comment by HZZformGD** [comment]
Add another point.  do the same thing by using Vanilla, it will not change the translate. it looks like some bug in react-moveable

**Comment by daybrush** [comment]
@HZZformGD 

hello.


The first is when rotate => translate is set.
The second is when translate => rotate is set.

The first one changes the translate value by rotating, but the second one doesn't need to change the translate value.

**Comment by HZZformGD** [comment]
@daybrush  thx~  i use (left, top) to save the coordinate instead of (translateX, translateY).
