### ISSUE TITLE
 Can moveable-control-box specify a container?

### ISSUE THREAD

**Issue by tolerance-go** [daybrush/moveable#72]
![image](https://user-images.githubusercontent.com/37258382/67617663-f8959680-f817-11e9-9c6f-329e522ef116.png)

Z-index Yes, I am not very familiar with it, but as shown in the figure, it can't exceed the level of the container.

The excess is not selected, but this feature is great, Do you agree？

Or there are other implementations, please let me know, thank you very much!

**Comment by tolerance-go** [comment]
![image](https://user-images.githubusercontent.com/37258382/67617717-aacd5e00-f818-11e9-80ac-21b382c2f915.png)

like this, i find it in [Framer](https://www.framer.com/)

by the way, this is a project I think is cool.

**Comment by daybrush** [comment]
@tolerance-go 

Test demo: 

https://codepen.io/daybrush/pen/rNNwwpZ

enable => `dragArea: true`
