### ISSUE TITLE
SVG g elements and getSVGGraphicsOffset

### ISSUE THREAD

**Issue by deltastudiobr** [daybrush/moveable#722]
## Environments
* Framework name: Angular
* Framework version: 14.0.6
* Moveable Component version: ngx-moveable 0.32.1
* Testable Address(optional): https://codesandbox.io/s/gallant-platform-u4h41f?file=/src/app/app.component.html

## Description
I was using the ngx-moveable version 0.25.0 and when i was selecting an svg "g" element the control box was placed correctly (with origin at center). Now i've updated to 0.32.1 and the controlbox is misplaced. I've searched the reason by comparing the changes from 0.25.0 to 0.32.1 source code and found that in the method "getSVGGraphicsOffset" (in utils.tsx) was added a condition to always return [0,0,0,0] if the tagName is equal to "g", so i commented this condition ("|| el.tagName.toLowerCase() === "g"")  and everything works again as expected. I would like to know the reason why this was added, if this was intentional and if is possible to remove this, because with this condition the offset of the "g" element will never be calculated causing the controlbox to be misplaced when the target is a "g" element.

**Comment by daybrush** [comment]
@deltastudiobr 

I'll fix within this week. Thank you :)

**Comment by daybrush** [comment]
@deltastudiobr 


ngx-moveable's new version is released. Check it again.

**Comment by deltastudiobr** [comment]
> @deltastudiobr
> 
> ngx-moveable's new version is released. Check it again.

@daybrush thank you. It's working now.
