### ISSUE TITLE
Resize 관련

### ISSUE THREAD

**Issue by 0hhanum** [daybrush/moveable#723]
Environments
Framework name: vue.js / moveable / selecto
Framework version: vue2 / 0.24.6 / 1.11.1
Description

안녕하세요.

moveable 이용해  자유롭게 컨텐츠를 배치할 수 있는 캔버스를 개발중입니다.

캔버스 상태를 save 할 필요가 있어 사용자가 save 시 moveable target 내의 svg 파일과 target의 position을 저장했다가

저장 캔버스를 불러오기 시 target 을 생성하고 그 내부에 저장했던 svg 를 innerHTML 로 삽입하여 load 기능을 구현하려 합니다.

위치, 크기, svg 까지 load 하는데는 성공했는데

이렇게 innerHTML 을 이용해 내부를 변경하니 drag, rotate 는 정상 작동하나 resize 시 target 과 moveable-control-box 는 리사이징 되지만 내부 요소(svg)들은 리사이징 적용이 안되는 현상이 발생합니다.

글로만 설명하니 파악이 힘드시겠지만 혹 예상 원인이나 관련 설정이 있다면 알려주시면 감사하겠습니다.

**Comment by 0hhanum** [comment]
```javascript
moveable.on("resize", (target, drag, width, height, inputEvent) => {
...
}
```

```inputEvent``` 를 비교해보면 직접 생성한(캔버스 앱의 기존 로직을 통해) 컨텐츠와 저장된 innerHTML을 붙여넣어 불러온 컨텐츠의 inputEvent.path 에 차이가 납니다.  서로 다른 target 을 바라보고 있는 것으로 추정되는데 확인해보면 좋을 부분이 있으면 알려주시면 감사하겠습니다.

**Comment by daybrush** [comment]
@0hhanum 

안녕하세요.

resizable은 style의 width, height 값을 조절하는데 사용합니다.

svg의 내부요소는 style의  width, height가 없기 때문에  resize는 사용이 불가능합니다.

대신 scale로 사용해보시길 바랍니다.

**Comment by 0hhanum** [comment]
@daybrush 

감사합니다.

그런데 직렬화해 저장된 svg 를 innerHTML 로 붙여넣은 target 말고 캔버스 앱 로직으로 생성한 target 내의 svg는 resize가 정상 동작했습니다.

moveable 말고 외부 로직에서 이유를 찾아보는게 나을까요?

**Comment by daybrush** [comment]
@daybrush 

아 혹시 "g", "path", "rect" 태그에 해당하는 엘리먼트를 리사이즈 하는게 아니라 `<svg>` 태그를 리사이즈 하는 건가요?

**Comment by 0hhanum** [comment]
@daybrush

아니요 정확한 구조는

![image](https://user-images.githubusercontent.com/79507291/185279317-c7ae732a-5f76-4dcf-b8d3-417575977794.png)

과 같이 되어있고

div 전체를 직렬화해 스토리지에 저장했다가 불러오기시 

이를 역직렬화해 moveable target 생성 후 target 의 innerHTML 으로 붙여넣고 있습니다.

기존에는 resize가 내부까지 잘 동작하나 innerHTML 을 이용해 불러온 객체의 resize 는 target과 control-box 에만 적용됩니다.\

감사합니다

**Comment by daybrush** [comment]
@0hhanum 

 햇갈리긴 한데  resize 는 target과 control-box 에만 적용되는게 맞는 것 같은데요.
target을 svg에 설정하는 것도 아닌 것 같습니다.

inputEvent의 path가 다른건 다른 이유를 찾아봐야 할 것 같습니다.
간단한 예시가 있었으면 좋긴하네요.

**Comment by 0hhanum** [comment]
@daybrush 

넵 외부에서 이유를 찾아보겠습니다. 감사합니다
