### ISSUE TITLE
[Question] Cannot drag with react-dnd  

### ISSUE THREAD

**Issue by dim0147** [daybrush/moveable#724]
## Environments
* Framework name: "react-moveable": "^0.38.2",, "react-dnd": "^16.0.1",
## Description
Hi, I'm building a project have a timeline like a video editor, the track item will move between rows so  I use` react-moveable` to resize the component (change the duration) and use `react-dnd` to change the position between rows, the `react-moveable` version `33.0` allow me `drag` using `react-dnd` (the yellow one) and also `resize` using `react-moveable` (the two blue dots) like the image below but when upgrading to `0.38.2` this doesn't allow me to `drag` anymore, I have turned off all the `preventClick` props for `<Moveable /> ` but still can't drag, any suggestion? Thank you
![image](https://user-images.githubusercontent.com/44487221/185388689-c5aac642-c62b-4558-941e-668283d1f240.png)

**Comment by daybrush** [comment]
@dim0147 

react-moveable 0.38.3 is released. Check it agian.

**Comment by dim0147** [comment]
It works now. Thank you!
