### ISSUE TITLE
[Question] How should we handle a large number of Moveable instances?

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#725]
Hello, @daybrush!

In our project we got to a point where we are using about 270-300 different Moveable instances at the same time. This leads to overall slowness in the app, while dragging elements, etc.

The reasons for using different Moveable instances (and not changing the target while clicking a certain element) are these:

1. We need to handle instant dragging while clicking an element (not click, and afterwards re-click to start the dragging).
2. We need to handle element hover:
a) show edgeDraggable/ resize edge lines, in order to support instant dragging/ resizing, without selecting - same as point 1
b) we use the dragArea property to show the actual element rect bounds (the same way that Canva does when an element is partially of page)
3. We need to support multi selection (similar to grouping)

Can you please advise on how we could achieve improved performance in these scenarios? Is there a way to only work with a single Moveable instance, but still meet all the requirements above?

Please note that not all elements are visible at the same time (maybe 40-50 elements are shown in the view port). Would destroying Moveable instances for invisible elements be a solution for this? (and then recreated them as soon as they get into the viewport)

How do you think it would be best to tackle this performance issue?
Thank you!

**Comment by daybrush** [comment]
@alexconstantin 

<img width="643" alt="image" src="https://user-images.githubusercontent.com/3433062/186206583-0bf9a218-dbd3-44c5-aeaa-39c5db3e41f4.png">

I've found a way to fix it and I'll try to fix it.

**Comment by daybrush** [comment]
@alexconstantin 


Test react-moveable@0.38.4-beta.0



I think it might have been a little bit more resolved.


I will do more research.

More than that is probably the number of DOMs, and you may have to create/destroy them using IntersectionObserver.

**Comment by alexconstantin** [comment]
@daybrush would it possible to have a beta version for the Vanilla version? I am not using the react distribution.

**Comment by daybrush** [comment]
@alexconstantin 

Test moveable@0.35.4-beta.0 version.

Thank you :)

**Comment by alexconstantin** [comment]
@daybrush there is definitely an improvement while dragging elements. The experience is much smoother now, thank you! I'll also play around with the IntersectionObserver API. When are you planning to release 0.35.4? Thank you!

**Comment by daybrush** [comment]
@alexconstantin 

0.35.4 is released. Try it!. Thank you :)

**Comment by alexconstantin** [comment]
Thank you!
