### ISSUE TITLE
"el is undefined" error

### ISSUE THREAD

**Issue by JulesVelo** [daybrush/moveable#73]
Hello, I use your module with Angular 8 and when I want to link a resize an drag element to an existing div, I get this error :
ERROR TypeError: "el is undefined"
Maybe you know why ?
Thank you

**Comment by daybrush** [comment]
@JulesVelo 

Could you show me the error call stack or the code you used?

**Comment by JulesVelo** [comment]
![image](https://user-images.githubusercontent.com/39760183/67762136-0bd97980-fa45-11e9-9980-f1b77c87f621.png)

**Comment by daybrush** [comment]
@JulesVelo 
Thanks for knowing what the bug is. I will fix it soon.

**Comment by phucha1986** [comment]
Hi,
Look like same issue in React. Kindly help to fix, thanks!
![image](https://user-images.githubusercontent.com/56842584/68082746-bbde2680-fe39-11e9-8579-edfb0f351722.png)

**Comment by daybrush** [comment]
@JulesVelo 

`ngx-moveable` 0.6.0 is released

@phucha1986 
`react-moveable` 0.13.6 is released


Thank you :)
