### ISSUE TITLE
Does moveabletarget support multiple group?

### ISSUE THREAD

**Issue by HZZformGD** [daybrush/moveable#731]
## Environments
* Framework name: React
* Framework version: 16.8
* Moveable Component version: react-moveable@0.38.0

## Description
Hey @daybrush~  
Does moveable's target support multiple group?  or  other approach to achieve this
like 
```javascript
<movebale targets={[['.group1'],['.group2']]}/>
```

**Comment by daybrush** [comment]
@HZZformGD 

Not yet, but will be added soon.
https://github.com/daybrush/moveable/issues/566

**Comment by HZZformGD** [comment]
> @HZZformGD
> 
> Not yet, but will be added soon. #566

oh yeah!  This feature seems excitedly. i can't wait for it!!!!

**Comment by daybrush** [comment]
@HZZformGD 


Moveable's new version is released.

Support Multiple Groups. [0, 1, 2] is single group. [[0, 1], 2] is multiple group.

```js
target={[[0, 1], 2]}
```

See demos:

https://daybrush.com/moveable/storybook2/?path=/story/group--multiple-group

Multiple Group with Selecto

https://daybrush.com/moveable/storybook2/?path=/story/combination-with-other-components--use-selecto-with-multiple-group

**Comment by HZZformGD** [comment]
> @HZZformGD
> 
> Moveable's new version is released.
> 
> Support Multiple Groups. [0, 1, 2] is single group. [[0, 1], 2] is multiple group.
> 
> ```js
> target={[[0, 1], 2]}
> ```
> 
> See demos:
> 
> https://daybrush.com/moveable/storybook2/?path=/story/group--multiple-group
> 
> Multiple Group with Selecto
> 
> https://daybrush.com/moveable/storybook2/?path=/story/combination-with-other-components--use-selecto-with-multiple-group

Exciting！！！！！！！！！！！  I will Try it as soon as posible
