### ISSUE TITLE
Limit Moveable controls to a specific container

### ISSUE THREAD

**Issue by acurrieclark** [daybrush/moveable#732]
## Environments
* Framework name: Svelte
* Framework version: Latest
* Moveable Component version: Latest
* Testable Address(optional): https://svelte.dev/repl/4b5399f09d9b45808ecac5879b632c07?version=3.50.0

## Description

Is there a way to append the moveable controls (blue lines and circles) to a specific container instead of `document.body`? I can only achieve what is shown below and in the attached example.

I am trying to contain the movable controls within the main box too. A use case would be when using moveable within a modal where the movable controls should not show outside the modal.

Many thanks.

![Screenshot 2022-09-02 at 17 57 26](https://user-images.githubusercontent.com/1306728/188202565-39aa7a50-5485-4d8d-94a1-c6fc2c0304d2.png)

**Comment by daybrush** [comment]
@acurrieclark 

It seems difficult. If you have a Moveable outside of overflow:hidden it will look like your screenshot. I think your screenshot is a normal image.

**Comment by daybrush** [comment]
@acurrieclark 
https://github.com/daybrush/scena/tree/master/packages/react-editor

The structure is as follows.
```tsx
<InfiniteViewer>
   <div class="viewport">
     <Moveable />
    </div>
</InfiniteViewer>
<Selecto />
```

**Comment by acurrieclark** [comment]
Wonderful. I am using Svelte, but I will try the same structure using the InfiniteViewer. I appreciate your help.

**Comment by acurrieclark** [comment]
My apologies for the continued plea for help, but I can't seem to achieve anything near what you have on the demo site.

https://svelte.dev/repl/8cf9a085752d4a109af135f3a99449c5?version=3.50.0

To be clear, what I am trying to achieve is that the `moveable-control-box` does not appear outside of the viewer.

What I currently see is:
![Screenshot 2022-09-09 at 15 05 51 - original](https://user-images.githubusercontent.com/1306728/189369654-7cea0ae5-45a8-4b2b-8e60-093bc4f31c94.png)

What I am looking for is:
![Screenshot 2022-09-09 at 15 05 51](https://user-images.githubusercontent.com/1306728/189369689-631e95cf-fc31-4d29-baf2-88f3068f7071.png)

**Comment by daybrush** [comment]
@acurrieclark 


svelte-moveable's new version is released. Check it again.

**Comment by acurrieclark** [comment]
This is wonderful. Thank you so much
