### ISSUE TITLE
Rotate group function unable to rotate freely with snappable bounds configuration

### ISSUE THREAD

**Issue by GohChunFeng** [daybrush/moveable#733]
## Environments
* Framework name: Vanilla Js
* Framework version:
* Moveable Component version: 0.35.4
* Testable Address(optional):

## Description
Hi, recently I upgrade moveable from 0.24.6 to 0.35.4, with the same snappable bounds properties ( bounds: { left: 0px, right: XXXpx, top: 0px, bottom: XXXpx } ), group rotate function has a problem to rotate freely, it will stop rotating and the event also not fired when it rotated after some angle.

It is because the moveable configuration I set it wrongly? I need some guidance on this issue. 

Thx for responding. I attached one video for your reference.

https://user-images.githubusercontent.com/58229496/188363659-f93c6f5c-fa63-45ca-aa81-761a941d87ca.mp4

**Comment by daybrush** [comment]
@GohChunFeng 


moveable's new version is released. Check it again.

If it doesn't work, give me the code or demo address.

**Comment by GohChunFeng** [comment]
It works. Thanks for the fix. I will close this issue.
