### ISSUE TITLE
Dragable, moveable is not worked in google map

### ISSUE THREAD

**Issue by abinhho** [daybrush/moveable#74]
I am using this module for move, resize in google map marker but it's not working.
https://jsfiddle.net/abinhho/bcfw5rv0/6/

[
![Screen Shot 2019-10-29 at 5 34 30 PM](https://user-images.githubusercontent.com/9253378/67759652-6b9a4980-fa72-11e9-8bf9-343e44a77918.png)
](url)

**Comment by daybrush** [comment]
@abinhho 

Each time Google Map calls draw, it creates a moveable instance. Try the following:

```js
var moveable;
gm.prototype.onAdd = function() {
    moveable = new Moveable(......);
}
gm.prototype.draw = function() {
  moveable.updateRect();
}
```

**Comment by abinhho** [comment]
@daybrush Thanks you !

I try your solution but I face with other problem. When I drag rectangle, the map also moved.
I think something wrong at `container` and I tried to change this setting but not luck.
https://jsfiddle.net/abinhho/2bo0k5ye/6/

**Comment by daybrush** [comment]
@abinhho 
I provide inputEvent on all events that can stopProppagation

**Comment by daybrush** [comment]
@abinhho 
`moveable` 0.10.0 is released.

All events in moveable have `inputEvent` to stopPropagation.
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-events
 
```js
moveable.on("dragStart", ({ inputEvent }) => {
   inputEvent.stopPropagation();
});
```

thank you :)

**Comment by abinhho** [comment]
@daybrush 
It's worked like champ.
https://jsfiddle.net/abinhho/2bo0k5ye/23/

Thanks you so much!
