### ISSUE TITLE
Dynamic add target class not make component moveable

### ISSUE THREAD

**Issue by actorius** [daybrush/moveable#740]
## Environments
* Framework name: Vue
* Framework version: 3.2.33
* Moveable Component version: vue-3moveable 0.10.4
* Testable Address(optional): https://codesandbox.io/s/keen-volhard-hou32e?file=/src/App.vue

## Description
Have simple draft of moveable in vue. 
Page have 2 buttons, first button onclick add class 'target' to second button by vue data. I'm expect that after add class 'target', button should be moveable. What is wrong?

Possible after add class to element, i should call some moveable method to start work?
``` html
<div>
  <button @click="btnClick">Add target class</button>
</div>
<component
  :is="'SimpleButton'"
  :class="className"
  @mousedown="mousedown"
/>
<Moveable
  ref="moveable"
  :target="target"
  :draggable="true"
  @drag="onDrag"
/>
```
``` js
data() {
  return {
    target: [".target"],
    className: "test-class",
    draggable: true,
  };
},
...
btnClick(e) {
    this.className = "target";
  },
```

**Comment by daybrush** [comment]
@actorius 

Call moveable's `updateSelectors` method.

```js
this.className="target";
moveable.updateSelectors();
```

**Comment by actorius** [comment]
Update vue3-moveable 0.11.0 but can not find method. 
![image](https://user-images.githubusercontent.com/855531/190931290-7cc1e881-731e-4dab-b8a2-33cdb90b2288.png)

I'm found this https://github.com/daybrush/moveable/commit/90f40e2b500bce6564f878294e1a0aaf27dd5b69 but it's looked like update only react component. 
Also seems wrong, but why `public updateSelectors() {}` is empty? May be it's should call froceUpdate like from InitialMoveable.tsx?
``` ts
    public updateSelectors() {
        this.selectorMap = {};
        this.refTargets = [];
        this.forceUpdate();
    }
```

**Comment by actorius** [comment]
Tryed use `moveable.forceUpdate();` but it's not working. 
Sandbox updated: [Updated ](https://codesandbox.io/s/keen-volhard-hou32e?file=/src/App.vue:1229-1252)

**Comment by daybrush** [comment]
@actorius 

moveable's new version is released.

updateSelectors is missing. try again

**Comment by actorius** [comment]
Ok, looks better. It's shoudl be used with `nextTick`, otherwise element setting moveable only on second click.

``` ts
 btnClick(e) {
      this.className = "target";
      this.$nextTick(() => {
        this.$refs.moveable.updateSelectors();
      });
    },
```

Sandbox updated: [Updated](https://codesandbox.io/s/keen-volhard-hou32e?file=/src/App.vue:1229-1252)

**Comment by pozdnyakov-ds** [comment]
Hello everyone!

Hello everyone
I have a simplified code that should make it possible to move elements and change their sizes.
When building a Vue3 project without SSR, the Moveable module is successfully initialized and everything works ok.

But in SSR mode, elements are created, but Moveable does not work. It also doesn't work if I go to the target page using <nuxt-link>.

Moveable initialization occurs only after the page is reloaded.

<template>
    <div>
        <div class="layout" style="width: 640px; height: 480px;">

            <Moveable
                :target="['.element']"
                ref="moveable"
                :individualGroupable="true"
                :draggable="true"
                :throttleDrag="1"
                :edgeDraggable="false"
                :startDragRotate="0"
                :throttleDragRotate="0"
                :resizable="true"
                :keepRatio="false"
                :throttleResize="1"
                :snappable="true"
                :bounds="{'left':0, 'top':0, 'right':0, 'bottom':0, 'position':'css'}"
                
                @drag="onDrag"
                @resize="onResize"
                @scale="onScale"
                @bound="onBound"
            />

        <div
            v-for="item in elements" 
            :key="item.id"
            class="element"
            :style="{ left: item.x + 'px', top: item.y + 'px', width: item.w + 'px', height: item.h + 'px' }"
        >{{ item.id }}
        </div>

        </div>

    </div>
</template>

<script setup> 
import Moveable from "vue3-moveable"

const moveable = ref(null)

const elements = ref([
    {id: 1, y: 10, x: 10, w: 100, h: 300 },
    {id: 2, y: 50, x: 50, w: 200, h: 200 },
    {id: 3, y: 90, x: 90, w: 300, h: 100 },
])

const onDrag = e => {
    //console.log("onDrag: ", e.target)
    e.target.style.transform = e.transform;
}

const onScale = e => {
    console.log("onScale: ", e.target)
    e.target.style.transform = e.drag.transform
}

const onResize = e => {
    //console.log("onResize: ", e.target)
    e.target.style.width = `${e.width}px`;
    e.target.style.height = `${e.height}px`;
    e.target.style.transform = e.drag.transform;
}

const onBound = e => {
    console.log(e)
}

onMounted(() => {
    nextTick(() => {
        console.log("onMounted nextTick", moveable.value)
        moveable.value.updateSelectors()
        moveable.value.forceUpdate()
        moveable.value.updateTarget()
        moveable.value.updateRect()
    })
})

</script>

<style lang="scss" scoped>
.layout {
    position: relative;
    border: 1px solid #ccc;
}

.element {
    border: 1px solid #ccc;
    background-color: #eee;
    position: absolute;
}

</style>
