### ISSUE TITLE
How to hide part which is not under bound or container

### ISSUE THREAD

**Issue by JigarPrajpati** [daybrush/moveable#741]
## Environments
* Framework name:
* Framework version:
* Moveable Component version:
* Testable Address(optional):

## Description

![image](https://user-images.githubusercontent.com/91531559/190557468-137c86ff-f2bc-48d3-a922-9c4c33a9bdf9.png)

Here you can see some part are out of container still it's looks to user, how can i hide or move into such container where side part not visible

**Comment by daybrush** [comment]
@JigarPrajpati 

Set `overflow: hidden;` on the container.
