### ISSUE TITLE
Possible to snap rotation by increments?

### ISSUE THREAD

**Issue by marlenekoh** [daybrush/moveable#744]
## Environments
* Framework name: React
* Framework version: 18.2.0
* Moveable Component version: 0.39.1
* Testable Address(optional):

## Description

Hi, really love your work! Would like to know if it's possible to snap the rotation by increments (e.g. every 45 degrees)? Thanks! :)

**Comment by daybrush** [comment]
@marlenekoh 

Use `throttleRotate` prop (throttleRotate={45})

**Comment by marlenekoh** [comment]
Nice, thanks lots!!

**Comment by amakoz-merix** [comment]
@daybrush I am aware of this throttleRotate prop but it allows you to select only 45/90.. angles. Is there any way to rotate objects and just add smooth snaps for the throttle angles?
