### ISSUE TITLE
Group manual drag start not working when starting the drag using the edge

### ISSUE THREAD

**Issue by alexconstantin** [daybrush/moveable#745]
## Environments
* Framework name: any
* Framework version: any
* Moveable Component version: any
* Testable Address(optional): https://codesandbox.io/s/cranky-gauss-8u89jt?file=/src/App.tsx

## Description
Hi @daybrush!

Please check the attached codesandbox link. Dragging one of the elements should trigger a bulk dragging. This works as expected as long as the dragging is started from the inside of one of the targets. If the dragging is started using the edge of one of the targets (edgeDraggable = true), the dragStart event is not propagated to the group.

Is there a workaround for this?

Thank you!

**Comment by daybrush** [comment]
@alexconstantin 

Thank you for bug reporting.
react-moveable's new version (0.39.2) is released.


And looking at your demo code, I think it could be more streamlined.

you take a look at this demo It might be of some help to you.
https://codesandbox.io/s/nostalgic-robinson-c801zi?file=/src/App.tsx

**Comment by alexconstantin** [comment]
@daybrush The fix is working perfectly. I'll also update my code to use the version you've provided in the codesandbox link. Thank you very much!
