### ISSUE TITLE
Fluidity differences bewteen chrome and firefox

### ISSUE THREAD

**Issue by JulesVelo** [daybrush/moveable#75]
Hello,
I open this issue just to aware you that there is big fluidity differences bewteen chrome and firefox when we put more than 15 or 20 resizable and dragable elements whith divs inside.
Chrome still 30+ fps when firefox fall to 4fps sometimes when dragging or resizing.

**Comment by daybrush** [comment]
@JulesVelo 

Can you give me a demo to test at firefox and chrome.

**Comment by JulesVelo** [comment]
Here is a demo, you can test in different browsers to see the differences
https://github.com/JulesVelo/BugsDragResize
Hope it help

**Comment by embeddedt** [comment]
Having the same issue on mobile (mid-class device) with just one draggable item. Chrome remains fluid while Firefox cannot even maintain 1 frame per second (freezes and then jumps to a new position).

I even tried it on an old 2013 device and Chrome was still buttery smooth while Firefox stuttered.

I had a look at the profiler and it appears most of the time is being spent inside the touch-related event handlers (`ontouchstart`, `ontouchmove`). This happens in both my own private React application and on https://daybrush.com/moveable.

Dragging seems to have slightly better performance than scaling, but still very poor.

**Comment by daybrush** [comment]
@JulesVelo 

Thank you for your demo.

I think Angular issue.

Angular can cause changeDetection problems just by registering mouse and touch events.

Try use OnPush  `changeDetection: ChangeDetectionStrategy.OnPush`
```js
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit, AfterViewInit {
  title = "TestDrag";
  bound = { left: 0, right: 1510, top: 0, bottom: 1010 };
  loadEnd: boolean = false;

  public translates: Map<string, any> = new Map();

  constructor(private dref: ChangeDetectorRef) {}
  ngOnInit() {
    for (let index = 0; index < 90; index++) {
      this.translates.set("num" + index, [0, 0]);
    }
    setTimeout(() => {
      this.loadEnd = true;
    });
  }
  ngAfterViewInit() {
    setTimeout(() => {
      this.dref.detectChanges();
    });
  }
}
```

**Comment by JulesVelo** [comment]
It worked well ! Thank you
