### ISSUE TITLE
Left and Top are missing from event.drag when rotating and using transform translate for positioning

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#750]
## Environments
* Framework name: VanillaJS
* Framework version: 
* Moveable Component version: 0.36.2
* Testable Address(optional): [Codepen](https://codepen.io/SidIcarus/pen/jOxazME?editors=0110)

## Description

When rotating/resizing/dragging and using `transform: translate()` for positioning, the `left` and `top` are zero from `event.drag/event`, respectively.
My tooltip to show the values in my example isn't working in codepen for some reason so you'll need to open the dev tools to see it.

When you use the css styles `left` and `top` for positioning, they are present in `event.drag`.

I would simply use `left` and `top` but there is juddering of the target position that happens to the target on render.

**Comment by daybrush** [comment]
@SidIcarus 

sorry. If left and top are used, there will almost always be tremors. You have to use transform.

**Comment by SidIcarus** [comment]
@daybrush I figured as much. I will keep using transform. Unfortunately, I do need the `left` and `top` values still.

I believe it is a bug that they are `0` when rotating and using transform in `e.drag`. Is this fixable?

**Comment by SidIcarus** [comment]
Oh, sorry
I had switched the css to use `top` and `left` for positioning.

I have fixed it to use `transform`
If you add in `console.log` again, you'll see that it does not.

**Comment by daybrush** [comment]
@SidIcarus 

Aha If you use translate, it is correct that left and top are 0.

There is no drag moving through rotate.

  Always left and top are 0 and the translate value will change.

**Comment by daybrush** [comment]
@SidIcarus 

So, I think it is okay to use the beforeTranslate value instead of the left and top values?

**Comment by SidIcarus** [comment]
I wasn't sure if it would be; it looks like it is so far. 
Thank you for the clarification!
