### ISSUE TITLE
Minor feature requests

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#751]
## Environments
* Framework name: **vanillajs**
* Framework version: **esnext**
* Moveable Component version: **0.36.2**
* Testable Address(optional): none

## Description

Hello!
Thank you for your phenomenal library. I've been using the library for a bit now and feel like these additions would be beneficial. 

Currently, upon rotating/resizing/dragging the `moveable-control-box` acquires the class `moveable-dragging`.
  - Request: Adding the respective action class: `moveable-resizing`, `moveable-rotating`, etc.?
    - perhaps either always adding them or as a `MoveableOption`
  - Request : Adding the respective action class to the targets
    - perhaps either always adding them or as a `MoveableOption`

I'm performing both of the above within their respective event handlers but it would be justifiable to have the library do this given it partially already does.

- Request: exposing the evaluated target(s): such as inner moveable properties `_elementTargets` and/or `selectorMap`?
    -  Scenario: you have a reference to moveable but also want to know the elements without having re-retrieve

Thoughts?

Separate from above
- Request: option for `horizontalGuidelines` and/or `verticalGuidelines` to always be rendered

**Comment by daybrush** [comment]
@SidIcarus 

> Request: Adding the respective action class: moveable-resizing, moveable-rotating, etc.?
> perhaps either always adding them or as a MoveableOption
> Request : Adding the respective action class to the targets
> perhaps either always adding them or as a MoveableOption

This is a very nice feature. I will add it later.

> Request: exposing the evaluated target(s): such as inner moveable properties _elementTargets and/or selectorMap?
> Scenario: you have a reference to moveable but also want to know the elements without having re-retrieve

What does mean?
What do you mean by `updateSelectors` or `getElements`?


> Request: option for horizontalGuidelines and/or verticalGuidelines to always be rendered


It seems difficult. It seems to be a problematic feature.

**Comment by SidIcarus** [comment]
> This is a very nice feature. I will add it later.

Wonderful. Thank you!

> What does mean? What do you mean by `updateSelectors` or `getElements`?

The library has `target: MoveableRefTargetType` which can be non-direct references to the elements, such as selectors, functions, etcetera. From what I've seen, it evaluates the option and keeps a reference to the resultant. 

![image](https://user-images.githubusercontent.com/3842798/192856677-18f094a3-9a66-4429-972a-a32f982c0a9f.png)

I was thinking that instead of the developer also keeping track of that resultant, the API could expose one or all of these properties as it already has them. This would reduce the number of query calls needed to retrieves those elements and prevent a disconnect from what the developer is keeping track of and what the library has.

> It seems difficult. It seems to be a problematic feature.
Ah I understand.
I have a workaround for this. Thank you for looking into it!

**Comment by daybrush** [comment]
@SidIcarus 

* `lit-moveable` 0.14.0
* `moveable` 0.37.0
* `preact-moveable` 0.39.0
* `react-compat-moveable` 0.25.0
* `react-moveable` 0.40.0
* `svelte-moveable` 0.29.0
* `vue-moveable` 2.0.0-beta.44
* `vue3-moveable` 0.12.0
* `ngx-moveable` 0.34.0


moveable's new version is released.

During dragging, moveable-dragging and moveable-{{ableName}}-dragging class names are added.
And `getTargets` method was added.

Check it again.

**Comment by SidIcarus** [comment]
Thank you for your work on this.

I see the classes on the control-box for single targets but not for the group events nor on the targets. Dragging a group does add `moveable-dragArea-dragging`.

**Comment by SidIcarus** [comment]
Also looks like `.moveable-roundable-dragging` does not get added to the `.viewContainer`.

**Comment by daybrush** [comment]
@SidIcarus 

Okay. I'll add it soon.

**Comment by daybrush** [comment]
@SidIcarus 


* `@moveable/helper` 0.0.4
* `lit-moveable` 0.15.0
* `moveable` 0.38.0
* `preact-moveable` 0.40.0
* `react-compat-moveable` 0.26.0
* `react-moveable` 0.41.0
* `svelte-moveable` 0.30.0
* `vue-moveable` 2.0.0-beta.46
* `vue3-moveable` 0.13.0
* `ngx-moveable` 0.35.0


moveable's new version is released.
