### ISSUE TITLE
Issue when using react-moveable along with tailwind

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [daybrush/moveable#754]
## Description
There is an issue when react-moveable is used along with tailwindcss. once `@tailwind base;` is commented out react-movable works fine.

The following repo will help in replicating the bug.
https://github.com/a-c-sreedhar-reddy/moveable-react-tailwind

```
clone the repo
npm install
npm run dev
```

With tailwind base:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/16081083/193317704-4cb7bc8a-7d0f-4fc5-8e5e-5ac6dec89329.png">

Without tailwind base:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/16081083/193317796-29b769f0-512e-445d-9de4-a5191dad1ccf.png">

**Comment by daybrush** [comment]
@a-c-sreedhar-reddy 

* `@moveable/helper` 0.0.4
* `lit-moveable` 0.13.4
* `moveable` 0.36.4
* `preact-moveable` 0.38.4
* `react-compat-moveable` 0.24.4
* `react-moveable` 0.39.4
* `svelte-moveable` 0.28.4
* `vue-moveable` 2.0.0-beta.41
* `vue3-moveable` 0.11.4
* `ngx-moveable` 0.33.4


moveable's new version is released. Check it again.

**Comment by a-c-sreedhar-reddy** [comment]
Thanks @daybrush
