### ISSUE TITLE
Bug: Roundable control not always initializing

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#756]
## Environments
* Framework name: VanillaJS
* Moveable Component version: 0.36.3
* Testable Address(optional): [Codepen](https://codepen.io/SidIcarus/pen/XWqVQzE)

## Description
Roundable control does not initialize on start or on edge double click.

I've gotten it to work on my local project somehow but when I try to use CSS variables to set the border radius, it ends up doing what we see in the linked codepen. 
If i update the CSS after initialization, it works with the css variable. But if the control is removed, clicking to create doesn't work.

**Comment by SidIcarus** [comment]
Issue seems to also be present in the [first storybook](https://daybrush.com/moveable/storybook/index.html?path=/story/basic--roundable)

**Comment by daybrush** [comment]
@SidIcarus 


* `@moveable/helper` 0.0.4
* `lit-moveable` 0.13.4
* `moveable` 0.36.4
* `preact-moveable` 0.38.4
* `react-compat-moveable` 0.24.4
* `react-moveable` 0.39.4
* `svelte-moveable` 0.28.4
* `vue-moveable` 2.0.0-beta.41
* `vue3-moveable` 0.11.4
* `ngx-moveable` 0.33.4

moveable's new version is released. Check it again.

In the future, the position/action of the roundable's control button will be changed more easily.

**Comment by SidIcarus** [comment]
Ahhh. I have figured out that either if the initial value of `border-radius` is `0`, the control will not render, or it renders at 0 which is where it goes away when you drop it there. This is not the case if `border-radius` is excluded. Is this intentional?
In my opinion, the behavior between explicitly set to `0` and unset would be the same given that the rendered would treat it the same.

It also seems that effects of `edge: true` prevents `roundClickable: true` from working.

So I guess, my issue may not have been that it was not initializing but that this was occurring along with the `edge: true` issue.
