### ISSUE TITLE
When pressing ctrl to select two elements, the upper left corner elements will flash

### ISSUE THREAD

**Issue by zhoulingz** [daybrush/moveable#760]
## Environments
* Framework name:vue
* Framework version:^2.6.11
* Moveable Component version:0.36.3
* Testable Address(optional): https://codesandbox.io/p/github/Teaghy/my-vue-app/csb-tt6ogb/draft/confident-danny?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue&selection=%5B%7B%22endColumn%22%3A11%2C%22endLineNumber%22%3A121%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A121%7D%5D

## Description
Press and hold the ctrl key to select the second element, and the zoom control frame will first appear in the upper left corner, and then display the zoom control frame in the corresponding position
![微信图片_20221009161451](https://user-images.githubusercontent.com/49084418/194745618-a76f1ca9-60eb-437b-a6d2-23a936289387.png)

**Comment by daybrush** [comment]
@zhoulingz 

* `@moveable/helper` 0.0.4
* `lit-moveable` 0.13.4
* `moveable` 0.36.4
* `preact-moveable` 0.38.4
* `react-compat-moveable` 0.24.4
* `react-moveable` 0.39.4
* `svelte-moveable` 0.28.4
* `vue-moveable` 2.0.0-beta.41
* `vue3-moveable` 0.11.4
* `ngx-moveable` 0.33.4

moveable's new version is released. Check it again.

**Comment by zhoulingz** [comment]
Sorry, it has been changed to a new version, but the problem still hasn't been solved. Your newly added demo has the same problem

[demo](https://codesandbox.io/s/infallible-meninsky-8sdi6m)

**Comment by daybrush** [comment]
@zhoulingz 

0.36.6 is released. Check it again.

**Comment by zhoulingz** [comment]
The same problem still occurs when multiple elements are selected at the same time

[Demo has been updated](https://codesandbox.io/s/cocky-grass-ggndjc)

**Comment by zhoulingz** [comment]
![微信图片_20221012154706](https://user-images.githubusercontent.com/49084418/195282324-359f631d-90e6-410e-af71-a9e8e3d1fdba.png)

Why is setTimeout set here?

**Comment by zhoulingz** [comment]
The above problems also occur when one element and two elements are selected for rapid transition

**Comment by zhoulingz** [comment]
> The same problem still occurs when multiple elements are selected at the same time
> 
> [Demo has been updated](https://codesandbox.io/s/cocky-grass-ggndjc)

**Comment by zhoulingz** [comment]
> > The same problem still occurs when multiple elements are selected at the same time
> > [Demo has been updated](https://codesandbox.io/s/cocky-grass-ggndjc)

The above problems also occur when one element and two elements are selected for rapid transition

**Comment by zhoulingz** [comment]
I added your line of code. This problem still occurs when you select one element to quickly transition to two elements or select two elements to select one element. It seems that it has not been solved

**Comment by daybrush** [comment]
@zhoulingz 

I modified it a bit and built it. How about testing with this file?
https://codesandbox.io/s/inspiring-hypatia-ofy450

**Comment by zhoulingz** [comment]
After modification, there is no problem in the current test, but this problem still occurs occasionally when one or two elements are selected for conversion. The following demo is the effect of my box selection. You can try to select one and then select two. Click the "selectSecond" button twice, and it will flicker
(https://codesandbox.io/s/blissful-burnell-5fqxux?file=/index.html:136-148)

**Comment by zhoulingz** [comment]
After modification, there is no problem in the current test, but this problem still occurs occasionally when one or two elements are selected for conversion. The following demo is the effect of my box selection. You can try to select one and then select two. Click the "selectSecond" button twice, and it will flicker
https://codesandbox.io/s/blissful-burnell-5fqxux?file=/index.html:136-148

**Comment by daybrush** [comment]
@zhoulingz 

* `lit-moveable` 0.14.0
* `moveable` 0.37.0
* `preact-moveable` 0.39.0
* `react-compat-moveable` 0.25.0
* `react-moveable` 0.40.0
* `svelte-moveable` 0.29.0
* `vue-moveable` 2.0.0-beta.44
* `vue3-moveable` 0.12.0
* `ngx-moveable` 0.34.0

moveable's new version is released. Check it again.

**Comment by zhoulingz** [comment]
Press and hold the ctrl key to select two and then deselect them. The problem may not be described clearly before. Please take a look at the demo
https://codesandbox.io/s/brave-rgb-mwon34?file=/src/components/HelloWorld.vue

**Comment by daybrush** [comment]
@zhoulingz 

oh sorry The modified code did not build.
The bug appeared properly on Windows.

Try version 0.37.1.

**Comment by zhoulingz** [comment]
@daybrush 
Thank you, the perfect solution！
