### ISSUE TITLE
Bug: `resizable: true, edge: true` prevents `roundClickable: true` from working

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#761]
## Environments
* Framework name: vanillaJS
* Moveable Component version: 0.36.4
* Testable Address(optional): [Codepen](https://codepen.io/SidIcarus/pen/XWqVQzE)

I believe my problem in the linked issue was the explicitly set `border-radius: 0` and this issue.

_Originally posted by @SidIcarus in https://github.com/daybrush/moveable/issues/756#issuecomment-1273767795_

**Comment by daybrush** [comment]
@SidIcarus 


well it's hard

I will improve Roundable.

I will change the position of the round control like figma.
<img width="351" alt="image" src="https://user-images.githubusercontent.com/3433062/195165447-afbb29f9-80f3-4489-9fe0-ad23c2b2bc25.png">

**Comment by daybrush** [comment]
@SidIcarus 

The round addition function through double-clicking the edge and line cannot be used at the same time.

But you can use `isDisplayShadowRoundControls={true or "horizontal"} `, `roundPadding`

https://daybrush.com/moveable/storybook2/?path=/story/basic--roundable

**Comment by SidIcarus** [comment]
This is a huge improvement! `isDisplayShadowRoundControls` is very cool!
