### ISSUE TITLE
type error after update vue-tsc

### ISSUE THREAD

**Issue by lastmirage** [daybrush/moveable#766]
## Environments
* Framework name: nuxt3
* Framework version: rc.11
* Moveable Component version: vue3-moveable 0.11.6
* Testable Address(optional):

## Description
I use vscode with volar.
after update volar and vue-tsc to 1.0.7, 
vue-tsc shows this error

`Type '{ class: string; target: any; dragTarget: any; 'drag-target': any; draggable: boolean | undefined; ... 8 more ...; 'render-directions': string[]; }' is missing the following properties from type 'VueMoveableInterface': $el, $_moveable, $props, pinchable, and 102 more.`

with older version of vue-tsc (0.40.11), there is no error

**Comment by daybrush** [comment]
@lastmirage 

I'll fix it within this week.

Thank you :)

**Comment by daybrush** [comment]
@lastmirage 

vue3-moveable's new version is released. Check it again.

**Comment by lastmirage** [comment]
It's all cleared !
thx
