### ISSUE TITLE
snapCenter is not working anymore: Moveable migration ^0.23.0 -> ^0.37.1

### ISSUE THREAD

**Issue by mhaidamashko** [daybrush/moveable#771]
## Environments
* Framework name: None
* Framework version: None
* Moveable Component version: ^0.37.1
* Testable Address(optional) 
v0.23.1 - https://codesandbox.io/s/stupefied-wave-21ons6  
v.0.37.1 - https://codesandbox.io/s/naughty-lalande-rvwwyb
## Description
Hi guys, thank you for the great library.

I migrated a library from ^0.23.0 to ^0.37.1 and lost the possibility to have guidelines related to the dragged element center.
Before I could just pass a `snapCenter` and it will work, but now it stops.
**_Expected(it was before):_**
![screencast 2022-10-25 18-40-07](https://user-images.githubusercontent.com/30477831/197819584-85200115-bae3-4aed-a621-5d4858aa550f.gif)
**_Current:_**
![screencast 2022-10-25 18-40-54](https://user-images.githubusercontent.com/30477831/197819644-15781046-bfe3-47ad-958b-b226e05e35d5.gif)

Do we have a workaround for it? Or is it a bug that we need to fix?

**Comment by daybrush** [comment]
@mhaidamashko 

use `snapDirections`

```js
snapDirections: {
    top: true,
    bottom: true,
    right: true,
    left: true,
    center: true,
    middle: true
  },
```

**Comment by mhaidamashko** [comment]
@daybrush Thank you so much! That's exactly what I need, these are much smarter props! Great job!
