### ISSUE TITLE
moveable-control-box has visibility set to hidden

### ISSUE THREAD

**Issue by noudadrichem** [daybrush/moveable#772]
## Environments

* Framework name: Moveable Vanilla
* Framework version: latest
* Moveable Component version: latest
* Testable Address(optional):

## Description:

On the initialisation of moveable the `moveable-control-box` has `visibility: hidden;` even tho all the positioning etc. is correct.
I'm unable to find in the doc how/what happens to make a moveable 'active' but I'm unable to find it. 

We initialise the moveable like so:
```ts
const moveable = new Moveable(container, {
    origin: false,
    target: document.querySelector('.moveable'),
    container: document.querySelector('#stage'),
    draggable: true,
    resizable: true,
    rotatable: true,
});
```

And as you can see here the visibility is hidden of the control box even tho everything else is correct : 
![image](https://user-images.githubusercontent.com/16288476/197987616-31853b17-6871-4d64-b8fc-14d5fcd16061.png)

I hope this has an easy fix but after 2 hours I reckon asking is the way to go. 
I'm unable to find why one moveable works, but initialising another does not. Can it not have 2 moveables active at the same time even tho they're different nodes?

**Comment by daybrush** [comment]
@noudadrichem 

I work fine. Only the first render is set to hidden and after that it is set to visible.


```html
<body>
    <input class="target target1" />
    <input class="target target2" />
</body>
<script>
    new Moveable(document.body, {
        draggable: true,
        target: document.querySelector(".target1"),
    }).on("drag", e => {
        e.target.style.transform = e.transform;
    });

    new Moveable(document.body, {
        draggable: true,
        target: document.querySelector(".target2"),
    }).on("drag", e => {
        e.target.style.transform = e.transform;
    });
</script>
```


Do not use container values. And please give me a codepen demo that I can check.

**Comment by noudadrichem** [comment]
Hi! We hacked together a solution by forcing the visiblitiy. We kinda redid the movable approach but it stayed hidden for some reason.. Not sure what is wrong and not worth spending more time on I guess?
But with that said, why shouldn't we use container values?

**Comment by daybrush** [comment]
@noudadrichem 

A container is a value that is controlled inside a moveable.

Use it only as the first argument of the Moveable class.



visibility hidden is set when the target does not exist.

It's hard to check without a demo I can test.
