### ISSUE TITLE
snapContainer property - change it on move

### ISSUE THREAD

**Issue by mhaidamashko** [daybrush/moveable#773]
## Environments
* Framework name: None
* Framework version: None
* Moveable Component version: ^0.37.1
* Testable Address(optional): https://codesandbox.io/s/zen-rumple-ycc6n9

## Description
Hi,
When I'm dragging an element It's possible to change `verticalGuidelines` `horizontalGuidelines` dynamically, but they are rendering relative to the `snapContainer`, so I want to change a `snapContainer` as well, but changing this property doesn't work.
Maybe I can resolve it in another way(change a container)?

I created a demo, when I move an element to another green zone I expect this will be a new `snapContainer`.

Thanks for your hard work!

**Comment by daybrush** [comment]
@mhaidamashko 
It probably didn't change because the snapshot was applied before dragStart.

I'll check it.

**Comment by daybrush** [comment]
@mhaidamashko 


* `@moveable/helper` 0.0.4
* `lit-moveable` 0.15.0
* `moveable` 0.38.0
* `preact-moveable` 0.40.0
* `react-compat-moveable` 0.26.0
* `react-moveable` 0.41.0
* `svelte-moveable` 0.30.0
* `vue-moveable` 2.0.0-beta.46
* `vue3-moveable` 0.13.0
* `ngx-moveable` 0.35.0


moveable's new version is released.

Change the snapContainer and it will work.
try it again.

**Comment by mhaidamashko** [comment]
@daybrush thank you, 
I just upgraded a package to 0.38.0 and tried but nothing changed, see the example.
https://codesandbox.io/s/bold-marco-05ftpl?file=/src/index.js
Could you check, please?

**Comment by daybrush** [comment]
@mhaidamashko

**Comment by daybrush** [comment]
@mhaidamashko 

* `@moveable/helper` 0.0.4
* `lit-moveable` 0.15.1
* `moveable` 0.38.1
* `preact-moveable` 0.40.1
* `react-compat-moveable` 0.26.1
* `react-moveable` 0.41.1
* `svelte-moveable` 0.30.1
* `vue-moveable` 2.0.0-beta.47
* `vue3-moveable` 0.13.1
* `ngx-moveable` 0.35.1

moveable's new version is released. Check it again.

**Comment by mhaidamashko** [comment]
@daybrush thanks, it looks good now
