### ISSUE TITLE
Cannot execute updateRect on ref.current.

### ISSUE THREAD

**Issue by SarunasMedeikis** [daybrush/moveable#785]
## Environments
* Framework name: react-moveable / React
* Framework version: 0.39.3
* Moveable Component version:
* Testable Address(optional):

## Description
I am updating my component's data, and also changing transform/translate values, everything works ok, except the control box, which moves more than needed, I have deduced it is due to the miscalculations, and I need to use updateRect to fix it.

I try to update it after I update my state in `onDragEnd` event, using `moveableRef.current.updateRect()`, I do not get any error, however, it does not seem to change anything. Below is a screenshot, green box is where controlbox supposed to be.
![Animation](https://user-images.githubusercontent.com/4465333/200140262-cf2c7bc1-74d5-4f8e-932a-203c1e003398.gif)

I inspected `moveableRef.current` and there is no such function in there, see screenshot below.
![image](https://user-images.githubusercontent.com/4465333/200140411-0f436407-4f64-4a8e-9431-4c2202cc5196.png)

If I call `moveableRef.updateRect()` - it seems to work, and the controlbox updates. See screenshot below.

![Animation2](https://user-images.githubusercontent.com/4465333/200140352-3d59a079-764c-4f6b-9e5f-ee601db480b5.gif)

However, I then get error, that no such function exists.
![image](https://user-images.githubusercontent.com/4465333/200139508-d67a8de1-53d8-4640-a84b-c97dcb2d4893.png)

Why it works, when I get the error, and it does not work, when it is supposed to work ? Am I missing some setup ?

My Moveable : 

![image](https://user-images.githubusercontent.com/4465333/200140523-83ba0359-fa77-4799-96ac-f1e626878f6f.png)

**Comment by daybrush** [comment]
@SarunasMedeikis 

If you use useRef and createRef, there are many ways to use moveableRef.current.updateRect().


Does transform(translate) exist in container or higher?

**Comment by daybrush** [comment]
@SarunasMedeikis 

I think I need to know the html structure to know this problem. Please tell me the demo or html structure and css.

**Comment by SarunasMedeikis** [comment]
@daybrush 
I have tried to transfer my code for demo into codesandbox, and the issue does not persist there, it works as expected...

In my original code, I deduced the issue to the part, that once i update translate `onDragEnd` in moveable, it does not update in the control box, until i press once again there.
![image](https://user-images.githubusercontent.com/4465333/200167533-5e4b8d8b-7d1f-461c-af10-c2b1a66a33c6.png)
`translate3d` should have the `left` and `top` attributes from the `textarea` , but it does not transfer, I feel I have made some silly mistake somewhere in between, however, I cannot find it yet.

Codesandbox, where it works:
https://codesandbox.io/s/youthful-tesla-hfi40l?file=/src/App.jsx

**Comment by SarunasMedeikis** [comment]
Thus far, I might have reached a sort of workaround, I can force `updateRect` everytime I update my component, it then works, and updates my control box.
`  useEffect(() => {
    moveableRef.current.updateRect();
  }, [components]);`

It does this pretty odd glitch, as you see below.
![Animation](https://user-images.githubusercontent.com/4465333/200169227-b3edf95f-bd86-42be-afb3-f9bef792d7be.gif)

**Comment by daybrush** [comment]
@SarunasMedeikis 
It will be because of the transform you set.

Since the state of React is asynchronous, the rect of the moveable is calculated without all styles applied.


```js
e.target.style.cssText +=
            `left: ${target.left}px;` +
            `top: ${target.top}px;` +
            `transform: translate(0px, 0px)`;
          frame.translate = [0, 0, 0, 0];
```


And check the box-sizing: border-box property of the target?


rect is offsetWidth and offsetHeight. The width and height are gradually increased.

```css
.target {
   box-sizing: border-box;
}
```

**Comment by SarunasMedeikis** [comment]
Thank you for the help 👍
