### ISSUE TITLE
Snappable bug when group is rotated

### ISSUE THREAD

**Issue by Raserad** [daybrush/moveable#786]
## Environments
* Framework name: vue
* Framework version: 3
* Moveable Component version: 0.13.1

@daybrush when we select several elements and move it the snappable work with offset. There is on video.

https://user-images.githubusercontent.com/34380690/200181840-8aca7b40-bfbd-4dd6-b93c-780548c5d67f.mp4

**Comment by Raserad** [comment]
@daybrush do you test with several selected with rotation as in video?

**Comment by Raserad** [comment]
@daybrush  this is demo: https://codesandbox.io/s/brave-bird-52jc1i
This is demo. Try to drag elements without rotation and after rotate

**Comment by daybrush** [comment]
@Raserad 

Thank you. I'll fix bug and release this sunday.

**Comment by daybrush** [comment]
@Raserad 

* `@moveable/helper` 0.0.4
* `lit-moveable` 0.16.0
* `moveable` 0.39.0
* `preact-moveable` 0.41.0
* `react-compat-moveable` 0.27.0
* `react-moveable` 0.42.0
* `svelte-moveable` 0.31.0
* `vue-moveable` 2.0.0-beta.48
* `vue3-moveable` 0.14.0
* `ngx-moveable` 0.36.0

moveable's new version is released. Check it again.
