### ISSUE TITLE
Pointer positions of clipped and rotated element are wrong

### ISSUE THREAD

**Issue by hrachmkr** [daybrush/moveable#788]
## Environments
* Framework name: React
* Framework version: 16.9.0
* Moveable Component version: 0.41.1
* Testable Address(optional):

## Description

I think there is an issue with the calculation of x and y positions of moveable-clip-control pointer. You can see the screenshot here`

![bug](https://user-images.githubusercontent.com/21039160/200299850-aed6f33c-51ab-465e-9b97-3cbcc981cd4d.gif)

**Comment by hrachmkr** [comment]
In addition, I have custom height and width for clip-control elements

**Comment by daybrush** [comment]
@hrachmkr 

How are the snap control's CSS and after CSS set up?



Did it show up correctly before customizing the CSS?

**Comment by hrachmkr** [comment]
@daybrush 

If I don't customize the snap controls css height and width, it works perfect

**Comment by hrachmkr** [comment]
`.moveable-clip-control {
    background: transparent;
    border-radius: 0px;
    border: none;
    background-size: contain;
    height: 20px;
    width: 20px;
    background-size: contain;
    background-image: url('imageurl');
  }
  .moveable-clip-control[data-clip-index='0'] {
    margin-left: -2px;
    margin-top: -2px;
    background-image: url('top-left-pointer.svg');
  }`
  

` .moveable-control::after {
      content: '';
      position: absolute;
      height: 18px;
      width: 18px;
      left: -3px;
      top: -3px;
    }`
    
   ::after is just for increasing the clickable area

**Comment by hrachmkr** [comment]
okaay, I got. Thanks a lot for your quick response :)
