### ISSUE TITLE
Idea how to keep throttleDrag when element is snapped

### ISSUE THREAD

**Issue by Raserad** [daybrush/moveable#789]
@daybrush i have an idea how to keep throttleDrag then element is snapped.
Look. The snappable is workign in 2 axis - horizontal and vertical. When element snapping by x or y or both axises you turn off throttleDrag to make accurancy snapping (in most cases you need turn off throttleDrag to make correct elements position depends on snapping elements). So you can go by another way. You can turn off throttleDrag to x axis or y axis depends on which axis is snapping. Whe we have horizontalSnaping you can turn off y axis of throttleDrag, when we have verticalSnapping you can turn off x axis of throttleDrag. 

Do you understand my idea?

**Comment by Raserad** [comment]
Yes it is work. Here is my code screenshot

![image](https://user-images.githubusercontent.com/34380690/200823282-de932614-6f3c-4414-81de-5f424083761b.png)

**Comment by daybrush** [comment]
@Raserad 

I know what you mean.
However, when rotated, it becomes difficult to distinguish between vertical and horizontal.

The behavior of throttleDrag will change.
Instead of the values of beforeTranslate and translate, it is changed based on the screen.

**Comment by daybrush** [comment]
@Raserad 

* `@moveable/helper` 0.0.4
* `lit-moveable` 0.16.0
* `moveable` 0.39.0
* `preact-moveable` 0.41.0
* `react-compat-moveable` 0.27.0
* `react-moveable` 0.42.0
* `svelte-moveable` 0.31.0
* `vue-moveable` 2.0.0-beta.48
* `vue3-moveable` 0.14.0
* `ngx-moveable` 0.36.0


I fixed it according to your suggestion. Check it again.
