### ISSUE TITLE
elementGuidelines is not working with VUE-moveable 

### ISSUE THREAD

**Issue by afnanz7634** [daybrush/moveable#790]
## Environments
* Vue.js and VUEX
* Vue:2.7.1:
*"vue-moveable": "^2.0.0-beta.40",

## Description
Hello I'm creating an custom editor tool I'm using vue-moveable now i'm stuck with adding snapguidelines
![image](https://user-images.githubusercontent.com/49157938/201210111-6147ecb9-f7ba-45d9-8650-44c118bbdcb2.png)

when i select and move the draggable object the snapguidlines doesn't appear when the object collapse with other object it feels like the object is snaping with the whole canvas 

[screen-capture (3).webm](https://user-images.githubusercontent.com/49157938/201210284-bf4c4f41-edb9-4d9e-b309-dc2da2aedf94.webm)

this is how i'm implementing the snappings 

![image](https://user-images.githubusercontent.com/49157938/201210484-7dd78588-5d0b-40d9-b813-f4ee51b890fd.png)
![image](https://user-images.githubusercontent.com/49157938/201210584-6f748236-9ab8-4d6c-8405-d0f720a2011b.png)
![image](https://user-images.githubusercontent.com/49157938/201210815-030efbb8-e419-4173-91a6-afb811299898.png)

this is the output html of objects i'm target the objects directly and i want the siblings to snap each other 
![image](https://user-images.githubusercontent.com/49157938/201211190-6bb967ef-ebb0-46bd-9190-bac1aa4c094c.png)

**Comment by EssDevUi** [comment]
@daybrush Please Help !!

**Comment by daybrush** [comment]
@EssDevUi 

If it doesn't work, I can make two guesses.

1. Does the element exist when document.querySelector is called?

Take a shot of elementGuidelines on the console


2. Does the element change? If so, pass it as a string array

elementGuidelines = [...., `div[data-id-t="..."]`];

**Comment by EssDevUi** [comment]
> @EssDevUi
> 
> If it doesn't work, I can make two guesses.
> 
> 1. Does the element exist when document.querySelector is called?
> 
> Take a shot of elementGuidelines on the console
> 
> 2. Does the element change? If so, pass it as a string array
> 
> elementGuidelines = [...., `div[data-id-t="..."]`];

NO brother when page load the elements doesn't exist on first load the user have to click on the element from sidebar to get his desired element inside the canvas when the page loads the elementGuidelinesArray is empty array [] . but when user click on the element from sidebar the watcher add a new element inside elementGuidelinesArray  like [...this.elementGuidelinesArray , document.querySelector("div[data-id-t=".idofItem"]")]

**Comment by daybrush** [comment]
@afnanz7634 

Send it as a selector array.

```js
this.elementGuidelines = ["div[data-id-t='0']", 'div[data-id-t='1']"];
```

**Comment by afnanz7634** [comment]
> @afnanz7634
> 
> Send it as a selector array.
> 
> ```js
> this.elementGuidelines = ["div[data-id-t='0']", 'div[data-id-t='1']"];
> ```

![image](https://user-images.githubusercontent.com/49157938/201380895-2601ea8c-9ed0-4850-9125-e1bc807c03d6.png)
I did but still not working

**Comment by afnanz7634** [comment]
![image](https://user-images.githubusercontent.com/49157938/201385206-2120be5f-1b15-48aa-9d90-4f52ebb8027d.png)



> @afnanz7634
> 
> Send it as a selector array.
> 
> ```js
> this.elementGuidelines = ["div[data-id-t='0']", 'div[data-id-t='1']"];
> ```

![image](https://user-images.githubusercontent.com/49157938/201385219-80baf193-d6b7-459c-88c2-ff5a239ad79a.png)
I've also tried to add them like this but in vain nothing happens is my configuration for adding snap is correct ? @daybrush

**Comment by afnanz7634** [comment]
@daybrush this is how the element is showing in the inspect element tool is it correct ? 
![image](https://user-images.githubusercontent.com/49157938/201385995-11fc868e-d5ea-4f4c-ae12-b8c2f6f9c09b.png)

**Comment by daybrush** [comment]
@afnanz7634 


There is no problem with portoalcontainer.

Would you like to run the following code in the drag event?


```js
// console.log(e.moveable.state.guidelines);
onDrag({ moveable }) {
    console.log(e.moveable.state.guidelines);
}
```

<img width="462" alt="image" src="https://user-images.githubusercontent.com/3433062/201386476-cbdfa79e-5e86-4c97-9c97-df37087215f2.png">


An object similar to the one below should appear. Can you show me with a screenshot?

**Comment by afnanz7634** [comment]
> @afnanz7634
> 
> There is no problem with portoalcontainer.
> 
> Would you like to run the following code in the drag event?
> 
> ```js
> // console.log(e.moveable.state.guidelines);
> onDrag({ moveable }) {
>     console.log(e.moveable.state.guidelines);
> }
> ```
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/3433062/201386476-cbdfa79e-5e86-4c97-9c97-df37087215f2.png">
> 
> An object similar to the one below should appear. Can you show me with a screenshot?

sure let me check and post the screenshot here stay with me bro @daybrush

**Comment by afnanz7634** [comment]
@daybrush this is what I'm getting 
![image](https://user-images.githubusercontent.com/49157938/201387209-c2026d28-0e7d-4998-a423-a0cd24c56936.png)
it's missing "element " & "elementRect" property

**Comment by daybrush** [comment]
@afnanz7634 
I'm not sure what the error is, but thanks for your help.

Would you like to print the code below?


```jsx
onDrag({ moveable }) {
    console.log(
                            moveable.props.elementGuidelines,
                            moveable.state.elementRects,
                            moveable.state.guidelines, 
    );
}
```

<img width="462" alt="image" src="https://user-images.githubusercontent.com/3433062/201393561-406a5f81-6529-4dcd-bbaa-081defa072af.png">

**Comment by afnanz7634** [comment]
sure just a sec

**Comment by daybrush** [comment]
@afnanz7634 

Ah, I think the grammar is wrong?
```diff
- v-bind:elementGuidelines={elementGuidelines}
+ v-bind:elementGuidelines="elementGuidelines"
```

**Comment by afnanz7634** [comment]
![image](https://user-images.githubusercontent.com/49157938/201394167-dfae47e4-1a4b-4f8b-8999-f7d74aabd549.png)
here you go bro

**Comment by afnanz7634** [comment]
> @afnanz7634
> 
> Ah, I think the grammar is wrong?
> 
> ```diff
> - v-bind:elementGuidelines={elementGuidelines}
> + v-bind:elementGuidelines="elementGuidelines"
> ```

yes it works thanks brooooooooooooooo
