### ISSUE TITLE
Click triggers dragStart event which moveable dispatches

### ISSUE THREAD

**Issue by kotarofunyu** [daybrush/moveable#796]
## Environments
* Framework name: plain javascript
* Framework version:
* Moveable Component version: latest
* Testable Address(optional):

## Description

It seems to me that clicking on moveable target triggers dragStart event which moveable dispatches.
If it's true, I prefer clicking on moveable target element does not trigger dragStart event.
How can I do that?
Thanks in advance.

Movie below is my example.
`dragStart` event handler changes element's opacity. You can see that only clicking fires `dragStart` event.

https://user-images.githubusercontent.com/58697518/202619465-df5d000e-9a17-4dfb-a8a9-78aa54abc61e.mp4

**Comment by daybrush** [comment]
@kotarofunyu

**Comment by daybrush** [comment]
@kotarofunyu 
sorry. The drag event consists of:

dragStart(mousedown)
drag (mousemove)
dragEnd(mouseup)

You seem to want dragStart to occur on the 1st mousemove.

I'll add an `isFirstDrag` property to the drag event later.

Let me know what you think.

**Comment by kotarofunyu** [comment]
@daybrush 

Thanks you for your quick reply.

> You seem to want dragStart to occur on the 1st mousemove.

Yes, that is what I wanted!

> isFirstDrag property to the drag event

I want to understand exactly your idea, so let me confirm it.
Is this right?👇

When isFirstDrag is false...

#### case 1

No dragStart event occur if mousemove event occurs.

1. Click => No dragStart events occur.
2. Click => No dragStart events occur.

#### case 2

mousemove event occurs, then dragStart event occurs.

1. Click
2. Mousemove => dragStart events occur.

**Comment by daybrush** [comment]
The dragStart event is inevitably triggered on mousedown.

```js
onDragStart={e => {
   //
}}

onDrag={e => {
   if (e.isFirstDrag) {
      // your code for dragStart
   }
}}
```

**Comment by kotarofunyu** [comment]
@daybrush 

Oh, I understood!
I am looking forward new feature to be released😀

**Comment by daybrush** [comment]
@kotarofunyu 

moveable's new version is released. Check it again.

```jsx
onDragStart={e => {
   //
}}

onDrag={e => {
   if (e.isFirstDrag) {
      // your code for dragStart
   }
}}
```

**Comment by kotarofunyu** [comment]
`isFirstDrag` property enabled me to handle `DragEvent` :+1:
Thanks!
