### ISSUE TITLE
react-moveable: advanced resizable min size with bounds jumpy bug

### ISSUE THREAD

**Issue by marlenekoh** [daybrush/moveable#799]
## Environments
* Framework name: react
* Framework version: 18.2
* Moveable Component version: 0.42.0
* Testable Address(optional):

## Description

Using bounds with `e.setMin()` creates this jumpy bug. Is this method supported?

https://user-images.githubusercontent.com/28558150/203729580-be8e656b-7709-4fd5-a7fb-68b18d14b744.mp4

My config:
```
<Moveable
  target={target?.ref}
  origin={false}
  draggable
  resizable
  rotatable
  renderDirections
  snappable
  bounds={{
    left: 0,
    right: imageSize.width,
    bottom: imageSize.height,
    top: 0,
  }}
  padding={{ left: 0, top: 0, right: 0, bottom: 0 }}
  rotationPosition="top"
  onDrag={(e) => {
    e.target.style.transform = e.transform;
  }}
  onResizeStart={(e) => {
    e.setMin([100, 100]);
  }}
  onResize={(e) => {
    e.target.style.width = `${e.width}px`;
    e.target.style.height = `${e.height}px`;
    e.target.style.transform = e.drag.transform;
  }}
  onRotate={(e) => {
    e.target.style.transform = e.drag.transform;
  }}
>
...
```

**Comment by daybrush** [comment]
@marlenekoh 

I made a demo, is there any difference from your code?

The action is good.

https://codesandbox.io/s/objective-wave-r6oy9l?file=/src/App.js

**Comment by marlenekoh** [comment]
Thanks for the demo! Was able to narrow it down to one of my useEffect hooks. Not a bug.
