### ISSUE TITLE
If the container has zoom css property movable calculations works wrong

### ISSUE THREAD

**Issue by MRJCrunch** [daybrush/moveable#800]
## Environments
* Framework name: N/A
* Framework version: N/A
* Moveable Component version: 0.39.1
* Testable Address(optional): https://codesandbox.io/s/movable-zoom-issue-7toyj3?file=/src/index.js

## Description
I have a case where component (#someAreaWithMovableElements) that includes movable components is placed inside the container with zoom css property (#containerWithZoom). In this case target will not follow the cursor for any actions (drag, rotate, resize). How can I handle it? 

I've seen this issue https://github.com/daybrush/moveable/issues/137 where it was suggested to use rootContainer, but it doesn't work, you can check the example.

**Comment by daybrush** [comment]
@MRJCrunch 

sorry. The zoom CSS property is not supported.

**Comment by MRJCrunch** [comment]
@daybrush how can I handle it and calculate transform by myself?

**Comment by daybrush** [comment]
@MRJCrunch 


How about using transform instead of zoom?

```css
/* zoom: 0.5 */
transform: scale(0.5);
transform-origin: 0 0;
```

**Comment by MRJCrunch** [comment]
@daybrush 
We decided to use zoom in the whole application instead of transform and it is not easy to change it right now, so I'm trying to find a solution for zoom

**Comment by daybrush** [comment]
@MRJCrunch 

I will try my best to make it work.
However, the functionality can be very limited.

**Comment by MRJCrunch** [comment]
@daybrush it would be really great if movable will support zoom! For my case I just need drag, rotate and resize.

**Comment by daybrush** [comment]
@MRJCrunch 

moveable's new version is released. Check it again.

**Comment by MRJCrunch** [comment]
@daybrush Dragging and resizing work great, but rotation looks buggy
https://user-images.githubusercontent.com/17198997/204209928-a220f976-db91-46ae-958a-121bbf1725af.mov

**Comment by MRJCrunch** [comment]
@daybrush  Another bug: if you first rotate, then resize, then rotate -> looks like origin was changed
![Screen Recording 2022-11-28 at 11 44 35](https://user-images.githubusercontent.com/17198997/204211542-45484ba1-3c0d-469c-b2f3-44850958e45d.gif)

**Comment by daybrush** [comment]
@MRJCrunch 

> @daybrush Another bug: if you first rotate, then resize, then rotate -> looks like origin was changed 


Try using `afterTransform`
```js
moveable.on("rotate", ({ target, dist, afterTransform }) => {
  target.style.transform = afterTransform;
});
```

**Comment by MRJCrunch** [comment]
@daybrush thanks! afterTransform helped with the second bug, but rotate with zoom is still bad

**Comment by daybrush** [comment]
@MRJCrunch 

I'm fixing the bug now.
wait a munite.

**Comment by MRJCrunch** [comment]
@daybrush was it fixed in 0.40.1? still have the issue with rotate 
https://codesandbox.io/s/movable-zoom-issue-7toyj3?file=/src/index.js

**Comment by daybrush** [comment]
@MRJCrunch 



I am looking for a solution to the problem now.

Temporarily try using css like below.
Try using position: relative on the parent element using zoom.

```css
#app {
  position: relative;
}
```

**Comment by MRJCrunch** [comment]
@daybrush great, it helped, thank you for workaround! but it is not always possible to have relative parent element, so I'll wait for your final solution

**Comment by daybrush** [comment]
@MRJCrunch 


moveable's new version is released.

Check it again. Thank you :)

**Comment by MRJCrunch** [comment]
@daybrush works great now! thank you very much!
