### ISSUE TITLE
Feature Request: Pass roundable value via able-interface

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#804]
## Environments
* Framework name: VanillaJS
* Moveable Component version: 0.40

## Description
I've developed a tooltip-able to be able to show the values that you can change via Moveable. The only value I am unable to provide via the able-interface, is the roundable value.

Would you be able to pass along this? I tried looking through the `moveable` param to find it but was unable to.

https://user-images.githubusercontent.com/3842798/204387766-c8bce4f8-8d8d-49cf-8ebe-20c244a70bd2.mov
```ts
// ...
export const TooltipViewable: Able<TooltipViewableProps> = {
  // ...
  render (moveable: MoveableManagerInterface<TooltipViewableProps>, renderer: Renderer) {
    const rect = moveable.getRect()
    const props = {
        // ...
        style: {
          '--moveable-height': rect.offsetHeight,
          '--moveable-width': rect.offsetWidth,
          '--moveable-rotation': rect.rotation,
          '--moveable-translatex': rect.left,
          '--moveable-translatey': rect.top,
        },
        'data-transformOriginX': rect.transformOrigin[0],
        'data-transformOriginY': rect.transformOrigin[1],
        'data-borderRadius': '0',
    }
    return renderer.createElement('div', props)
  },
}
```

**Comment by daybrush** [comment]
@SidIcarus 
If roundable is enabled, you can use style.borderRadius.

```js
const borderRadius = moveable.state.style.borderRadius;
```
