### ISSUE TITLE
Shake during resize with transform scale and guidelines

### ISSUE THREAD

**Issue by mdominiak2** [daybrush/moveable#806]
## Environments
* Framework name: Vanilla JS
* Framework version:
* Moveable Component version: 0.41.0
* Testable Address(optional): https://codesandbox.io/s/twilight-shape-xrxiex?file=/src/index.js

## Description
![bug](https://user-images.githubusercontent.com/109274806/205623222-f461ac4a-018d-409e-94eb-820170d89618.gif)

**Comment by daybrush** [comment]
@mdominiak2 


moveable's new version is released. Check it again.
