### ISSUE TITLE
Question: Why is there no OnDragOriginStart.set, OnRoundStart.set

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/moveable#807]
## Environments
* Framework name: VanillaJS
* Moveable Component version: 0.41.1

## Description
Moveable currently initializes the drag origin of a given target at the current value they have set for `transformOrigin`, defaulting to `50%, 50%`.  The same goes for `border radius` and roundable. 

Would adding in `e.set` to these two be useful?

```js
  dragOriginStart (e) {
    const state = getState(e.target)
    e.set(state.origin) // <--
    e.dragStart && e.dragStart.set(state.translate)
  },
  ```

**Comment by daybrush** [comment]
@SidIcarus 

You can omit both e.set and e.dragStart.set

**Comment by SidIcarus** [comment]
Makes sense. Thank you for the clarification.

Will you be able to add `@deprecated` to the function definitions? It will then show up in the type definitions.

**Comment by daybrush** [comment]
@SidIcarus 

Although it seems to be rarely used, `set` is called internally with the default value.

Perhaps in the next version there will be a simpler usage.

1. Current
```js
onDrag={e => {
    e.target.style.transform = e.transform;
}}
onDragOrigin={e => {
    e.target.style.transformOrigin = e.transformOrigin;
    e.target.style.transform = e.drag.transform;
}}
```

2. Next 1
```js
onDrag={e => {
    e.target.style.cssText += e.cssText;
}}
onDragOrigin={e => {
    e.target.style.cssText += e.cssText;
}}
```

3. Next 2
```js
onRender={e => {
    e.target.style.cssText += e.cssText;
}}
```
