### ISSUE TITLE
moveable bound 관련

### ISSUE THREAD

**Issue by 0hhanum** [daybrush/moveable#809]
Environments
Framework name: vue.js / moveable / selecto
Framework version: vue2 / 0.24.6 / 1.11.1
Description

안녕하세요.

moveable / selecto 감사히 사용하고 있습니다.

현재 진행중인 프로젝트에서 moveable 컨테이너 좌측 메뉴를 접었다 폈다 하는 기능이 있는데

메뉴를 접어 moveable 영역이 확장된 상태에서 확장된 곳에 있던 객체를

메뉴를 다시 폈을 시 가려져 사용이 어려운 문제가 있습니다.

혹시 이런 경우 사용할 수있는 방법이 있을까요?

좌측 메뉴를 다시 열었을 때 가려지는 부분의 객체들에게 drag 이벤트를 주면 bounds 속성때문에 튕겨져 나오는 것 같던데

실제 드래그를 하지 않고 객체들에게 drag 이벤트를 줄 수 있는지 궁금합니다.

감사합니다. 주말 잘 보내세요.

**Comment by daybrush** [comment]
@0hhanum 

안녕하세요. moveable과 selecto를 사용해주셔서 감사합니다.

해결 방법을 찾던 중에 버그가 발견되어 새 버전으로 배포했습니다. (moveable@0.42.1)

먼저 새버전으로 업데이트하시고 moveable 인스턴스의 request 메서드를 사용해보시길 바랍니다.

```js
moveable.request("draggable", { deltaX: 0, deltaY: 0 }, true);
```

**Comment by 0hhanum** [comment]
안녕하세요. 빠른 답변 및 처리 감사드립니다.

말씀해주신대로 request 메서드 호출 시 requester 를 반환하지만 해당 requester 의 정확한 사용법을 알기 어렵습니다.

![image](https://user-images.githubusercontent.com/79507291/208329540-a4020094-d51f-4679-abf9-e8e07b36504f.png)

제가 사용한 방식이 맞는지 확인 부탁드립니다.

첫 이슈는 위의 컨테이너를 벗어난 객체는 실제 드래그 시 bounds 속성에 의해 튕겨져 나오는데

이를 이벤트를 발생시켜 강제로 할 수 있는 방법이 있는지 였습니다.

해당 컨테이너의 bounds.right 값은 1300 이라 

`moveable.request("draggable", { deltaX: 1300, deltaY: 0 }, true);` 을 실행해도 영역을 벗어난 객체에 대해 드래그 이벤트가 발생 

하지는 않았습니다. 어떤 방식으로 사용해야 할 지 알려주시면 감사하겠습니다.

* 추가로 request  의 두번째 파라미터의 deltaX / deltaY 는 해당 위치에 있는 객체들에 대해서만 draggable 이벤트를 발생시키는 건가요?
