### ISSUE TITLE
Guidelines are flickering when classname is changing

### ISSUE THREAD

**Issue by MRJCrunch** [daybrush/moveable#810]
## Environments
* Framework name: N/A
* Framework version: N/A
* Moveable Component version: 0.42.1
* Testable Address(optional): https://codesandbox.io/s/movable-guidelines-issue-2upuxb?file=/src/index.js

## Description
I have a logic to hide control-box when the movable element is not selected (I've seen similar issue and it was suggested to make `display: none` to the control-box). In order to do it I add/remove class `active` to the movable element to understand what style should be applied. Also I use guidelines. The problem is if change the className of movable element on `mousedown` event (it is ok with `click`, but I need `mousedown`), guidelines are flickering, and if there are a lot of elements it is really disturbing, how I can fix it?

![Screen Recording 2022-12-12 at 14 03 04](https://user-images.githubusercontent.com/17198997/207004806-b7840583-beef-41a5-9fb8-5ceef8f6a2a5.gif)

**Comment by daybrush** [comment]
@MRJCrunch 

Okay, I'll fix it so that the guidelines are displayed on the first drag.

**Comment by MRJCrunch** [comment]
@daybrush it was fixed, thanks!
