### ISSUE TITLE
A dist logic calculation different between versions

### ISSUE THREAD

**Issue by mhaidamashko** [daybrush/moveable#815]
## Environments
* Framework name: None
* Framework version: None
* Moveable Component version: 0.42.1
* Testable Address(optional): https://codesandbox.io/s/little-https-w9566t

## Description
Hi, I upgraded moveable and see that in the new `0.42.1` version (previously I had `^0.23.0` and there is no bug)
When I `resize/drag` an element you modify the dist depending on the element `width/height`.
and when I try to change an element to 12 pixels I receive a value like 11.5/11.6/12.4 in the dist(depending on element parameters).
![image](https://user-images.githubusercontent.com/30477831/207572359-51757fc5-b58e-4e58-8710-a324e305e79e.png)
![image](https://user-images.githubusercontent.com/30477831/207572399-cfa8dd75-7d42-41f0-93be-946c38409770.png)

Is it the right logic?
(in the 0.23.0, it changes a value without enhancing it and I can rely on it in calculations and tests)

Thanks for your hard work.

**Comment by daybrush** [comment]
@mhaidamashko 

Set `throttleResize: 0` (default: 1)

Since it is 1, the moveable will try to keep the target's width and height values as integers.
