### ISSUE TITLE
Changing a snappable  property on drag(state updates differently between versions)

### ISSUE THREAD

**Issue by mhaidamashko** [daybrush/moveable#818]
## Environments
* Framework name: None
* Framework version: None
* Moveable Component version:  0.42.2
* Testable Address(optional): https://codesandbox.io/s/beautiful-wilson-n5pkmb?file=/src/index.js

## Description
When I set a `snappable` false in the handlers(drag/dragStart) it does not affect a moveable object/state immediately. However, in the previous versions, it works as expected. 
![image](https://user-images.githubusercontent.com/30477831/208486452-f77853b4-1769-49d5-8690-f21eed61da40.png)

@daybrush Can you guide me? Thank you a lot for your supporting any issue.

**Comment by daybrush** [comment]
@mhaidamashko 

Changing props works asynchronously.

```js
moveable. snappable = false;
```
It will change to false after 1 tick.

If you want to synchronize
```js
moveable. snappable = false;
moveable. forceUpdate();
```
call this
