### ISSUE TITLE
안녕하세요. 빠른 답변 및 처리 감사드립니다.

### ISSUE THREAD

**Issue by 0hhanum** [daybrush/moveable#823]
** 관련 이슈
https://github.com/daybrush/moveable/issues/809#issuecomment-1356944330

말씀해주신대로 request 메서드 호출 시 requester 를 반환하지만 해당 requester 의 정확한 사용법을 알기 어렵습니다.

![image](https://user-images.githubusercontent.com/79507291/208329540-a4020094-d51f-4679-abf9-e8e07b36504f.png)

제가 사용한 방식이 맞는지 확인 부탁드립니다.

첫 이슈는 위의 컨테이너를 벗어난 객체는 실제 드래그 시 bounds 속성에 의해 튕겨져 나오는데

이를 이벤트를 발생시켜 강제로 할 수 있는 방법이 있는지 였습니다.

해당 컨테이너의 bounds.right 값은 1300 이라 

`moveable.request("draggable", { deltaX: 1300, deltaY: 0 }, true);` 을 실행해도 영역을 벗어난 객체에 대해 드래그 이벤트가 발생 

하지는 않았습니다. 어떤 방식으로 사용해야 할 지 알려주시면 감사하겠습니다.

* 추가로 request  의 두번째 파라미터의 deltaX / deltaY 는 해당 위치에 있는 객체들에 대해서만 draggable 이벤트를 발생시키는 건가요?

_Originally posted by @0hhanum in https://github.com/daybrush/moveable/issues/809#issuecomment-1356944330_

**Comment by daybrush** [comment]
@0hhanum 

deltaX, deltaY는 타겟의 움직일 양이라고 보시면 될 것 같아요.

다음 코드펜을 참고해보시길 바랍니다.
https://codepen.io/daybrush/pen/xxJGELx

**Comment by 0hhanum** [comment]
확인했습니다. 정말 감사합니다 !
