### ISSUE TITLE
Question: How to set visibility of controllers.

### ISSUE THREAD

**Issue by yulafezmesi** [daybrush/moveable#828]
## Environments
* Framework name: moveable
* Framework version: ^0.42.2
* Moveable Component version:
* Testable Address(optional):

## Description

Hi! Huge thanks for the great framework!

I've a quick question. Is there any way to set visibility of controllers without breaking functionality? For example I want to remove lines while dragging. Do I have to do via using class or styles?

Thanks.

**Comment by daybrush** [comment]
@yulafezmesi 


1. The className prop is provided. You can change CSS.
2. `hideDefaultLines` prop is provided. You can make the default line invisible.

**Comment by yulafezmesi** [comment]
className would be a certain solution in this case. hideDefaultLines flag only toggle visibility of lines not included resize handlers.
