### ISSUE TITLE
updateRect on react

### ISSUE THREAD

**Issue by Aleksis92** [daybrush/moveable#84]
Hi, on react sandBox example [https://codesandbox.io/s/react-moveable-demo-jl69c](url) is error with resize rect.
this.moveable doesn't exist (undefined)
![Screenshot from 2019-11-05 17-31-50](https://user-images.githubusercontent.com/31177965/68217083-0eaf0e00-fff3-11e9-9bad-348b9428d698.png)
![Screenshot from 2019-11-05 17-31-58](https://user-images.githubusercontent.com/31177965/68217084-0eaf0e00-fff3-11e9-859f-ecf01fd086a4.png)
![Screenshot from 2019-11-05 17-32-04](https://user-images.githubusercontent.com/31177965/68217086-0f47a480-fff3-11e9-86b9-1c4ee1b178c4.png)

So how can i use updateRect function on react?
Thanks

**Comment by daybrush** [comment]
@Aleksis92 

Fixed it in the demo. Thank you :)
