### ISSUE TITLE
Drag from outside ?

### ISSUE THREAD

**Issue by Marius8881** [daybrush/moveable#85]
Is there something similar to this  https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html ? I can not seem to find it. 
Thank you.

**Comment by daybrush** [comment]
@Marius8881 

Is this the demo you think?
https://codepen.io/pistell/pen/XWWdZrv


It's a related issue.
https://github.com/daybrush/moveable/issues/54

**Comment by Marius8881** [comment]
I found this one also, the thing is, it uses html5 drag and drop also, and I thought maybe there is a option in react for this. 
Thank you for answering, I appreciate it.

**Comment by Marius8881** [comment]
Also, for react this is a really "hacky" way to do it, is it possible to include a function onDragOver and on onDrop ?

**Comment by daybrush** [comment]
It's impossible to put the html5 api.

Instead

onDragOver => onDrag
onDrop => onDragEnd


```js
moveable.on("dragStart", e => {
    e.datas.a = 1;
    console.log(e.inputEvent.target);
});
moveable.on("drag", e => {
    console.log(e.inputEvent.target);
    console.log(e.datas.a);
});
moveable.on("dragEnd", e => {
    console.log(e.inputEvent.target);
    console.log(e.datas.a);
});

```
