### ISSUE TITLE
ngx-moveable broken after 0.38.0, previous 0.37.1 works great, see video

### ISSUE THREAD

**Issue by born2net** [daybrush/moveable#856]
As you can see from the attached gif, in Angular project all is well in version 0.37.1
As soo as we move to 0.38.+ or greater multi select is broken things jump around and resize to top and also we can drag outside the ruler area, all these issues work fine in 0.37.1....

is anyone else seeing this? Is there broking changes we need to change? ( I don't think as we still in minor version change)

Thanks for a great project,

![moveable](https://user-images.githubusercontent.com/5090936/222959989-8d85b87f-a6bf-43e1-a3e5-083b4606a96b.gif)

**Comment by daybrush** [comment]
@born2net 

Can you briefly tell the code of onDragGroup?

Or can you reproduce the problem via codesandbox?

**Comment by born2net** [comment]
sure here you go:

![image](https://user-images.githubusercontent.com/5090936/223038315-ce5872cf-3860-44f0-930e-c341154b1b5f.png)

**Comment by born2net** [comment]
I am now printing the console.log left / top so you can see that values received are wrong:
![dragGroup](https://user-images.githubusercontent.com/5090936/223041107-97438383-26bb-49e7-8303-7ea4e389254e.gif)

**Comment by born2net** [comment]
any more info needed? tx!

**Comment by daybrush** [comment]
@born2net 

I figured out the cause of the bug.
It will be released within this week.

**Comment by born2net** [comment]
thank you, I am just wondering why no one else reported this? 
this has been since 0.38 and clearly MANY people use this lib. any ideas?

TX for an amazing lib,

Sean.

**Comment by daybrush** [comment]
@born2net 

Maybe it's because you're using a transform other than left or top.

**Comment by born2net** [comment]
Hi...
I tested ```"ngx-moveable": "^0.40.1",``` but unfortunately I am seeing the same behavior, jumps right onto the cornet on group drag :(

**Comment by daybrush** [comment]
@born2net 


ngx-moveable's latest version is 0.41.0. Test 0.41.0 version/

**Comment by born2net** [comment]
I now tried version ```"ngx-moveable": "^0.40.1",``` and I am sorry to report that the issue still persists.
it's still jumps to corner on multi selection.

**Comment by born2net** [comment]
I now tried version "ngx-moveable": "^0.41.0", and I am sorry to report that the issue still persists.
it's still jumps to corner on multi selection :/

**Comment by daybrush** [comment]
@born2net 

ngx-moveable@0.41.1 is released. Check it again.

This correction was not reflected properly and was reflected again.

**Comment by born2net** [comment]
u r d man!
fixed it!!!
TX for the best lib!!!
Sean <3
