### ISSUE TITLE
StopPropagation another event on all events (exclude drag)

### ISSUE THREAD

**Issue by Aleksis92** [daybrush/moveable#86]
Hi again!
Is It possible  to add props for stopPropagation other DOM events on resize, rotate and etc?
For example I have some elements which can be target for 1 moveable on one area. I change target on mouseDown on those elements and want to remove target on area mouseDown. So if i try to resize moveable element - area mouseDown event fired and removed target.

**Comment by daybrush** [comment]
@Aleksis92 
`moveable` 0.10.0 is released.

All events in moveable have `inputEvent` to stopPropagation.
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-events
 
```js
moveable.on("dragStart", ({ inputEvent }) => {
   inputEvent.stopPropagation();
});
```

thank you :)
