### ISSUE TITLE
Border have offset with respect to target in a Web-component

### ISSUE THREAD

**Issue by zsoerenm** [daybrush/moveable#860]
## Environments
* Framework name: Firefox
* Framework version: 110.0.1 
* Moveable Component version: 0.43.1
* Testable Address(optional): https://stackblitz.com/edit/lit-element-typescript-demo-vpuvyn?file=moveable-elements.ts,index.ts,index.html,tsconfig.json,package.json

## Description
I know this has been touched in https://github.com/daybrush/moveable/commit/af20f7e04a692e192bb6b27e4478c9d0cb0cfd29
But it doesn't only affect react components.
I build a lit component, that uses moveable js. It has the same problem:
![grafik](https://user-images.githubusercontent.com/375486/223480083-5c20fde0-8ade-4aff-b31a-c24fae615d3a.png)

**Comment by daybrush** [comment]
@zsoerenm 

Actually, that commit is a slightly different issue.

It is probably a problem that has not been handled for padding and margin in html and body.

Try setting it like this:
```css
html, body {
   padding: 0;
   margin: 0;
}
```

**Comment by zsoerenm** [comment]
Well yes, for this example this works, but if I add a header it doesn't work anymore:
![grafik](https://user-images.githubusercontent.com/375486/223507548-867c7e9a-692f-461c-a8fd-d0730d3d1911.png)
The header has a height of 150px. The offset between the yellow target and the border is also 150px.

Here is the stackblitz to try out:
https://stackblitz.com/edit/lit-element-typescript-demo-vpuvyn?file=moveable-elements.ts,index.ts,index.html,tsconfig.json,package.json

**Comment by daybrush** [comment]
@zsoerenm 

I'll check it out and release it within this week.

**Comment by daybrush** [comment]
@zsoerenm 

Hello. 

I checked the reason, try removing `container: this` option.

**Comment by zsoerenm** [comment]
Thanks that worked!
What's actually the difference between the `parentElement` in `new Moveable(parentElement, optionsopt)`, `container`, `rootContainer`, `portalContainer`, `viewContainer`?

**Comment by daybrush** [comment]
@zsoerenm 

container, rootContainer, and portalContainer are internally used codes.

parentElement is the parent element into which the Moveable is inserted.

The viewContainer is an area that allows you to maintain the shape of the cursor while dragging.
