### ISSUE TITLE
Help request: Controls lag behind element when dragged/scaled/rotated

### ISSUE THREAD

**Issue by quinn280** [daybrush/moveable#862]
## Environments
* Framework name: React
* Framework version: 18.2
* Moveable Component version: 0.47.1
* Testable Address(optional):

## Description

![Example](https://user-images.githubusercontent.com/54292238/224523552-9920da38-dd42-4322-9ccb-5d6b0b82851a.gif)

My example here closely follows the examples I've seen in the storybook so I am unsure what is causing the issue here

[Code Sandbox Example](https://codesandbox.io/s/react-overlay-issue-sjwfjh?file=/src/App.js)

**Comment by daybrush** [comment]
@quinn280 

See README for React 18 concurrent mode. And use `flushSync`.
https://github.com/daybrush/moveable/tree/master/packages/react-moveable#react-18-concurrent-mode

Thank you :)

**Comment by quinn280** [comment]
Ahh, thank-you!
