### ISSUE TITLE
onKeyDown event not fired on moveable items 

### ISSUE THREAD

**Issue by quinn280** [daybrush/moveable#863]
## Environments
* Framework name: React
* Framework version: 18.2
* Moveable Component version: 
* Testable Address(optional): https://codesandbox.io/s/moveable-onkeydown-issue-0tchy3?file=/src/App.js

## Description

I would like to create a feature where users can remove an item by selecting it and pressing the backspace or delete key on their keyboard. 

![backspace (2)](https://user-images.githubusercontent.com/54292238/224603443-82ff8561-68c9-436e-adfe-496a684663fe.gif)

However, when I make the items moveable, the onKeyDown event doesn't trigger. Any idea how this could be fixed?

**Comment by daybrush** [comment]
@quinn280 

By default, preventDefault is set for mousedown, so focus is not achieved.

If you want focus, try with the following code.

```js
onDragStart={e => {
          e.target.focus();
}}
```


And the moveable is not automatically updated.

Also try with the following code by `updateSelectors` method.


```jsx
  const handleRemove = (key) => {
    setAnimals(animals.filter((f) => f.key != key));

    requestAnimationFrame(() => {
      moveableRef.current.updateSelectors();
    });
  };
```

**Comment by quinn280** [comment]
perfect, thank-you!
