### ISSUE TITLE
useChangeObserver - feature proposition

### ISSUE THREAD

**Issue by Crazy-Ivan** [daybrush/moveable#869]
UseResizeObserver works great for situations when I update element size from the input form. However, I also have input for the position and rotation. those changes aren't visible by movable. Would be great to have something general like useChangeObserver. So there would be no need to monitor it by myself and trigger updates.

**Comment by daybrush** [comment]
@Crazy-Ivan 

In fact, I think it would be difficult because the Observer has an API for detecting location changes.

but the style attribute is detectable.

**Comment by daybrush** [comment]
@Crazy-Ivan 

moveable's new version is released.
`useMutationObserver` prop is added.

There is no API for position checking yet, but inline style detection will do.

**Comment by Crazy-Ivan** [comment]
@daybrush Thank you!  👍

**Comment by reactone** [comment]
This works with roatation, but not with other css transformations. Im trying to update the moveable blue rectangle when I apply scale and translations but it stays in a fixed place.
transform: rotate(-31.24deg) scale(1.95172) translateX(78.9642px) translateY(78.9642px)
Is there a way to do this? @daybrush
![Screenshot 2023-05-13 at 12 44 22](https://github.com/daybrush/moveable/assets/48355087/e2295fbe-c4b7-4aab-8007-6c1a789afc9d)
