### ISSUE TITLE
Offset of 3px when resize

### ISSUE THREAD

**Issue by JulesVi** [daybrush/moveable#87]
![image](https://user-images.githubusercontent.com/39760183/68308531-4aa6a980-00ad-11ea-8b55-bfbc91bca9ff.png)
Hello, as you can see, I aligned the tiles, but when I resize one, it got an offset of 3px that I did'nt programm, which make it out of the grid made by the throttle that I set with your module.
(on the picture, 2 tiles : green and orange hav'nt been resized, but the 3 on the right have been, and the moveable-box-control is 3 px for the top and right less than the div it contain)

**Comment by JulesVelo** [comment]
It seems to happen only on Google Chrome, not on Firefox

**Comment by daybrush** [comment]
@JulesVelo 

Can you show me a codepen demo for test?

**Comment by JulesVelo** [comment]
After trying on a other project, I did'nt reproduce the bug so I think it come from my code, if it happen again I'll show you

**Comment by daybrush** [comment]
@JulesVelo 

ngx-moveable 0.6.3 is released.
Probably solved the same problem as your issue.
Check it again.

**Comment by JulesVi** [comment]
Sorry for the delay, I tested and it work perfectly on the resize, no problem anymore.
It still a slight offset on the first drag of an element : if it has'nt been resize yet, it does a little offset but this is minor
