### ISSUE TITLE
Resize anchor point question / suggestion

### ISSUE THREAD

**Issue by lukrak** [daybrush/moveable#88]
Hey mate, I have a question / suggestion.

When resizing element, it's always anchored to top left corner no matter which corner you drag, would it be possible for you to add an option for this so that when you drag, opposite corner is used as an anchor point ?

**Comment by daybrush** [comment]
@lukrak 
Is this what you think it is right?
https://codepen.io/daybrush/pen/XWWdeZX?editors=1010

https://github.com/daybrush/moveable/issues/41

**Comment by lukrak** [comment]
Oh. Yes. Exactly what I meant. Thank you. I'll definitely use your example.
