### ISSUE TITLE
Enhancement - Percentage based snap guidelines

### ISSUE THREAD

**Issue by sdraper69** [daybrush/moveable#884]
Version - latest
Javascript

As per the examples I am setting up my guidelines like so...
verticalGuidelines = [0, 100,200,500];

However I really just want them to at a set percentage, no matter the viewport width.

Can the guidelines be set using percentages  (eg. 50%) rather than what I assume is px?

**Comment by daybrush** [comment]
@sdraper69 

OK, I'll add it in the next version.
