### ISSUE TITLE
Snappable element with centered container

### ISSUE THREAD

**Issue by yuri-dzabaev** [daybrush/moveable#888]
## Environments
* Framework name: React 
* Framework version: 18.2.0
* Moveable Component version: 0.48.0
* Testable Address(optional): https://codesandbox.io/s/nifty-snyder-721im8?file=/src/App.js

## Description
Hi @daybrush , thanks a lot for your great work 🙏
I have a centered container with an odd width. And snappable element got half pixel position X (0.5 instead of 0). How can I fix it? (its ok without justifyContent: "center", but I need to center the container)
![image](https://user-images.githubusercontent.com/44072734/231008108-4f599dad-f7b4-4252-8d71-952aac5d8341.png)

**Comment by yuridzabaev** [comment]
thanks @daybrush ! seems ok for fixed width container, but when the "root" container has a width of 100%, the error seems to be reproduced


I have updated the repro link (when the width of the container is set to 100% then the value of width can be a float, so just for reproduce the issue I set the width to 700.2px manually) https://codesandbox.io/s/nifty-snyder-721im8?file=/src/App.js

**Comment by daybrush** [comment]
@yuridzabaev 


thanks. The delta calculation has been reversed and unnecessary calculations have been removed.

Test with version 0.49.1.

**Comment by yuridzabaev** [comment]
@daybrush works perfect, thank you! 💪
