### ISSUE TITLE
Question: Can snapping work on center of item?

### ISSUE THREAD

**Issue by andrejohansson** [daybrush/moveable#89]
Is it possible to make snapping consider the dragged objects **center** lines also instead of just boundaries?

This would make it easy to center objects in the container for example.

![image](https://user-images.githubusercontent.com/2828428/68478083-54581a80-022f-11ea-82eb-12bcd8c0174d.png)

**Comment by daybrush** [comment]
@andrejohansson 

enable `snapCenter`: true

https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#snappableguidelines--boundaries
https://daybrush.com/moveable/release/latest/doc/Moveable.html#snapCenter

**Comment by andrejohansson** [comment]
Works like a charm, thank you!
