### ISSUE TITLE
Error when moving group whilst scaling the same group on a multitouch device

### ISSUE THREAD

**Issue by nathnolt** [daybrush/moveable#898]
## Environments
* Framework name: moveable.js
* Framework version: 0.45
* Moveable Component version:
* Testable Address(optional): https://codepen.io/nathnolt/pen/MWPbvgP

## Description

Error when dragigng a group whilst simultaniously scaling the group on multitouch device.

Reproduce steps:
1. you start scaling a group with 1 finger, but you don't let your finger go off the screen
2. with a different finger: you start to touch on that group and start dragging.

Error messages:

- iPad
  TypeError: undefined is not an object (evaluating 'datas[ableName]') in https://example.com/test/moveable.js @ 5824:28

- android
  Uncaught typeError: Cannot read properties of undefined (reading 'draggable') in https://example.com/test/moveable.js @ 5824:28

So also in the same location.

This is: function setCustomDrag 

```
function setCustomDrag(e, state, delta, isPinch, isConvert, ableName) {
  var _a, _b;

  if (ableName === void 0) {
    ableName = "draggable";
  }

  var result = (_b = (_a = state.gestos[ableName]) === null || _a === void 0 ? void 0 : _a.move(delta, e.inputEvent)) !== null && _b !== void 0 ? _b : {};
  var datas = result.originalDatas || result.datas;
  var ableDatas = datas[ableName] || (datas[ableName] = {}); // this is the line Where the error happens. result seems like it's empty as well.
  return __assign(__assign({}, isConvert ? convertDragDist(state, result) : result), {
    isPinch: !!isPinch,
    parentEvent: true,
    datas: ableDatas,
    originalDatas: e.originalDatas
  });
}
```

Testing link:
https://codepen.io/nathnolt/pen/MWPbvgP

Note that on the example page, we don't get this nice error because the location of the script is on another domain. So to get a better error, you need to download the files.

Thanks for reading

**Comment by daybrush** [comment]
@nathnolt 

* `croact-moveable` 0.3.0
* `@moveable/helper` 0.1.2
* `lit-moveable` 0.24.0
* `moveable` 0.47.0
* `preact-moveable` 0.49.0
* `react-moveable` 0.50.0
* `svelte-moveable` 0.39.0
* `vue-moveable` 2.0.0-beta.66
* `vue3-moveable` 0.22.0
* `ngx-moveable` 0.44.0



moveable's new version is released. Check it again.

**Comment by nathnolt** [comment]
Okay, the bug has been resolved. Nice.
