### ISSUE TITLE
Selecto issue with individualGroupable

### ISSUE THREAD

**Issue by JDMCreator** [daybrush/moveable#905]
## Environments
* Framework name: Moveable + Selecto
* Framework version:
* Moveable Component version:
* Testable Address(optional): [https://codesandbox.io/s/charming-khorana-qxumzy?file=/src/index.ts](https://codesandbox.io/s/charming-khorana-qxumzy?file=/src/index.ts)

## Description

It seems some elements are not selected when using `Selecto` and `individualGroupable` is set to true.

![Recording 2023-04-28 at 20 55 39](https://user-images.githubusercontent.com/2695778/235274109-ddbe52be-577d-41a7-89d3-7212a82b3bce.gif)

**Comment by daybrush** [comment]
@JDMCreator 

* `croact-moveable` 0.3.0
* `@moveable/helper` 0.1.2
* `lit-moveable` 0.24.0
* `moveable` 0.47.0
* `preact-moveable` 0.49.0
* `react-moveable` 0.50.0
* `svelte-moveable` 0.39.0
* `vue-moveable` 2.0.0-beta.66
* `vue3-moveable` 0.22.0
* `ngx-moveable` 0.44.0



moveable's new version is released. Check it again.

**Comment by JDMCreator** [comment]
Thank you, it is fixed!
