### ISSUE TITLE
How can you detect a long press on a Moveable object?

### ISSUE THREAD

**Issue by embeddedt** [daybrush/moveable#91]
Hi,

I'm using Moveable in a project and loving it so far. It's much more intuitive (especially for touch users) than my previous solution which involved buttons for scaling and rotating. Now I can just naturally use my fingers. :slightly_smiling_face: 

One of my requirements is that I need to know when a draggable object is tapped and held without moving. I've had a look through the various forms of documentation but I haven't found anything related to this feature.

I'd be happy to implement it myself with some pointers of where to start.

**Comment by daybrush** [comment]
@embeddedt 
I'm sorry. moveable does not provide the feature.
But you can make it custom:
```js
moveable.on("dragStart", e => {
    e.datas.startTime = Date.now();
}).on("dragEnd", e => {
    if(e.isDrag) {
        return;
    }
    const distTime = Date.now() - e.datas.startTime;
    if (distTime >= 1000) {
        console.log("longpress");
    }
});

**Comment by embeddedt** [comment]
Thanks! It works exactly as I needed!
