### ISSUE TITLE
Vue 3 Movable not working

### ISSUE THREAD

**Issue by shalinisubramani** [daybrush/moveable#910]
## Environments
* Framework name: Vue 3 Laravel
* Moveable Component version: ^0.22.3
After Upgrade the version movable not working. It is not Working in "0.22.1" also.
## Description
![image](https://user-images.githubusercontent.com/6822777/236801583-591b9f11-6f06-41db-817c-5fcacb667fc3.png)

We faced build error like below:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/6822777/236788731-830e982c-c611-438c-8a5c-c4a2a5340e49.png">

It was working fine on past week. Now it is breaking. 

"Module not found: Error: Can't resolve 'moveable' in '/../node_modules/vue3-moveable/dist'"

**Comment by daybrush** [comment]
@shalinisubramani 

vue3-moveable@0.22.6 is released. Check it again.

**Comment by shalinisubramani** [comment]
> @shalinisubramani
> 
> vue3-moveable@0.22.6 is released. Check it again.

Working fine as expected. Thank you @daybrush
