### ISSUE TITLE
Missing type

### ISSUE THREAD

**Issue by John60676** [daybrush/moveable#911]
## Environments
* Framework name: Vanilla JS
* Framework version: - 
* Moveable Component version: 0.47.6
* Testable Address(optional): 

## Description

Missing type

<img width="633" alt="image" src="https://user-images.githubusercontent.com/21698973/236973205-00430ce7-d246-4def-8c17-ff51e54e03d0.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/21698973/236973265-21024af1-61ef-4c61-8753-241e95a62b51.png">

**Comment by daybrush** [comment]
@John60676 

moveable's new version is released. Check it again.
