### ISSUE TITLE
Moveable group of SVG not working when parentElement has position set

### ISSUE THREAD

**Issue by nathnolt** [daybrush/moveable#914]
## Environments
* Framework name: moveable
* Framework version: 0.47.6
* Moveable Component version: 0.47.6 ( I think )
* Testable Address(optional): https://codepen.io/nathnolt/pen/JjmLWBY

## Description

Moveable group not working when there are multiple SVG elements in it and the moveable parentElement has a CSS position value other than static.

Version 0.45.0 works, and
Version: 0.46.0 - 0.47.6 doesn't work.

Example ( 0.47.6 ) This version is broken
    https://codepen.io/nathnolt/pen/JjmLWBY

Example ( 0.45.0 ) This version works
    https://codepen.io/nathnolt/pen/RweMgGO

Thanks for reading

**Comment by daybrush** [comment]
@nathnolt 

@John60676 

moveable's new version is released (0.47.7). Check it again.
