### ISSUE TITLE
Styles are copied multiple times while moving

### ISSUE THREAD

**Issue by zsoerenm** [daybrush/moveable#916]
## Environments
* Moveable Component version: 0.47.2
* Testable Address(optional):

## Description
The styles for moveable guidelines etc. are copied multiple times when moving a node around.

https://github.com/daybrush/moveable/assets/375486/e429e1d3-59c4-465f-b32a-3d862600d4d7

I don't have a minimum working example in this case, sorry.
Do you have a clue, why this could be the case?
My initial layout has 5 nodes inside. I guess this is why it has 5 styling components in the beginning.
I guess one would be sufficient?

**Comment by daybrush** [comment]
@zsoerenm 

I do not know why.

Please update the version to version 0.47.7 and let me know if you encounter any issues.

https://codepen.io/daybrush/pen/gOBzyVW

The demo doesn't seem to have any problems. It is difficult to reproduce the situation.

Please tell me which prop you used.

**Comment by daybrush** [comment]
@zsoerenm 


moveable's new version is released. (0.47.8)
Check it again.

**Comment by zsoerenm** [comment]
Cool this does seem to work thank you!
However, I think there is a dependency missing:
https://stackblitz.com/edit/lit-element-typescript-demo-orvaz6?file=package.json,moveable-elements.ts
I need to install string-hash manually to make it work.

**Comment by daybrush** [comment]
@zsoerenm 


moveable's new version is released. (0.47.9.)
Test it again.
