### ISSUE TITLE
Moveable .moveable-around-control elements ( controlPadding ) not positioned correctly

### ISSUE THREAD

**Issue by nathnolt** [daybrush/moveable#918]
## Environments
* Framework name: vanilla
* Framework version: 0.47.7
* Moveable Component version: 0.47.7
* Testable Address(optional): https://codepen.io/nathnolt/pen/dygKvXL

## Description

As you can see in the Testable Address, I've colorized the .moveable-around-control elements, and the .moveable-edge elements

The .moveable-edge elements (caused by linePadding) are positioned exactly outside of the element. This makes sense.

The .moveable-around-control elements (caused by controlPadding) are positioned incorrectly. The  bottom right one looks like it is in the correct position. The rest of them are positioned incorrectly.

This problem does not seem to happen when controlPadding is exactly 20, But this issue is noticable at smaller values (10) or larger values (30)

Thanks for reading

**Comment by daybrush** [comment]
@nathnolt 


moveable's new version is released. (0.47.8)
Check it again.

**Comment by nathnolt** [comment]
Sorry for late reaction again. But nice, this is also fixed :)
