### ISSUE TITLE
Edges of child elements of group cause dead zone when control-box has an overwrite z-index set.

### ISSUE THREAD

**Issue by nathnolt** [daybrush/moveable#919]
## Environments
* Framework name: vanilla
* Framework version: 0.47.7
* Moveable Component version: 0.47.7
* Testable Address(optional): https://codepen.io/nathnolt/pen/JjmZyrx

## Description

You cannot move the box by dragging on the grey line boxes, which are the :before of the .moveable-line elements of the children.

I know that this requires the user to overwrite the standard z-index of 3000, so it's partly on the user. But as you can see in the css panel at the bottom, I've provided some ways of fixing this problem.

Then again, maybe this shouldn't be considered a bug, and people should fix this themselves in user land, since it's easy to fix in userland.

Another fix would be to add a new configure option, in order to specifiy a custom higher z-index.

Thanks for reading

**Comment by daybrush** [comment]
@nathnolt 


If set to group, child moveable cannot be dragged.

The child's linepadding now appearing in your codepen is considered a bug.

**Comment by daybrush** [comment]
@nathnolt 


moveable's new version is released. (0.47.8)
Check it again.

**Comment by nathnolt** [comment]
Sorry for late reaction. But yes. This issue is resolved.
