### ISSUE TITLE
Clippable use keepRatio and clipTargetBounds

### ISSUE THREAD

**Issue by anphamhoai133** [daybrush/moveable#924]
## Environments
* Framework name: Script
* Framework version: 0.0.1
* Moveable Component version: 0.47.9
* Testable Address(optional):

## Description

Clippable use keepRatio and clipTargetBounds: (error in image)
<img width="212" alt="Screen Shot 2023-05-17 at 17 41 12" src="https://github.com/daybrush/moveable/assets/14211302/0ad33860-c9c9-416c-8890-69e4589e3776">

https://daybrush.com/moveable/storybook/index.html?path=/story/basic--basic-clippable&args=clipTargetBounds:true;keepRatio:true

**Comment by daybrush** [comment]
@anphamhoai133 

* `croact-moveable` 0.4.0
* `@moveable/helper` 0.1.2
* `lit-moveable` 0.25.0
* `moveable` 0.48.0
* `preact-moveable` 0.50.0
* `react-moveable` 0.51.0
* `svelte-moveable` 0.40.0
* `vue-moveable` 2.0.0-beta.76
* `vue3-moveable` 0.23.0
* `ngx-moveable` 0.45.0


moveable's new version is released. That bug has beed fixed.

**Comment by anphamhoai133** [comment]
Thank you @daybrush
