### ISSUE TITLE
How to enable DimensionTooltip and RotationTooltip (Custom ables) only during "resize" and "rotate" events?

### ISSUE THREAD

**Issue by jadiagaurang** [daybrush/moveable#925]
## Environments
* Framework name: Vanilla JS
* Framework version: N/A
* Moveable Component version: 0.47.9
* Testable Address(optional): https://codepen.io/jadiagaurang/pen/PoyXWgJ

## Description
I am building a designing tool which will help to design social media post and website sections. I have added two custom `ables` (`DimensionTooltip` and `RotationTooltip`) to show Width and Height and Rotation as a Tooltip.

But, I would like to show `DimensionTooltip` only during "resize" event and `RotationTooltip` only during "rotate" event.

I tried to make `window.objMoveable.props.dimensiontooltip = false;` and `window.objMoveable.props.rotationtooltip = false;` but, that didn't help.

Thanks in advance!

**Comment by jadiagaurang** [comment]
Hi @daybrush,

I found one of your example at [https://codepen.io/daybrush/pen/OJVxpLK](https://codepen.io/daybrush/pen/OJVxpLK) where you have used Fixed Label to show Dimension and Rotation Info next to Mouse Pointer.

That is very helpful; I have updated my example with that solution. https://codepen.io/jadiagaurang/pen/PoyXWgJ

I have question that should I use `getRect` function from the `objMoveable` to collect info?

```javascript
window.labelElement = $(".label");
function setLabel(clientX, clientY, text) {
    window.labelElement.css({
        "display": "block",
        "transform": `translate(${clientX}px, ${clientY - 10}px) translate(-100%, -100%)`
    });
    window.labelElement.html(text);
}
```

```javascript
objMoveable.on("resize", function (_a) {
    let clientX = _a.clientX, clientY = _a.clientY;
    let rect = objMoveable.getRect();
    setLabel(clientX, clientY, `W: ${Math.round(rect.offsetWidth)} H: ${Math.round(rect.offsetHeight)}`);
}).on("resizeEnd", function (_a) {
    labelElement.hide();
});
```

```javascript
objMoveable.on("rotate", function (_a) {
    let clientX = _a.clientX, clientY = _a.clientY;
    let deg = objMoveable.getRect().rotation;
    setLabel(clientX, clientY, `${deg.toFixed(1)}&deg;`);
}).on("rotateEnd", function (_a) {
    labelElement.hide();
});
```

**Comment by daybrush** [comment]
@jadiagaurang 

The `moveable-control-box` has classes.

`moveable - draggable`, `moveable-resizable`, `moveable - rotatable`

When you drag, the following happens. Check it.

`moveable-dragggable-dragging`, `moveable-resizable-dragging`, `moveable-rotatable-dragging`

I think you can use these well to write css.

Alternatively, there is a method called `.isDragging`.
As an example, if you want to know if you are resizing, call `moveable.isDragging("resizable")`.

**Comment by jadiagaurang** [comment]
@daybrush I will try and let you know! Thanks

**Comment by jadiagaurang** [comment]
@daybrush I was able to show/hide based on those CSS class!
