### ISSUE TITLE
OnClick Event Conflicting Selecto and Editable (a Custom ables)

### ISSUE THREAD

**Issue by jadiagaurang** [daybrush/moveable#926]
## Environments
* Framework name: Vanilla JS
* Framework version: N/A
* Moveable Component version: 0.47.9
* Testable Address(optional): https://codepen.io/jadiagaurang/pen/PoyXWgJ

## Description
I have added a custom ables (`Editable`) with TaggedJSX to show delete button on an Element. The button doesn't trigger OnClick callback anymore after adding Selecto.

Thanks in advance!

**Comment by jadiagaurang** [comment]
@daybrush Yours following two replies helped me resolve the issue by adding conditions in the `dragStart` event of the Selecto!

https://github.com/daybrush/selecto/issues/101
https://github.com/daybrush/selecto/issues/121

I have follow up question regarding how to listen click event on the same element as `dragContainer`?

**Comment by jadiagaurang** [comment]
@daybrush Thanks for adding Feature Label for the request.

For now, I am going to use [ContextMenu Event]( https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) to continue my development.

Looking forward to have this feature implemented. Thanks!

**Comment by daybrush** [comment]
@jadiagaurang 


Try using the `preventClickDefault` option(to true) on moveable.

However, clicks occur on moveable controls, including custom ables such as editable and dimesion.


```js
    if (!objMoveable.isMoveableElement(event.target)) {
      addImage({ "x": x, "y": y });
    }
```


I plan to add the `.getControlBoxElement()` method later.

```js
 // to-be
    if (!objMoveable.getControlBoxElement().contains(event.target)) {
      addImage({ "x": x, "y": y });
    }
```

**Comment by daybrush** [comment]
@jadiagaurang 

* `croact-moveable` 0.4.0
* `@moveable/helper` 0.1.2
* `lit-moveable` 0.25.0
* `moveable` 0.48.0
* `preact-moveable` 0.50.0
* `react-moveable` 0.51.0
* `svelte-moveable` 0.40.0
* `vue-moveable` 2.0.0-beta.76
* `vue3-moveable` 0.23.0
* `ngx-moveable` 0.45.0


moveable's new version is released. `.getControlBoxElement()` method is added.

**Comment by jadiagaurang** [comment]
@daybrush Thanks for addressing my question.

I tried to add the solution you have provided in a Example. Testable Address: [https://codepen.io/jadiagaurang/pen/PoxYVRN](https://codepen.io/jadiagaurang/pen/PoxYVRN)

I am listening click event on the container called `smart-designer` and I have added the IF condition you provided something like this.

```javascript
$(".smart-designer").on("click", function (event) {
  event.preventDefault();
  event.stopPropagation();

  var offset = this.getClientRects()[0];
  let x = (event.clientX - offset.left);
  let y = (event.clientY - offset.top);

  //console.log(objMoveable.getControlBoxElement(), event.target);

  //if (window.objMoveable.target.length === 0) {
  if (!objMoveable.getControlBoxElement().contains(event.target)) {
      addImage({ "x": x, "y": y });
  }
});
```

When I tried to select a Element or select multiple Elements. `addImage` is being triggered. The method is useful but, I may not work for my implementation.

I will use [ContextMenu Event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) if it is tricky to wire up all these events in correct way. Let me know!

Thanks again for providing quick response and implementing feature requests and fixing bugs! 🙏

**Comment by daybrush** [comment]
@jadiagaurang 

Set up the following two cases.

1. addImage only if `e.currentTarget === e.target` is true
2. As a basic operation, click occurs even when dragging. Set `preventClickEventOnDrag` to true in selecto.
3. 
```js
....
$(".smart-designer").on("click", function (event) {
     if (event.target !== event.currentTarget) {
          return;
     }
     .....
});
....
window.objSelecto = new Selecto({
     ...
     preventClickEventOnDrag: true,
});
...
```

**Comment by jadiagaurang** [comment]
@daybrush Thanks, It works!

Example: https://codepen.io/jadiagaurang/pen/PoxYVRN

**Comment by jadiagaurang** [comment]
@daybrush Thanks, It works!

Example: https://codepen.io/jadiagaurang/pen/PoxYVRN
