### ISSUE TITLE
Scalables are broken when persisted with zero width or zero height

### ISSUE THREAD

**Issue by vlorian-de** [daybrush/moveable#927]
# Environments
Framework name: React
Framework version: 18.2
Moveable Component version: 0.48.0
Testable Address: https://codesandbox.io/s/react-moveable-forked-6g9109?file=/src/App.tsx

# Description
When working with Scalables, we've noticed a glitch. This occurs when the Scalable has a zero width or height. Even though the dimensions still appear correct, the position exhibits an odd offset. Once this kind of scale is persisted, it seems to break the Scalable completely. It becomes impossible to return it to a non-zero height/width, and it assumes a random position when a user attempts to rescale it.
![image](https://github.com/daybrush/moveable/assets/64640147/1279cc63-64e5-4e68-94aa-a07e5cb77846)
(Position for non-zero heights is marked with yellow cross)

Interestingly, we don't encounter this issue when working with Resizables.
We tried to implement a workaround using Resizables but were unable to get the flipping over the axis to work.
Has anyone else been able to successfully implement this?

**Comment by daybrush** [comment]
@vlorian-de 


* `croact-moveable` 0.4.0
* `@moveable/helper` 0.1.2
* `lit-moveable` 0.25.0
* `moveable` 0.48.0
* `preact-moveable` 0.50.0
* `react-moveable` 0.51.0
* `svelte-moveable` 0.40.0
* `vue-moveable` 2.0.0-beta.76
* `vue3-moveable` 0.23.0
* `ngx-moveable` 0.45.0

moveable's new version is released. Try it agian.

**Comment by daybrush** [comment]
@vlorian-de 

But if the size is 0, the ratio is unknown.

If you want to use keepRatio

Try using `e.setRatio(1);` in onScaleStart.
