### ISSUE TITLE
Able is missing

### ISSUE THREAD

**Issue by JulesVelo** [daybrush/moveable#93]
Hello, I just did the update (0.6.0 for angular) and when I compile, this trouble appear :
![image](https://user-images.githubusercontent.com/39760183/68662018-44487f80-053c-11ea-8262-e363934e61ac.png)

**Comment by daybrush** [comment]
@JulesVelo 

`ngx-moveable` 0.6.1 is released.

Thank you :)

**Comment by JulesVelo** [comment]
Everything work well now, thanks
