### ISSUE TITLE
How to export in svg the result?

### ISSUE THREAD

**Issue by microSoftware** [daybrush/moveable#931]

**Comment by daybrush** [comment]
@microSoftware 

what do you want? A detailed explanation is needed.

**Comment by microSoftware** [comment]
> @microSoftware
> 
> what do you want? A detailed explanation is needed.

Well, let's say i have many shapes which has been added, moved, resized, rotated and so on.
I'd love to export the overall html view which contain all the current shapes into svg format.

**Comment by daybrush** [comment]
@microSoftware 

sorry. For html results, use `DOM.outerHTML`.

In Moveable, you can get the four points, width, height, and position of the Moveable Control Box through `.getRect`.

**Comment by microSoftware** [comment]
Perfect this is exactly what i was looking for.
