### ISSUE TITLE
Recommended way to access width/height after scaling

### ISSUE THREAD

**Issue by jqhercules** [daybrush/moveable#94]
How would I go about accessing the width and height of the target when using onScaleEnd event in React. 

Currently, I'm can it with .getBoundingClientRect() but was wondering if there is a better way?

**Comment by daybrush** [comment]
@jqhercules 

How about using the getRect method?

```
const { width, height } = moveable.getRect();
```

This is the same as the width and height of getBoundingClientRect.

**Comment by jqhercules** [comment]
I'm using your <Moveable onScaleEnd={e => { ... }} /> react component, how would one access .getRect() within it then?

**Comment by daybrush** [comment]
@jqhercules 

```tsx

<Moveable onScaleEnd={e => {
    e.currentTarget.getRect();
 }} />
// or

<Moveable ref={e => { this.moveable = e; }} />



```

**Comment by jqhercules** [comment]
Can't believe I missed that, thank you.
