### ISSUE TITLE
What does the "snapGap" configuration do?

### ISSUE THREAD

**Issue by woke-T** [daybrush/moveable#943]
## Environments
* Framework name: react
* Framework version: 18
* Moveable Component version: 0.47.0
* Testable Address(optional): 

## Description
No matter how I use this configuration, it has no effect. Can you tell me the correct usage scenario?

**Comment by daybrush** [comment]
snapGap is an option that can be used with `elementGuidelines`.
`snapGap` works when the same distance between elements is reached.

```tsx
snappable={true}
elementGuidelines={...}
snapGap={true}
```

**Comment by woke-T** [comment]
> snapGap is an option that can be used with `elementGuidelines`. `snapGap` works when the same distance between elements is reached.
> 
> ```tsx
> snappable={true}
> elementGuidelines={...}
> snapGap={true}
> ```

ohhhhhh!!  i got it ,thx
