### ISSUE TITLE
Minimum Values for Resize and Scale

### ISSUE THREAD

**Issue by jadiagaurang** [daybrush/moveable#944]
## Environments
* Framework name: Vanilla JS
* Framework version: N/A
* Moveable Component version: v0.48.0
* Testable Address(optional): https://codepen.io/jadiagaurang/pen/PoxYVRN

## Description
I would like to set minimum value for Resize and Scale. So, User can't make element to small or zero (`width: 0px;` and `height: 0px;`)

I would like to limit the resizing to minimum width `50px` and height `50px`.

Is it possible with any currently implemented prop?

**Comment by daybrush** [comment]
@jadiagaurang 

In the "resizeStart" event, there is a `.setMin` function.
Try using `e.setMin([50, 50])`.

But there is no `.setMin` for scalable yet. It'll take a while, but I'll add it.

**Comment by jadiagaurang** [comment]
@daybrush It works well. Thanks!
