### ISSUE TITLE
Bug upon scaling a group to negative, and then scaling again

### ISSUE THREAD

**Issue by nathnolt** [daybrush/moveable#950]
## Environments
* Framework name: Vanilla JS
* Framework version: -
* Moveable Component version: 0.48.0
* Testable Address(optional): https://codepen.io/nathnolt/pen/WNYQpNZ

## Description

Whenever you scale a group negatively, and afterwards, you start scaling again,

The elements within the group jump around, and the anchor point of the scale moves towards a point inside of the group itself, instead of on the edge or corner.

**Comment by daybrush** [comment]
@nathnolt 


* `croact-moveable` 0.5.0
* `@moveable/helper` 0.1.3
* `lit-moveable` 0.26.0
* `moveable` 0.49.0
* `preact-moveable` 0.51.0
* `react-moveable` 0.52.0
* `svelte-moveable` 0.41.0
* `vue-moveable` 2.0.0-beta.77
* `vue3-moveable` 0.24.0
* `ngx-moveable` 0.46.0

moveable's new version is released.
Check it again.

**Comment by nathnolt** [comment]
It's fixed. 1 thing that is weird though, is that even though the demo uses the 0.48 version hard coded in the URL, it's still fixed.
