### ISSUE TITLE
Padding gets larger

### ISSUE THREAD

**Issue by nathnolt** [daybrush/moveable#951]
## Environments
* Framework name: VanillaJS
* Framework version: -
* Moveable Component version: 0.48.0
* Testable Address(optional): https://codepen.io/nathnolt/pen/RwqWVvq

## Description
When you set padding in a config, something like
padding: {left: 5, top: 5, right: 5, bottom: 5}
And you have scalable set to true, the padding scales and thus becomes larger.
Right now there is no way to add a bit of padding which does not become larger.
In most cases this is not a problem, but if you have a tiny shape, the padding becomes huge, as you can see in the testable address.

See, I'm using moveable in a drawing application, and so the user can freedraw, creating SVG shapes, so they can make tiny shapes. In these cases, it can become a problem.

I'm not sure if this should be considered a bug, as this could be something people are relying upon.

**Comment by daybrush** [comment]
@nathnolt 

I'll fix it the next version.

**Comment by daybrush** [comment]
@nathnolt 


* `croact-moveable` 0.5.0
* `@moveable/helper` 0.1.3
* `lit-moveable` 0.26.0
* `moveable` 0.49.0
* `preact-moveable` 0.51.0
* `react-moveable` 0.52.0
* `svelte-moveable` 0.41.0
* `vue-moveable` 2.0.0-beta.77
* `vue3-moveable` 0.24.0
* `ngx-moveable` 0.46.0


moveable's new version is released.
Check it again.

**Comment by nathnolt** [comment]
It's fixed. Nice :)
