### ISSUE TITLE
How to force draggable, resizable to increment or decrement to the multiples of Xpx (i.e. 50px)

### ISSUE THREAD

**Issue by jadiagaurang** [daybrush/moveable#954]
## Environments
* Framework name: Vanilla JS
* Framework version: N/A
* Moveable Component version: 0.48.0
* Testable Address(optional): https://codepen.io/jadiagaurang/pen/QWJyEaE

## Description
I am trying to force user to drag or resize single element or group of element to the multiple of Xpx (i.e. 50px).

![image](https://github.com/daybrush/moveable/assets/430637/6863700a-108c-4164-8602-97fc86e2c716)

I am using following config properties to achieve 50x50 grid.

```javascript
snapDigit: 50,
snapThreshold: 50, // Distance value that can snap to guidelines
snapGridWidth: 50, 
snapGridHeight: 50, 
```

But, for some reason, sometimes, users are able to drag or resize Elements into non multiples of 50px x 50px cell.

For time being I am using [request](https://daybrush.com/moveable/release/latest/doc/Moveable.html#request) to move the element back into into 50px x 50px cell.

But, is there any efficient inbuild way to achieve that?

**Comment by daybrush** [comment]
@jadiagaurang 

It is correct to use it according to your option.

If it doesn't move in multiples of 50x50, that's a bug.

If it doesn't work as it is, is it possible to share a screenshot or gif?

**Comment by jadiagaurang** [comment]
@daybrush 

I have attached the screenshot recording for you to take a look at.

https://github.com/daybrush/moveable/assets/430637/88aaeff5-e81f-46d4-9ccb-18d707a8fa10

Currently, I use request to move into a multiple of 50px. Here is the basic setup to call `request("draggable")` after `dragEng`. 

```javascript
objMoveableRef.on("dragEnd", function (event) {
    var target = event.target;

    var parsedTransform = parseComplexStyleProperty(target.style.transform);

    var x = (parsedTransform["translate"][0].split(',')[0]).replace("px", "").trim();
    var y = (parsedTransform["translate"][0].split(',')[1]).replace("px", "").trim();

    requestDraggable(x, y);
});
requestDraggable: function (x, y) {
  var cellWidth = 50;
  var cellHeight = 50;
  
  if (x % cellWidth != 0 || y % cellHeight != 0) {
        x = roundTo(x, cellWidth);
        y = roundTo(y, cellHeight);

        objMoveableRef.request("draggable", {
            x: x,
            y: y
        }, true);
    }
}
parseComplexStyleProperty = function (style) {
    var regex = /(\w+)\((.+?)\)/g, transform = {}, match;

    while (match = regex.exec(style))
        transform[match[1]] = transform[match[1]]
            ? transform[match[1]].concat([match[2]])
            : [match[2]]

    return transform;
};
roundTo = function (number, roundto) {
    return roundto * Math.round(number / roundto);
};
```

But, there is an issue when Element has any Rotation, then it keeps calling `dragEnd` after `request("draggable")`, which goes into Infinite Loop.

I have attached the screenshot recording for you to take a look at.

https://github.com/daybrush/moveable/assets/430637/f7e69a3d-1976-47b8-92d7-f67406cc6647

Thank you in advance for helping me!

**Comment by daybrush** [comment]
@jadiagaurang 
In the next patch, I will add a function to enable snap to request.

**Comment by jadiagaurang** [comment]
@daybrush Thanks!

For the time being! I first changed my implementation to update Element's Style `transform: translate (x, y)` in the DOM and I call `objMoveableRef.updateRect();` later

```javascript
objMoveableRef.on("dragEnd", function (event) {
  var target = event.target;
  var shouldSnap = true;  // Condition to check if Snapping is needed!
  var x = ?, y = ?, deg = ?;
  if (shouldSnap) {
    target.style.transform = "translate(" + x + "px, " + y + "px) rotate(" + deg + ")";
    objMoveableRef.updateRect();
  }
```

**Comment by jadiagaurang** [comment]
@daybrush Will I be able to Snap Single Element as well as Group on drag, resize and rotate events?

**Comment by daybrush** [comment]
@jadiagaurang 

I hope it will work like that.

**Comment by daybrush** [comment]
@jadiagaurang 


* `croact-moveable` 0.5.0
* `@moveable/helper` 0.1.3
* `lit-moveable` 0.26.0
* `moveable` 0.49.0
* `preact-moveable` 0.51.0
* `react-moveable` 0.52.0
* `svelte-moveable` 0.41.0
* `vue-moveable` 2.0.0-beta.77
* `vue3-moveable` 0.24.0
* `ngx-moveable` 0.46.0



moveable's new version is released.



use `useSnap` with draggable, resizable request

* `Request Draggable with Snappable`
https://daybrush.com/moveable/storybook/index.html?path=/story/request-ables-through-a-method--request-draggable-snappable
* `Request Resizable with Snappable`
https://daybrush.com/moveable/storybook/index.html?path=/story/request-ables-through-a-method--request-resizable-snappable
