### ISSUE TITLE
Accept custom ownerDocument

### ISSUE THREAD

**Issue by ritz078** [daybrush/moveable#957]
## Environments
* Framework name: react
* Framework version: ^18
* Moveable Component version: 0.51.0
* Testable Address(optional):

## Description

The codebase has a lot of references of document. The problem of using document is that it causes a lot of issues when the the component is dynamically added to an iframe. This technique is different from loading a separate URL in an iframe. See https://dev.to/graftini/rendering-in-an-iframe-in-a-react-app-2boa for more details about this approach.

This technique is generally useful for libraries because:

- You can keep your styling isolated
- You can keep your events listeners isolated and
- You can accept any JS as a library option which would not have been possible if you loaded a separate HTML.

## Suggestions

- moveable can accept the custom ownerDocument as an option
- A better approach is to automatically detect the correct ownerDocument by adding a ref to any element and the do `element.ownerDocument` and window using `element.ownerDocument.defaultView` instead of directly using `document` and `window` respectively.

**Comment by daybrush** [comment]
@ritz078 


It is already working inside an iframe.

https://github.com/daybrush/moveable/issues/932


I created a demo by referring to the `dev.to` link.


```tsx
import * as React from "react";
import { createPortal } from "react-dom";
import Moveable from "react-moveable";

function Iframe(props: Record<string, any>) {
    const [ref, setRef] = React.useState<HTMLIFrameElement | null>();
    const container = ref?.contentWindow?.document?.body;

    return (
        <iframe ref={setRef}>
            {container && createPortal(props.children, container)}
        </iframe>
    );
}

export default function App() {
    const targetRef = React.useRef<HTMLDivElement>(null);

    return (
        <div className="root">
            <div className="container">
                <Iframe>
                    <div className="target" ref={targetRef}>Target</div>
                    <Moveable
                        target={targetRef}
                        draggable={true}
                        onRender={e => {
                            e.target.style.cssText += e.cssText;
                        }}
                    />
                </Iframe>
            </div>
        </div>
    );
}
```

**Comment by ritz078** [comment]
Thanks for the code example. This is really helpful.

**Comment by brutal-orange** [comment]
@ritz078 Sorry for the necro, but does this still work for you? We found that nothing but the simple drag functionality works now. Putting a `Moveable` inside an iframe pretty much breaks all functionality.
