### ISSUE TITLE
Propagate click event inside dragGroup element

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#96]
I have a text element inside a dragGroup element that has contenteditable set to true when clicked upon. However, because of moveable-area div, the click event does not reach the element below it. Is there any way to make the click event reach the div below the moveable-area div?

I am also attaching the video for the desired behaviour. Can you please help?

![canva_group_gif](https://user-images.githubusercontent.com/23035769/68825539-74209000-06c0-11ea-8d68-cdbb15175080.gif)

**Comment by daybrush** [comment]
@adityakrshnn 

Sorry if it's a group, it should be ahead because of the drag event. Instead, Moveable provides an `onClickGroup` event.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#.OnClickGroup

```js
moveable.on("clickGroup", e => {
    console.log(e.inputTarget); // maybe text?
});
```

**Comment by katOstrynska** [comment]
@adityakrshnn  hello, did You manage to add content edit functionallity in Moveable element? I have got the same issue, but without moveableGroup and in Vue framerork; I have moveable element and contenteditable div inside

**Comment by adityakrshnn** [comment]
If you are not using moveableGroup, there should be no problems while making the div contenteditable. Make sure you set contenteditable to true and then set focus to the element.

**Comment by katOstrynska** [comment]
@adityakrshnn  my div has contenteditable set to true anf I focus it after click, but my caret position in always on div start and I am not able to set it different; I know it is because I use moveable - if I turn it off, my focus works great and I set caret position at click place

**Comment by adityakrshnn** [comment]
The problem exists with groupables because there is a layer over your elements. However with regular moveables your click events directly go to your elements. You might wanna check if your events have proper x and y coordinates and you are setting correct caret range.

**Comment by katOstrynska** [comment]
Thank You for Your answer. I still have this problem - my content IS editable, I can update text inside, but my caret position is always on text start and back to start after I start typing. Did U have the same problem with groups? How did You manage to fix it?

**Comment by ajinkya-dev** [comment]
@adityakrshnn @daybrush 
How to manage contentEditable true to elements inside groupable ?

**Comment by hrachmkr** [comment]
@katOstrynska I've been struggling with this issue too. Just toggle `draggable` to `false` if your target html element has contentEditable attribute and you'll be able to edit your element wherever you clicked

**Comment by lixue007** [comment]
@adityakrshnn
Have you achieved the effect in the video? How to set the dotted  moveable-line?

**Comment by adityakrshnn** [comment]
You can work with groupable and its events to achieve the desired effect. If you just want dotted lines then it is possible through CSS.
