### ISSUE TITLE
Bug: Moveable + Selecto : Cannot set properties of null (setting 'dist')

### ISSUE THREAD

**Issue by CarlMahnke1** [daybrush/moveable#960]
## Environments
Moveable 0.49.0
Selecto 1.25.0

## Description
I have a very basic scenario with two moveable divs and also selecto in place. When you move the divs around, one after the other, you notice sometimes an error in the console. The result is, that the div wont move.

The issue does not occur, when you deselect everything first, before you go on to move the next div.

https://github.com/daybrush/moveable/assets/109098443/a944a4e4-1f3c-4d28-be2a-ccec8400702e

Basic Demo at:
https://codepen.io/Carl-Mahnke/pen/QWJdoeJ

The issue does also occur in the storybook:
https://daybrush.com/moveable/storybook/?path=/story/combination-with-other-components--components-selecto

![image](https://github.com/daybrush/moveable/assets/109098443/01ac437b-bfbc-49cc-85e0-14810f9f998d)

**Comment by daybrush** [comment]
@CarlMahnke1 

* `croact-moveable` 0.5.1
* `@moveable/helper` 0.1.3
* `lit-moveable` 0.26.1
* `moveable` 0.49.1
* `preact-moveable` 0.51.1
* `react-moveable` 0.52.1
* `svelte-moveable` 0.41.1
* `vue-moveable` 2.0.0-beta.78
* `vue3-moveable` 0.24.1
* `ngx-moveable` 0.46.1

moveable's new version is released. Try it again.

**Comment by CarlMahnke1** [comment]
@daybrush Bug is fixed. Awesome work!
