### ISSUE TITLE
Question about Grid Offset

### ISSUE THREAD

**Issue by CarlMahnke1** [daybrush/moveable#965]
## Environments
"moveable": "^0.47.9",
"selecto": "^1.25.0",

## Description
I have a question regarding the grid offset. In my demo it looks like the grid offset is always the browsers viewport. Is that how it works?
https://codepen.io/Carl-Mahnke/pen/wvQdoOa

Because, it woud be cool to have an option to set the grid offset to the parent element,

**Comment by daybrush** [comment]
@CarlMahnke1

The snap area is basically an offsetContainer.

Since `position: relative` does not exist in `.container`, it is set as the parent element (maybe document.body)


set `position: relative;` to `.container`
```css
.container {
            position:relative;
}
```

**Comment by CarlMahnke1** [comment]
@daybrush Yes, that works. However, as I see, there is the limitation that, when instancing new Moveable, we can only pass one container.
So, when I have mutiple drag areas, as in my example, it won't work.
No need for you to get active, I just wanted to get this clarified! 

Thank you!
