### ISSUE TITLE
`moveable.dragStart(event)` is not working with `individualGroupable: true`

### ISSUE THREAD

**Issue by ivadenis** [daybrush/moveable#967]
## Environments
```
"dependencies": {
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-moveable": "0.52.1",
}
```

## Description
I'm trying to make item drag on `mouseDown` event.
When `individualGroupable: true`, `moveable.dragStart()` is not working. Toggle it off, and everything works.

```
const onMouseDown = (e) => {
    const moveable = moveableRef.current;
    const { nativeEvent } = e;
    moveable.waitToChangeTargets().then(() => {
      moveable.dragStart(nativeEvent);
    });

    setTarget(nativeEvent.target);
  };
```

See: https://codesandbox.io/p/sandbox/serene-fire-zynp6k?file=%2Fsrc%2FApp.js%3A77%2C3-85%2C5

**Comment by daybrush** [comment]
@ivadenis 

* `croact-moveable` 0.6.1
* `@moveable/helper` 0.1.3
* `lit-moveable` 0.27.1
* `moveable` 0.50.1
* `preact-moveable` 0.52.1
* `react-moveable` 0.53.1
* `svelte-moveable` 0.42.1
* `vue-moveable` 2.0.0-beta.80
* `vue3-moveable` 0.25.1
* `ngx-moveable` 0.47.1

moveable's new version is released. Check it again.

**Comment by ivadenis** [comment]
@daybrush it works! thanks!

**Comment by UreMySunshine** [comment]
it happends again in react18,sad
