### ISSUE TITLE
Move control display wrong position in google map and Safari

### ISSUE THREAD

**Issue by abinhho** [daybrush/moveable#97]
Hi again!

I am using moveable in google map. It's worked fine in Chrome but something wrong in Safari browser.
<img width="605" alt="Screen Shot 2019-11-14 at 11 02 31 AM" src="https://user-images.githubusercontent.com/9253378/68825961-9caf8680-06ce-11ea-94a7-a761626ef65f.png">

Here is my code: https://jsfiddle.net/abinhho/2bo0k5ye/67/
Please help !

**Comment by daybrush** [comment]
@abinhho 

Thank you for bug reporting.

moveblae 0.10.4 is released.
After releasing and checking, there seems to be no problem. try it again.

**Comment by abinhho** [comment]
@daybrush 
Thanks you !
