### ISSUE TITLE
How to set dragTarget (DragHandle) Button next to Rotation Handle Button?

### ISSUE THREAD

**Issue by jadiagaurang** [daybrush/moveable#975]
## Environments
* Framework name: Vanilla JS
* Framework version: N/A
* Moveable Component version: 0.52.0
* Testable Address(optional): I have attached Video

## Description
Hi @daybrush,

I want to place `dragTarget` (DragHandle) next to Rotation Handle, but I am not able to do it using `moveable.getRect()` or `moveable.state.pos2` or `moveable.state.pos4`!

I created `dragTarget` (DragHandle) using Custom Able.

```javascript
const { html } = TaggedJSX;
    const DragHandleAble = ({
        name: "draghandleable",
        props: {},
        events: {},
        render: function (moveable, Renderer) {
            const rect = moveable.getRect();
            const { pos2 } = moveable.state;

            const DragHandleViewer = moveable.useCSS("button", `{
                position: absolute;
                left: 0px;
                top: 0px;
                will-change: transform;
                transform-origin: 0px 0px;
            }`);

            return html`<${DragHandleViewer} className="dragHandle" style=${{ transform: `translate(${pos2[0]}px, ${pos2[1]}px) rotate(${rect.rotation}deg) translate(10px)`, }}> </>`(Renderer.createElement);
        }
    });
```
1. Single Element
![image](https://github.com/daybrush/moveable/assets/430637/bee94f99-2c51-4e6a-a82f-6661a215db0a)

2. Multiple Elements
![image](https://github.com/daybrush/moveable/assets/430637/446b1df7-acd3-4a6c-b4d0-9c7d13f6aae6)

3. During Rotation, I want to keep the `dragTarget` (DragHandle) Button next to Rotation Handle Button!

https://github.com/daybrush/moveable/assets/430637/57828a44-507c-45f3-b418-7e85030e67d0

I really appreciate any help you can provide.

**Comment by daybrush** [comment]
@jadiagaurang 

Your rotation position is at the bottom. Right?


The bottom is the middle point between pos3 and pos4. Please refer to the code below.


```js
const rect = moveable.getRect();
const { pos3, pos4 } = moveable.state;

const center = [(pos3[0] + pos4[0]) / 2, (pos3[1] + pos4[1]) / 2];

// transform: `translate(${pos2[0]}px, ${pos2[1]}px) rotate(${rect.rotation}deg) translate(10px)`
```

**Comment by jadiagaurang** [comment]
Hi @daybrush 

You are right! I have a Rotation Position at the Bottom. I updated my Code with the X, Y from the Center. But, It cannot keep the same spacing between them when I rotate an Element.

```javascript
const { html } = TaggedJSX;
const DragHandleAble = ({
    name: "draghandleable",
    props: {},
    events: {},
    render: function (moveable, Renderer) {
        const rect = moveable.getRect();
        const { pos2, pos3, pos4 } = moveable.state;
        const center = [((pos3[0] + pos4[0]) / 2) + 5, ((pos3[1] + pos4[1]) / 2) + 10];

        const DragHandleViewer = moveable.useCSS("button", `{
            position: absolute;
            left: 0px;
            top: 0px;
            will-change: transform;
            transform-origin: 0px 0px;
        }`);

        return html`<${DragHandleViewer} className="dragHandle" style=${{ transform: `translate(${center[0]}px, ${center[1]}px) rotate(${rect.rotation}deg)`, }}> </>`(Renderer.createElement);
    }
});
```

Please take a look at my video below.

https://github.com/daybrush/moveable/assets/430637/0b703d05-6450-4fb1-bef1-a1a3f01bc8e6

**Comment by daybrush** [comment]
@jadiagaurang 

try translate after rotate

```js
transform: `translate(${center[0]}px, ${center[1]}px) rotate(${rect.rotation}deg) translate(5px, 10px)`
```

https://codepen.io/daybrush/pen/NWEXEYo

**Comment by jadiagaurang** [comment]
Hi @daybrush This is wonderful. Thank you so much for providing the code snippet with codepen example. 🙏
