### ISSUE TITLE
Pixel-perfect bounds

### ISSUE THREAD

**Issue by superMDguy** [daybrush/moveable#977]
## Environments
* Framework name: Moveable
* Framework version: 0.51.0
* Testable Address(optional):

## Description

I've seen a few minor issues with snapping to bounds.

As an example, I made [this](https://jsfiddle.net/muntfoah/) to test.

After dragging the square to the bottom left, the `transform` is set to `-1px, 197px`, when I think it should be `0px, 198px` to be perfectly accurate. Let me know if there's any way I can help get to the bottom of this!

**Comment by daybrush** [comment]
@superMDguy 

snapContainer is calculated based on the offset including the border.

This example has a border. Therefore, considering the border, it moves up to -1.

**Comment by superMDguy** [comment]
Ok, thank you
