### ISSUE TITLE
moveable-control-box position is not the same with the wrapped element when on mobile

### ISSUE THREAD

**Issue by darsodango** [daybrush/moveable#98]
![image](https://user-images.githubusercontent.com/36293486/68914751-84a53900-079a-11ea-847b-d2986dbdce9c.png)

the attached photo is my issue. the control-box position should wrap the signature element but it somehow likes this on mobile view. on a desktop view, there's no problem though.

I haven't made some custom positioning for this so maybe there some issues on mobile?

**Comment by daybrush** [comment]
@darsodango 
I released a new version a few hours ago and it solved a similar problem, check again.

Thank you :)

**Comment by darsodango** [comment]
@daybrush
I just updated our package and it works now. what was the issue of why it behaves on mobile view but not on desktop view?

anyway, thank you!

**Comment by daybrush** [comment]
@darsodango 
Maybe your mobile is iOS.
The offset value of the webkit browser is different from other browsers.
However, the problem seems to be caused by incorrect calculations for the webkit.
Thank you :)
