### ISSUE TITLE
Help needed developing a web app with Moveable

### ISSUE THREAD

**Issue by danpii** [daybrush/moveable#985]
Hi,

I am looking for a developer on freelancer basis who can support me in implementing a web app with Moveable.
Budget depends on the scope. Time frame is flexible.

@daybrush: 
- I hope it's ok if I ask for development support here.
- Do you do freelance work?

Thanks

**Comment by daybrush** [comment]
@danpii 

If you need help, please write an issue or email. I don't do any freelance work.
